package ots

class SampleData_KnowledgePoint_Parent_Relations1 {

	String content = '''下游点	上游点
[排除:besides,except,but,except for]	[except,介词]
[排除:besides,except,but,except for]	[besides,介词]
[排除:besides,except,but,except for]	[but,介词]
[排除:besides,except,but,except for]	[except for,复合介词]
[a bottle of juice]	[不可数名词修饰语]
[a bottle of juice]	[juice,不可数名词instances]
[a bottle of juice]	[a bottle of]
[a bottle of]	[bottle,表示数量单位的名词]
[a cup of tea]	[不可数名词修饰语]
[a cup of tea]	[a cup of]
[a cup of tea]	[tea,不可数名词instances]
[a cup of]	[cup,表示数量单位的名词]
[a few,不定代词]	[不定代词]
[a few,不定代词]	[a few]
[a few]	[few]
[a few+可数名词]	[a few,不定代词]
[a few+可数名词]	[可数名词修饰语]
[a glass of]	[glass,表示数量单位的名词]
[a good time]	[time]
[a good time]	[good]
[a little,不定代词]	[不定代词]
[a little,不定代词]	[a little]
[a little]	[不定代词]
[a little]	[little]
[a little+不可数名词]	[不可数名词修饰语]
[a little+不可数名词]	[a little,不定代词]
[a little+形容词副词比较级]	[形容词和副词比较级修饰语]
[a little+形容词副词比较级]	[a little]
[a long history]	[history]
[a long history]	[long]
[a number of]	[number,表示数量单位的名词]
[a number of+复数名词,主谓一致]	[a number of]
[a number of+复数名词,主谓一致]	[主谓一致]
[a pair of shoes]	[a pair of]
[a pair of shoes]	[shoe,规则可数名词instances]
[a pair of shoes]	[可数名词修饰语]
[a pair of]	[pair,表示数量单位的名词]
[a piece of bread]	[不可数名词修饰语]
[a piece of bread]	[a piece of]
[a piece of bread]	[bread,不可数名词instances]
[a piece of news]	[news,不可数名词instances]
[a piece of news]	[不可数名词修饰语]
[a piece of news]	[a piece of]
[a piece of paper]	[不可数名词修饰语]
[a piece of paper]	[a piece of]
[a piece of paper]	[paper,不可数名词instances]
[a piece of]	[piece,表示数量单位的名词]
[a second time]	[time]
[a second time]	[序数词用法]
[a second time]	[a+序数词]
[a second time]	[second]
[a/an+可数名词+of+名词所有格]	[of,介词]
[a/an+可数名词+of+名词所有格]	[双重所有格]
[a/an+可数名词+of+名词所有格]	[名词所有格]
[a/an+可数名词+of+名词性物主代词]	[of,介词]
[a/an+可数名词+of+名词性物主代词]	[双重所有格]
[a/an+可数名词+of+名词性物主代词]	[名词性物主代词]
[a]	[冠词]
[a+非元音开头的词]	[a]
[a+序数词]	[a]
[a+序数词]	[序数词]
[able]	[单词]
[about,介词]	[about]
[about,介词]	[介词]
[about]	[单词]
[accept,receive:辨析]	[accept]
[accept,receive:辨析]	[receive]
[accept]	[单词]
[achieve one's dream]	[dream]
[achieve one's dream]	[achieve]
[achieve]	[单词]
[across,介词]	[across]
[across,介词]	[介词]
[across]	[单词]
[advice,不可数名词instances]	[不可数名词instances]
[advice,不可数名词instances]	[advice]
[advice]	[单词]
[advise]	[单词]
[advise…to do]	[advise]
[advise…to do]	[不定式习语]
[afford,动词instances]	[afford]
[afford,动词instances]	[动词instances]
[afford]	[单词]
[afraid of]	[of,介词]
[afraid of]	[afraid,表语补语形容词]
[afraid,表语补语形容词]	[afraid]
[afraid,表语补语形容词]	[表语补语形容词]
[afraid]	[单词]
[after all]	[all]
[after all]	[after]
[after supper]	[零冠词惯用法]
[after supper]	[supper]
[after supper]	[after,介词]
[after,介词]	[介词]
[after,介词]	[after]
[after,连词]	[after]
[after,连词]	[连词]
[after,引导时间状语从句]	[after,连词]
[after,引导时间状语从句]	[时间状语从句,连词]
[after]	[单词]
[against,介词]	[介词]
[against,介词]	[against]
[against]	[单词]
[ago]	[单词]
[agree to]	[to,介词]
[agree to]	[agree]
[agree with]	[with,介词]
[agree with]	[agree]
[agree]	[单词]
[all,both]	[both]
[all,both]	[all]
[all]	[单词]
[allow,及物动词]	[及物动词]
[allow,及物动词]	[allow]
[allow]	[单词]
[alone,lonely]	[alone,表语补语形容词]
[alone,lonely]	[lonely,形容词instances]
[alone,lonely]	[形容词惯用法]
[alone,表语补语形容词]	[表语补语形容词]
[alone,表语补语形容词]	[alone]
[alone]	[单词]
[along]	[单词]
[already,副词instances]	[副词instances]
[already,副词instances]	[already]
[already,用于现在完成时]	[用于现在完成时的副词]
[already,用于现在完成时]	[already,副词instances]
[already]	[单词]
[also]	[单词]
[although,but不可一起使用]	[but,连词]
[although,but不可一起使用]	[although,连词]
[although,连词]	[although]
[although,连词]	[连词]
[although,引导让步状语从句]	[让步状语从句,连词]
[although,引导让步状语从句]	[although,连词]
[although]	[单词]
[always,频率副词]	[频率副词]
[always,频率副词]	[always]
[always,用于一般现在时]	[always,频率副词]
[always,用于一般现在时]	[一般现在时的时间状语]
[always]	[单词]
[among,介词]	[介词]
[among,介词]	[among]
[among]	[单词]
[amusing,-ing形式的形容词]	[-ing形式的形容词]
[amusing,-ing形式的形容词]	[amusing]
[amusing]	[单词]
[an]	[冠词]
[an+元音开头的词]	[an]
[and then]	[then]
[and then]	[and]
[and,连词]	[and]
[and,连词]	[连词]
[and]	[单词]
[angry]	[单词]
[another,不定代词]	[不定代词]
[another,不定代词]	[another]
[another,形容词instances]	[形容词instances]
[another,形容词instances]	[another]
[another]	[单词]
[another+基数词]	[基数词]
[another+基数词]	[another]
[anxious]	[单词]
[any other]	[other]
[any other]	[any]
[any]	[单词]
[any+可数名词]	[可数名词修饰语]
[any+可数名词]	[any]
[anyone,复合不定代词]	[anyone]
[anyone,复合不定代词]	[复合不定代词]
[anyone]	[单词]
[anything,复合不定代词]	[anything]
[anything,复合不定代词]	[复合不定代词]
[anything]	[单词]
[anything+形容词]	[anything,复合不定代词]
[anywhere]	[单词]
[apple,是元音开头的词]	[apple]
[apple,是元音开头的词]	[an+元音开头的词]
[apple,是元音开头的词]	[元音开头的词]
[apple]	[单词]
[around]	[单词]
[arrive at]	[arrive]
[arrive at]	[at,介词]
[arrive in]	[in,介词]
[arrive in]	[arrive]
[arrive, get to, reach]	[arrive]
[arrive, get to, reach]	[get to]
[arrive, get to, reach]	[reach]
[arrive]	[单词]
[as long as,引导条件状语从句]	[条件状语从句,连词]
[as long as,引导条件状语从句]	[as long as]
[as long as]	[as]
[as long as]	[long]
[as soon as,引导时间状语从句]	[时间状语从句,连词]
[as soon as,引导时间状语从句]	[as soon as]
[as soon as]	[as]
[as soon as]	[soon]
[as well as,主谓一致]	[as well as]
[as well as,主谓一致]	[主谓一致]
[as well as]	[as]
[as well as]	[well]
[as,介词]	[as]
[as,介词]	[介词]
[as...as,引导比较状语从句]	[as...as]
[as...as,引导比较状语从句]	[比较状语从句,连词]
[as...as]	[as]
[as...as]	[形容词和副词的原级]
[as]	[单词]
[ask]	[单词]
[ask…to do]	[ask]
[ask…to do]	[不定式习语]
[at a time]	[time]
[at a time]	[at]
[at last]	[序数词用法]
[at last]	[last]
[at last]	[at,介词]
[at times]	[time]
[at times]	[at]
[at weekends]	[weekend]
[at weekends]	[表示时间:at,in,on]
[at,介词]	[at]
[at,介词]	[介词]
[at]	[单词]
[attend,join,join in,take part in]	[join]
[attend,join,join in,take part in]	[join in]
[attend,join,join in,take part in]	[attend]
[attend,join,join in,take part in]	[take part in]
[attend]	[单词]
[away]	[单词]
[bad]	[单词]
[bad->worse,比较级]	[bad]
[bad->worse,比较级]	[worse]
[bad->worse,比较级]	[形容词副词比较级构成]
[basketball,是球类棋类]	[play+球类棋类]
[basketball,是球类棋类]	[basketball]
[basketball,是球类棋类]	[球类棋类]
[basketball]	[单词]
[be + v-ed + to do]	[带宾语从句的句子,被动语态]
[be able to]	[able]
[be against doing]	[v-ing习语]
[be against doing]	[against,介词]
[be allowed to do]	[allow,及物动词]
[be allowed to do]	[be + v-ed + to do]
[be angry with]	[with,介词]
[be angry with]	[angry]
[be away from]	[from,介词]
[be away from]	[away]
[be busy with]	[with,介词]
[be busy with]	[busy]
[be covered with]	[cover,及物动词]
[be covered with]	[with,介词]
[be famous for]	[famous]
[be famous for]	[for,介词]
[be filled with]	[with,介词]
[be filled with]	[filled]
[be fond of]	[of,介词]
[be fond of]	[fond]
[be full of energy]	[energy]
[be full of energy]	[be full of]
[be full of]	[of,介词]
[be full of]	[full]
[be going to do]	[be going to]
[be going to do]	[一般将来时]
[be going to]	[go]
[be going to]	[to]
[be going to]	[be]
[be good at]	[good]
[be good at]	[at,介词]
[be happy for]	[happy]
[be happy for]	[for,介词]
[be happy with]	[with,介词]
[be happy with]	[happy]
[be heard to do sth]	[to不可省略,be v-ed to do]
[be heard to do sth]	[hear,及物动词]
[be home to]	[to,介词]
[be home to]	[home]
[be home to]	[be]
[be interested in]	[in,介词]
[be interested in]	[interested]
[be keen on]	[keen]
[be keen on]	[on,介词]
[be keen on<->be fond of]	[be keen on]
[be keen on<->be fond of]	[be fond of]
[be keen on<->be fond of]	[同义转换]
[be known to be]	[be + v-ed + to do]
[be known to be]	[be]
[be known to be]	[know,及物动词]
[be late for]	[late]
[be late for]	[for,介词]
[be made from]	[make,及物动词]
[be made from]	[from,介词]
[be made of]	[of,介词]
[be made of]	[make,及物动词]
[be made to do sth]	[make,及物动词]
[be made to do sth]	[to不可省略,be v-ed to do]
[be pleased with]	[with,介词]
[be pleased with]	[pleased]
[be proud of]	[of,介词]
[be proud of]	[proud]
[be regarded as]	[regard,及物动词]
[be regarded as]	[as,介词]
[be responsible for]	[responsible]
[be responsible for]	[for,介词]
[be strict with]	[strict]
[be strict with]	[with,介词]
[be supposed to do]	[be + v-ed + to do]
[be supposed to do]	[suppose,及物动词]
[be the pride of]	[of,介词]
[be the pride of]	[pride]
[be used in]	[in,介词]
[be used in]	[use,及物动词]
[be used to do]	[use,及物动词]
[be used to do]	[不定式习语]
[be used to doing]	[v-ing习语]
[be used to doing]	[to,介词]
[be used to doing]	[use]
[be worn out]	[wear]
[be worn out]	[out]
[be worn out]	[worn]
[be worried about]	[worried]
[be worried about]	[about,介词]
[be worth doing]	[v-ing习语]
[be worth doing]	[worth]
[be,是系动词]	[系动词]
[be,是系动词]	[be]
[be]	[单词]
[be+形容词]	[系动词+形容词]
[be+形容词]	[be,是系动词]
[be+形容词+不定式]	[be+形容词]
[be+形容词+不定式]	[不定式]
[because of]	[of]
[because of]	[because]
[because,连词]	[because]
[because,连词]	[连词]
[because,引导原因状语从句]	[because,连词]
[because,引导原因状语从句]	[原因状语从句,连词]
[because]	[单词]
[bed]	[单词]
[beef,不可数名词instances]	[不可数名词instances]
[beef,不可数名词instances]	[beef]
[beef]	[单词]
[before,连词]	[before]
[before,连词]	[连词]
[before,引导时间状语从句]	[before,连词]
[before,引导时间状语从句]	[时间状语从句,连词]
[before]	[单词]
[believe in]	[in,介词]
[believe in]	[believe]
[believe]	[单词]
[believe…,应答句]	[believe]
[believe…,应答句]	[应答句]
[belong to sb]	[belong to]
[belong to]	[belong]
[belong to]	[to]
[belong]	[单词]
[besides,副词instances]	[副词instances]
[besides,副词instances]	[besides]
[besides,介词]	[besides]
[besides,介词]	[介词]
[besides]	[单词]
[best]	[单词]
[better]	[单词]
[between A and B]	[between,介词]
[between,介词]	[between]
[between,介词]	[介词]
[between]	[单词]
[Be动词,用于现在完成时]	[be]
[Be动词,用于现在完成时]	[现在完成时]
[boiled water]	[boiled,-ed形式的形容词]
[boiled water]	[water]
[boiled,-ed形式的形容词]	[-ed形式的形容词]
[boiled,-ed形式的形容词]	[boiled]
[boiled]	[单词]
[boring,-ing形式的形容词]	[-ing形式的形容词]
[boring,-ing形式的形容词]	[boring]
[boring]	[单词]
[borrow,lend]	[borrow]
[borrow,lend]	[lend]
[borrow]	[单词]
[both,不定代词]	[不定代词]
[both,不定代词]	[both]
[both,形容词instances]	[形容词instances]
[both,形容词instances]	[both]
[both]	[单词]
[both…and,是并列结构连词]	[并列结构的连词]
[both…and,是并列结构连词]	[both…and]
[both…and,主谓一致]	[both…and]
[both…and,主谓一致]	[主谓一致]
[both…and]	[and]
[both…and]	[both]
[bottle,表示数量单位的名词]	[表示数量单位的名词]
[bottle,表示数量单位的名词]	[bottle]
[bottle]	[单词]
[bread,不可数名词instances]	[不可数名词instances]
[bread,不可数名词instances]	[bread]
[bread]	[单词]
[break down]	[down]
[break down]	[break]
[break out]	[break]
[break out]	[out]
[break the record]	[record]
[break the record]	[break]
[break]	[单词]
[breakfast]	[单词]
[bring,carry,pass,take,fetch]	[carry]
[bring,carry,pass,take,fetch]	[pass]
[bring,carry,pass,take,fetch]	[fetch]
[bring,carry,pass,take,fetch]	[take]
[bring,carry,pass,take,fetch]	[bring]
[bring]	[单词]
[bus]	[单词]
[busy (in) doing]	[v-ing习语]
[busy (in) doing]	[in,介词]
[busy (in) doing]	[busy]
[busy]	[单词]
[but also]	[but]
[but also]	[also]
[but,介词]	[but]
[but,介词]	[介词]
[but,连词]	[but]
[but,连词]	[连词]
[but]	[单词]
[by bus]	[by+交通通讯方法]
[by bus]	[交通通讯方法]
[by bus]	[bus]
[by oneself]	[by,介词]
[by oneself]	[oneself]
[by the end of]	[of,介词]
[by the end of]	[by]
[by the end of]	[end]
[by the end of+过去时间点,用于过去完成时]	[过去完成时的时间状语]
[by the end of+过去时间点,用于过去完成时]	[by the end of+过去时间点]
[by the end of+过去时间点]	[by the end of]
[by the time,引导时间状语从句]	[by the time]
[by the time,引导时间状语从句]	[时间状语从句,连词]
[by the time]	[time]
[by the time]	[by]
[by the time+一般过去时,主句用过去完成时]	[by the time,引导时间状语从句]
[by the time+一般过去时,主句用过去完成时]	[过去完成时的时间状语]
[by the time+一般过去时,主句用过去完成时]	[时间状语从句,时态]
[by,被动语态]	[by,介词]
[by,被动语态]	[被动语态]
[by,介词]	[介词]
[by,介词]	[by]
[by]	[单词]
[by+交通通讯方法]	[by,介词]
[by+交通通讯方法]	[零冠词]
[call on]	[call]
[call on]	[on,介词]
[call]	[单词]
[Can I…,疑问句]	[一般疑问句]
[Can I…,疑问句]	[can,情态动词]
[Can I…,应答句]	[表示请求,应答句]
[Can I…,应答句]	[Can I…,疑问句]
[Can you…,疑问句]	[一般疑问句]
[Can you…,疑问句]	[can,情态动词]
[can,afford]	[afford,动词instances]
[can,afford]	[can,情态动词]
[can,be able to:辨析]	[be able to]
[can,be able to:辨析]	[can,情态动词]
[can,被动语态]	[情态动词的被动语态]
[can,被动语态]	[can,情态动词]
[can,情态动词]	[情态动词]
[can,情态动词]	[can]
[can]	[单词]
[cannot help doing]	[v-ing习语]
[cannot help doing]	[help]
[can't,mustn't]	[can't]
[can't,mustn't]	[mustn't]
[can't]	[can,情态动词]
[care about doing]	[v-ing习语]
[care about doing]	[care about]
[care about]	[care]
[care about]	[about,介词]
[care]	[单词]
[carry]	[单词]
[catch a cold]	[catch]
[catch a cold]	[cold]
[catch]	[单词]
[cause,及物动词]	[及物动词]
[cause,及物动词]	[cause]
[cause]	[单词]
[chance]	[单词]
[cheer up]	[up]
[cheer up]	[cheer]
[cheer]	[单词]
[cheerfully,副词instances]	[副词instances]
[cheerfully,副词instances]	[cheerfully]
[cheerfully]	[单词]
[chess,是球类棋类]	[chess]
[chess,是球类棋类]	[play+球类棋类]
[chess,是球类棋类]	[球类棋类]
[chess]	[单词]
[chicken,不可数名词instances]	[不可数名词instances]
[chicken,不可数名词instances]	[chicken]
[chicken]	[单词]
[chip]	[单词]
[coffee,不可数名词instances]	[不可数名词instances]
[coffee,不可数名词instances]	[coffee]
[coffee]	[单词]
[cold]	[单词]
[colour]	[单词]
[come out]	[come]
[come out]	[out]
[come true]	[true]
[come true]	[come+形容词]
[come up with]	[come]
[come up with]	[up]
[come up with]	[with,介词]
[come,是系动词]	[come]
[come,是系动词]	[系动词]
[come]	[单词]
[come+形容词]	[系动词+形容词]
[come+形容词]	[come,是系动词]
[consider doing]	[v-ing习语]
[consider doing]	[consider]
[consider]	[单词]
[continue to do,continue doing]	[v-ing习语]
[continue to do,continue doing]	[continue]
[continue to do,continue doing]	[不定式习语]
[continue]	[单词]
[correct]	[单词]
[cost,pay,spend,take]	[pay]
[cost,pay,spend,take]	[cost]
[cost,pay,spend,take]	[take]
[cost,pay,spend,take]	[spend]
[cost]	[单词]
[Could I,疑问句]	[could,情态动词]
[Could I,疑问句]	[一般疑问句]
[Could I…,应答句]	[表示请求,应答句]
[Could I…,应答句]	[Could I,疑问句]
[Could you please do sth,应答句]	[表示请求,应答句]
[Could you please do sth,应答句]	[Could you please,疑问句]
[Could you please,疑问句]	[could,情态动词]
[Could you please,疑问句]	[一般疑问句]
[could you…,引导的主句]	[could,情态动词]
[could you…,引导的主句]	[主句过去时]
[could you…,引导的主句]	[主句现在时]
[could,情态动词]	[情态动词]
[could,情态动词]	[could]
[could]	[单词]
[cover,及物动词]	[及物动词]
[cover,及物动词]	[cover]
[cover]	[单词]
[crazy about]	[about,介词]
[crazy about]	[crazy]
[crazy]	[单词]
[cup,表示数量单位的名词]	[表示数量单位的名词]
[cup,表示数量单位的名词]	[cup]
[cup]	[单词]
[danger]	[单词]
[decide to do]	[decide]
[decide to do]	[不定式习语]
[decide]	[单词]
[decision]	[单词]
[deep,deeply区别]	[deeply,副词instances]
[deep,deeply区别]	[副词惯用法]
[deep,deeply区别]	[deep,副词instances]
[deep,副词instances]	[副词instances]
[deep,副词instances]	[deep]
[deep]	[单词]
[deeply,副词instances]	[副词instances]
[deeply,副词instances]	[deeply]
[deeply]	[单词]
[diet]	[单词]
[direction]	[单词]
[do one's best]	[do]
[do one's best]	[best]
[do well in…]	[in,介词]
[do well in…]	[do]
[do well in…]	[well,副词instances]
[do you think,特殊疑问句]	[do you think]
[do you think,特殊疑问句]	[特殊疑问句]
[do you think]	[think]
[do]	[单词]
[don't]	[do]
[don't…,祈使句的否定形式]	[don't]
[don't…,祈使句的否定形式]	[祈使句]
[down]	[单词]
[dream]	[单词]
[dress,put on,wear]	[wear]
[dress,put on,wear]	[put on]
[dress,put on,wear]	[dress]
[dress]	[单词]
[during,介词]	[介词]
[during,介词]	[during]
[during]	[单词]
[duty]	[单词]
[each,不定代词]	[不定代词]
[each,不定代词]	[each]
[each,主谓一致]	[each,不定代词]
[each,主谓一致]	[主谓一致]
[each]	[单词]
[east]	[单词]
[easy]	[单词]
[-ed形式的形容词]	[形容词]
[either,不定代词]	[不定代词]
[either,不定代词]	[either]
[either,形容词instances]	[形容词instances]
[either,形容词instances]	[either]
[either]	[单词]
[either…or,是并列结构连词]	[并列结构的连词]
[either…or,是并列结构连词]	[either…or]
[either…or,主谓一致]	[either…or]
[either…or,主谓一致]	[主谓一致]
[either…or]	[either]
[either…or]	[or]
[else,形容词instances]	[形容词instances]
[else,形容词instances]	[else]
[else]	[单词]
[encourage]	[单词]
[encourage…to do]	[不定式习语]
[encourage…to do]	[encourage]
[end]	[单词]
[energy,不可数名词instances]	[不可数名词instances]
[energy,不可数名词instances]	[energy]
[energy]	[单词]
[enjoy oneself]	[enjoy]
[enjoy oneself]	[oneself]
[enjoy]	[单词]
[enough,副词instances]	[副词instances]
[enough,副词instances]	[enough]
[enough]	[单词]
[enter for]	[enter]
[enter for]	[for,介词]
[enter]	[单词]
[especially,副词instances]	[副词instances]
[especially,副词instances]	[especially]
[especially]	[单词]
[European,是非元音开头的词]	[Europen]
[European,是非元音开头的词]	[a+非元音开头的词]
[European,是非元音开头的词]	[非元音开头的词]
[Europen]	[单词]
[even though,引导让步状语从句]	[让步状语从句,连词]
[even though,引导让步状语从句]	[even though]
[even though]	[though]
[even though]	[even]
[even,副词instances]	[副词instances]
[even,副词instances]	[even]
[even]	[单词]
[even+形容词副词比较级]	[形容词和副词比较级修饰语]
[even+形容词副词比较级]	[even,副词instances]
[ever since,用于现在完成时]	[ever since]
[ever since,用于现在完成时]	[用于现在完成时的副词]
[ever since]	[since]
[ever since]	[ever]
[ever,副词instances]	[副词instances]
[ever,副词instances]	[ever]
[ever,用于现在完成时]	[ever,副词instances]
[ever,用于现在完成时]	[用于现在完成时的副词]
[ever]	[单词]
[everybody,复合不定代词]	[everybody]
[everybody,复合不定代词]	[复合不定代词]
[everybody]	[单词]
[everyone except,主谓一致]	[everyone,复合不定代词]
[everyone except,主谓一致]	[主谓一致]
[everyone,复合不定代词]	[everyone]
[everyone,复合不定代词]	[复合不定代词]
[everyone]	[单词]
[everything,复合不定代词]	[everything]
[everything,复合不定代词]	[复合不定代词]
[everything]	[单词]
[everywhere]	[单词]
[exam]	[单词]
[except for,复合介词]	[except for]
[except for,复合介词]	[复合介词]
[except for]	[except]
[except for]	[for]
[except,介词]	[except]
[except,介词]	[介词]
[except,主谓一致]	[except,介词]
[except,主谓一致]	[主谓一致]
[except]	[单词]
[excited,-ed形式的形容词]	[-ed形式的形容词]
[excited,-ed形式的形容词]	[excited]
[excited]	[单词]
[exciting,-ing形式的形容词]	[-ing形式的形容词]
[exciting,-ing形式的形容词]	[exciting]
[exciting]	[单词]
[expect]	[单词]
[expect…to do]	[expect]
[expect…to do]	[不定式习语]
[familiar with]	[familiar]
[familiar with]	[with,介词]
[familiar]	[单词]
[famous]	[单词]
[far,比较级构成]	[farther]
[far,比较级构成]	[形容词副词比较级构成]
[far,比较级构成]	[further]
[far,比较级构成]	[far]
[far]	[单词]
[farther]	[单词]
[fast food]	[food]
[fast food]	[fast]
[fast]	[单词]
[feel,是系动词]	[系动词]
[feel,是系动词]	[feel]
[feel]	[单词]
[feel+形容词]	[系动词+形容词]
[feel+形容词]	[feel,是系动词]
[fetch]	[单词]
[few,不定代词]	[不定代词]
[few,不定代词]	[few]
[few]	[单词]
[few+可数名词]	[few]
[few+可数名词]	[可数名词修饰语]
[few->fewer,比较级]	[few]
[few->fewer,比较级]	[形容词副词比较级构成]
[few->fewer,比较级]	[fewer]
[few->fewest,最高级]	[few]
[few->fewest,最高级]	[fewest]
[few->fewest,最高级]	[形容词和副词最高级构成]
[fewer]	[单词]
[fewest]	[单词]
[filled]	[单词]
[find … doing]	[v-ing习语]
[find … doing]	[find]
[find it+形容词+to do]	[find]
[find it+形容词+to do]	[不定式,it,宾语]
[find out]	[find]
[find out]	[out]
[find]	[单词]
[finish doing]	[v-ing习语]
[finish doing]	[finish]
[finish]	[单词]
[fish and chips,主谓一致]	[fish and chips]
[fish and chips,主谓一致]	[主谓一致]
[fish and chips]	[fish,不可数名词instances]
[fish and chips]	[chip]
[fish,不可数名词instances]	[不可数名词instances]
[fish,不可数名词instances]	[fish]
[fish,名词复数]	[不规则可数名词.复数]
[fish,名词复数]	[fish]
[fish]	[单词]
[fix up]	[up]
[fix up]	[fix]
[fix]	[单词]
[fond]	[单词]
[food,不可数名词instances]	[不可数名词instances]
[food,不可数名词instances]	[food]
[food]	[单词]
[foot]	[单词]
[for,介词]	[介词]
[for,介词]	[for]
[for]	[单词]
[for+一段时间,用于现在完成时]	[for+一段时间]
[for+一段时间,用于现在完成时]	[延续性动词,用于现在完成时]
[for+一段时间,用于现在完成时]	[现在完成时的时间状语]
[for+一段时间]	[表示时间:during,for]
[for+一段时间]	[表示时间:for,from,since]
[forget to do,forget doing]	[v-ing习语]
[forget to do,forget doing]	[不定式习语]
[forget to do,forget doing]	[forget]
[forget,leave:辨析]	[leave]
[forget,leave:辨析]	[forget]
[forget]	[单词]
[forward]	[单词]
[for引导不定式逻辑主语]	[for]
[for引导不定式逻辑主语]	[不定式的逻辑主语]
[friend]	[单词]
[friendly,-ly结尾的形容词]	[-ly结尾的形容词]
[friendly,-ly结尾的形容词]	[friendly]
[friendly]	[单词]
[from,介词]	[介词]
[from,介词]	[from]
[from]	[单词]
[from…to…]	[from,介词]
[from…to…]	[to,介词]
[front]	[单词]
[full]	[单词]
[fun]	[单词]
[further]	[单词]
[future]	[单词]
[German,规则可数名词instances]	[规则可数名词instances]
[German,规则可数名词instances]	[German]
[German]	[单词]
[get along with]	[with,介词]
[get along with]	[get]
[get along with]	[along]
[get into]	[get]
[get into]	[into,介词]
[get off]	[off]
[get off]	[get]
[get on with]	[with,介词]
[get on with]	[get]
[get on with]	[on]
[get over]	[get]
[get over]	[over]
[get to]	[to,介词]
[get to]	[get]
[get up]	[up]
[get up]	[get]
[get,是系动词]	[系动词]
[get,是系动词]	[get]
[get]	[单词]
[get+形容词]	[系动词+形容词]
[get+形容词]	[get,是系动词]
[give advice]	[give]
[give advice]	[advice]
[give away]	[give]
[give away]	[away]
[give out]	[give]
[give out]	[out]
[give sb a chance]	[give]
[give sb a chance]	[chance]
[give sb a hand]	[give]
[give sb a hand]	[hand]
[give sb a ring]	[give]
[give sb a ring]	[ring]
[give up doing]	[v-ing习语]
[give up doing]	[give up]
[give up]	[give]
[give up]	[up]
[give]	[单词]
[glass,表示数量单位的名词]	[表示数量单位的名词]
[glass,表示数量单位的名词]	[glass]
[glass]	[单词]
[go + v-ing]	[v-ing习语]
[go + v-ing]	[go]
[go swimming]	[go + v-ing]
[go swimming]	[swim]
[go to bed]	[go]
[go to bed]	[零冠词惯用法]
[go to bed]	[bed]
[go to bed]	[to]
[go]	[单词]
[good]	[单词]
[grow]	[单词]
[grown-up]	[grow]
[grown-up]	[up]
[grown-up]	[复合形容词]
[guitar,是乐器]	[guitar]
[guitar,是乐器]	[乐器]
[guitar,是乐器]	[the+乐器]
[guitar]	[单词]
[had better,不定式]	[不加to的动词不定式]
[had better,不定式]	[had better]
[had better]	[had]
[had better]	[better]
[had]	[单词]
[hand]	[单词]
[happen]	[单词]
[happy]	[单词]
[hard,hardly区别]	[副词惯用法]
[hard,hardly区别]	[hardly,频率副词]
[hard,hardly区别]	[hard,副词instances]
[hard,副词instances]	[副词instances]
[hard,副词instances]	[hard]
[hard]	[单词]
[hardly,反意疑问句]	[hardly,否定含义]
[hardly,反意疑问句]	[否定含义的词+反意疑问句]
[hardly,否定含义]	[hardly,频率副词]
[hardly,否定含义]	[否定含义的词]
[hardly,频率副词]	[hardly]
[hardly,频率副词]	[频率副词]
[hardly]	[单词]
[hard-working]	[hard]
[hard-working]	[复合形容词]
[hard-working]	[work]
[have a cold]	[cold]
[have a cold]	[have]
[have a difficult time (in) doing]	[v-ing习语]
[have a difficult time (in) doing]	[have a difficult time]
[have a difficult time]	[time]
[have a difficult time]	[have]
[have a look at]	[have]
[have a look at]	[at,介词]
[have a look at]	[look]
[have another try]	[have]
[have another try]	[another]
[have another try]	[try]
[have been in]	[Be动词,用于现在完成时]
[have been to,have gone to,have been in]	[have been in]
[have been to,have gone to,have been in]	[have gone to]
[have been to,have gone to,have been in]	[have been to]
[have been to]	[Where have/has...been]
[have been to]	[Be动词,用于现在完成时]
[have breakfast]	[have]
[have breakfast]	[breakfast]
[have fun doing]	[v-ing习语]
[have fun doing]	[have fun]
[have fun]	[fun]
[have fun]	[have]
[have gone to]	[go]
[have no idea]	[have]
[have no idea]	[idea]
[have sth done]	[have]
[have sth done]	[v-ed习语]
[have to,被动语态]	[have to,情态动词]
[have to,被动语态]	[情态动词的被动语态]
[have to,情态动词]	[情态动词]
[have to,情态动词]	[have to]
[have to]	[have]
[have to]	[to]
[have trouble doing]	[v-ing习语]
[have trouble doing]	[have trouble]
[have trouble]	[trouble]
[have trouble]	[have]
[have]	[单词]
[he,人称代词主格]	[人称代词主格]
[he,人称代词主格]	[he]
[he]	[单词]
[health]	[单词]
[hear from]	[from,介词]
[hear from]	[hear]
[hear of]	[of]
[hear of]	[hear]
[hear,及物动词]	[及物动词]
[hear,及物动词]	[hear]
[hear]	[单词]
[help oneself to…]	[help]
[help oneself to…]	[oneself]
[help oneself]	[help]
[help oneself]	[oneself]
[help sb with sth]	[help]
[help sb with sth]	[with,介词]
[help]	[单词]
[help…out]	[help]
[help…out]	[out]
[help…to do]	[help]
[help…to do]	[不定式习语]
[her,人称代词宾格]	[人称代词宾格]
[her,人称代词宾格]	[her]
[her,形容词性物主代词]	[形容词性物主代词]
[her,形容词性物主代词]	[her]
[her]	[单词]
[hers,名词性物主代词]	[名词性物主代词]
[hers,名词性物主代词]	[hers]
[hers]	[单词]
[herself,反身代词]	[反身代词]
[herself,反身代词]	[herself]
[herself]	[单词]
[high,形容词instances]	[形容词instances]
[high,形容词instances]	[high]
[high]	[单词]
[him,人称代词宾格]	[人称代词宾格]
[him,人称代词宾格]	[him]
[him]	[单词]
[himself,反身代词]	[反身代词]
[himself,反身代词]	[himself]
[himself]	[单词]
[his,名词性物主代词]	[名词性物主代词]
[his,名词性物主代词]	[his]
[his,形容词性物主代词]	[形容词性物主代词]
[his,形容词性物主代词]	[his]
[his]	[单词]
[history]	[单词]
[hold on]	[hold]
[hold on]	[on]
[hold]	[单词]
[home]	[单词]
[honest,是元音开头的词]	[an+元音开头的词]
[honest,是元音开头的词]	[honest]
[honest,是元音开头的词]	[元音开头的词]
[honest]	[单词]
[hope to do]	[hope]
[hope to do]	[不定式习语]
[hope]	[单词]
[hour,是元音开头的词]	[hour]
[hour,是元音开头的词]	[an+元音开头的词]
[hour,是元音开头的词]	[元音开头的词]
[hour]	[单词]
[how about doing]	[v-ing习语]
[how about doing]	[how about]
[How about...,应答句]	[how about]
[How about...,应答句]	[表达建议/意见/观点,应答句]
[how about]	[about]
[how about]	[how,疑问副词]
[how far,特殊疑问句]	[how far]
[how far,特殊疑问句]	[特殊疑问句]
[how far]	[how]
[how far]	[far]
[how long,宾语从句连接词]	[宾语从句语序]
[how long,宾语从句连接词]	[宾语从句的连接词]
[how long,宾语从句连接词]	[how long]
[how long,特殊疑问句]	[how long]
[how long,特殊疑问句]	[特殊疑问句]
[how long]	[how]
[how long]	[long]
[how long特殊疑问句,现在完成时]	[how long,特殊疑问句]
[how long特殊疑问句,现在完成时]	[现在完成时]
[how long特殊疑问句,应答句]	[特殊疑问句,应答句]
[how long特殊疑问句,应答句]	[how long,特殊疑问句]
[how many,特殊疑问句]	[how many]
[how many,特殊疑问句]	[特殊疑问句]
[how many]	[how]
[how many]	[many]
[how much,宾语从句连接词]	[how much]
[how much,宾语从句连接词]	[宾语从句语序]
[how much,宾语从句连接词]	[宾语从句的连接词]
[how much,特殊疑问句]	[how much]
[how much,特殊疑问句]	[特殊疑问句]
[how much]	[much]
[how much]	[how]
[how often,宾语从句连接词]	[宾语从句语序]
[how often,宾语从句连接词]	[how often]
[how often,宾语从句连接词]	[宾语从句的连接词]
[how often,特殊疑问句]	[how often]
[how often,特殊疑问句]	[特殊疑问句]
[how often]	[how]
[how often]	[often]
[how often特殊疑问句,应答句]	[特殊疑问句,应答句]
[how often特殊疑问句,应答句]	[how often,特殊疑问句]
[how old,宾语从句连接词]	[宾语从句语序]
[how old,宾语从句连接词]	[宾语从句的连接词]
[how old,宾语从句连接词]	[how old]
[how old]	[how]
[how old]	[old]
[how soon,特殊疑问句]	[how soon]
[how soon,特殊疑问句]	[特殊疑问句]
[how soon]	[how]
[how soon]	[soon]
[how soon特殊疑问句,应答句]	[特殊疑问句,应答句]
[how soon特殊疑问句,应答句]	[how soon,特殊疑问句]
[how to do]	[疑问词+不定式]
[how to do]	[how,疑问副词]
[how,宾语从句连接词]	[宾语从句语序]
[how,宾语从句连接词]	[how,疑问副词]
[how,宾语从句连接词]	[宾语从句的连接词]
[how,特殊疑问句]	[how,疑问副词]
[how,特殊疑问句]	[特殊疑问句]
[how,疑问副词]	[how]
[how,疑问副词]	[疑问副词]
[how]	[单词]
[how引导的感叹句]	[how]
[how引导的感叹句]	[感叹句]
[hundred,基数词]	[基数词]
[hundred,基数词]	[hundred]
[hundred]	[单词]
[hundreds of…]	[of]
[hundreds of…]	[基数词用法]
[hundreds of…]	[hundred,基数词]
[hurry]	[单词]
[I don't mind]	[mind]
[idea]	[单词]
[if,宾语从句连接词]	[宾语从句语序]
[if,宾语从句连接词]	[if,连词]
[if,宾语从句连接词]	[宾语从句的连接词]
[if,连词]	[if]
[if,连词]	[连词]
[if,引导条件状语从句]	[条件状语从句,连词]
[if,引导条件状语从句]	[if,连词]
[if]	[correct]
[I'm sorry …,应答句]	[表达歉意,应答句]
[I'm sorry …,应答句]	[sorry]
[important,是元音开头的词]	[important]
[important,是元音开头的词]	[an+元音开头的词]
[important,是元音开头的词]	[元音开头的词]
[important]	[单词]
[in a hurry]	[in,介词]
[in a hurry]	[hurry]
[in bed]	[in,介词]
[in bed]	[零冠词惯用法]
[in bed]	[bed]
[in front of,复合介词]	[front]
[in front of,复合介词]	[复合介词]
[in one's fifties]	[in,介词]
[in one's fifties]	[年龄]
[in order to do]	[不定式习语]
[in order to do]	[in order to]
[in order to]	[order]
[in recent years,用于现在完成时]	[现在完成时的时间状语]
[in recent years,用于现在完成时]	[in recent years]
[in recent years]	[in,介词]
[in recent years]	[recent]
[in recent years]	[year]
[in the east]	[the惯用法]
[in the east]	[east]
[in the east]	[表示方位:in,on,to]
[in the end]	[in,介词]
[in the end]	[the惯用法]
[in the end]	[end]
[in the future,用于一般将来时]	[in the future]
[in the future,用于一般将来时]	[一般将来时的时间状语]
[in the future]	[in,介词]
[in the future]	[the惯用法]
[in the future]	[future]
[in the past few years,用于现在完成时]	[in the past few years]
[in the past few years,用于现在完成时]	[现在完成时的时间状语]
[in the past few years]	[in,介词]
[in the past few years]	[past]
[in the past few years]	[year]
[in time]	[in]
[in time]	[time]
[in,介词]	[in]
[in,介词]	[介词]
[in]	[单词]
[in…health]	[in,介词]
[in…health]	[health]
[information,不可数名词instances]	[不可数名词instances]
[information,不可数名词instances]	[information]
[information]	[单词]
[-ing形式的形容词]	[形容词]
[instead of]	[of,介词]
[instead of]	[instead]
[instead,副词instances]	[副词instances]
[instead,副词instances]	[instead]
[instead]	[单词]
[interest]	[单词]
[interested]	[单词]
[interesting,-ing形式的形容词]	[-ing形式的形容词]
[interesting,-ing形式的形容词]	[interesting]
[interesting,是元音开头的词]	[an+元音开头的词]
[interesting,是元音开头的词]	[元音开头的词]
[interesting,是元音开头的词]	[interesting]
[interesting]	[单词]
[into,介词]	[into]
[into,介词]	[介词]
[into]	[单词]
[introduce sb to]	[to,介词]
[introduce sb to]	[introduce]
[introduce]	[单词]
[invite]	[单词]
[invite…to do]	[不定式习语]
[invite…to do]	[invite]
[It is our duty to do]	[duty]
[It is our duty to do]	[不定式,it,主语]
[it is+时间段+since]	[since,引导时间状语从句]
[it is+时间段+since]	[时间状语从句,时态]
[It seem that…]	[it形式主语]
[It seem that…]	[seem]
[it,人称代词宾格]	[it]
[it,人称代词宾格]	[人称代词宾格]
[it,人称代词主格]	[it]
[it,人称代词主格]	[人称代词主格]
[it]	[代词]
[it]	[单词]
[it形式宾语]	[it]
[it形式宾语]	[宾语]
[it形式主语]	[it]
[it形式主语]	[主语]
[join in]	[in]
[join in]	[join]
[join]	[单词]
[joy]	[单词]
[juice,不可数名词instances]	[不可数名词instances]
[juice,不可数名词instances]	[juice]
[juice]	[单词]
[just now,用于一般过去时]	[一般过去时的时间状语]
[just now,用于一般过去时]	[just now]
[just now]	[just]
[just now]	[now]
[just]	[单词]
[keen]	[单词]
[keep a secret]	[keep]
[keep a secret]	[secret]
[keep doing]	[v-ing习语]
[keep doing]	[keep]
[keep off]	[keep]
[keep off]	[off]
[keep,是系动词]	[keep]
[keep,是系动词]	[系动词]
[keep]	[单词]
[keep+…+形容词]	[keep]
[keep+…+形容词]	[动词+…+形容词]
[keep+形容词]	[系动词+形容词]
[keep+形容词]	[keep,是系动词]
[keep…doing]	[v-ing习语]
[keep…doing]	[keep]
[key to]	[to,介词]
[key to]	[key]
[key]	[单词]
[know,及物动词]	[及物动词]
[know,及物动词]	[know]
[know]	[单词]
[last]	[单词]
[late,副词instances]	[副词instances]
[late,副词instances]	[late]
[late]	[单词]
[laugh at]	[at,介词]
[laugh at]	[laugh]
[laugh]	[单词]
[least]	[单词]
[leave a message]	[leave]
[leave a message]	[message]
[leave for]	[leave]
[leave for]	[for,介词]
[leave]	[单词]
[left]	[单词]
[lend]	[单词]
[less]	[单词]
[let sb down]	[down]
[let sb down]	[let]
[let,不定式]	[let]
[let]	[单词]
[let's]	[us]
[let's]	[let]
[let's+反义疑问词]	[let's]
[let's+反义疑问词]	[反意疑问句]
[lie]	[单词]
[lie->lying,现在分词]	[lying]
[lie->lying,现在分词]	[v+ing构成]
[lie->lying,现在分词]	[lie]
[light up]	[up]
[light up]	[light]
[light]	[单词]
[like to do]	[like]
[like to do]	[不定式习语]
[like,介词]	[like]
[like,介词]	[介词]
[like]	[单词]
[like…better]	[well->better,比较级]
[like…better]	[like]
[listen to music,listen to the music]	[music,不可数名词instances]
[listen to music,listen to the music]	[listen to]
[listen to]	[to,介词]
[listen to]	[listen]
[listen]	[单词]
[little]	[不定代词]
[little]	[单词]
[little+不可数名词]	[不可数名词修饰语]
[little+不可数名词]	[little]
[little->least,最高级]	[形容词和副词最高级构成]
[little->least,最高级]	[least]
[little->least,最高级]	[little]
[little->less,比较级]	[less]
[little->less,比较级]	[形容词副词比较级构成]
[little->less,比较级]	[little]
[lonely,形容词instances]	[形容词instances]
[lonely,形容词instances]	[lonely]
[lonely]	[单词]
[long]	[单词]
[look after]	[look]
[look after]	[after,介词]
[look for]	[for]
[look for]	[look]
[look forward to doing]	[v-ing习语]
[look forward to doing]	[look forward to]
[look forward to]	[forward]
[look forward to]	[to,介词]
[look forward to]	[look]
[look out]	[out]
[look out]	[look]
[look over]	[over]
[look over]	[look]
[look through]	[through]
[look through]	[look]
[look up]	[up]
[look up]	[look]
[look,是系动词]	[系动词]
[look,是系动词]	[look]
[look]	[单词]
[look+like+名词]	[like,介词]
[look+like+名词]	[look]
[look+形容词]	[系动词+形容词]
[look+形容词]	[look,是系动词]
[lovely,-ly结尾的形容词]	[-ly结尾的形容词]
[lovely,-ly结尾的形容词]	[lovely]
[lovely]	[单词]
[lying]	[单词]
[-ly结尾的形容词]	[形容词]
[mad at]	[mad]
[mad at]	[at,介词]
[mad]	[单词]
[make a decision]	[make]
[make a decision]	[decision]
[make friends with]	[make]
[make friends with]	[with,介词]
[make friends with]	[friend]
[make it+名词]	[make]
[make noise]	[make]
[make noise]	[noise]
[make oneself heard]	[make]
[make oneself heard]	[oneself]
[make oneself heard]	[v-ed习语]
[make up]	[make]
[make up]	[up]
[make,不定式]	[make]
[make,不定式]	[不加to的动词不定式]
[make,及物动词]	[make]
[make,及物动词]	[及物动词]
[make]	[单词]
[make+sth+形容词]	[make]
[make…one's home]	[make]
[make…one's home]	[home]
[man,名词复数]	[man]
[man,名词复数]	[不规则可数名词.复数]
[man]	[单词]
[many]	[单词]
[many+可数名词]	[many]
[many+可数名词]	[可数名词修饰语]
[many->more,比较级]	[形容词副词比较级构成]
[many->more,比较级]	[more]
[many->more,比较级]	[many]
[matter]	[单词]
[May I…,疑问句]	[一般疑问句]
[May I…,疑问句]	[may,情态动词]
[may,情态动词]	[情态动词]
[may,情态动词]	[may]
[may]	[单词]
[may疑问句,应答句]	[表示请求,应答句]
[may疑问句,应答句]	[May I…,疑问句]
[me,人称代词宾格]	[人称代词宾格]
[me,人称代词宾格]	[me]
'''
}
