package ots

class SampleData_QuestionMapping4 {

	String content ='''[21873]	David talked with a friend of ____ on the Internet for a long time yesterday.	[a/an+可数名词+of+名词所有格]
[21868]	David suddenly felt nervous. ____, it was his first time to go on stage.	[after all]
[21863]	David often ____ to the movies on weekends. He likes action movies.	[often,用于一般现在时]
[21853]	David is a good boy. He always makes ____ mistakes than others.	[few->fewer,比较级]
[21853]	David is a good boy. He always makes ____ mistakes than others.	[few+可数名词]
[21834]	David doesn't know ____ for Guangzhou, because the boss hasn't decided who to go.	[if,宾语从句连接词]
[21829]	David didn't give up ____ he had failed in the experiment four-times.	[though,引导让步状语从句]
[21824]	David Burt's dream in China is to go into the west and ____ an early childhood school there.	[set up]
[21819]	David Beckham decided to ____ playing football match forever because he is not energetic enough.	[give up]
[21815]	David ____ his friend's invitation to the picnic in order to stay at home and have a good rest.	[情境语义]
[21800]	Dave had ____ friends here, so he often stays at home by himself and feels lonely.	[辨析:few,a few]
[21791]	Danny did all kinds of things to make the baby ____.	[make,不定式]
[21791]	Danny did all kinds of things to make the baby ____.	[stop to do,stop doing]
[21786]	Daniel, you are not ____ what I'm saying! What are you doing?	[listen to]
[21782]	Daniel could ____ hear what the teacher said because he just sat in the front of the classroom.	[副词instances]
[21767]	Dad, you have worked for three hours. Stop ____ and have a rest, please.	[stop to do,stop doing]
[21762]	Dad, I'm sorry I haven't passed the English exam this time. But I ____.	[do one's best]
[21757]	Dad ____ the USA in two weeks.	[现在进行时]
[21757]	Dad ____ the USA in two weeks.	[leave for]
[21747]	Could you tell me what ____ it is today?	[情境语义]
[21743]	Could you tell me the way ____ the zoo?	[to,介词]
[21738]	Could you tell me how long ____ the football club?	[延续性动词,用于现在完成时]
[21738]	Could you tell me how long ____ the football club?	[how long,宾语从句连接词]
[21719]	Could you tell me ____?	[where,宾语从句连接词]
[21694]	Could you tell me ____ a meeting in Guangzhou next week?	[there be句型]
[21694]	Could you tell me ____ a meeting in Guangzhou next week?	[could you…,引导的主句]
[21684]	Could you record the football game for me? I can watch ____ later.	[one,it]
[21679]	Could you please tell us ____ in Shanghai?	[when,宾语从句连接词]
[21674]	Could you please tell me ____? I want to see him right now.	[could you…,引导的主句]
[21669]	Could you please tell me ____?	[when,宾语从句连接词]
[21659]	Could you please lend me some money? I've run out of ____.	[run out]
[21659]	Could you please lend me some money? I've run out of ____.	[of,介词]
[21659]	Could you please lend me some money? I've run out of ____.	[mine,名词性物主代词]
[21654]	Could you please give some ____ to the ____ teachers?	[复合名词.复数]
[21654]	Could you please give some ____ to the ____ teachers?	[give advice]
[21649]	Could you please get me some ____? I'm hungry.	[情境语义]
[21635]	Could tell me ____?	[where,宾语从句连接词]
[21626]	Could please tell me ____?	[could you…,引导的主句]
[21621]	Could I have an early morning call ____ six o'clock tomorrow?	[表示时间:at,in,on]
[21616]	Connie arrived ____ the village ____ a snowy night.	[表示时间:at,in,on]
[21616]	Connie arrived ____ the village ____ a snowy night.	[arrive at]
[21611]	Congratulations, John! I'm really happy ____ you.	[be happy for]
[21606]	Computers, however, are actually ____ they were five years ago.	[形容词和副词比较级]
[21581]	Come, ____ you'll be late.	[祈使句+or+陈述句]
[21577]	Come on, Sue! Here's ____ about the English Speech Contest.	[something+形容词]
[21572]	Colors can change our moods (情绪) and make us ____ happy or sad, energetic or sleepy.	[make,不定式]
[21567]	College students are old enough to teach ____.	[themselves,反身代词]
[21553]	Cindy, do you have ____ e-mail address? I want to send you some photos.<\\n>Yes, I do. It's cindy126@sohu.com.	[字母,读音以元音开头]
[21548]	Cindy is ____ amazing singer. She has lots of fans.	[an+元音开头的词]
[21543]	Cici enjoys dancing. It's one of her ____.	[one of + 名词复数]
[21509]	Chinese ____ by the largest number of people.	[一般现在时的被动语态]
[21505]	Chinese ____ by more and more people in the world.	[一般现在时的被动语态]
[21495]	Chinese ____ by more and more people from all over the world today.	[一般现在时的被动语态]
[21490]	China plans to let tourists ____ the Xisha Island in the South China Sea this year.	[let,不定式]
[21485]	China lies ____ the east of Asia.	[表示方位:in,on,to]
[21470]	China is very ____ the Great Wall and pandas.	[be famous for]
[21465]	China is trying to find ways to take care of the children ____ parents have left their homes to work in cities.	[whose,引导的定语从句]
[21460]	China is larger than ____ in Africa.	[than any…]
[21455]	China is developing ____ of all the countries in the world.	[形容词和副词最高级]
[21450]	China is a great country with 56 peoples, ____ is the Han.	[which,引导的定语从句]
[21445]	China has offered much help to Japan since it ____ by the earthquake and tsunami (海啸).	[since+一般过去时,主句用现在完成时]
[21445]	China has offered much help to Japan since it ____ by the earthquake and tsunami (海啸).	[一般过去时的被动语态]
[21440]	China has ____ area of about 9600000 square kilometres.	[an+元音开头的词]
[21432]	China ____ a lot since the reform and opening-up.	[since+过去时间点,用于现在完成时]
[21427]	Children like houses ____ are painted in different colours.	[which,引导的定语从句]
[21412]	Chiang Mai (清迈) has been one of ____ tourist places for Chinese since the movie Lost in Thailand (《泰囧》) was shown.	[one of + the + 形容词和副词最高级]
[21402]	Chen Guangbiao says he ____ all his money to charities when he dies.	[一般将来时]
[21402]	Chen Guangbiao says he ____ all his money to charities when he dies.	[时间状语从句用一般现在时表示将来]
[21392]	Charlie can't go with us because he ____ a professor around our company.	[现在进行时]
[21383]	CCTV-10 often plays ____ around the world. It can help us learn more about not only nature but also different cultures and customs.	[something+形容词]
[21378]	Cathy was born blind so she has ____ seen our beautiful world.	[never,频率副词]
[21368]	Cathy did quite ____ in the English competition, I did even ____.	[do well in…]
[21368]	Cathy did quite ____ in the English competition, I did even ____.	[even+形容词副词比较级]
[21353]	Carl felt ____ because he won the first prize in the school singing competition.	[情境语义]
[21348]	Captain Alison will ____ at eight o'clock, so we shall have plenty of time.	[set out]
[21343]	Cao Wenxuan's new book has just ____. Let's go and buy one.	[come out]
[21333]	Can you tell me ____?	[宾语从句语序]
[21313]	Can you tell me ____ after this exam?	[宾语从句语序]
[21303]	Can you see ____?	[宾语从句语序]
[21298]	Can you see ____ sun at night?	[sun,独一无二的事物]
[21293]	Can you pass my glasses to me, Betty? I can ____ see the words on the blackboard.	[hardly,频率副词]
[21283]	Can you imagine what life will be like in ____ time?	[名词复数的所有格]
[21283]	Can you imagine what life will be like in ____ time?	[名词所有格]
[21278]	Can you imagine that ____ little ants can carry ____many big worms?	[so+形容词副词]
[21278]	Can you imagine that ____ little ants can carry ____many big worms?	[such+可数名词]
[21268]	Can you go and find out when the plane to New York ____?	[take off]
[21233]	Can I take Lisa to the aquarium tomorrow? If she ____ there, she ____ a good time.	[一般将来时]
[21233]	Can I take Lisa to the aquarium tomorrow? If she ____ there, she ____ a good time.	[时间状语从句用一般现在时表示将来]
[21228]	Can I have ____ look at the photo of your pen friend?	[have a look at]
[21218]	By the time I got to the cinema, the movie ____ for ten minutes.	[by the time+一般过去时,主句用过去完成时]
[21218]	By the time I got to the cinema, the movie ____ for ten minutes.	[for+一段时间]
[21213]	By the end of last month, I ____ all the CDs of Justin Bieber.	[by the end of+过去时间点,用于过去完成时]
[21208]	By reading the article, we know how ____ in our daily life.	[宾语从句语序]
[21198]	British people eat ____ a lot, and they are cooked in different ways.	[规则可数名词.复数]
[21193]	Bring these flowers into a warm room ____ they'll soon open.	[祈使句+and+陈述句]
[21188]	Brian is so kind that he often gives me a ____ when I'm in trouble.	[give sb a hand]
[21178]	Breakfast is ____ meal of the day. It provides us with energy after a long night without food.	[形容词和副词最高级]
[21174]	Boys and girls, the books in the library should ____ good care of.	[take care of]
[21174]	Boys and girls, the books in the library should ____ good care of.	[should,被动语态]
[21169]	Boys and girls, please stop ____ so much noise. It's time for class.	[make noise]
[21169]	Boys and girls, please stop ____ so much noise. It's time for class.	[stop to do,stop doing]
[21165]	Boys and girls, feeling peaceful is the first step to become ____ in the exams. So please take a deep breath and calm down.	[情境语义]
[21160]	Boys and girls, don't forget your report. It ____ today.	[should,被动语态]
[21156]	Boys and girls, calm down and focus on the test paper ____ you begin to think about the answers. Be confident. You can do it!	[as soon as,引导时间状语从句]
[21151]	Both parents were born ____ 1970.	[表示时间:at,in,on]
[21121]	Books are made ____ paper while paper is mainly made ____ wood.	[be made from]
[21121]	Books are made ____ paper while paper is mainly made ____ wood.	[be made of]
[21101]	Bob used to be a problem child, but his mother was very patient and didn't [stop] trying to help him.	[give up doing]
[21101]	Bob used to be a problem child, but his mother was very patient and didn't [stop] trying to help him.	[stop to do,stop doing]
[21096]	Bob told me that his next match was against ____ team from another school.	[a]
[21096]	Bob told me that his next match was against ____ team from another school.	[名词所有格]
[21086]	Bob often says that swimming is ____ than hiking in reducing weight, but he always spends more time on swimming.	[形容词副词比较级构成]
[21057]	Bob hurt his ____ yesterday, he can't walk now.	[情境语义]
[21048]	Billy can make hamburgers, ____ he can't make salad.	[but,连词]
[21028]	Bill was ill last night, so his father went to the town to ____ a doctor.	[情境语义]
[21019]	Bill likes playing ____ basketball, but he doesn't like playing ____ piano.	[piano,是乐器]
[21019]	Bill likes playing ____ basketball, but he doesn't like playing ____ piano.	[basketball,是球类棋类]
[21005]	Bill has made great progress ____ the help of his teachers.	[with the help of]
[21000]	Bill asked me ____ the songs. He wanted to listen to the pop music.	[ask…to do]
[21000]	Bill asked me ____ the songs. He wanted to listen to the pop music.	[stop to do,stop doing]
[20990]	Betty will ring me up when she ____ in Shanghai.	[时间状语从句用一般现在时表示将来]
[20985]	Betty will ring me up when she ____ in Beijing.	[时间状语从句用一般现在时表示将来]
[20955]	Ben was busy taking a training class. ____ we had to wait for him for half an hour..	[so,连词]
[20950]	Ben was busy taking a training class, ____ we had to wait for him for half an hour.	[so,连词]
[20930]	Being honest is the first ____ if you want to make friends with others.	[情境语义]
[20925]	Being blind is something ____ most people can't imagine.	[something,后接that定语从句]
[20920]	Beijing, the capital of China, is one of ____ cities in the world.	[one of + the + 形容词和副词最高级]
[20915]	Beijing, ____ capital of China, has ____ long history.	[a]
[20915]	Beijing, ____ capital of China, has ____ long history.	[the]
[20900]	Beijing is ____ capital of China and it is ____ city with many places of interest.	[a]
[20900]	Beijing is ____ capital of China and it is ____ city with many places of interest.	[the]
[20895]	Before the bridge was built ____ the river, the villagers had to take a boat to the other side.	[across,介词]
[20890]	Before going to the History Museum, our teacher told us ____ the public rules.	[tell…to do]
[20885]	Beef noodles in Lanzhou taste the best in China and ____.	[sell well]
[20880]	Because of the bad weather, we have to ____ the meeting till next week.	[put off]
[20875]	Be sure to let Tom know the notice as soon as he ____.	[时间状语从句用一般现在时表示将来]
[20870]	Be sure to ____ your names before you hand in your papers.	[write down]
[20850]	Be careful, ____ you'll miss the right answer.	[祈使句+or+陈述句]
[20835]	Be careful to look ____ ways before you cross the street.	[both,形容词instances]
[20825]	Basketball is a kind of ____ sport. You can't win the match by yourself.	[情境语义]
[20820]	Basketball has a history of nearly 300 years. Today it is still loved by ____ the young ____ the old.	[both…and,是并列结构连词]
[20802]	Bamboo can ____ paper.	[be used to do]
[20797]	Ba Jin, one of the greatest writers in China, ____ as People's Writer.	[be regarded as]
[20767]	Auatar (阿凡达) is such ____ wonderful science fiction movie that I want to see it ____ second time．	[such+可数名词]
[20767]	Auatar (阿凡达) is such ____ wonderful science fiction movie that I want to see it ____ second time．	[a second time]
[20757]	Attention, please! There will ____ a class meeting ____ the morning of the May 4th.	[there be句型]
[20757]	Attention, please! There will ____ a class meeting ____ the morning of the May 4th.	[表示时间:at,in,on]
[20732]	At the end of the volleyball match, our school ____ won by 3:1.	[情境语义]
[20712]	At present, blogs are ____ traditional diaries (日记) among young people.	[much+形容词副词比较级]
[20702]	At least 300 million people are using QQ ____ by Ma Huateng to chat on line.	[v-ed]
[20697]	At least 24 people ____ in the earthquake in Yingjiang on March 10th.	[一般过去时的被动语态]
[20692]	At last the boy was made ____ and began to laugh.	[be made to do sth]
[20692]	At last the boy was made ____ and began to laugh.	[stop to do,stop doing]
[20672]	As young adults, it is our ____ to try our best to deal with each challenge in our education with the help of our teacher.	[It is our duty to do]
[20672]	As young adults, it is our ____ to try our best to deal with each challenge in our education with the help of our teacher.	[情境语义]
[20667]	As we know, the Huanghe River is one of ____ rivers in our country.	[one of + the + 形容词和副词最高级]
[20663]	As we know, the Changjiang River is one of ____ rivers in the world.	[one of + the + 形容词和副词最高级]
[20653]	As we all know, smoking is bad for us, ____ for children.	[副词instances]
[20649]	As we all know, planting trees is good for the environment. Our class will go to the Sun Island tomorrow. As soon as we ____ there, we'll begin to plant trees.	[时间状语从句用一般现在时表示将来]
[20644]	As we all know, it's not polite to keep others ____ for a long time.	[keep doing]
[20624]	As usual he got up ____ this morning.	[late,副词instances]
[20620]	As teenagers, we're old enough ____ with housework. We can help set the table, wash the dishes and clean our own rooms.	[不定式]
[20615]	As students, we should always be ready to help ____ whenever they are in trouble.	[others]
[20610]	As soon as he ____ the bus, the poor man realized he had left his wallet on it.	[get off]
[20605]	As one of the school rules, middle school students are not ____ to smoke.	[be allowed to do]
[20595]	As for learning English, students who read a lot can do much better than ____ who don't.	[than those…]
[20590]	As close friends, they used to walk to school ____.	[side by side]
[20585]	As a middle school students, we should start thinking about ____ for our country in the future.	[what,宾语从句连接词]
[20570]	Around the world more and more people are ____ dangerous sports activities, because life in modern societies has become safe and boring.	[take part in]
[20550]	Anyone who sings well can ____ the activity in our school.	[take part in]
[20540]	Another two months will be needed before the new bridge ____.	[时间状语从句用一般现在时表示将来]
[20540]	Another two months will be needed before the new bridge ____.	[一般现在时的被动语态]
[20536]	Another new railway station ____ in Changsha in 2011.	[一般将来时的被动语态]
[20526]	Another new fiction by HanHan is being printed and it will soon ____.	[come out]
[20521]	Ann's wedding is coming. Many friends ____ to her wedding party this Sunday.	[一般将来时的被动语态]
[20511]	Annie ____ to the party. She had a wonderful time with us.	[一般过去时的被动语态]
[20502]	Anna ____ the piano when I went to see her mother.	[主句和从句,一般时和进行时]
[20497]	Ann often helps me ____ math after school.	[help sb with sth]
[20483]	Angel [is keen on] all kinds of pop music. The underlined part means ____.	[be keen on]
[20483]	Angel [is keen on] all kinds of pop music. The underlined part means ____.	[be keen on<->be fond of]
[20473]	Andy often helps her mother ____ the housework on Sunday afternoon.	[help sb with sth]
[20468]	Andrea Bocelli never ____, which makes him a successful singer.	[give up]
[20458]	An official ____ by some reporters on food problems in Shanghai yesterday.	[一般过去时的被动语态]
[20443]	Amy, I'll be on holiday for a week. Could you help me ____ my dog?	[look after]
[20439]	Amy will have her ____ birthday party next Friday.	[形容词性物主动词+序数词]
[20414]	Although you may meet some difficulties, you should never ____.	[give up]
[20385]	Although Lucy is only three years old, she is able to ____ herself.	[dress,put on,wear]
[20381]	Although it rained ____, Yao Ming's fans still waited for him outside the hotel.	[副词instances]
[20377]	Although I failed four times, my father encouraged me to have a ____ try.	[a+序数词]
[20372]	Although he's now an old man, he's ____ very lively.	[still,并列结构的连词]
[20352]	Although he is considered a great writer, ____.	[although,but不可一起使用]
[20347]	Although he is ____ old man, he can go to ____ university for the old.	[an+元音开头的词]
[20347]	Although he is ____ old man, he can go to ____ university for the old.	[university,是非元音开头的词]
[20342]	Allen, let me have ____ look at your new car, OK?	[have a look at]
[20323]	All the students have gone home ____ Tom, so he feels lonely in the school.	[排除:besides,except,but,except for]
[20294]	All the ____enjoyed themselves on March 8th because it was their own holiday.	[复合名词.复数]
[20289]	All the ____ teachers enjoyed themselves on March 8th, because it was their own holiday.	[woman teacher,复数]
[20285]	All the ____ in our school enjoyed themselves on March 8th because it was their own holiday.	[woman teacher,复数]
[20280]	All of us will be happy ____ you can come with us.	[if,引导条件状语从句]
[20276]	All of us went to the park ____ Bob. He had to look after his sister.	[排除:besides,except,but,except for]
[20271]	All of us want to do more work with ____ time and ____ workers.	[few->fewer,比较级]
[20271]	All of us want to do more work with ____ time and ____ workers.	[little+不可数名词]
[20271]	All of us want to do more work with ____ time and ____ workers.	[few+可数名词]
[20271]	All of us want to do more work with ____ time and ____ workers.	[little->less,比较级]
[20266]	All of us find ____ necessary to take exercise every day.	[find it+形容词+to do]
[20262]	All of us find ____ necessary to eat healthy food to keep fit.	[find it+形容词+to do]
[20257]	All of us find ____ difficult to put up the machine.	[find it+形容词+to do]
[20252]	All of us are proud of the great changes in Shanghai. We're sure Shanghai will be even ____ tomorrow.	[even+形容词副词比较级]
[20227]	All Chinese people [raised] money for the people in Yunnan.	[情境语义]
[20217]	Alice in Wonderland is a fantastic movie. It's about ____.	[how,宾语从句连接词]
[20212]	Alice in Wonderland ____ for 15 days and many of us like the film very much.	[for+一段时间]
[20207]	Alice had a wonderful time yesterday, ____?	[反意疑问句]
[20197]	Alice explains things very well, what she says can be understood very ____.	[情境语义]
[20187]	Alice ____ watches the news round-up, so she knows little about the world.	[seldom,频率副词]
[20178]	Alex has beaten the other people at the class competition, so he's [top dog].	[情境语义]
[20163]	Again and again, the doctor ____ the boy, but he couldn't find out what was wrong with him.	[look over]
[20158]	After winning the badminton championship at Wuhan Sports Center in May, the Chinese players' faces ____ with joy.	[light up]
[20149]	After walking for four hours, he was ____ tired ____ move on.	[too…to]
[20144]	After trying many times, we got successful [in the end].	[at last]
[20144]	After trying many times, we got successful [in the end].	[in the end]
[20139]	After the students ____ their exams, they celebrated by having a party.	[pass one's exam]
[20135]	After the meeting, we will have a party. If you ____ free, come and join us.	[条件状语从句,时态]
[20131]	After the final exams, Changchang, ____ her mother, is going to travel to Canada instead of staying at home all the times.	[with,主谓一致]
[20127]	After the earthquake, the injured (受伤的) people ____ to the hospitals in the neighboring cities.	[一般过去时的被动语态]
[20122]	After the earthquake in Japan, we are trying to help the ____ people to rebuild their homes.	[情境语义]
[20108]	After the Asian Games, ____ people came to Guangzhou for a visit during holidays.	[thousands of…]
[20103]	After so many years' hard work, Zhao Hongbo and Shen Xue's dream ____ in 2010 Vancouver Winter Olympic Games.	[come true]
[20098]	After several campus (校园) attacks, many schools across the country have already taken action ____ their campuses ____.	[不定式,句子成分]
[20088]	After moving to their new house, the Lees bought some ____ in the mall nearby.	[情境语义]
[20084]	After lunch she ____ the dishes and went out quickly.	[take away]
[20079]	After hours of discussion, the plan ____.	[agree to]
[20079]	After hours of discussion, the plan ____.	[一般过去时的被动语态]
[20064]	After having breakfast, he ____ to the bus stop this morning.	[run off]
[20059]	After hard training for a long time, Liu Xiang ____ the records again.	[break the record]
[20054]	After Donghai Bridge ____, it became a new tourist attraction.	[一般过去时的被动语态]
[20054]	After Donghai Bridge ____, it became a new tourist attraction.	[after,引导时间状语从句]
[20049]	After discussing, the students ____ some good ideas to work on the project.	[come up with]
[20040]	According to the library rules, books ____ for two weeks at most.	[for+一段时间]
[20035]	According to the latest reports on TV and in the newspaper, food safety is becoming a ____ serious worldwide problem.	[比较级 + and + 比较级]
[20010]	About ____ of the workers in the factory were born in the ____.	[分数作主语,主谓一致]
[20010]	About ____ of the workers in the factory were born in the ____.	[世纪年代]
[19996]	About ____ of the students in our class were born in the ____.	[分数作主语,主谓一致]
[19996]	About ____ of the students in our class were born in the ____.	[世纪年代]
[19987]	About ____ fans went to the airport to welcome Yao Ming back to China.	[thousand,基数词]
[19917]	A woman with two children ____ along the street at the moment.	[with,主谓一致]
[19913]	A typhoon hit this area with heavy rains and winds ____ strong as what happened in 2008.	[as...as,引导比较状语从句]
[19908]	A tsunami (海啸) happened in some southern Asian countries ____ December, 2004.	[表示时间:at,in,on]
[19903]	A true friend can see the pain in your eyes ____ everyone else believes the smile on your face.	[while,引导让步状语从句]
[19898]	A traffic jam will make it possible for most drivers to sit and wait ____.	[情境语义]
[19893]	A tourist will easily lose his way in Beijing ____ he has a map or a guide.	[unless,引导条件状语从句]
[19888]	A terrible earthquake happened in Japan ____ March, 2011.	[表示时间:at,in,on]
[19878]	A talk on science ____ in our school next Monday.	[一般将来时的被动语态]
[19854]	A student in Fudan University was killed by his roommate just because of small things in daily life. It is important for students to learn how to ____ each other.	[get on with]
[19844]	A smile costs nothing, but gives so ____.	[情境语义]
[19839]	A school in Anshun held an activity called Recommend (推荐) Books to Your Teachers. The students made a ____ of 1000 books!	[情境语义]
[19819]	A number of tourists ____ Yangzhou many times because it is such a beautiful city.	[have been to,have gone to,have been in]
[19819]	A number of tourists ____ Yangzhou many times because it is such a beautiful city.	[a number of+复数名词,主谓一致]
[19815]	A number of students ____ playing on the playground, and the number of students in our school ____ increasing.	[the number of+复数名词,主谓一致]
[19815]	A number of students ____ playing on the playground, and the number of students in our school ____ increasing.	[a number of+复数名词,主谓一致]
[19791]	A new road was built between our village and the town. ____ road is wide and clean.	[the]
[19787]	A new hospital ____ in my hometown last year．	[一般过去时的被动语态]
[19783]	A new factory is being built in Neijiang. I hope it ____ at the end of this year.	[一般将来时的被动语态]
[19773]	A new club ____ in our school at the beginning of this year and now it has many members.	[一般过去时的被动语态]
[19753]	A moment, please. I'm checking if Mr. Smith ____ free tomorrow.	[tomorrow,用于一般将来时]
[19753]	A moment, please. I'm checking if Mr. Smith ____ free tomorrow.	[主句现在时]
[19744]	A low-carbon (低碳) lifestyle has ____ effect on our daily life. People are paying more and more attention to saving ____ these days.	[energy,不可数名词instances]
[19744]	A low-carbon (低碳) lifestyle has ____ effect on our daily life. People are paying more and more attention to saving ____ these days.	[an+元音开头的词]
[19734]	A lot of trees ____ around here every year, and we can enjoy fresher air now.	[一般现在时的被动语态]
[19729]	A lot of tourists will come to Meizhou to visit Hake Museum tomorrow, ____ you'd better get up early if you want to visit it.	[so,连词]
[19709]	A lot of new roads ____ built in the west of China.	[must,被动语态]
[19704]	A lot of foreigners ____ familiar with the famous places of interest in China.	[familiar with]
[19704]	A lot of foreigners ____ familiar with the famous places of interest in China.	[be+形容词]
[19699]	A lot of famous doctors gathered in Harbin ____ save China's most beautiful teacher -- Ms Zhang Lili.	[in order to do]
[19690]	A large number of engineers ____ to Africa by our government to help the people there every year.	[一般现在时的被动语态]
[19685]	A human brain can do some things, such as creating new ideas, ____ than a computer.	[形容词和副词比较级]
[19675]	A great meeting about weather change ____ in Copenhagen (哥本哈根) in December, 2009.	[take place]
[19660]	A good friend always gives you a helping hand ____ you're in trouble.	[when,引导时间状语从句]
[19655]	A good beginning makes ____ good ending.	[a]
[19650]	A friend is someone ____ says, what! You too? I thought I was the only one!	[who,引导的定语从句]
[19645]	A foreign visitor is coming to visit our new house this evening. My mother will offer him ____ to eat.	[something,复合不定代词]
[19640]	A Disneyland Park ____ in Shanghai Pudong New Area in the near future.	[一般将来时的被动语态]
[19635]	A direct order like Daisy, pass me the book sounds rude. We'd better say: ____	[情境语义]
[19626]	A country has dream. We teenagers ____ also have dreams. With dreams and hard work, anything amazing can be created.	[must,should,ought to]
[19622]	A blog (博客) is considered as an invention ____ can express your own idea and feelings freely. It's the room to communicate with other people.	[that,引导的定语从句]
[19612]	A big party was held in NO.18 Middle School last night, the teacher with students ____ singing and dancing happily at the party.	[with,主谓一致]
[19612]	A big party was held in NO.18 Middle School last night, the teacher with students ____ singing and dancing happily at the party.	[一般过去时]
[19608]	A big earthquake hit Japan ____ the afternoon of March 11th, 2011.	[表示时间:at,in,on]
[19603]	A 100-year-old man ran a marathon in Toronto on Sunday. He became the ____ person to complete the long-distance running in the world.	[情境语义]
[19599]	A ____ girl named Dong Xinyi looked after her disabled father.	[three-year-old]
[19594]	____Greens are preparing for the coming Thanksgiving Day.	[the+姓氏,主谓一致]
[19585]	____, volunteering is both a chance to help others and a good way to develop ourselves. So you'd better make time to volunteers.	[to be honest]
[19576]	____, the healthier you will be.	[比较级 + and + 比较级]
[19576]	____, the healthier you will be.	[情境语义]
[19566]	____, is there a restaurant in the neighborhood?	[情境语义]
[19552]	____ Zhai Xiaowei has only one leg, he can dance wonderfully.	[though,引导让步状语从句]
[19547]	____ you're tasted it, you can't imagine how delicious the dishes are.	[unless,引导条件状语从句]
[19542]	____ your sunglasses, Sally. The sun is so bright.	[put on]
[19537]	____ your name on the paper and you can get a magazine.	[put down]
[19532]	____ your help, I passed the exam.	[thanks to]
[19522]	____ you wait a few more minutes? It'll be your turn soon.	[could,情态动词]
[19517]	____ you told me, I had heard nothing of what happened.	[not…until]
[19513]	____ you please sing us an English song?	[Would you please,疑问句]
[19508]	____ you please give me a hand? The box is too heavy.	[could,情态动词]
[19503]	____ you have tried it on, you can't imagine how pretty the new style skirt is.	[unless,引导条件状语从句]
[19499]	____ you have to wear a uniform at school?	[一般疑问句]
[19490]	____ you don't go to bed earlier, you will feel tired in the morning.	[if,引导条件状语从句]
[19486]	____ you don't give up, your dreams will come true.	[as long as,引导条件状语从句]
[19476]	____ you do, don't miss this exhibition, for it's so hard for me to get the tickets.	[whatever,引导让步状语从句]
[19471]	____ you ____ your brother can join us. We want one of you.	[either…or,是并列结构连词]
[19466]	____ worried about me, Mom. I've grown up.	[be worried about]
[19466]	____ worried about me, Mom. I've grown up.	[don't…,祈使句的否定形式]
[19461]	____ wonderful Yang Liping's dance is!	[how引导的感叹句]
[19451]	____ wonderful news report he wrote! All of us were proud of him.	[what,引导的感叹句]
[19446]	____ wonderful concert they are putting on in the city square!	[what,引导的感叹句]
[19441]	____ woman in red had ____ baby on ____ Children's Day.	[冠词]
[19436]	____ woman in a purple skirt is Betty's mother.	[the]
[19422]	____ wide the streets are!	[how引导的感叹句]
[19412]	____ went hiking last weekend because of the bad weather.	[no one]
[19407]	____ weekdays, what time does your father get up?	[表示时间:at,in,on]
[19403]	____ weather it is! Let's go out and enjoy the sunshine.	[weather,不可数名词instances]
[19403]	____ weather it is! Let's go out and enjoy the sunshine.	[what,引导的感叹句]
[19398]	____ weather it is today! Let's go out for a walk.	[weather,不可数名词instances]
[19398]	____ weather it is today! Let's go out for a walk.	[what,引导的感叹句]
[19393]	____ we work, ____ we feel.	[the+比较级...the+比较级,引导比较状语从句]
[19388]	____ we don't save water, we will have no water to drink one day.	[if,引导条件状语从句]
[19383]	____ we deal with our problems, we can easily become unhappy.	[unless,引导条件状语从句]
[19379]	____ was born being good at all things. You can do well in things through hard work. As an English learner, you can't be excellent without enough practice.	[nobody,复合不定代词]
[19374]	____ Wang Shasha often acts in TV plays and movies, she does well in her schoolwork.	[although,引导让步状语从句]
[19369]	____ visitors come to China every year.	[thousands of…]
[19349]	____ trees will be planted on that mountain next spring.	[thousands of…]
[19345]	____ trees were cut down. And many birds lost their home.	[thousands of…]
[19340]	____ trees we paint, ____ our Mother Earth will be.	[the+比较级...the+比较级,引导比较状语从句]
[19335]	____ trees have been planted near here, so the air is very fresh.	[hundreds of…]
[19325]	____ Tony ____ Frank likes the CD. They think the music is too noisy.	[neither…nor,主谓一致]
[19320]	____ Tom ____ Peter are fond of watching TV.	[both…and,主谓一致]
[19315]	____ Tom ____ Mary speaks good Chinese, so they can communicate with these Chinese students very well.	[not only…but also,主谓一致]
[19311]	____ to some fruits, Mum said to my friends.	[help oneself to…]
[19311]	____ to some fruits, Mum said to my friends.	[yourselves,反身代词]
[19306]	____ this rock music, please. I'm afraid some people can't stand the noise!	[祈使句]
[19301]	____ they may not succeed, they will try their best.	[though,引导让步状语从句]
[19296]	____ they are very tired, they feel happy because they've finally finished their project.	[although,引导让步状语从句]
[19286]	____ there were only five soldiers left at the front, ____ they went on fighting.	[though,but不可一起使用]
[19281]	____ the water was cold, Wei Qinggang jumped into it to save others.	[although,引导让步状语从句]
[19277]	____ the teacher, I've made great progress.	[thanks to]
[19272]	____ the sun's heat or light, there would be no life on the earth.	[without,介词]
[19267]	____ the program, I'm beginning to understand my Chinese roots and I have so many memories of China to take with me.	[thanks to]
'''
}
