package ots

class SampleData_QuestionMapping6 {

	String content ='''[17054]	— Would you come to my birthday party tomorrow evening?<\\n>— I'm afraid I ____. I have to look after my sister.	[Would you like to do sth,应答句]
[17044]	— Wish you good luck in this English exam.<\\n>— ____	[祝愿祝福,应答句]
[17039]	— Wish you good luck in the exam.<\\n>— ____.The same to you.	[祝愿祝福,应答句]
[17034]	— Wish you a pleasant journey!<\\n>— Thanks! I'll give you a ____ as soon as I arrive in Paris.	[give sb a ring]
[17034]	— Wish you a pleasant journey!<\\n>— Thanks! I'll give you a ____ as soon as I arrive in Paris.	[情境语义]
[17024]	— Will you take part in the English speech competition tomorrow?<\\n>— Sure. I see as a chance to prove ____.	[prove oneself]
[17019]	— Will you stay for some more days?<\\n>— Sorry, I ____. My mother called to ask me to go back at once.	[can,be able to:辨析]
[16989]	— Will you please take a message for the headteacher?<\\n>— ____.	[Would you like to do sth,应答句]
[16955]	— Will you go to the London Olympic Games with your sister?<\\n>— Dad can only afford one ticket, so ____ of us has to stay at home	[either,不定代词]
[16950]	— Will you go to the concert after school?<\\n>— If Jenny ____ to the concert, I'll go, too.	[条件状语从句,时态]
[16950]	— Will you go to the concert after school?<\\n>— If Jenny ____ to the concert, I'll go, too.	[if,引导条件状语从句]
[16945]	— Will you go to the cinema, Mary?<\\n>— No, I'm afraid not. Because I ____ my ticket.	[非延续性动词,用于现在完成时]
[16940]	— Will you go and see the movie Net Mother with me?<\\n>— Thank you. But I ____ it already.	[already,用于现在完成时]
[16930]	— Will you come to the dinner party.<\\n>— I won't come unless Jenny ____.	[条件状语从句,时态]
[16930]	— Will you come to the dinner party.<\\n>— I won't come unless Jenny ____.	[unless,引导条件状语从句]
[16930]	— Will you come to the dinner party.<\\n>— I won't come unless Jenny ____.	[一般现在时的被动语态]
[16925]	— Will you come to Selina's birthday party?<\\n>— I won't come unless Jenny ____.	[条件状语从句,时态]
[16925]	— Will you come to Selina's birthday party?<\\n>— I won't come unless Jenny ____.	[if,引导条件状语从句]
[16920]	— Will you come to Salina's birthday party?<\\n>— I won't come unless Jenny ____.	[条件状语从句,时态]
[16920]	— Will you come to Salina's birthday party?<\\n>— I won't come unless Jenny ____.	[unless,引导条件状语从句]
[16920]	— Will you come to Salina's birthday party?<\\n>— I won't come unless Jenny ____.	[一般现在时的被动语态]
[16916]	— Will you come over for dinner on Monday or Tuesday?<\\n>— I'm afraid ____ day is OK. I'll fly to Paris on holiday for the whole week.	[neither,不定代词]
[16912]	— Will you come on Monday or Tuesday?<\\n>— I'm afraid ____ day is possible. I'll be busy next week.	[neither,不定代词]
[16908]	— Will you be able to finish your report today?<\\n>— ____.	[情境语义]
[16903]	— Will you be able to come and help us clean the room?<\\n>— ____, but I'm doing my homework.	[Would you like to do sth,应答句]
[16893]	— Will the new iphone cost a lot?<\\n>— I ____ think so. Apple's products are usually expensive.	[would,虚拟语气]
[16883]	— Will the foreigners have any problems talking with Chinese in Beijing in 2008?<\\n>— I don't think so. Now ____ the young ____ the old are learning to speak English.	[not only…but also,是并列结构连词]
[16873]	— Will Mary go to the movie with us?<\\n>— I don't think so. She ____ to go shopping.	[现在完成时]
[16873]	— Will Mary go to the movie with us?<\\n>— I don't think so. She ____ to go shopping.	[decide to do]
[16868]	— Will Liu Ying come to school today?<\\n>— I don't know. But I also want to know ____.	[if,宾语从句连接词]
[16863]	— Why would some workers in Foxcon die ____ continue working in the factory?<\\n>— Psychologists say they are under too much pressure.	[rather than,不定式]
[16859]	— Why not take a taxi home?<\\n>— Because I don't have any ____ with me.	[情境语义]
[16855]	— Why not stay for a few more minutes?<\\n>— ____. My parents will be worried.	[情境语义]
[16850]	— Why not go to the office and ask your teacher for help?<\\n>— I ____. But I didn't find her there.	[省略句]
[16845]	— Why not go to Qingdao on May Day, Jim?<\\n>— I'm afraid it's not a good ____. I have been there several times.	[表达建议/意见/观点,应答句]
[16840]	— Why not go out and have a picnic tomorrow, Simon?<\\n>— ____, but I will help Li Ming with his lessons. He is new here.	[Would you like to do sth,应答句]
[16830]	— Why not get your husband a CD player for his birthday?<\\n>— ____ That's too expensive.	[表达建议/意见/观点,应答句]
[16825]	— Why not ask Bob to join us in the school trip?<\\n>— I can't tell if he's able to. He's always ____ with his work.	[be busy with]
[16820]	— Why not ____ to the park now?<\\n>— Good idea! Let's go.	[why,不定式]
[16815]	— Why not ____ the music club?<\\n>— I'm sorry. I can't sing or dance.	[why,不定式]
[16810]	— Why not ____ John a toy car for his birthday?<\\n>— Good idea! He is crazy about cars.	[why,不定式]
[16795]	— Why is the traffic today moving so slowly? We are running late!<\\n>— Calm down. Let's take ____ route. Turn left over there.	[a]
[16780]	— Why is Linlin practicing speaking English?<\\n>— ____ abroad for further study.	[不定式,句子成分]
[16770]	— Why hasn't Mr. Li come to work today?<\\n>— ____ he has gone to Beijing to have a meeting.	[because,引导原因状语从句]
[16761]	— Why don't you like winter in Beijing?<\\n>— Because it is ____ winter in Guangzhou.	[情境语义]
[16751]	— Why don't you come and join us in the game?<\\n>— ____, but I must go to meet Mr. Smith at the airport.	[Would you like to do sth,应答句]
[16746]	— Why don't you choose the red tie?<\\n>— For me, it doesn't ____ my shirt very well.	[情境语义]
[16736]	— Why don't we take a little break?<\\n>— Didn't we just have ____?	[one,it]
[16726]	— Why do you speak in ____ a loud voice?<\\n>— Because I want to make myself ____ clearly.	[such+可数名词]
[16726]	— Why do you speak in ____ a loud voice?<\\n>— Because I want to make myself ____ clearly.	[make oneself heard]
[16717]	— Why do you like this story?<\\n>— Because it is so moving that it makes me ____.	[make,不定式]
[16707]	— Why do you like staying in Guiyang?<\\n>— Because the weather there is ____ too hot ____ too cold.	[neither…nor,是并列结构连词]
[16692]	— Why do you collect so many old bikes?<\\n>— I'll have them ____ and give away to the children who don't have bikes.	[fix up]
[16692]	— Why do you collect so many old bikes?<\\n>— I'll have them ____ and give away to the children who don't have bikes.	[have sth done]
[16687]	— Why do you always watch Channel 10 instead of Channel 5, Grandpa?<\\n>— The programs on Channel 10 are ____ better.	[much+形容词副词比较级]
[16682]	— Why do you always sleep ____?<\\n>— Because I'm afraid of the dark.	[情境语义]
[16677]	— Why do you always go to Lanzhou University on weekends?<\\n>— Because there're lots of great speakers I can practice English ____ in the English Corner there.	[with,介词]
[16672]	— Why do we eat vegetable every day, Mum?<\\n>— ____ healthy, my dear.	[keep+形容词]
[16672]	— Why do we eat vegetable every day, Mum?<\\n>— ____ healthy, my dear.	[不定式,句子成分]
[16657]	— Why didn't you go to play football with us yesterday afternoon?<\\n>— I ____ my mother with the housework then.	[过去进行时]
[16652]	— Why didn't you give me a call at that time?<\\n>— I ____. But nobody answered the phone.	[省略句]
[16642]	— Why didn't Betty come to school yesterday?<\\n>— ____ she was ill.	[because,引导原因状语从句]
[16637]	— Why did you vote for Maggie?<\\n>— Because she is very ____. She always shares things with others.	[情境语义]
[16627]	— Why did you laugh just now?<\\n>— Ted wanted to tell us ____ very funny story, but he forgot ____ end himself.	[a]
[16627]	— Why did you laugh just now?<\\n>— Ted wanted to tell us ____ very funny story, but he forgot ____ end himself.	[the]
[16617]	— Why are your parents so ____ with you today?<\\n>— Because I got an A in the English exam this time.	[be pleased with]
[16612]	— Why are you worried?<\\n>— I'm expecting a call from my daughter. She ____ New York for three days.	[have been to,have gone to,have been in]
[16608]	— Why are you unhappy, Kate?<\\n>— I didn't finish my homework again. I'm afraid Miss Gao will be ____ me.	[be angry with]
[16603]	— Why are you unhappy, Ben?<\\n>— I was late for class again. I'm afraid Miss Li will be ____ me.	[be angry with]
[16598]	— Why are you still waiting in line?<\\n>— I've missed my ____.	[情境语义]
[16593]	— Why are you standing, Alice?<\\n>— I can't see the blackboard clearly. Two tall boys are sitting ____me.	[in front of,复合介词]
[16588]	— Why are you standing, Alice?<\\n>— I can't see the blackboard clearly. Two tall boys are sitting ____ me.	[in front of,复合介词]
[16579]	— Why are you standing here, Mrs. White?<\\n>— I'm waiting for my son. He ____ back from school.	[现在完成时]
[16574]	— Why are you so tired these days?<\\n>— Well, I have ____ work to do.	[much+不可数名词]
[16569]	— Why are you so tired these days?<\\n>— Well, I have ____ homework to do.	[too+形容词副词]
[16565]	— Why are you so many boys and girls here on this cold night?<\\n>— Because Jacky Jay will give a concert here. They are all his ____.	[情境语义]
[16560]	— Why are you so excited?<\\n>— Peter invited me ____ on a trip to Yuntai Mountain.	[invite…to do]
[16550]	— Why are you so ____, Amy?<\\n>— I thought I lost my purse, and I haven't I found it in my study!	[情境语义]
[16545]	— Why are you in such a hurry, Mike?<\\n>— There ____ an NBA basketball game in ten minutes.	[there be句型]
[16545]	— Why are you in such a hurry, Mike?<\\n>— There ____ an NBA basketball game in ten minutes.	[一般将来时]
[16540]	— Why are you in such a hurry, John?<\\n>— There ____ a basketball match between Class Three and our class in ten minutes.	[there be句型]
[16540]	— Why are you in such a hurry, John?<\\n>— There ____ a basketball match between Class Three and our class in ten minutes.	[be going to do]
[16526]	— Why are the windows so dirty?<\\n>— Because we ____ them for a long time.	[现在完成时]
[16521]	— Whose T-shirt is this?<\\n>— It ____ be John's. It's much too small for him.	[can't,mustn't]
[16517]	— Whose T-shirt is this?<\\n>— It ____ be John's. It's ____ small for him.	[can't,mustn't]
[16517]	— Whose T-shirt is this?<\\n>— It ____ be John's. It's ____ small for him.	[too+形容词副词]
[16512]	— Whose shoes are these?<\\n>— They ____ be Mike's. They are much too large for him.	[can't,mustn't]
[16507]	— Whose shirt is this?<\\n>— It ____ be Li Lei's. It is too big for him.	[can't,mustn't]
[16488]	— Whose notebook is this?<\\n>— It ____ Tom. I saw he used it just now.	[belong to sb]
[16488]	— Whose notebook is this?<\\n>— It ____ Tom. I saw he used it just now.	[must,should,ought to]
[16479]	— Whose jacket is it?<\\n>— It ____ be Wu Lei's. I saw him wear it just now.	[must,should,ought to]
[16474]	— Whose is the pencil box?<\\n>— It ____ be Tom's. Look at his name on the cover!	[must,should,ought to]
[16469]	— Whose is ____ pen on my desk?<\\n>— It's Mary's.	[the]
[16464]	— Whose exam paper is it?<\\n>— It ____ be Li Lei's. He always forgets to write his name on it.	[must,should,ought to]
[16459]	— Whose English-Chinese dictionary is this?<\\n>— It's ____. My parents bought it for my sister and me.	[mine,名词性物主代词]
[16454]	— Whose computer doesn't work?<\\n>— ____, I think.	[名词所有格]
[16449]	— Whose book is this?<\\n>— It ____ our geography teacher's. You see, his name is on it.	[must,should,ought to]
[16444]	— Whose book is this?<\\n>— It ____ be Linda's. It has her name on it.	[must,should,ought to]
[16409]	— Who's the most modest boy in your class?<\\n>— Daniel. He never ____ in public.	[show off]
[16389]	— Who's that young man on the poster?<\\n>— Justin Bieder, ____ excellent singer.	[an+元音开头的词]
[16379]	— Who's that man?<\\n>— Jeremy Lin. He's ____ American basketball player.	[字母,读音以元音开头]
[16374]	— Who's that man? Is he Mr. Brown?<\\n>— That ____ be Mr. Brown. He never walks this way.	[can't,mustn't]
[16370]	— Who's that man under the tree? Is it Mr. Black, our new English teacher?<\\n>— It ____ be. Mr. Black has gone to Shanghai for a holiday.	[can't,mustn't]
[16365]	— Who's that lovely girl?<\\n>— You mean ____ girl with long hair? That's Kate.	[the]
[16360]	— Who's that girl?<\\n>— You mean ____ one with long blond hair? That's Jack's daughter.	[the]
[16355]	— Who's that boy reading in the garden? Is it David?<\\n>— It ____ be David. I saw him in the classroom just now.	[can't,mustn't]
[16335]	— Who will teach ____ oral English next term? Can it be a new teacher?<\\n>— Perhaps. But our head teacher hasn't told us ____.	[yet,用于现在完成时]
[16330]	— Who will send you to the new school, your mom or your dad?<\\n>— ____. I'll go there alone.	[neither,不定代词]
[16325]	— Who will be ____ duty tomorrow?<\\n>— Susan will.	[on duty]
[16315]	— Who will ____ the baby when your aunt is away?<\\n>— Nobody but me.	[look after]
[16306]	— Who took you to the new school, your dad or mum?<\\n>— ____. I went there alone.	[neither,不定代词]
[16297]	— Who teaches ____ music?<\\n>— Nobody. I teach ____.	[myself,反身代词]
[16297]	— Who teaches ____ music?<\\n>— Nobody. I teach ____.	[you,人称代词宾格]
[16293]	— Who teaches ____ English?<\\n>— No one. I teach ____.	[myself,反身代词]
[16293]	— Who teaches ____ English?<\\n>— No one. I teach ____.	[you,人称代词宾格]
[16274]	— Who runs ____, Nick or Harry?<\\n>— Nick.	[形容词和副词比较级]
[16269]	— Who is your new English teacher?<\\n>— Elena, the woman ____ is wearing a red T-shirt over there.	[who,引导的定语从句]
[16259]	— Who is the most ____ student in your class?<\\n>— I think Jimmy is. He is very out-going, helpful and creative.	[情境语义]
[16254]	— Who is the little boy in the picture?<\\n>— It's me. The picture ____ 10 years ago.	[一般过去时的被动语态]
[16244]	— Who is the girl standing over there?<\\n>— Well, if you ____ know, her name is Joe.	[must,情态动词]
[16239]	— Who is the boy over there?<\\n>— It's ____ brother.	[my,形容词性物主代词]
[16230]	— Who is that?<\\n>— It ____ be Shirley. Only she is in red today.	[must,情态动词]
[16225]	— Who is that woman on TV?<\\n>— ____ pop singer, I often listen to her songs.	[a]
[16216]	— Who is that little boy in the photo, Oscar?<\\n>— Oh, it's me! It ____ when I was five years old.	[一般过去时的被动语态]
[16206]	— Who is Ren Changxia?<\\n>— A great policewoman. She always thought ____ of others than herself.	[much->more,比较级]
[16202]	— Who is Mr. Xu?<\\n>— He is ____ teacher and he teaches ____ P.E.	[our,形容词性物主代词]
[16202]	— Who is Mr. Xu?<\\n>— He is ____ teacher and he teaches ____ P.E.	[us,人称代词宾格]
[16197]	— Who is it?<\\n>— ____. I took this photo when I was 4.	[me,人称代词宾格]
[16187]	— Who is ____, Tom, Jim, or David?<\\n>— I think Jim is.	[形容词和副词比较级]
[16182]	— Who is ____ man in a black hair?<\\n>— It's Jim Brown. We often play ____ basketball together in our free time.	[the]
[16182]	— Who is ____ man in a black hair?<\\n>— It's Jim Brown. We often play ____ basketball together in our free time.	[basketball,是球类棋类]
[16172]	— Who helped you with your English?<\\n>— ____! I learned it all by myself.	[nobody,复合不定代词]
[16159]	— Who helped you clean the room yesterday afternoon?<\\n>— ____. I cleaned it all by myself.	[nobody,复合不定代词]
[16155]	— Who helped you clean the classroom yesterday?<\\n>— ____. I cleaned it all by myself.	[nobody,复合不定代词]
[16150]	— Who helped you clean the bedroom yesterday, Kitty?<\\n>— ____. I cleaned it all by myself.	[nobody,复合不定代词]
[16125]	— Who has ____ marks in English, Wang Lin, Zhang Fang or Li Hong?<\\n>— Li Hong.	[形容词和副词最高级]
[16121]	— Who gets up ____ of you all in the dormitory, Tony?<\\n>— Jimmy does.	[形容词和副词最高级]
[16116]	— Who do you like better, Lin Zhixuan or Huang Qishan?<\\n>— ____ of them. I like YuQuan (羽泉) best.	[neither,不定代词]
[16111]	— Who did you go to the movie ____?<\\n>— Nobody. I went alone.	[with,介词]
[16106]	— Who did English homework better, Leo or Nick?<\\n>— Leo was more careful. I think Leo did ____ Nick.	[形容词和副词比较级]
[16096]	— Who broke the window?<\\n>— ____. A strong wind broke it last night.	[nobody,复合不定代词]
[16092]	— Who also did this wonderful job, Uncle Wang?<\\n>— It's ____.	[me,人称代词宾格]
[16083]	— Which would you like, tea or coffee?<\\n>— ____ is OK, I don't mind.	[either,不定代词]
[16058]	— Which team do you think ____ the game?<\\n>— Hard to say. There are still ten minutes before it ends.	[do you think,特殊疑问句]
[16058]	— Which team do you think ____ the game?<\\n>— Hard to say. There are still ten minutes before it ends.	[一般将来时]
[16053]	— Which sweater do you like better?<\\n>— ____.	[情境语义]
[16048]	— Which subject do you like better, English or Chinese?<\\n>— ____, I like maths.	[neither,不定代词]
[16044]	— Which subject do you like ____, math or history?<\\n>— History, because it makes me wise.	[like…better]
[16034]	— Which subject do you like ____, art or science?<\\n>— Science. I want to be a scientist.	[like…better]
[16000]	— Which scarf do you prefer?<\\n>— The red one. It ____ more comfortable.	[feel+形容词]
[15995]	— Which room does Tom live in?<\\n>— Sorry, I can't remember his room ____.	[情境语义]
[15990]	— Which province is the ____ one in winter?<\\n>— It should be Hainan Province, I think.	[情境语义]
[15985]	— Which one of these do you want?<\\n>— ____. Either will be OK.	[I don't mind]
[15985]	— Which one of these do you want?<\\n>— ____. Either will be OK.	[情境语义]
[15970]	— Which of these two English books will you borrow?<\\n>— I'll borrow ____ of them. Because they are very interesting.	[both,不定代词]
[15965]	— Which of the two T-shirts will you take?<\\n>— I'll take ____. One is for my brother and the other is for myself.	[both,不定代词]
[15960]	— Which of the two T-shirts do you prefer?<\\n>— ____ is OK. I don't like their styles.	[neither,不定代词]
[15955]	— Which of the two subjects do you like, art or music?<\\n>— ____. They are really interesting.	[both,不定代词]
[15951]	— Which of the caps will you take?<\\n>— I'll take ____, one for my father, the other for my brother.	[both,不定代词]
[15946]	— Which magazine do you like better, Crazy Reading or Teens' Space?<\\n>— I like ____ of them. They are useful for English learners.	[both,不定代词]
[15937]	— Which is the second day of a week?<\\n>— ____, of course.	[情境语义]
[15917]	— Which is ____ in China, football, basketball or table tennis?<\\n>— Table tennis.	[the+形容词最高级+名词]
[15912]	— Which hobby do you think ____ the least time?<\\n>— Collecting stamps.	[take up]
[15907]	— Which hobby do you think ____ the least space?<\\n>— Collecting stamps, I think.	[take up]
[15902]	— Which hat would you like, the blue one or the red one?<\\n>— ____. I prefer the yellow one.	[neither,不定代词]
[15883]	— Which dress do you prefer?<\\n>— The red one. It ____ more comfortable.	[feel+形容词]
[15878]	— Which dress do you like best, Madam?<\\n>— Sorry, I can't decide ____ now.	[which to do]
[15874]	— Which do you prefer, tea or coffee?<\\n>— ____ is OK. I don't care.	[either]
[15869]	— Which do you prefer, tea ____ coffee?<\\n>— Tea, please.	[or,连词]
[15864]	— Which do you prefer, a CD player or a walkman?<\\n>— ____. I prefer the new kind of MP4.	[neither,不定代词]
[15854]	— Which do you like better, math or physics?<\\n>— ____. I'm interested in them and quite good at them.	[both,不定代词]
[15834]	— Which do you like ____, summer or winter?<\\n>— I'd prefer winter.	[形容词和副词比较级]
[15829]	— Which do you like ____, summer or winter?<\\n>— I prefer summer.	[like…better]
[15825]	— Which country is your favorite, Lin Tao?<\\n>— France, of course. It's the ____ place that I want to visit.	[the+形容词最高级+名词]
[15815]	— Which colour do you like ____, blue or green?<\\n>— blue.	[形容词和副词比较级]
[15795]	— Which class won the match in the end?<\\n>— I'm not quite sure. Perhaps ____ did.	[编号]
[15790]	— Which city is your favorite?<\\n>— Hangzhou, of course. It's the ____ place that I want to visit.	[the+形容词最高级+名词]
[15776]	— Which cake do you like better?<\\n>— I prefer this one. It ____ more delicious.	[taste,是系动词]
[15766]	— Which basketball player do you like best, Kobe, James or Jordan?<\\n>— ____ of them. Lin shuhao is my favorite.	[none,不定代词]
[15757]	— Where's your father, Tom?<\\n>— He ____ to Changsha.	[have gone to]
[15733]	— Where's our math teacher?<\\n>— He ____ to Shanghai.	[have been to,have gone to,have been in]
[15723]	— Where's Mrs. Li taking Polly and Mickey?<\\n>— She's taking ____ across the street.	[them,人称代词宾格]
[15718]	— Where's Mr. Yu, do you know?<\\n>— Well. it's hard to say. But I saw him ____ a football game just now.	[see…doing]
[15714]	— Where's Mr. Green?<\\n>— He ____ to Changsha.	[have been to,have gone to,have been in]
[15710]	— Where's Mom, Daddy?<\\n>— Look! She ____ some clothes downstairs.	[现在进行时]
[15700]	— Where's Lucy?<\\n>— I'm not sure. She ____ in the school library.	[may,情态动词]
[15695]	— Where's Lisa, Eric?<\\n>— She ____ to the library.	[have gone to]
[15676]	— Where's Jack?<\\n>— He's left a ____ saying that he will be back in a minute.	[information,不可数名词instances]
[15676]	— Where's Jack?<\\n>— He's left a ____ saying that he will be back in a minute.	[news,不可数名词instances]
[15671]	— Where's her second son? I haven't seen him for a long time.<\\n>— He ____ Maine looking for a place to work.	[have gone to]
[15666]	— Where's David?<\\n>— He ____ be in the playground because he is fond of playing basketball.	[may,情态动词]
[15662]	— Where would you like to visit?<\\n>— I'd like to go ____.	[somewhere,anywhere,nowhere,everywhere:辨析]
[15662]	— Where would you like to visit?<\\n>— I'd like to go ____.	[relaxing,-ing形式的形容词]
[15657]	— Where would you like to go on your summer holiday, Mike?<\\n>— I'd like to go ____.	[somewhere,anywhere,nowhere,everywhere:辨析]
[15657]	— Where would you like to go on your summer holiday, Mike?<\\n>— I'd like to go ____.	[interesting,-ing形式的形容词]
[15652]	— Where would you like to go on vacation?<\\n>— I'd like to go ____.	[somewhere,anywhere,nowhere,everywhere:辨析]
[15652]	— Where would you like to go on vacation?<\\n>— I'd like to go ____.	[relaxing,-ing形式的形容词]
[15648]	— Where would you like to go on vacation, Lily?<\\n>— It's hot here. I'd like to go ____.	[somewhere,anywhere,nowhere,everywhere:辨析]
[15643]	— Where will Alice sit?<\\n>— The seat next to Kenny's is ____.	[hers,名词性物主代词]
[15633]	— Where were you this morning?<\\n>— I ____ in the supermarket.	[过去进行时]
[15623]	— Where were you last Saturday?<\\n>— I ____ in the Capital Museum.	[一般过去时]
[15613]	— Where may you advise me to start my business?<\\n>— In my opinion, Yichang is ____one of ____ best places for you.	[one of + the + 形容词和副词最高级]
[15609]	— Where is Zhang Ming?<\\n>— Oh, don't you know he ____ to Beijing to see his parents and he'll be back tomorrow.	[have been to,have gone to,have been in]
[15564]	— Where is your father?<\\n>— He ____ Australia and he ____ Sydney for two weeks.	[have been to,have gone to,have been in]
[15559]	— Where is your father, Han Mei?<\\n>— He ____ the factory.	[have been to,have gone to,have been in]
[15549]	— Where is your cousin?<\\n>— He ____ an English exam now.	[现在进行时]
[15489]	— Where is my pen?<\\n>— Oh, sorry. I have taken ____ by mistake.	[yours,名词性物主代词]
[15479]	— Where is my notebook?<\\n>— I don't know. It isn't here. Maybe ____ took it away by mistake.	[somebody,复合不定代词]
[15475]	— Where is my hat?<\\n>— Is ____ one behind the door yours?	[the]
[15471]	— Where is my eraser, Ann?<\\n>— It's ____ the floor.	[on,介词]
[15461]	— Where is Mrs. Wilson?<\\n>— I saw her in the library ____. I'm not sure if she is still there.	[just now,用于一般过去时]
[15436]	— Where is Mr. Lee? I have something important to tell him.<\\n>— You ____ find him. He ____ Japan.	[have been to,have gone to,have been in]
[15431]	— Where is Mr. Black? I have something important to tell him.<\\n>— You can't find him. He ____ Hong Kong.	[have been to,have gone to,have been in]
[15411]	— Where is Michael?<\\n>— He ____ TV at home, I think.	[现在进行时]
[15406]	— Where is Mary?<\\n>— She ____ to Harbin.	[have been to,have gone to,have been in]
[15386]	— Where is Leo?  He said he would come tonight!<\\n>— Yes, he did say so, ____ we can't find him now.	[but,连词]
[15362]	— Where is Bob?<\\n>— He ____ to Harbin for a meeting.	[have been to,have gone to,have been in]
[15348]	— Where is ____ key to the door, Jim?<\\n>— It's in my pocket.	[the]
[15343]	— Where is ____ girl?<\\n>— She is making paper flowers over there.	[the]
[15338]	— Where is ____ cat?<\\n>— It's under ____ desk.	[the]
[15333]	— Where does your uncle work, Jack?<\\n>— In a ____ in Paris. He is a policeman.	[情境语义]
[15328]	— Where does Maria sit?<\\n>— She sits ____ my right.	[on the right]
[15314]	— Where did you go last week?<\\n>— I went to Zhang Aiping's hometown and visited the house ____ he was born in.	[that,引导的定语从句]
[15309]	— Where did you go last night?<\\n>— I ____ to go to Li Lei's birthday party.	[一般过去时的被动语态]
[15299]	— Where can we go into the trade center?<\\n>— Haven't you seen the sign ____ over there?	[情境语义]
[15290]	— Where can I find Jack?<\\n>— He is playing volleyball in the ____ now.	[情境语义]
[15280]	— Where are you going, Lily?<\\n>— I'm going to the ____ to fly a kite.	[情境语义]
[15275]	— Where are you going for the coming winter camp?<\\n>— I won't decide on the place ____ the end of this month.	[not…until]
[15266]	— Where are the Greens, may I ask?<\\n>— Well, they ____ England. They have been there for nearly a week now.	[have been to,have gone to,have been in]
[15251]	— Where are the ____ students?<\\n>— They are playing football with ____ students from Hilltop School.	[the]
[15251]	— Where are the ____ students?<\\n>— They are playing football with ____ students from Hilltop School.	[复合名词.复数]
[15246]	— Where are Lucy and Lily?<\\n>— Oh, they must ____ a game in the garden now.	[情态动词,时态]
[15241]	— Where are Diaoyu Islands?<\\n>— Look, they are here, in the east of China, ____ Taiwan Province.	[near,介词]
[15236]	— Where ____ you ____ lunch?<\\n>— At home. There was no school lunch.	[一般过去时]
[15231]	— Where ____ the 2010 World EXPO ____?<\\n>— In Shanghai.	[一般现在时的被动语态]
[15227]	— When will you aunt leave for Shanghai?<\\n>— I don't know, but I'll call you as soon as she ____.	[时间状语从句用一般现在时表示将来]
[15217]	— When will they be back?<\\n>— They ____ back until the work ____ finished.	[时间状语从句用一般现在时表示将来]
[15217]	— When will they be back?<\\n>— They ____ back until the work ____ finished.	[not…until]
[15193]	— When were you born?<\\n>— I was born ____ the morning of May 7th, 1995.	[表示时间:at,in,on]
[15184]	— When were you born?<\\n>— I was born ____ November 6th, 1996.	[表示时间:at,in,on]
[15170]	— When was the car invented?<\\n>— It ____ in 1885.	[一般过去时的被动语态]
[15165]	— When was Shenzhou-10 sent into space?<\\n>— ____ the afternoon of June 11,2013.	[表示时间:at,in,on]
[15156]	— When was Michael Phelps born?<\\n>— He was born ____ June, 1985.	[arrive in]
[15151]	— When was David born?<\\n>— He was born ____ June 12,1989.	[表示时间:at,in,on]
[15146]	— When should I hand in my paper?<\\n>— Your paper must ____ as soon as the bell ____.	[时间状语从句用一般现在时表示将来]
[15146]	— When should I hand in my paper?<\\n>— Your paper must ____ as soon as the bell ____.	[must,被动语态]
[15141]	— When shall we have the party, Saturday or Sunday?<\\n>— ____ is OK. I'm free this weekend.	[either,不定代词]
[15136]	— When shall we go to the museum, this afternoon or tomorrow morning?<\\n>— ____ is OK. I'm free these days.	[either,不定代词]
[15131]	— When shall I phone you, morning or afternoon?<\\n>— ____. I'll be at home all day.	[either,不定代词]
[15111]	— When is Henry's birthday party, Lynn?<\\n>— The 18th, ____ about three o'clock in the afternoon.	[表示时间:at,in,on]
[15086]	— When do you go to school every day?<\\n>— ____ seven o'clock.	[表示时间:at,in,on]
[15077]	— When did your uncle ____ in Shanghai?.<\\n>— The day before yesterday.	[arrive in]
[15068]	— When did you join the League?<\\n>— Last year. I ____ a league member for one year.	[延续性动词,用于现在完成时]
[15049]	— When did you buy the computer?<\\n>— I have ____ this computer for 5 years, but it still works well.	[延续性动词,用于现在完成时]
[15040]	— When did Tom come to your art class?<\\n>— He ____ here for weeks.	[have been to]
[15036]	— When did the old man die?<\\n>— In 2007. He ____ for nearly three years.	[延续性动词,用于现在完成时]
[15031]	— When did the earthquake in Lushan happen?<\\n>— It happened ____ 8:02 ____ the morning of April 20,2013.	[表示时间:at,in,on]
[15021]	— When can you go hiking with us, on Thursday or Friday?<\\n>— ____ is OK. I'm free this week.	[either,不定代词]
[14997]	— When are you going to have your hair ____?<\\n>— This afternoon.	[have sth done]
[14993]	— When are you going to Beijing for your holiday?<\\n>— I haven't decided. ____ this Sunday ____ next Sunday is OK.	[either…or,是并列结构连词]
[14988]	— When are you going to ____ for Shanghai?<\\n>— Tomorrow morning.	[set off]
[14983]	— When and where were you born?<\\n>— I was born ____ October 1st, 1998 ____ Suzhou.	[表示地点:at,in]
[14983]	— When and where were you born?<\\n>— I was born ____ October 1st, 1998 ____ Suzhou.	[表示时间:at,in,on]
[14979]	— When ____ your mother ____ you that blue dress, Lucy?<\\n>— Sorry, I really can't remember. Maybe two or three weeks ago.	[一般过去时]
[14974]	— When ____ you come here?<\\n>— Two years ago. I have been here for two years.	[一般过去时]
[14964]	— When ____ you ____ reading Jane Eyre?<\\n>— It's hard to say. I'm busy recently.	[一般将来时]
[14959]	— When ____ this kind of car ____?<\\n>— Three years ago.	[一般过去时的被动语态]
[14955]	— When ____ the teaching buildings ____ in your school?<\\n>— In 2001.	[一般过去时的被动语态]
[14930]	— What's your plan for this weekend?<\\n>— I'm going to ____ it with my grandparents.	[cost,pay,spend,take]
[14925]	— What's your plan for the summer holidays?<\\n>— I've no idea, but I've decided ____ at home and have a good rest first.	[decide to do]
[14915]	— What's your name?<\\n>— ____.	[情境语义]
[14905]	— What's your job, Henry?<\\n>— I'm a ____. I work late. I'm very busy when people go out to dinners.	[情境语义]
[14895]	— What's your favourite fruit?<\\n>— Apples. You know, ____ apple a day keeps the doctor away.	[apple,是元音开头的词]
[14886]	— What's your favorite subject?<\\n>— ____ favorite subject is P.E.	[my,形容词性物主代词]
[14882]	— What's your favorite ____?<\\n>— Summer. Because I can swim in rivers.	[情境语义]
[14877]	— What's your favorite ____?<\\n>— Physics. It's interesting and useful.	[情境语义]
[14863]	— What's your favorite ____?<\\n>— Evening News on CCTV-1.	[情境语义]
[14849]	— What's your father doing now?<\\n>— He ____ the room.	[现在进行时]
[14845]	— What's your dream job, Tom?<\\n>— I hope ____ a policeman.	[hope to do]
[14840]	— What's your ____?<\\n>— I like swimming.	[情境语义]
[14835]	— What's your ____?<\\n>— I like listening to music.	[情境语义]
[14830]	— What's your ____ name, please?<\\n>— Robert Thomas Brown. You can call me Robert.	[情境语义]
[14821]	— What's wrong with your daughter's ____?<\\n>— She can't see things clearly.	[情境语义]
[14801]	— What's wrong with my bike?<\\n>— It's broken, but it ____ in an hour	[can,被动语态]
[14796]	— What's this in English?<\\n>— ____.	[情境语义]
[14791]	— What's the time now?<\\n>— It's ____.	[时刻]
[14776]	— What's the news about?<\\n>— ____ entertainment stars gathered to attract donations for Yushu.	[a number of]
[14771]	— What's the matter?<\\n>— I have a ____. I have to go to the doctor.	[have a cold]
[14761]	— What's the matter with you?<\\n>— I caught ____ bad cold and had to stay in ____ bed.	[catch a cold]
[14761]	— What's the matter with you?<\\n>— I caught ____ bad cold and had to stay in ____ bed.	[in bed]
[14736]	— What's on TV tonight?<\\n>— There's ____. It's boring.	[nothing+形容词]
[14727]	— What's on the desk?<\\n>— There ____ some books.	[There be A and B,主谓一致]
[14722]	— What's on ____ side of the hill, mum?<\\n>— A big lake.	[the other]
[14717]	— What's in the icebox?<\\n>— A few ____, but little ____.	[little+不可数名词]
[14712]	— What's in the fridge?<\\n>— There ____ some orange, some milk and some apples.	[There be A and B,主谓一致]
[14707]	— What's in the cupboard?<\\n>— A few ____, but little ____.	[little+不可数名词]
[14707]	— What's in the cupboard?<\\n>— A few ____, but little ____.	[coffee,不可数名词instances]
[14707]	— What's in the cupboard?<\\n>— A few ____, but little ____.	[a few+可数名词]
[14703]	— What's in the box?<\\n>— There is ____ apple and some oranges in it.	[There be A and B,主谓一致]
[14698]	— What's his brother?<\\n>— He is a teacher. He ____ maths at a school.	[一般现在时]
[14683]	— What's ____ most useful invention in the 20th century?<\\n>— ____ computer, I think.	[the+形容词最高级+名词]
[14678]	— What's ____ date today?<\\n>— It's June 26th.	[the]
[14673]	— What would you like, sir?<\\n>— ____.	[a bottle of]
[14663]	— What would you like, Madam?<\\n>— ____, please. I'm hungry.	[情境语义]
[14659]	— What would you like, Helen?<\\n>— I'd like some ____.	[可数名词]
[14655]	— What would you like to have, tea or juice?<\\n>— ____ is OK. I'm really thirsty.	[either,不定代词]
[14645]	— What would you like to drink, coffee or tea?<\\n>— ____. Some orange juice, please.	[neither,不定代词]
[14631]	— What would you like for ____ breakfast, Mr. Green?<\\n>— Two pieces of bread and ____ cup of tea, please.	[a cup of tea]
[14631]	— What would you like for ____ breakfast, Mr. Green?<\\n>— Two pieces of bread and ____ cup of tea, please.	[零冠词惯用法]
[14626]	— What would you do if it ____ tomorrow?<\\n>— We have to carry it on, since we've got everything ready.	[时间状语从句用一般现在时表示将来]
[14621]	— What will you do ____ the summer holiday?<\\n>— I think I shall watch London Olympic Games. It will ____ in August.	[表示时间:during,for]
[14621]	— What will you do ____ the summer holiday?<\\n>— I think I shall watch London Olympic Games. It will ____ in August.	[一般将来时的被动语态]
[14607]	— What will Lucy do this Sunday?<\\n>— She as well as her family ____ go camping by a small lake.	[as well as,主谓一致]
[14587]	— what were you doing when the earthquake happened in Yushu?<\\n>— I ____ breakfast when I heard the news.	[过去进行时]
[14577]	— What were you doing this time yesterday?<\\n>— I ____ on the grass and drawing a picture.	[过去进行时]
[14568]	— What were you doing at ten last night?<\\n>— I was playing ____ guitar.	[guitar,是乐器]
[14558]	— What was your day off?<\\n>— Pretty good. I ____ the science museum with my classmates.	[一般过去时]
[14538]	— What volunteer work would you like to do?<\\n>— I'd like to ____ sick people in the hospital.	[cheer up]
[14533]	— What time will Mr. Brown be back to China?<\\n>— Sorry. I don't know ____.	[how long,宾语从句连接词]
[14528]	— What time is it?<\\n>— It's twelve o'clock.<\\n>— Oh, it's too late. I ____ better ____ at once.	[had better,不定式]
[14524]	— What time is it?<\\n>— It's 12 o'clock. It's time for ____.	[情境语义]
[14494]	— What smells terrible?<\\n>— Sorry, I'll ____ my shoes and wash them at once.	[take away]
[14489]	— What smells terrible, Ted?<\\n>— I'm sorry. I'll ____ my shoes and wash them at once.	[take away]
[14485]	— What should you do if you find a man ____ leg is badly hurt?<\\n>— Send him to the hospital at once.	[whose,引导的定语从句]
[14471]	— What shall we do now?<\\n>— ____ it's raining hard, let's stay at home.	[since,引导原因状语从句]
[14467]	— What shall we do next?<\\n>— Take the advice ____ is given by Dr. Bloch.	[which,引导的定语从句]
[14453]	— What kind of music do you like?<\\n>— I like the music ____ I can dance to.	[that,引导的定语从句]
[14440]	— What is your mother going to do this Saturday?<\\n>— I 'm not sure. She ____ go to see my grandmother.	[may,情态动词]
[14435]	— What is your favourite sport?<\\n>— Swimming, I think. It's ____ of all.	[形容词和副词最高级]
[14425]	— What is your father like?<\\n>— He ____.	[what…like]
[14411]	— What is the name of the song you sang just now? It ____ beautiful.<\\n>— It is You And Me.	[sound+形容词]
[14401]	— what is Mum cooking in the kitchen?<\\n>— Fish, I guess. How nice it ____!	[smell+形容词]
[14396]	— What is Mum cooking in the kitchen?<\\n>— Chicken, I guess. How nice it____!	[smell+形容词]
[14366]	— What else do you want?<\\n>— ____ else. I think I've got everything ready.	[nothing+形容词]
[14361]	— What else do you want?<\\n>— ____ else. I think I have got everything ready.	[nothing+形容词]
[14352]	— What else do you need for your trip?<\\n>— ____ else. I've packed everything.	[nothing+形容词]
[14342]	— What does your new English teacher look like?<\\n>— She is a pretty lady ____ long hair.	[with,介词]
[14337]	— What does your mother do to keep healthy, Tim?<\\n>— She usually ____.	[usually,用于一般现在时]
[14327]	— What does Tom's uncle do?<\\n>— He is a teacher. He ____ physics at a school now.	[一般现在时]
[14322]	— What does the instruction say?<\\n>— The colors in the dress will ____ if you use hot water.	[情境语义]
[14317]	— What does the fresh juice contain?<\\n>— ____ of the juice ____ orange. It's very pure.	[分数作主语,主谓一致]
[14297]	— What do you want to be in the future, Nick?<\\n>— I want to be ____ pilot. It is ____ exciting job.	[an+元音开头的词]
[14287]	— What do you want most?<\\n>— A room of ____ own.	[of+形容词性物主代词+own]
[14278]	— What do you usually do in your leisure time?<\\n>— I enjoy reading in the library ____ I lose myself in a world of good books.	[where,引导的定语从句]
[14274]	— What do you usually do in the morning?<\\n>— I often practice ____ English.	[practise]
[14264]	— What do you think your life will be like ____ twenty years?<\\n>— Yeah. I have thought about it ____ three years.	[表示时间:after,in]
'''
}
