package ots

class SampleData_QuestionMapping10 {
	
	String content ='''[47729]	(改为同义句)<\\n>I wondered what I should do next.<\\n>I wondered what ____ ____ next.	[what连接的宾语从句<->what to do]
[47726]	(划线部分提问)<\\n>Li Ming often chats (聊天) with his friends [by phone].<\\n>____ ____ Li Ming often chat with his friends?	[how,特殊疑问句]
[47723]	(改为感叹句)<\\n>Your bedroom is clean and tidy.<\\n>____ clean and tidy your bedroom ____!	[how+/形容词,副词原级/+/主语/+/谓语/]
[47720]	(合并成一个复合句)<\\n>I like music. The music makes me excited.<\\n>I like music ____ ____ me excited.	[which,引导的定语从句]
[47717]	(改为否定句)<\\n>Sometimes you're supposed to come early.<\\n>Sometimes you ____ ____ supposed to come early.	[被动语态的/陈述句/->/否定句/,/疑问句/]
[47714]	(两句合并为一句)<\\n>Mrs. Smith is busy. She is doing her housework now.<\\n>Mrs. Smith is ____ ____ her housework now.	[be busy with]
[47711]	(对划线部分提问)<\\n>Tom visits his grandparents [once a week].<\\n>____ ____ does Tom visit his grandparents?	[how often,特殊疑问句]
[47708]	(用Japan改为选择疑问句)<\\n>My pen pal is from America.<\\n>Is your pen pal from America ____ ____?	[/选择疑问句/instances]
[47705]	The teacher said, "Don't cheat in exams, children!"<\\n>The teacher told the children ____ ____ cheat in exams.	[tell…to do]
[47703]	Mary is happy, because it's her ____ birthday today. (nine)	[create序数词(nine)]
[47703]	Mary is happy, because it's her ____ birthday today. (nine)	[/形容词性物主代词/+/序数词/+/名词/]
[47701]	As middle school students, we should depend on ____ in life. (we)	[ourselves,反身代词]
[47701]	As middle school students, we should depend on ____ in life. (we)	[/介词/+oneself]
[47699]	His ____ made his family very sad. (dead)	[death<->dead,名词<->形容词]
[47697]	His mother asked him to do his homework ____. (quiet)	[quiet<->quietly,形容词<->副词]
[47695]	Yao Ming is one of the ____ basketball players in NBA. (popular)	[one of+the+/形容词最高级/]
[47695]	Yao Ming is one of the ____ basketball players in NBA. (popular)	[popular->most popular:最高级]
[47691]	(就划线部分提问)<\\n>The nurse passed the doctor [a knife] when he began the operation.<\\n>____ ____ the nurse ____ the doctor when he began the operation?	[what,特殊疑问句]
[47687]	(就括号中部分提问)<\\n>Lucy goes to the cinema [twice a week].<\\n>____ ____ ____ Lucy go to the cinema?	[how often,特殊疑问句]
[47683]	(合并成一个句子)<\\n>Wei Hua is on the team.<\\n>Ann is on the team, too.<\\n>____ Wei Hua ____ Ann ____ on the team.	[both A and B,主谓一致]
[47680]	(改为被动语态)<\\n>Mary often sings the English song "Pretty Boy". <\\n>The English song "Pretty Boy" ____ often ____ by Mary.	[ved(/verb/)]
[47680]	(改为被动语态)<\\n>Mary often sings the English song "Pretty Boy". <\\n>The English song "Pretty Boy" ____ often ____ by Mary.	[am/is/are v-ed]
[47677]	(改为同义句)<\\n>We [had a good time] yesterday.<\\n>We ____ ____ yesterday.	[enjoy oneself<->have a good time]
[47673]	(改为同义句)<\\n>Uncle Li bought the new watch three years ago.<\\n>Uncle Li ____ ____ the new watch ____ three years.	[/延续性动词/,现在完成时,for+一段时间]
[47671]	Nothing can prevent us from ____ (realize) our Chinese Dream.	[prevent…from doing]
[47669]	Unfortunately he had his left leg ____ (break) in the high jump last week.	[have…+/v-ed/]
[47667]	Tom ____ (write) his lessons when he heard a terrible noise outside.	[时间状语从句:主句进行时/从句一般时]
[47665]	We have walked for a long time. Let's stop ____ (have) some water.	[stop to do]
[47662]	— ____ you ever ____ (be) to an amusement park?<\\n>— Yes, I have.	[have been (to)]
[47660]	The old lady could hardly believe that she had got the travel pass to Hong Kong so ____. (easy)	[easy<->easily,形容词<->副词]
[47658]	Mr. Chen was surprised to see the fast ____ in Shanghai after his long absence from the city. (develop)	[develop<->development]
[47656]	Feng Ai's love and ____ will always be remembered by her students and their parents in Yunnan. (kind)	[kindness<->kind,名词<->形容词]
[47654]	Many people caught cold last month because of the____ weather. (change)	[change<->changeable]
[47652]	Watch ____, and you will find the difference between the two pictures. (care)	[careful<->carefully,形容词<->副词]
[47652]	Watch ____, and you will find the difference between the two pictures. (care)	[care<->careful]
[47650]	We will have no water to drink or use if we ____ (not stop) wasting it now.	[主将从现,条件状语从句]
[47648]	The world's first great nurse Nightingale's birthday ____ (become) International Nurses' Day in 1974.	[in+/年份/,用于一般过去时]
[47646]	Scientists ____ (study) the global warming for several years. They are working hard to find a solution.	[/延续性动词/,现在完成时,for+一段时间]
[47644]	I'm sorry I didn't hear you because I ____ (listen) to music.	[was/were v-ing]
[47642]	The Conference on Scaling Up Poverty Reduction (扶贫大会) ____ (hold) in Shanghai in May, 2004.	[ved(/verb/)]
[47642]	The Conference on Scaling Up Poverty Reduction (扶贫大会) ____ (hold) in Shanghai in May, 2004.	[was/were v-ed]
[47639]	(对划线部分提问)<\\n>The American spacecraft  Galileo travelled and worked in space [for 14 years].<\\n>____ ____did the American spacecraft Galileo travel and work in space?	[how long,特殊疑问句]
[47636]	(保持句意基本不变)<\\n>Jack's mother asked him, "Have you packed your things?"<\\n>Jack's mother asked him ____ he ____ pack his things.	[do+/verb/,加强语气]
[47636]	(保持句意基本不变)<\\n>Jack's mother asked him, "Have you packed your things?"<\\n>Jack's mother asked him ____ he ____ pack his things.	[if,宾语从句连接词]
[47636]	(保持句意基本不变)<\\n>Jack's mother asked him, "Have you packed your things?"<\\n>Jack's mother asked him ____ he ____ pack his things.	[whether,宾语从句连接词]
[47634]	(保持句意基本不变)<\\n>After a quick breakfast, Mary left in a hurry.<\\n>After a quick breakfast, Mary ____.	[hurry off]
[47632]	Grandpa is sitting ____ in the sofa, enjoying the view through the big window of our new flat. (comfortable)	[/形容词/<->/副词/]
[47630]	The New Year ____ are so beautiful that everyone is looking forward to the party in the hall this afternoon. (decorate)	[decorate<->decoration]
[47628]	The most famous ____ park in the world is Disneyland. (amusing)	[amusement<->amusing,名词<->形容词]
[47626]	Anyone who finds ____ animals, please send them to the SPCA kennels. (home)	[home<->homeless]
[47624]	The new carpet is ____ clean. Shall we take off our shoes before entering the room? (spot)	[spotless<->spotlessly,形容词<->副词]
[47624]	The new carpet is ____ clean. Shall we take off our shoes before entering the room? (spot)	[spot<->spotless,名词<->形容词]
[47622]	When spring ____ (come), the animals which sleep in winter start waking up.	[presentense(/verb/)]
[47620]	Our manager ____ (go) to Paris on business already and he will be back in a few days.	[have gone (to)]
[47618]	The Eiffel Tower ____ ____ (design) by a Frenchman called Gustave Eiffel over 100 years ago.	[was/were v-ed]
[47616]	While we ____ (travel) in Australia last summer, I visited Lucy who once taught English in our school.	[时间状语从句,主句一般时/从句进行时]
[47614]	The suspect denied ____ (steal) the valuable painting before the witness appeared.	[ving(/verb/)]
[47614]	The suspect denied ____ (steal) the valuable painting before the witness appeared.	[deny doing]
[47611]	(对划线部分提问)<\\n>This sign means [cars and buses mustn't turn right here].<\\n>____ ____ this sign mean?	[what,特殊疑问句]
[47608]	(保持句意基本不变)<\\n>The ice cream will melt, so you'd better put it in the fridge at once.<\\n>The ice cream will melt ____ you ____ put it in the fridge at once.	[if,引导条件状语从句]
[47605]	(保持句意基本不变)<\\n>Comics are exciting to read.<\\n>It is ____ ____ read comics.	[be+ /形容词/+ to do]
[47603]	Jane has been very sad because her computer was ____ (steal) a few days ago.	[ved(/verb/)]
[47601]	My sister is busy ____ (prepare) for her exam, so she has no time to play outside.	[be busy (in) doing]
[47599]	With the ____ (develop) of modern society, the computer is more widely used.	[develop<->development]
[47597]	If it is sunny tomorrow, I think we'll have a ____ (please) weekend.	[please<->pleasant,动词<->形容词]
[47595]	Before you make an important ____ (choose), please think it over.	[choose<->choice]
[47593]	I'm looking forward to ____ (收到) letters from my mother.	[look forward to doing]
[47591]	President Hu Jintao ____ (fly) to the earthquake-hit region in Yushu, Qinghai on April 18, 2010.	[pastense(/verb/)]
[47589]	I'm ____ (feel) terrible today, so my mother will take me to see a doctor.	[ving(/verb/)]
[47587]	The compass helped people make many ____ (discover) in the past.	[discover<->discovery,动词<->名词]
[47587]	The compass helped people make many ____ (discover) in the past.	[/动词/<->/名词/]
[47585]	He held a glass with care, because he was afraid of ____ (break) it.	[ving(/verb/)]
[47583]	Our village has developed ____ (rapid) now, our life is becoming better and better.	[/形容词/<->/副词/]
[47581]	Help y____ to some cakes, children.	[help oneself to…]
[47579]	It's ____ (possible) to master English if you don't have enough practice.	[possible<->impossible:反义词]
[47577]	The lecture was so ____ (bore) that some people fell asleep while listening.	[bore<->boring,动词<->形容词]
[47575]	Many foreigners enjoy Chinese fashion, ____ (especial) the Tang costume.	[especial<->especially,形容词<->副词]
[47573]	No one can ____ (success) without any hard work.	[succeed<->success]
[47571]	It rained ____ last night and the river rose two feet. (heavy)	[rain heavily]
[47571]	It rained ____ last night and the river rose two feet. (heavy)	[/形容词/<->/副词/]
[47569]	The fishermen are told to be more careful on ____ days. (wind)	[wind<->windy]
[47567]	More people are getting to know the ____ of environmental protection. (important)	[importance<->important]
[47565]	I ____ we see a film about the Anti-Japanese War. (suggestion)	[suggest<->suggestion]
[47563]	____ food is convenient to cook so it's a craze in supermarkets. (freeze)	[ved(/verb/)]
[47560]	(改为否定句)<\\n>The old man realized that too much salt was harmful to health.<\\n>The old man ____ ____ that too much salt was harmful to health.	[一般过去时的/陈述句/->/否定句/,/疑问句/]
[47557]	(对划线部分提问)<\\n>London held the first World Expo [in 1851].<\\n>____ did London ____ the first Word Expo?	[when,特殊疑问句]
[47554]	(合并句子)<\\n>Betty likes taking a bus to work.<\\n>She likes taking an underground to work better.<\\n>Betty ____ taking an underground ____ taking a bus to work.	[prefer v-ing to v-ing]
[47551]	(改为被动语态)<\\n>We publish our school newspaper twice a month.<\\n>Our school newspaper ____ ____ twice a month.	[am/is/are v-ed]
[47548]	(改为简单句)<\\n>The poor child was so lucky that she received many books from Project Hope.<\\n>The poor child was ____ ____ to receive many books from Project Hope.	[/形容词,副词原级/+enough to do]
[47545]	(改为否定句)<\\n>Sam wants to look for a job in London after he graduates from university.<\\n>Sam ____ ____ to look for a job in London after he graduates from university.	[一般现在时的/陈述句/->/否定句/,/疑问句/]
[47542]	(改为反意疑问句)<\\n>Tom didn't take part in the after-school activity yesterday.<\\n>Tom didn't take part in the after-school activity yesterday, ____ ____?	[反意疑问句:否定的/陈述部分/+肯定的/附加疑问句/]
[47539]	(对划线部分提问)<\\n>The students' projects will be on show [in three days].<\\n>____ ____ will the students' projects be on show?	[how soon特殊疑问句,应答句]
[47536]	(改为简单句)<\\n>Can you tell me when I should water the flowers?<\\n>Can you tell me ____ ____ water the flowers?	[when连接的宾语从句<->when to do]
[47533]	(保持句意基本不变)<\\n>Laura spent one week finishing reading the book Harry Potter.<\\n>It ____ Laura one week ____ finish reading the book Harry Potter.	[It takes sb...to do<->spend doing]
[47531]	The street near my house is always crowded with cars and ____. (bus)	[create名词复数(/规则可数名词/)]
[47529]	Mum made a big chocolate cake for little Kevin's ____ birthday. (six)	[create序数词(six)]
[47527]	"Would you tell ____ about your trip to Russia?" the children asked Uncle Joe. (we)	[us,人称代词宾格]
[47527]	"Would you tell ____ about your trip to Russia?" the children asked Uncle Joe. (we)	[/及物动词/+/人称代词宾格/]
[47525]	The Iraq War has made thousands of children ____. (home)	[home<->homeless]
[47523]	Listen! The birds are singing ____ in the woods. (beautiful)	[beautiful<->beautifully,形容词<->副词]
[47521]	I believe knowledge is more ____ than money. (power)	[power<->powerful,名词<->形容词]
[47519]	The students had a ____ in the English class yesterday. (discuss)	[discuss<->discussion]
[47517]	Put some milk into the flour, break two eggs and then ____ them. (mixture)	[mix<->mixture]
[47514]	(改为一般疑问句)<\\n>Alan often does housework after school.<\\n>____ Alan often ____ housework after school?	[一般现在时的/陈述句/->/否定句/,/疑问句/]
[47511]	(对划线部分提问)<\\n>Mr. and Mrs. Brown have already been to China [twice].<\\n>____ ____ times have Mr. and Mrs. Brown been to China?	[how many,特殊疑问句]
[47508]	(改为感叹句)<\\n>It is very convenient to travel by underground.<\\n>____ ____ it is to travel by underground!	[how+/形容词,副词原级/+/主语/+/谓语/]
[47505]	(保持句意基本不变)<\\n>Mr. Li is our teacher and friend as well.<\\n>Mr. Li is ____ only our teacher ____ also our friend.	[not only A but (also) B,并列结构]
[47502]	(合并句子)<\\n>Will Bob join the swimming club? Please tell me.<\\n>Please tell me ____ Bob ____ join the swimming club.	[if,宾语从句连接词]
[47502]	(合并句子)<\\n>Will Bob join the swimming club? Please tell me.<\\n>Please tell me ____ Bob ____ join the swimming club.	[whether,宾语从句连接词]
[47500]	Billy looks upset. What happened to ____? (he)	[him,人称代词宾格]
[47500]	Billy looks upset. What happened to ____? (he)	[/介词/+/人称代词宾格/]
[47498]	It is said that eight ____ of water a day can help you keep fit. (glass)	[create名词复数(/规则可数名词/)]
[47496]	Linton is interested in Chinese history and this is his ____ visit to Beijing. (four)	[create序数词(four)]
[47494]	Don't throw the old watch away. It is still ____. (use)	[use<->useful]
[47492]	Fishing is one of my ____ outdoor activities. (favour)	[favor<->favourite,/名词/<->/形容词/]
[47490]	Grandpa is going to ____ his house and live with us. (sale)	[sell<->sale]
[47488]	Nowadays too many boys want to become ____. (act)	[act<->actor]
[47486]	Mary is good at writing. She will ____ be a reporter in the future. (possible)	[possible<->possibly,形容词<->副词]
[47483]	(改为一般疑问句)<\\n>Susan has her piano lesson on Saturday afternoon.<\\n>____ Susan ____ her piano lesson on Saturday afternoon?	[一般现在时的/陈述句/->/否定句/,/疑问句/]
[47480]	(对划线部分提问)<\\n>That [new blue] car is my father's.<\\n>____ ____ is your father's?	[which,特殊疑问句]
[47477]	(改为感叹句)<\\n>The new housing estate in the city center is very expensive.<\\n>____ ____ the new housing estate in the city center is!	[how+/形容词,副词原级/+/主语/+/谓语/]
[47474]	(保持句意基本不变)<\\n>Why don't the twins look the same as each other?<\\n>Why do the twins look ____ ____ each other?	[be different from]
[47471]	(合并句子)<\\n>What would Bob like to be in the future? Bob hasn't told his friends yet.<\\n>Bob hasn't told his friends ____ ____ would like to be in the future.	[what,宾语从句连接词]
[47469]	Many historical ____ will be shown on National Day. (movie)	[create名词复数(/规则可数名词/)]
[47467]	With the help of Yellow Pages, we found the address of the theatre ____. (easy)	[easy<->easily,形容词<->副词]
[47465]	(用括号内所给词的适当形式填空, 使句意完整)<\\n>I'm going to be a ____ (report) when I grow up. I like meeting different people every day.	[report<->reporter,动词<->名词]
[47463]	(用括号内所给词的适当形式填空, 使句意完整)<\\n>China has become much ____ (strong) than before. We're all proud of her.	[比较级(/形容词,副词原级/)]
[47463]	(用括号内所给词的适当形式填空, 使句意完整)<\\n>China has become much ____ (strong) than before. We're all proud of her.	[much+/比较级/]
[47461]	(用括号内所给词的适当形式填空, 使句意完整)<\\n>Look! The children are playing  ____ (happy) in the park.	[happy<->happily,形容词<->副词]
[47459]	(用括号内所给词的适当形式填空, 使句意完整)<\\n>Of all the vegetables, I like ____ (tomato) best.	[名词复数(tomato)]
[47457]	(用括号内所给词的适当形式填空, 使句意完整)<\\n>Stop ____ (talk), please, Let's begin our meeting.	[stop doing]
[47455]	Eric, the ____ son of the family, has a special interest in physics. (three)	[create序数词(three)]
[47453]	It's ____ for him to be so active today as he is always a man of few words. (usual)	[usual<->unusual:反义词]
[47451]	Who is the ____ of the book War and Peace? (write)	[write<->writer]
[47449]	The short play was very ____. I laughed from beginning to end. (fun)	[fun<->funny]
[47447]	It's raining heavily. I'd ____ you call a taxi home now. (suggestion)	[suggest<->suggestion]
[47445]	I think the girl is old enough to tie up her shoes by ____. (her)	[by oneself]
[47445]	I think the girl is old enough to tie up her shoes by ____. (her)	[herself,反身代词]
[47442]	(改为一般疑问句)<\\n>They work on the farm with their parents every weekend.<\\n>____ they ____ on the farm with their parents every weekend?	[一般现在时的/陈述句/->/否定句/,/疑问句/]
[47439]	(改为反意疑问句)<\\n>Let's take a picture in front of the fountain.<\\n>Let's take a picture in front of the fountain, ____ ____?	[反意疑问句:/陈述部分/为let's引导的祈使句,/附加疑问句/为shall we或will you]
[47436]	(对划线部分提问)<\\n>The Shanghai International Arts Festival is held [once a year].<\\n>____ ____ is the Shanghai International Arts Festival held?	[how often,特殊疑问句]
[47433]	(合并为一句)<\\n>He was very nervous. He couldn't go on with the job interview.<\\n>He was ____ nervous ____ go on with the job interview.	[too…to do]
[47430]	(改为简单句)<\\n>I have no idea how I can operate the new machine.<\\n>I have no idea ____ ____ operate the new machine.	[how to do]
[47427]	(保持句意基本不变)<\\n>I'm going to make an early start in order not to miss the train.<\\n>I'm going to make an early start ____ ____ I won't miss the train.	[so that,引导目的状语从句]
[47425]	Joanna received many ____ when graduating from middle school. (gift)	[create名词复数(/规则可数名词/)]
[47423]	Alex is ____ years old and is taken good care of in the kindergarten. (fourth)	[create序数词(four)]
[47421]	Whose school uniform is that on the chair, yours or ____? (my)	[mine,名词性物主代词]
[47421]	Whose school uniform is that on the chair, yours or ____? (my)	[/名词性物主代词/,作表语]
[47419]	It was ____ for human beings to predict whether in the past. (difficulty)	[difficulty<->difficult]
[47417]	There is a beautiful ____ on the wall in each room of my house. (paint)	[paint<->painting]
[47415]	You need to explain your opinions quite ____ when having a debate. (clear)	[clear<->clearly,形容词<->副词]
[47413]	Let's hope that all our troubles will ____ soon. (appear)	[appear<->disappear:反义词]
[47411]	The local people are ____ that the whole nation are helping them rebuild the town. (thank)	[thank<->thankful]
[47408]	(改为一般疑问句)<\\n>Peter often helps in the house at the weekend.<\\n>____ Peter often ____ in the house at the weekends?	[一般现在时的/陈述句/->/否定句/,/疑问句/]
[47405]	(对划线部分提问)<\\n>We used to stay [in a hotel by the sea] on family holidays.<\\n>____ ____ you use to stay on family holidays?	[包含used to的陈述句->否定句,疑问句]
[47402]	(改为反义疑问句)<\\n>Your mother has never tried shopping on the Internet.<\\n>Your mother has never tried shopping on the Internet, ____ ____?	[陈述句中包含never,反意疑问句]
[47399]	(保持句意基本不变)<\\n>James spent ten years making this amazing film.<\\n>____ ____ Janes ten years to make this amazing film.	[It takes sb...to do<->spend doing]
[47396]	(合并为一句)<\\n>Chris has gone to South Africa to enjoy the 2010 World Cup.<\\n>Karen  has gone to South Africa to enjoy the 2010 World Cup, too.<\\n>____ Chris ____ Karen have gone to South Africa to enjoy the 2010 World Cup.	[both A and B,主谓一致]
[47394]	(改为简单句)<\\n>Visitors love this city because it has historical sites and delicious food.<\\n>Visitors love this city ____ its historical sites and delicious food.	[due to,复合介词]
[47394]	(改为简单句)<\\n>Visitors love this city because it has historical sites and delicious food.<\\n>Visitors love this city ____ its historical sites and delicious food.	[because of]
[47392]	Climb up to the ____ floor, and you can enjoy a better view. (eleven)	[create序数词(eleven)]
[47390]	____, Grace made up her mind to live abroad with her daughter. (final)	[final<->finally,形容词<->副词]
[47388]	It is a very ____ book for language learners to improve writing skills. (use)	[use<->useful]
[47386]	Don't worry about your son. He is old enough to be independent and live by ____. (he)	[himself,反身代词]
[47386]	Don't worry about your son. He is old enough to be independent and live by ____. (he)	[by oneself]
[47384]	The movie kungfu Panda is sure to ____ a large number of teenagers. (attractive)	[attract<->attractive]
[47382]	If you don't go on a diet, it is ____ for you to lose weight. (possible)	[possible<->impossible:反义词]
[47380]	The local people had to move away because of the serious ____. (pollute)	[pollute<->pollution]
[47378]	The great ____ gave his first show in Shanghai and the tickets sold out in minutes. (art)	[art<->artist]
[47375]	(改为否定句)<\\n>We keep in touch with each other by email.<\\n>We ____ ____ in touch with each other by email	[一般现在时的/陈述句/->/否定句/,/疑问句/]
[47372]	(对划线部分提问)<\\n>Our school organizes an English speech contest [once a year].<\\n>____ ____ does your school organize an English speech contest?	[how often,特殊疑问句]
[47369]	(改为感叹句)<\\n>The beach is a nice place for tourists.<\\n>____ ____ nice place the beach is for tourists!	[what+a(n)+/形容词/+/可数名词/+/主语/+/谓语/]
[47366]	(合并为一句)<\\n>“Are there any new markets in Asia?”<\\n>The sales manager wants to know.<\\n>The sales manager wants to know ____ there ____ any new markets in Asia.	[if,宾语从句连接词]
[47366]	(合并为一句)<\\n>“Are there any new markets in Asia?”<\\n>The sales manager wants to know.<\\n>The sales manager wants to know ____ there ____ any new markets in Asia.	[whether,宾语从句连接词]
[47363]	(改为被动语态)<\\n>The university will invite many graduates to celebrate its 100th birthday.<\\n>Many graduates will ____ ____ by the university to celebrate its 100th birthday.	[shall/will be v-ed]
[47360]	(保持句意不变)<\\n>We shouldn't talk loudly in the theatre.<\\n>We shouldn't smoke there, either.<\\n>We should ____ talk loudly ____ smoke in the theatre.	[neither A nor B,并列结构]
[47358]	The students took the PISA test in ____ subjects -- reading, maths and science. (third)	[create序数词(three)]
[47356]	Board games are more and more popular among ____. (teenager)	[create名词复数(/规则可数名词/)]
[47354]	I liked to walk in fields on ____ days and to see my footprints left behind. (snow)	[snow<->snowy]
[47352]	____ people often begin their conversations by talking about the weather. (Britain)	[British(英国人)<->Britain]
[47350]	The news about education has attracted the public attention ____. (recent)	[recent<->recently,形容词<->副词]
[47348]	The World Chocolate Park showed a ____ of many kinds of chocolates. (collect)	[collect<->collection]
[47346]	To improve your writing skills, you'd better ____ a habit of reading. (development)	[develop<->development]
[47344]	Don't tell lies. Nobody likes those ____ people. (honest)	[honest<->dishonest:反义词]
[47341]	(改为一般疑问句)<\\n>The new product consists of four main parts inside.<\\n>____ the new product ____ of four main parts inside?	[一般现在时的/陈述句/->/否定句/,/疑问句/]
[47339]	(保持句意基本不变)<\\n>Jessica solved the physics problems without any help.<\\n>Jessica ____ the physics problems without any help.	[deal with]
[47339]	(保持句意基本不变)<\\n>Jessica solved the physics problems without any help.<\\n>Jessica ____ the physics problems without any help.	[work out]
[47336]	(对划线部分提问)<\\n>Susan followed [Ben's] advice to design smart shoes.<\\n>____ advice ____ Susan follow to design smart shoes?	[whose,特殊疑问句]
[47333]	(合并为一句)<\\n>Lin Dan played badminton very well.<\\n>He won the Thomas Cup again.<\\n>Lin Dan played badminton well ____ ____ win the Thomas Cup again.	[/形容词,副词原级/+enough to do]
[47330]	(改为被动语态)<\\n>My students always share ideas in class.<\\n>Ideas ____ always ____ by my students in class.	[am/is/are v-ed]
[47327]	(保持句意基本不变)<\\n>Choose the perfect grapes only, or you won't be able to make the best wine.<\\n>You ____ be able to make the best wine ____ you choose the perfect grapes only.	[/祈使句/+or+/陈述句:shall,will/]
[47324]	(改为宾语从句)<\\n>"Is it the first boys-only school in the city?" asked a parent.<\\n>A parent asked ____ it ____ the first boys-only school in the city.	[宾语从句:主句一般过去时,从句一般过去时]
[47322]	The prices of many ____ usually go up during festivals. (flower)	[create名词复数(/规则可数名词/)]
[47320]	This is the ____ time for our school to hold the robot-making contest. (six)	[create序数词(six)]
[47318]	I could hardly believe she had made a video about water pollution by ____. (her)	[by oneself]
[47318]	I could hardly believe she had made a video about water pollution by ____. (her)	[herself,反身代词]
[47316]	The company hopes its new product will be ____ on the European market. (success)	[success<->successful]
[47314]	Larry has put on too much weight because of his ____ diet. (healthy)	[healthy<->unhealthy:反义词]
[47312]	Jack finds it difficult to pronounce some English words ____. (correct)	[/形容词/<->/副词/]
[47310]	Don't use the lift when you escape from a high ____ during a fire. (build)	[build<->building,动词<->名词]
[47308]	It is not wise of young people to ____ their jobs from time to time. (changeable)	[change<->changeable]
[47305]	(改为否定句)<\\n>Fred plans to work in the charity hospital in the community.<\\n>Fred ____ ____ to work in the charity hospital in the community	[一般现在时的/陈述句/->/否定句/,/疑问句/]
[47302]	(对划线部分提问)<\\n>Jim's office is [four kilometres away] from the nearest underground station.<\\n>____ ____ is Jim's office from the nearest underground station?	[how far,特殊疑问句]
[47299]	(改为被动语态)<\\n>Though the earthquake destroyed many houses, people didn't lose hope.<\\n>Though many houses ____ ____ by the earthquake, people didn't lose hope.	[was/were v-ed]
[47296]	(合并为一句)<\\n>This year's car exhibition was very special．It attracted many visitors.<\\n>This year's car exhibition was ____ special ____ it attracted many visitors.	[so…that,引导结果状语从句]
[47293]	(保持句意基本不变)<\\n>With the help of a local guide, they reached the mountain top in the end.<\\n>With the help of a local guide, they reached the mountain top ____ ____.	[at last<->in the end]
[47290]	(改为感叹句)<\\n>Our journey to Britain last summer was amazing.<\\n>____ ____our journey to Britain last summer was!	[how+/形容词,副词原级/+/主语/+/谓语/]
[47287]	(改为宾语从句)<\\n>"Who is responsible for the food safety problem?" asked the reporter.<\\n>The reporter asked ____ ____ responsible for the food safety problem.	[宾语从句:主句一般过去时,从句一般过去时]
[47285]	Damin feels ____ because few young people want to learn this kind of skill. (happy)	[happy<->unhappy:反义词]
[47283]	Too much work and practice made Jim look older and ____. (ill)	[ill->worse,比较级]
[47281]	Excuse me, could you tell me the ____ of the Great Wall? (long)	[length<->long]
[47279]	Kitty is sure that she will ____ in the final examination. (success)	[succeed<->success]
[47277]	Nowadays blogs are much more helpful than ____ diaries. (tradition)	[tradition<->traditional]
[47275]	Finally Detective Lin made a ____ to search the bedroom for the suspect. (decide)	[decide<->decision]
[47273]	Sally’s interest in painting ____ comes from his art teacher. (main)	[main<->mainly,形容词<->副词]
[47271]	The woman next door took up the piano-playing in her ____. (sixty)	[in one's+/年龄带/]
[47269]	Extreme heat can ____ an illustration (图案) of water on a highway in summer. (creative)	[create<->creative,动词<->形容词]
[47267]	Detective Ken solved the case of the ____ vase in the end. (steal)	[ved(/verb/)]
[47265]	The man on the court denied that he was ____ for the crime. (responsibility)	[responsibility<->responsible,名词<->形容词]
[47265]	The man on the court denied that he was ____ for the crime. (responsibility)	[be responsible for]
[47263]	Let life be beautiful as summer flowers and ____ like autumn leaves. (die)	[die<->death]
[47261]	It's unforgettable to celebrate our ____ birthday in Liuhe. (fourteen)	[create序数词(fourteen)]
[47261]	It's unforgettable to celebrate our ____ birthday in Liuhe. (fourteen)	[/形容词性物主代词/+/序数词/+/名词/]
[47259]	success in study ____ depends on one's efforts. (main)	[main<->mainly,形容词<->副词]
[47257]	Experience tells ____ that we can't judge a book by its cover. (we)	[us,人称代词宾格]
[47257]	Experience tells ____ that we can't judge a book by its cover. (we)	[/及物动词/+/人称代词宾格/]
[47255]	Do you agree that an exchange of ____ is helpful. (opinion)	[名词复数(opinion)]
[47253]	When people get older, their short-term memory becomes ____. (bad)	[bad->worse,比较级]
[47251]	It's easy to ____ the words if we know how to read them correctly. (memory)	[memorize<->memory,动词<->名词]
[47249]	If you feel that it hurts you, it will ____ hurt the rest too. (probable)	[/形容词/<->/副词/]
[47247]	All pilot are ____ for their passengers' safety. (responsibility)	[responsibility<->responsible,名词<->形容词]
[47245]	Yao Ming's ____ makes him stand out in the crowd. (high)	[height<->high]
[47243]	Almost everyone agreed that the New Year party was a great ____. (succeed)	[succeed<->success]
[47241]	Every student in Grade ____ is studying hard to achieve more. (ninth)	[create序数词(nine)]
[47241]	Every student in Grade ____ is studying hard to achieve more. (ninth)	[Grade+/基数词/]
[47239]	Life is simple. You make ____, and you don't look back. (choice)	[名词复数(choice)]
[47237]	I'm ____ sorry that I couldn't find your palmtop computer, Jane. (terrible)	[terrible<->terribly,形容词<->副词]
[47235]	The main reason computers got smaller was through the ____ of the computer chip (芯片) in 1962. (invent)	[invent<->invention]
[47233]	A ____ survey shows that almost 80 percent of vets think that more pets are getting fat. (recently)	[/形容词/<->/副词/]
[47231]	Nowadays blogs are much more useful than ____ diaries. (tradition)	[tradition<->traditional]
[47229]	Kids are asked to dress ____ in the kindergarten. (they)	[/及物动词/+oneself]
[47229]	Kids are asked to dress ____ in the kindergarten. (they)	[themselves,反身代词]
[47227]	The Parthenon is a temple that was built in the ____ century B.C. in Athens. (five)	[create序数词(five)]
[47225]	Sherlock Holmes solved a lot of ____ according to the clues. (case)	[名词复数(case)]
[47223]	More and more underground ____ are being built or will be built in our city. (line)	[名词复数(line)]
[47221]	After World War II, some European countries worked together to ____ Europe and to prevent another war. (build)	[build<->rebuild,近义词]
[47219]	The end of the world rumor (谣言) was ____ reported on newspapers and the Internet some time ago. (wide)	[辨析:wide,widely]
[47217]	The medicine is known to ____ side effects on children. (production)	[produce<-production,动词<->名词]
[47215]	The government hasn't reached a final ____ on the funding yet. (decide)	[decide<->decision]
[47213]	Life of Pi is considered to be one of the most ____ films of the year. (power)	[power<->powerful,名词<->形容词]
[47211]	The automobile industry played an important role in America throughout the ____ century. (twenty)	[create序数词(twenty)]
[47209]	Jackson has been named as the biggest selling artist in the UK since his ____ in 2009. (die)	[die<->death]
[47207]	It was ____ for such old people to dance Swan Lake in China Got Talent. (usual)	[usual<->unusual:反义词]
[47205]	With the help of the police, Tim was ____ enough to get back his lost bike. (luck)	[luck<->lucky]
[47203]	These factories are trying their best not to ____ the river any longer. (pollution)	[pollute<->pollution]
[47201]	With the ____ of economy, our life is getting better and better. (develop)	[develop<->development]
[47199]	All your suggestions will be discussed ____ before we come to a decision. (careful)	[careful<->carefully,形容词<->副词]
[47197]	You know Mike's hobby is playing football, but ____ is collecting stamps. (I)	[mine,名词性物主代词]
[47197]	You know Mike's hobby is playing football, but ____ is collecting stamps. (I)	[/名词性物主代词/,作主语]
[47195]	At this year's American Music Awards, Taylor Swift took home ____ trophies, including the top honour, Artist of the Year. (third)	[create序数词(three)]
[47193]	After six ____ in prison, the famous music producer and director was set free. (month)	[名词复数(month)]
[47191]	When the news came, everybody was ____ at the rare flood in Beijing. (shock)	[ved(/verb/)]
[47189]	The chemicals in the bottle are dangerous and it must be ____ locked in the lab. (secure)	[secure<->securely,形容词<->副词]
[47187]	According to the plan they have made, I am sure they won't ____. (success)	[succeed<->success]
[47185]	Liu Xiang received an ____ in the USA and it was very successful. (operate)	[operate<->operation]
[47183]	Mrs. Anderson has a little garden and she grows some ____ in it. (tomato)	[名词复数(tomato)]
[47181]	Chinese people ____ clean their houses before the Spring Festival. (usual)	[usual<->usually,形容词<->副词]
[47179]	After Andy was retired, the company wanted to find a new ____ urgently. (drive)	[drive<->driver]
[47177]	Mo Yan is the ____ Chinese to win the Nobel Prize in Literature. (one)	[create序数词(one)]
[47175]	Are there any ____ news reports in today’s newspaper, my son? (interest)	[interest<->interesting]
[47173]	My son was ____ yesterday because he had no time to see his favourite film. (happy)	[happy<->unhappy:反义词]
[47171]	Sherry ____ the maths problems with her classmates after school. (discussion)	[discuss<->discussion]
[47169]	My father ____ forgot where he had put his wallet the day before yesterday. (complete)	[complete<->completely,形容词<->副词]
[47167]	Though he is not so good at English, he has done ____ than before. (well)	[well->better,比较级]
[47167]	Though he is not so good at English, he has done ____ than before. (well)	[/比较级/+than before]
[47165]	The ____ of his pet dog called Jimmy made him very sad indeed. (die)	[die<->death]
[47163]	The little girl introduced ____ to her new English teacher bravely. (her)	[/及物动词/+oneself]
[47163]	The little girl introduced ____ to her new English teacher bravely. (her)	[herself,反身代词]
[47161]	Many ____ like to go to Hainan Island to enjoy their winter holidays. (visit)	[visit<->visitor]
[47159]	Though it was not a good ____, he still said his watch went wrong. (excusable)	[excuse<->excusable,动词<->形容词]
[47157]	Quite a few clubs have been set up to make our school life more ____. (colour)	[colour<->colourful]
[47155]	Don't ____ kids with terrible stories when they do something wrong. (frightening)	[frighten<->frightening,动词<->形容词]
[47153]	It rained so hard that the road was ____ covered by water soon. (complete)	[complete<->completely,形容词<->副词]
[47151]	The manager talked about the ____ of the project again and again. (important)	[importance<->important]
[47149]	James and I were told that the toy department was on the ____ floor. (four)	[create序数词(four)]
[47149]	James and I were told that the toy department was on the ____ floor. (four)	[on+the+/序数词/+floor]
[47147]	You can use my dictionary if you can't find ____. (you)	[yours,名词性物主代词]
[47147]	You can use my dictionary if you can't find ____. (you)	[/及物动词/+/名词性物主代词/]
[47145]	He likes the film because one of his favourite ____ is in it. (actress)	[名词复数(actress)]
[47143]	The classroom is ten metres in ____. (long)	[length<->long]
[47141]	I think these things are ____. Please put them in the rubbish bin. (use)	[use<->useless,动词<->形容词]
[47139]	Don't disturb him. He is in deep ____. (think)	[think<->thought,动词<->名词]
[47137]	The good news made all of us ____. (excite)	[make…+/形容词/]
[47137]	The good news made all of us ____. (excite)	[excite<->excited]
[47135]	Mike and his classmates enjoy ____ in the pool in summer. (swim)	[ving(swim)]
[47133]	Everyone should ____ our environment because it's important to our health. (protective)	[protect<->protective,动词<->形容词]
[47131]	The boy was the ____ one to get to the school playground. (four)	[create序数词(four)]
[47129]	We can look at ____ in the mirror. (we)	[ourselves,反身代词]
[47129]	We can look at ____ in the mirror. (we)	[/介词/+oneself]
[47127]	Recently there have been a ____ of health education activities in our school. (various)	[variety<->various,名词<->形容词]
[47125]	It’s amazing to see these local people wear their ____ hats and skirts in festivals. (tradition)	[tradition<->traditional]
[47123]	Someone phoned the police that two young men were planning to ____ a bank. (robbery)	[rob<->robbery,动词<->名词]
[47123]	Someone phoned the police that two young men were planning to ____ a bank. (robbery)	[/动词/<->/名词/]
[47121]	Martin helped the little girl out of a car accident, but he was ____ wounded instead. (serious)	[serious<->seriously,形容词<->副词]
[47119]	LiuQian put some coins in a magic box and said, "These coins will ____ soon." (appear)	[appear<->disappear:反义词]
[47117]	Many people are crazy at Moyan’s ____ in winning the Nobel Prize for Literature. (succeed)	[succeed<->success]
[47115]	MoMoWu (吴莫愁) prepared a lot for The voice of China and won the ____ prize. (two)	[create序数词(two)]
[47113]	Overwork in big ____ in China has brought many problems to young people. (city)	[名词复数(city)]
[47111]	Don't ____ too much on your parents. Try to deal with problems yourselves. (independent)	[depend<->independent,动词<->形容词]
[47109]	Mrs. Zhou always does her favour to students who need help with great ____. (pleased)	[pleasure<->pleased]
[47107]	Doctor Lin left in a hurry to ____on a wonderful young man just now. (operation)	[operate<->operation]
[47105]	Williams gave his students a wonderful ____ on Manners last Wednesday. (speak)	[speak<->speech]
[47103]	I hear that her uncle has bought a new flat in the city centre ____. (recent)	[recent<->recently,形容词<->副词]
[47101]	April Fool’s Day is a(n)____holiday. You can play a trick on anybody around you. (usual)	[usual<->unusual:反义词]
[47099]	The 3rd China’s Got Talent offers the child a chance to show his special ____. (able)	[ability<->able,名词<->形容词]
[47097]	Yesterday the couple talked a lot with a friend of ____ on the internet. (they)	[/名词/+of+/名词性物主代词/]
[47095]	They've done their best to find a good ____ to the rising prices of vegetables. (solve)	[solve<->solution]
[47093]	The little child looks thin and weak because of his ____ diet. (healthy)	[healthy<->unhealthy:反义词]
[47091]	For ____ reasons, the work can't be done at present. (variety)	[variety<->various,名词<->形容词]
[47089]	Miss Lin is sure that she will ____ in the coming writing competition, (success)	[succeed<->success]
[47087]	People felt very sad when they heard about the ____ of the Super-girl Wangbei. (die)	[die<->death]
[47085]	My son's interest in music comes ____ from himself. (main)	[main<->mainly,形容词<->副词]
[47083]	It's his ____ time to visit the Oriental Pearl TV Tower this year. (two)	[create序数词(two)]
[47081]	Detectives have caught several ____ in the past few weeks. (thief)	[名词复数(thief)]
[47079]	They are ____ children because they don't have enough to eat. (healthy)	[healthy<->unhealthy:反义词]
[47077]	We promise to make less rubbish and never ____ the earth. (pollution)	[pollute<->pollution]
[47075]	It was the most ____ experience of my life. Oh, what a tiring day! (frighten)	[frighten<->frightening,动词<->形容词]
[47073]	A kind ____ raised much money for those homeless people there. (art)	[art<->artist]
[47071]	To improve your memory, you’d better use ____ memorizing methods. (variety)	[variety<->various,名词<->形容词]
[47069]	With his teacher’s help, he has made great progress in English ____. (recent)	[recent<->recently,形容词<->副词]
[47067]	I know the ____ of his foot but he doesn't know mine. (long)	[length<->long]
[47065]	The ____ Olympic Games were held in London in 2012. (thirty)	[create序数词(thirty)]
[47063]	The Chinese were the first to use paper money, ____ as early as the eleventh century. (probable)	[/形容词/<->/副词/]
[47061]	"Your job is to ____ customers well, please keep it in mind." The manager said. (service)	[serve<->service:动词<->名词]
[47059]	Neither of them knows ____, so I have to ask a third person for help. (France)	[French(法语,法国人)<->France]
[47057]	Most of the students are ____ with the style of the new school uniform. (satisfy)	[satisfy<->satisfied]
[47055]	It is a wise ____ for these patients to give up smoking. (choose)	[choose<->choice]
[47053]	If you don't go on a diet, it’s ____ for you to lose weight. (possible)	[possible<->impossible:反义词]
[47051]	Mr. Jackson lives on the ____ floor, so he has a better view. (twenty)	[create序数词(twenty)]
[47049]	We were shown quite a few ____ of Beijing last night. (photo)	[名词复数(photo)]
[47047]	The old man felt ____ when he was in dangerous situation and no one was around. (helpful)	[helpful<->helpless:反义词]
[47045]	It is great ____ to talk with Mr. Smith. His talks are full of jokes. (funny)	[fun<->funny]
[47043]	You will be ____ if you try your best to overcome all the difficulties. (success)	[success<->successful]
[47041]	Jim became a Shanghai ____ after he had lived in the city for five years. (city)	[city<->citizen]
[47039]	Mary had ____ known the secret before you told her about it. (possible)	[possible<->possibly,形容词<->副词]
[47037]	Please ____ the hall from the door on the right. (entrance)	[enter<->entrance]
[47035]	Sandy just takes three ____ for meals a day when he is busy. (sandwich)	[名词复数(sandwich)]
[47033]	The students usually have a mid-exam in the ____ week of the term. (ten)	[create序数词(ten)]
[47031]	Mr. Ren, a Chinese ____, began to study global climate change more than a decade ago. (science)	[science<->scientist,名词<->名词]
[47029]	The police will try to find out the ____ of the traffic accident. (true)	[truth<->true]
[47027]	We human beings are closely related to the ____ world in some way. (nature)	[nature<->natural,名词<->形容词]
[47025]	The students in that school are ____ from Asian countries like Japan. (main)	[main<->mainly,形容词<->副词]
[47023]	The guests were told to introduce ____ before the opening ceremony. (they)	[/及物动词/+oneself]
[47023]	The guests were told to introduce ____ before the opening ceremony. (they)	[themselves,反身代词]
[47021]	On the top of the ____ you can have a bird's eyes view of the whole city. (build)	[build<->building,动词<->名词]
[47019]	Be ____ while getting off the train. The ground is wet. (carefully)	[careful<->carefully,形容词<->副词]
[47017]	China will be the ____ nation to build a space station in outer space. (three)	[create序数词(three)]
[47015]	The secrets about the singer are ____ spread among the young fans. (wide)	[辨析:wide,widely]
[47013]	A story about a bad world often ____ as a warning about the present. (service)	[serve<->service:动词<->名词]
[47011]	It was ____ of you to tell such a lie. (honest)	[honest<->dishonest:反义词]
[47009]	As Sally fell down and hurt ____ leg, she won't be able to dance for a long time. (she)	[her+/名词/]
[47007]	Smiling is the best way to show our ____ to others. (kind)	[kindness<->kind,名词<->形容词]
[47005]	I never want to do the same things ____. I like surprises. (two)	[create次数(two)]
[47003]	____ hutongs have a very special and important place in the rich history of Beijing. (tradition)	[tradition<->traditional]
[47001]	The government spent a lot of money building schools and ____. (church)	[名词复数(church)]
[46999]	The old bridge can no longer be used because it was ____ damaged yesterday. (serious)	[serious<->seriously,形容词<->副词]
[46997]	Could you tell me who ____ the first lift in 1853? (invention)	[invent<->invention]
[46995]	The teachers are correcting our exercises ____ in the office. (busy)	[/形容词/<->/副词/]
[46993]	Miss Elizabeth has never been to ____ from birth. (English)	[English(英语)<->England,名词<->名词]
[46991]	Obama is a good ____, that’s why he could beat his partner in American election. (speak)	[speak<->speaker]
[46989]	The organizing Committee is in Room 805 on the ____ floor. Let’s take the elevator. (eight)	[on+the+/序数词/+floor]
[46987]	This is not my pocket calculator. It is ____. (he)	[/名词性物主代词/,作表语]
[46987]	This is not my pocket calculator. It is ____. (he)	[his,名词性物主代词]
[46985]	Those common people who do good deeds are real ____. (hero)	[名词复数(hero)]
[46983]	Jason is too busy, so it’s ____  for him to go to the concert with us tonight. (possible)	[possible<->impossible:反义词]
[46981]	David was able to ____ the math problem with the help of his classmates. (solution)	[solve<->solution]
[46979]	This story tells us that sometimes money doesn't bring ____ to us. (happy)	[happiness<->happy,名词<->形容词]
[46977]	We all know that cigarette smoking can ____ damage our health. (serious)	[serious<->seriously,形容词<->副词]
[46975]	Jack found the map ____ because he couldn't find the place anywhere. (use)	[use<->useless,动词<->形容词]
[46973]	Mrs. Brown has bought a new flat in this building and it’s on the ____ floor. (eight)	[on+the+/序数词/+floor]
[46971]	Lucy said the blue bag on the chair was Tom’s, not ____ . (she)	[/名词性物主代词/,作表语]
[46971]	Lucy said the blue bag on the chair was Tom’s, not ____ . (she)	[hers,名词性物主代词]
[46969]	Mary bought two ____ of fruit from the supermarket yesterday. (box)	[名词复数(box)]
[46967]	Much of this waste does a lot of ____ to the plants. (harmful)	[harm<->harmful]
[46965]	This is the ____ plan. Please go over it. (change)	[change<->changed,动词<->形容词]
[46963]	Tom’s answer was ____. The teacher nodded with a smile. (satisfy)	[satisfy<->satisfying]
[46963]	Tom’s answer was ____. The teacher nodded with a smile. (satisfy)	[satisfy<->satisfactory]
[46961]	In Western countries many young people still keep up the ____ that women will get married in a long white dress. (traditional)	[tradition<->traditional]
[46959]	The weather in Shanghai ____ greatly in the early spring, doesn't it? (variety)	[vary<->variety]
[46957]	Take care of yourself, the mother said ____ to her son. (gentle)	[gentle<->gently,形容词<->副词]
[46955]	How can I get rid of this ____ visitor? (welcome)	[welcome<->unwelcome:反义词]
[46953]	Mike believed his lucky number was ten, so he decided to live on the ____ floor. (ten)	[on+the+/序数词/+floor]
'''
}
