package ots

class SampleData_QuestionMapping5 {

	String content ='''[19263]	____ the one-child policy, our country has controlled the population successfully.	[thanks to]
[19253]	____ the movie star goes, there are lots of fans waiting to see her.	[wherever,引导让步状语从句]
[19248]	____ the morning of September 8th, many visitors arrived ____ the train station for a tour.	[表示时间:at,in,on]
[19248]	____ the morning of September 8th, many visitors arrived ____ the train station for a tour.	[arrive at]
[19243]	____ the morning of March 31, she made an important decision in her life.	[表示时间:at,in,on]
[19234]	____ the help of the teacher, he became a good student.	[with the help of]
[19229]	____ the Great Green Wall, the land produces more crops.	[thanks to]
[19214]	____ the children have fun, parents can take dance lessons on the beach.	[while,引导时间状语从句]
[19210]	____ the bad weather, the swimming match had been put off.	[thanks to]
[19200]	____ the afternoon of June 2nd, many foreigners arrived ____ Shanghai.	[arrive in]
[19200]	____ the afternoon of June 2nd, many foreigners arrived ____ Shanghai.	[表示时间:at,in,on]
[19195]	____ the 632-meter Shanghai Tower is finished, it will be the second tallest building in the world.	[when,引导时间状语从句]
[19195]	____ the 632-meter Shanghai Tower is finished, it will be the second tallest building in the world.	[时间状语从句用一般现在时表示将来]
[19190]	____ that they haven't known the news.	[It seem that…]
[19180]	____ Thanksgiving Day Americans usually eat the pies ____ pumpkins.	[with,介词]
[19180]	____ Thanksgiving Day Americans usually eat the pies ____ pumpkins.	[表示时间:at,in,on]
[19175]	____ tall the girl is!	[how引导的感叹句]
[19170]	____ sugar is delicious, too much of it is bad for your health.	[though,引导让步状语从句]
[19165]	____ something wrong with my bike. Can I use yours?	[there is something wrong with]
[19155]	____ smoke here, dad. Smoking has been banned in public places.	[don't…,祈使句的否定形式]
[19150]	____ sleep too late. It's bad for your health.	[don't…,祈使句的否定形式]
[19135]	____ room is big and bright. They like it very much.	[名词所有格]
[19131]	____ quickly, or you'll be late for school.	[祈使句+or+陈述句]
[19126]	____ pretty your dress is! Where did you get it?	[how引导的感叹句]
[19111]	____ out your love. The world will become a nicer place to live in.	[祈使句]
[19107]	____ our surprise, the twin sisters went to Peking University at the same time last year.	[to one's surprise]
[19102]	____ our government, the students in the countryside can enjoy Nutrition Meals (营养餐) at school now.	[thanks to]
[19092]	____ old man in ____ brown coat over there is Mr. Jackson.	[a]
[19092]	____ old man in ____ brown coat over there is Mr. Jackson.	[the]
[19087]	____ old man behind Tom is ____ university teacher.	[the]
[19087]	____ old man behind Tom is ____ university teacher.	[university,是非元音开头的词]
[19082]	____ of these two hats looks good on my daughter. Do you have another one?	[neither,不定代词]
[19072]	____ of the two story books are very interesting, so I can't decide which one to choose.	[both,不定代词]
[19067]	____ of the two new books are interesting.	[both,不定代词]
[19053]	____ of the students in our school ____ girls.	[分数作主语,主谓一致]
[19048]	____ of the students in our class ____ money to the disabled people these days.	[分数作主语,主谓一致]
[19048]	____ of the students in our class ____ money to the disabled people these days.	[现在完成时]
[19043]	____ of the students in our class ____ boys.	[分数作主语,主谓一致]
[19038]	____ of the land in that district ____ covered with trees and grass.	[分数作主语,主谓一致]
[19038]	____ of the land in that district ____ covered with trees and grass.	[be covered with]
[19033]	____ of the land in that country ____ covered with tree and grass.	[分数作主语,主谓一致]
[19028]	____ of the girls in this school are fans of Li Yuchun.	[分数作主语,主谓一致]
[19010]	____ of his works were written in his ____.	[分数作主语,主谓一致]
[19010]	____ of his works were written in his ____.	[in one's fifties]
[19005]	____ of his time ____ been spent on studies every day.	[分数作主语,主谓一致]
[19005]	____ of his time ____ been spent on studies every day.	[现在完成时的被动语态]
[19001]	____ October 12, 2005, Shenzhou VI was sent up into space successfully.	[表示时间:at,in,on]
[18977]	____ my mother ____ my sister watches football games these days.	[neither…nor,主谓一致]
[18962]	____ my father ____ my mother is able to drive a car. However, they are going to buy one.	[neither…nor,主谓一致]
[18958]	____ my father ____ my brother take good care of me. I love them so much.	[both…and,主谓一致]
[18954]	____ mothers can't go to the meeting, because they have gone to New York on business.	[名词所有格]
[18950]	____ mothers can't come to the meeting because they have gone to Dalian.	[名词所有格]
[18945]	____ more, and you'll improve your spoken English.	[祈使句+and+陈述句]
[18940]	____ meeting it is!	[important,是元音开头的词]
[18940]	____ meeting it is!	[what,引导的感叹句]
[18936]	____ me the truth, or I won't let you leave here.	[祈使句+or+陈述句]
[18931]	____ may have a chance to be successful if he tries his best.	[everybody,复合不定代词]
[18921]	____ many students in China ever ____ to a westerner before?	[ever,用于现在完成时]
[18916]	____ many children like KFC, I think they'd better try not to eat it too often.	[although,引导让步状语从句]
[18911]	____ man riding a motorbike is ____ university teacher.	[the]
[18911]	____ man riding a motorbike is ____ university teacher.	[university,是非元音开头的词]
[18906]	____ man in black is from ____ England.	[零冠词+人名地名]
[18906]	____ man in black is from ____ England.	[the]
[18901]	____ man in a black hat is my PE teacher. He often plays ____ football with us.	[the]
[18901]	____ man in a black hat is my PE teacher. He often plays ____ football with us.	[play+球类棋类]
[18892]	____ Lucy ____ you can't go to the party. One of you has to stay at home to look after your grandma.	[either…or,是并列结构连词]
[18882]	____ lovely weather! Let's go on a picnic.	[weather,不可数名词instances]
[18882]	____ lovely weather! Let's go on a picnic.	[what,引导的感叹句]
[18873]	____ lion is a dangerous animal. Don't you think so?	[the]
[18868]	____ Lesson is not so difficult as we think.	[the+序数词]
[18863]	____ John failed to climb to the top of the mountain several times, he didn't give up.	[although,引导让步状语从句]
[18848]	____ it's difficult to make her dream come true, she never gives up.	[though,引导让步状语从句]
[18843]	____ it was yesterday because of the storm!	[weather,不可数名词instances]
[18843]	____ it was yesterday because of the storm!	[what,引导的感叹句]
[18838]	____ it snowed heavily yesterday, nobody in our class missed the lesson.	[though,引导让步状语从句]
[18833]	____ it is very late, ____ my mother is still at work.	[although,but不可一起使用]
[18824]	____ it got dark, they still worked hard there.	[though,引导让步状语从句]
[18819]	____ is waiting for you at the gate. He wants to say thanks to you.	[somebody,复合不定代词]
[18810]	____ is necessary for us ____ our own dreams.	[不定式,it,主语]
[18795]	____ is difficult if you put your heart into it.	[nothing,复合不定代词]
[18780]	____ interesting it is to go sailing in Qingdao in summer!	[how引导的感叹句]
[18776]	____ interesting books! I want to buy them.	[what,引导的感叹句]
[18766]	____ in the sun is bad for your eyes.	[v-ing作主语,主谓一致]
[18761]	____ I was in the US, I made a lot of American friends.	[while,引导时间状语从句]
[18756]	____ I see your ID card, sir? We have to check your information.	[May I…,疑问句]
[18751]	____ I read, ____ I'll be.	[the+比较级...the+比较级,引导比较状语从句]
[18746]	____ I have lost my new English dictionary.	[情境语义]
[18741]	____ I am in trouble, my best friend Li Lei always helps me.	[whenever,引导让步状语从句]
[18736]	____ her husband, she has now became a famous film star.	[thanks to]
[18731]	____ her great joy, her daughter was finally saved by the doctors.	[to one's joy]
[18722]	____ he was only twelve, he could run faster than any kids in the school.	[though,引导让步状语从句]
[18713]	____ he knew he was wrong, he didn't say sorry to us.	[though,引导让步状语从句]
[18708]	____ he is only 8 years old, he knows more about science than his father.	[though,引导让步状语从句]
[18699]	____ he has little knowledge, the old worker has a lot of experience.	[although,引导让步状语从句]
[18694]	____ hard it was, he would never give up.	[no matter+wh-/how,引导让步状语从句]
[18689]	____ happily the children are flying kites!	[how引导的感叹句]
[18684]	____ Greens are preparing for the coming Thanksgiving Day.	[the+姓氏,主谓一致]
[18679]	____ great picture! Who painted it?	[what,引导的感叹句]
[18669]	____ good time they had last weekend!	[what,引导的感叹句]
[18660]	____ good advice you've told me! Thank you very much!	[what,引导的感叹句]
[18655]	____ girls took part in the Happy Girl Competition but only few of them succeeded.	[millions of…]
[18650]	____ Gina ____ Tara are studying Chinese history and culture now. They find them rich and amazing.	[both…and,是并列结构连词]
[18650]	____ Gina ____ Tara are studying Chinese history and culture now. They find them rich and amazing.	[both…and,主谓一致]
[18646]	____ get off the bus before it stops.	[don't…,祈使句的否定形式]
[18621]	____ football fans (球迷) are still hoping to see Roberto Baggio (罗伯特·巴乔) in this summer' s World Cup finals (决赛) in Japan and South Korea (韩国).	[millions of…]
[18611]	____ fine weather today! Why not go out for a walk?	[weather,不可数名词instances]
[18611]	____ fine weather today! Why not go out for a walk?	[what,引导的感叹句]
[18606]	____ fine day it is! Let's go and fly a kite.	[what,引导的感叹句]
[18602]	____ exercising, and you'll be healthier.	[祈使句+and+陈述句]
[18602]	____ exercising, and you'll be healthier.	[keep doing]
[18598]	____ exercise you take, ____ you'll be.	[the+比较级...the+比较级,引导比较状语从句]
[18593]	____ exciting sport it is to climb the mountains!	[what,引导的感叹句]
[18588]	____ exciting news! We will have a ____ holiday after the exam.	[复合形容词]
[18588]	____ exciting news! We will have a ____ holiday after the exam.	[news,不可数名词instances]
[18588]	____ exciting news! We will have a ____ holiday after the exam.	[what,引导的感叹句]
[18584]	____ exciting news you've told me!	[news,不可数名词instances]
[18584]	____ exciting news you've told me!	[what,引导的感叹句]
[18574]	____ exciting event the 2006 World Cup is!	[what,引导的感叹句]
[18569]	____ excellent basketball player Jeremy Lin (林书豪) is! I really love this talented guy.	[what,引导的感叹句]
[18564]	____ English well, one must have a lot of practice.	[不定式,句子成分]
[18560]	____ English well, he practices speaking English every day.	[不定式,句子成分]
[18555]	____ English teacher is not only strict with the students but also with ____.	[her,形容词性物主代词]
[18555]	____ English teacher is not only strict with the students but also with ____.	[himself,反身代词]
[18550]	____ energy, turn off the hot water after you take a shower.	[不定式,句子成分]
[18540]	____ early, and you won't be late for school.	[get up]
[18540]	____ early, and you won't be late for school.	[祈使句+and+陈述句]
[18531]	____ do you play the piano? Twice a week.	[how often特殊疑问句,应答句]
[18526]	____ do you like better, tea or coffee?	[which,特殊疑问句]
[18521]	____ do you have a face-to-face talk with your parent(s)?	[how often,特殊疑问句]
[18516]	____ do you guess will be the first 10 top students in English in your school next term?	[who,特殊疑问句]
[18512]	____ do the shoes cost? They are 65 yuan.	[how much,特殊疑问句]
[18507]	____ disappointed he is! Let's help him, ____?	[let's+反义疑问词]
[18507]	____ disappointed he is! Let's help him, ____?	[how引导的感叹句]
[18497]	____ day it is! Let's go out and enjoy the clear air and the sunshine.	[what,引导的感叹句]
[18493]	____ dangerous it is to ride fast on a busy road!	[how引导的感叹句]
[18469]	____ children there are in a family, ____their life will be.	[the+比较级...the+比较级,引导比较状语从句]
[18464]	____ children Simon and Jim are! They help Mrs. Li clean the house every day.	[what,引导的感叹句]
[18455]	____ call me Wang Wang! It's my dog's name.	[don't…,祈使句的否定形式]
[18450]	____ call me Mimi! It's my cat's name.	[don't…,祈使句的否定形式]
[18445]	____ buy your ticket from a ticket machine. There are lots of people there.	[don't…,祈使句的否定形式]
[18441]	____ beautiful day! Shall we go camping?Good idea!	[what,引导的感叹句]
[18431]	____ are you going to the airport?	[how,特殊疑问句]
[18422]	____ and then you can pass the exam. My teacher said.	[祈使句+and+陈述句]
[18412]	____ an Englishman, John is looking forwards ____ the 2012 Olympic Games.	[as,介词]
[18412]	____ an Englishman, John is looking forwards ____ the 2012 Olympic Games.	[look forward to]
[18407]	____ Amy likes to go to the cinema, but she doesn't like to see horror films.	[though,but不可一起使用]
[18382]	____ age 7, Bruce won second prize in the piano competition.	[at,介词]
[18377]	____ after the explosion happened in a factory in Dehui, Jilin on June 3rd, a lot of firemen rushed to put out the fire.	[shortly after]
[18372]	____ about the sports meeting make us excited.	[规则可数名词instances]
[18372]	____ about the sports meeting make us excited.	[不可数名词instances]
[18367]	____ a terrible rainy night, many farmers' houses were destroyed.	[表示时间:at,in,on]
[18363]	____ a teacher, John thinks that his main duty is to help the students to become better learners.	[as,介词]
[18353]	____ a light when necessary. You will bring light to other people and yourself.	[turn on]
[18349]	____ a driver is found to be drunk while driving, he will get a fine and even be in danger.	[if,引导条件状语从句]
[18344]	____ a book in the library, enter a key word into the computer.	[不定式,句子成分]
[18339]	____ a beautiful car! I've never seen it before.	[what,引导的感叹句]
[18334]	____ 15th International Film Festival will be held in Shanghai.	[the+序数词]
[18330]	[The Smiths] are watching the men's table tennis match at the moment.	[the+姓氏]
[18326]	[One fourth] of the children are singing in the music classroom.	[分数]
[18326]	[One fourth] of the children are singing in the music classroom.	[一半，四分之一]
[18317]	[Be careful]! There's some broken glass on the ground. The underlined part means ____.	[look out]
[18312]	[At times] an ad can lead you to buy something you don't need at all, so you have to be careful.	[at times]
[18307]	[At last], all the students in our class passed the exam.	[at last]
[18307]	[At last], all the students in our class passed the exam.	[in the end]
[18297]	(词义接近)<\\n>Tom didn't hand in his homework this morning, [it got up his teacher's nose].	[情境语义]
[18292]	(词义接近)<\\n>Maybe the best gift in the world is [not expensive], but must be full of love.	[情境语义]
[18287]	(词义接近)<\\n>[That is a monkey on his back]. Let's help him.	[情境语义]
[18282]	My football socks are ____ out.<\\n>How long have you ____ them?	[延续性动词,用于现在完成时]
[18282]	My football socks are ____ out.<\\n>How long have you ____ them?	[how long特殊疑问句,现在完成时]
[18282]	My football socks are ____ out.<\\n>How long have you ____ them?	[be worn out]
[18278]	Marcia, could you please ____ my dog when I'm on vacation? Yes, sure.	[look after]
[18274]	Is that boy Ken? It ____ be him. He has gone to Zunyi.	[can't,mustn't]
[18269]	I'll pay him as soon as he ____ the TV set to my home, said the man.	[时间状语从句用一般现在时表示将来]
[18265]	How much money did you ____ in fixing your watch? About ten yuan.	[spend (in) doing]
[18261]	How do you often go to school? I ____ take a bus but I walk now.	[used to,情态动词]
[18257]	Have you ever finished your homework? No, ____.	[yet,用于现在完成时]
[18253]	Have you ____ spoken to a foreigner? Not yet. I haven't got a chance.	[ever,用于现在完成时]
[18249]	For your coming vacation, why ____ coming to Guiyang? Good idea!	[why,不定式]
[18249]	For your coming vacation, why ____ coming to Guiyang? Good idea!	[consider doing]
[18245]	Do you want to go to ____ action movie? No, I don't want to.	[an+元音开头的词]
[18241]	Do you know ____ have our summer holiday? Next week.	[when,宾语从句连接词]
[18237]	Do you have your summer plan, Bill? Well, I want to go ____ to relax with my family.	[somewhere,anywhere,nowhere,everywhere:辨析]
[18233]	Could you please tell me ____? It's next to the hotel.	[where,宾语从句连接词]
[18224]	— Zigong is becoming more and more beautiful!<\\n>— Yes. Lots of trees and flowers ____ these years.	[现在完成时的被动语态]
[18220]	— Zhou Weilun could hardly speak English three years ago, ____?<\\n>— No, he couldn't. But now he is quite good at it.	[hardly,反意疑问句]
[18205]	— Yummy! The coffee is good.<\\n>— That's right. It will taste ____ with some milk.	[形容词和副词比较级]
[18200]	— You've left the light on.<\\n>— Oh, sorry. ____ and turn it off.	[情境语义]
[18195]	— You've given us a wonderful dinner, Mrs. Li. Thank you!<\\n>— ____.	[Thank you…,应答句]
[18185]	— You've dropped ____ s in the word necessary.<\\n>— Oh, ____ letter s is doubled.	[字母,读音以元音开头]
[18185]	— You've dropped ____ s in the word necessary.<\\n>— Oh, ____ letter s is doubled.	[the]
[18185]	— You've dropped ____ s in the word necessary.<\\n>— Oh, ____ letter s is doubled.	[冠词]
[18181]	— You've done a nice job!<\\n>— Thanks. I always do everything ____.	[副词的构成]
[18181]	— You've done a nice job!<\\n>— Thanks. I always do everything ____.	[副词instances]
[18176]	— You've done a great job, Grace.<\\n>— ____	[赞誉和表扬的应答句]
[18166]	— You're supposed to hand in the travel diary as soon as possible.<\\n>— I see. I'm going to ____ until 11:30 pm once more.	[stay up]
[18161]	— You're new here, ____?<\\n>— Yes, I'm from Dujiangyan. I came here last week.	[反意疑问句]
[18152]	— Your watch is so beautiful. It must be expensive.<\\n>— Not at all. I only ____￥20 on it.	[cost,pay,spend,take]
[18152]	— Your watch is so beautiful. It must be expensive.<\\n>— Not at all. I only ____￥20 on it.	[spend on]
[18142]	— Your tea smells great!<\\n>— It's from India. Would you like ____?	[some+不可数名词]
[18132]	— Your sweater looks nice, is it made of wool?<\\n>— Yes, and it's made ____ Shanghai.	[in,介词]
[18127]	— Your son is much ____ now.<\\n>— Yes. The jeans he wore last year are already too short for him.	[much+形容词副词比较级]
[18112]	— Your Japanese is so good. How long have you learned it?<\\n>— ____ I was six.	[since+一般过去时,主句用现在完成时]
[18097]	— Your father is sleeping. Would you mind turning down the TV?<\\n>— ____. I'll do it right away.	[Would you mind…,应答句]
[18093]	— Your English is very good.<\\n>— Thank you. I ____ English since I was five years old.	[since+一般过去时,主句用现在完成时]
[18088]	— Your English is quite good.<\\n>— ____.	[赞誉和表扬的应答句]
[18084]	— Your English is pretty good! How about ____ some advice to me?<\\n>— With pleasure.	[how about doing]
[18074]	— Your coat is so beautiful. It must be expensive.<\\n>— Not really. I only ____ 30 yuan on it.	[cost,pay,spend,take]
[18074]	— Your coat is so beautiful. It must be expensive.<\\n>— Not really. I only ____ 30 yuan on it.	[spend on]
[18065]	— Your classroom is very clean.<\\n>— Yes, it ____ every day.	[一般现在时的被动语态]
[18061]	— Your classroom is really bright and clean.<\\n>— It ____ after school every day.	[一般现在时的被动语态]
[18057]	— Your city looks beautiful.<\\n>— Yes. Many bridges ____ last year.	[一般过去时的被动语态]
[18052]	— Your city looks beautiful!<\\n>— Yes. Lots of trees and grass ____ last year.	[一般过去时的被动语态]
[18042]	— Your brother's never been abroad, has he?<\\n>— ____. He studied there last year.	[反意疑问句,应答句]
[18037]	— Your brother often disagree with you, ____ he?<\\n>— ____. We often have different opinions.	[反意疑问句,应答句]
[18032]	— Your brother doesn't get up early, does he?<\\n>— ____. But he gets up late on weekends.	[反意疑问句,应答句]
[18027]	— Your bag looks the same ____ mine.<\\n>— Oh, really? It's a gift ____ my father.	[the same as]
[18027]	— Your bag looks the same ____ mine.<\\n>— Oh, really? It's a gift ____ my father.	[from,介词]
[18022]	— Your aunt often walks the dog in the morning.<\\n>— Yeah, ____ bad weather stops her.	[unless,引导条件状语从句]
[18002]	— You won the first prize in the English competition?<\\n>— ____ I always fail in English tests.	[赞誉和表扬的应答句]
[17987]	— You were not in when I went to see you yesterday.<\\n>— Oh, I ____ for a friend from England at the airport at that moment.	[过去进行时]
[17978]	— You speak good English. Could you tell me ____?<\\n>— You'd better communicate with others in English as much as possible.	[how,宾语从句连接词]
[17968]	— You speak English so well. ____ have you learned English?<\\n>— For 5 years.	[how long特殊疑问句,现在完成时]
[17963]	— You speak English much ____ than before.<\\n>— Thank you.	[much+形容词副词比较级]
[17953]	— You play the piano so well. How long have you learned it?<\\n>— ____ ten years.	[for+一段时间,用于现在完成时]
[17948]	— You never told us why you were late for the meeting, ____?<\\n>— ____. I think it is not necessary to explain.	[never,反意疑问句]
[17943]	— You never exercise.<\\n>— ____. I walk for more than one hour every day.	[反意疑问句,应答句]
[17918]	— You look so happy. What happened?<\\n>— I have got an A in ____ P.E. test.	[my,形容词性物主代词]
[17913]	— You look so ____. What's wrong?<\\n>— My clothes are out of style.	[情境语义]
[17908]	— You look sad. What has happened?<\\n>— Everyone ____ us to win the match, but we lost.	[expect…to do]
[17908]	— You look sad. What has happened?<\\n>— Everyone ____ us to win the match, but we lost.	[一般过去时]
[17898]	— You look ____. What's up, sir?<\\n>— I can't find my ticket, but it's time to check in.	[情境语义]
[17888]	— You haven't been to the West Lake, have you?<\\n>— ____. But I will go there with my parents this summer vacation.	[反意疑问句,应答句]
[17883]	— You have seen the film The Dead Reading, haven't you?<\\n>— ____. How I wish to see it again!	[情境语义]
[17878]	— You have a nice watch.<\\n>— Thank you. I ____ it since I got married.	[since+一般过去时,主句用现在完成时]
[17878]	— You have a nice watch.<\\n>— Thank you. I ____ it since I got married.	[延续性动词,用于现在完成时]
[17873]	— You have a beautiful voice. I love your songs.<\\n>— ____.	[赞誉和表扬的应答句]
[17869]	— You had nothing for breakfast this morning, ____?<\\n>— No, I got up too late.	[nothing,反意疑问句]
[17864]	— You don't smoke, do you?<\\n>— ____. I have never smoked a cigarette before.	[反意疑问句,应答句]
[17854]	— You don't look well, Don! You'd better see your doctor.<\\n>— I ____, but he said there was nothing wrong.	[省略句]
[17839]	— You didn't send me an e-mail last night, did you?<\\n>— Sorry. My ____ broke down. I couldn't get online.	[情境语义]
[17819]	— You come from England, don't you?<\\n>— ____. I come from a small town near London.	[反意疑问句,应答句]
[17814]	— You come from England, don't you?<\\n>— ____. How do you know that?	[反意疑问句,应答句]
[17799]	— You can hardly swim, ____ you?<\\n>— ____. But my mother says she'll teach me during my summer holiday.	[hardly,反意疑问句]
[17799]	— You can hardly swim, ____ you?<\\n>— ____. But my mother says she'll teach me during my summer holiday.	[反意疑问句,应答句]
[17794]	— You bought a new car! An American car?<\\n>— No. A Chinese car. It ____ in Taizhou.	[一般过去时的被动语态]
[17790]	— You aren't a student now, are you?<\\n>— ____, don't you remember ____ me in the classroom ten minutes ago?	[remember to do,remember doing]
[17790]	— You aren't a student now, are you?<\\n>— ____, don't you remember ____ me in the classroom ten minutes ago?	[反意疑问句,应答句]
[17785]	— You are standing too near to the TV. Can you move a bit ____?<\\n>— 0K. Mum. Is it all fight here?	[far,比较级构成]
[17775]	— You are so ____, Harris. What's wrong?<\\n>— Oh, I just feel a little tired and don't want to say anything.	[情境语义]
[17765]	— You are not allowed ____.<\\n>— It's dangerous, really!	[be allowed to do]
[17761]	— You are always talking about your pet cat. What does it look like?<\\n>— ____.	[what...look like]
[17757]	— You are ____ on the phone, Mary.<\\n>— Yes, mum. ____.	[情境语义]
[17747]	— You ____ be happy with the strong public support you've received.<\\n>— Yes, you're right. I'm really excited.	[must,should,ought to]
[17742]	— You ____ be excited that you're going back to your hometown soon.<\\n>— Yes, I can't wait any longer.	[must,should,ought to]
[17737]	— Yesterday I won the first place in the 100-meter race.<\\n>— Really? ____!	[陈述成就,应答句]
[17732]	— Yesterday I received a letter from John.<\\n>— You did? I hear he ____ for America next year.	[现在进行时]
[17732]	— Yesterday I received a letter from John.<\\n>— You did? I hear he ____ for America next year.	[leave for]
[17727]	— Yao Ming is very popular among teenagers.<\\n>— Yes. Many middle school students are his ____.	[情境语义]
[17723]	— Xie Hui jumps ____ in our class. I believe that he will win the high jump.	[形容词和副词最高级]
[17718]	— Xiao Wang, ____ will it take to fly to Guangzhou?<\\n>— Sorry, I don't know.	[how long,特殊疑问句]
[17703]	— Wow, your new bicycle looks the same as ____.<\\n>— Really?	[mine,名词性物主代词]
[17693]	— Wow, you have a ticket to the Expo.<\\n>— It ____ by my uncle. He is working in Shanghai.	[一般过去时的被动语态]
[17689]	— Wow, what a nice MP4! Whose is it?<\\n>— My aunt bought it for my brother and me. It's ____.	[ours,名词性物主代词]
[17684]	— Wow, so many new houses! I can't believe that. It used to be a poor village.<\\n>— Yes. ____ has changed here.	[everything,复合不定代词]
[17679]	— Wow, so many beautiful cars! I don't know which one to buy.<\\n>— Anyway, you have to make a ____.	[make a decision]
[17674]	— Wow! You've got so many skirts.<\\n>— But ____ of them are in fashion now.	[none of+复数名词,主谓一致]
[17669]	— Wow! You've got so many clothes.<\\n>— But ____ of them are in fashion now.	[none of+复数名词,主谓一致]
[17659]	— Wow! What a ____ park! You can hardly hear the traffic!<\\n>— Yes, and no one is shouting.	[情境语义]
[17649]	— Would you please ____ the paper for me and see if there are any obvious (明显的) mistakes?<\\n>— Of course I will.	[look through]
[17644]	— Would you please tell me ____?<\\n>— OK, her name is Cici.	[what,宾语从句连接词]
[17640]	— Would you please tell me ____?<\\n>— At 10:00 this evening.	[when,宾语从句连接词]
[17635]	— Would you please tell me ____ next?<\\n>— Think it over. You'll find a good way.	[what to do]
[17630]	— Would you please see the film Iron Man 3 with me tonight, Kate?<\\n>— I'd love to, but I've ____ Linda's invitation to dinner.	[accept,receive:辨析]
[17620]	— Would you please pass me the ____? I need to look up a word in it.<\\n>— OK, here you are.	[情境语义]
[17615]	— Would you please pass me something to drink?<\\n>— What about some ____?	[juice,不可数名词instances]
[17610]	— Would you please help me with my writing skills?<\\n>— ____.You can come to my office every Saturday.	[表示请求,应答句]
[17605]	— Would you please help me with my drawing skills?<\\n>— ____. You can come to my studio every Saturday.	[表示请求,应答句]
[17596]	— Would you please drive ____, Nick? It's a little late.<\\n>— I'd like to, but safety must come first.	[形容词副词比较级构成]
[17591]	— Would you please carry the heavy box for me?<\\n>— ____.	[Would you please do sth,应答句]
[17586]	— Would you mind watering the flowers for me?<\\n>— ____. I have to go to the post office.	[Would you mind…,应答句]
[17571]	— Would you mind turning down the music? I'm studying for my test.<\\n>— ____.	[Would you mind…,应答句]
[17566]	— Would you mind stopping your cigarette?<\\n>— ____. I forget it's No-smoking here.	[Would you mind…,应答句]
[17556]	— Would you mind opening the window?<\\n>— ____. It's very hot and wet in the room.	[Would you mind…,应答句]
[17551]	— Would you mind opening the window? It's too hot in the room.<\\n>— ____. I'll do it right away.	[Would you mind…,应答句]
[17547]	— Would you mind opening the window, sir?<\\n>— ____. It's really hot.	[Would you mind…,应答句]
[17543]	— Would you mind not ____ your schoolbag here?<\\n>— Sorry. I'll put it somewhere else.	[mind doing]
[17538]	— would you mind my using your dictionary?<\\n>— ____.	[Would you mind…,应答句]
[17533]	— Would you mind my using your computer?<\\n>— ____	[Would you mind…,应答句]
[17528]	— Would you mind my sitting next to you?<\\n>— ____.	[Would you mind…,应答句]
[17524]	— Would you mind my closing the window?<\\n>— ____.	[Would you mind…,应答句]
[17514]	— Would you mind if I smoke here?<\\n>— ____, Look at the sign. It says No Smoking .	[Would you mind…,应答句]
[17505]	— Would you mind cleaning your room?<\\n>— OK. I'll do it in ____ minute.	[a]
[17505]	— Would you mind cleaning your room?<\\n>— OK. I'll do it in ____ minute.	[表示时间:after,in]
[17496]	— Would you mind cleaning the blackboard?<\\n>— ____. I'll do it in a minute.	[Would you mind…,应答句]
[17491]	— Would you mind ____ your bike?<\\n>— Sorry. I'll do it right away.	[mind doing]
[17482]	— Would you mind ____ the music a little? Don't you think it is too loud?<\\n>— Sorry! I'll do it in a minute.	[mind doing]
[17482]	— Would you mind ____ the music a little? Don't you think it is too loud?<\\n>— Sorry! I'll do it in a minute.	[turn down]
[17472]	— Would you mind ____ my pet dog when I am out?<\\n>— Sorry, I can't. I have to study for my test this week.	[mind doing]
[17472]	— Would you mind ____ my pet dog when I am out?<\\n>— Sorry, I can't. I have to study for my test this week.	[take care of]
[17462]	— Would you mind ____ in the dining hall?<\\n>— Of course not.	[mind doing]
[17457]	— Would you like to watch the three-D film Titanic with me?<\\n>— Certainly. I don't mind seeing it again although I ____ it twice.	[现在完成时的时间状语]
[17442]	— Would you like to tell me ____?<\\n>— Sure. Practice makes perfect.	[how,宾语从句连接词]
[17433]	— Would you like to see a movie this weekend?<\\n>— [Wonderful]! I'd love to.	[情境语义]
[17418]	— Would you like to play table tennis with me?<\\n>— I don't feel like it. I would rather ____ at home and watch TV.	[would rather,不定式]
[17413]	— Would you like to have a walk after supper with us?<\\n>— ____.	[Would you like to do sth,应答句]
[17408]	— Would you like to have ____ coffee?<\\n>— No, thanks. I don't want ____ drinks now.	[some,any]
[17403]	— Would you like to have ____ cake?<\\n>— No, thanks. I've had two. That's enough.	[another,形容词instances]
[17399]	— Would you like to have ____ cake?<\\n>— No, thanks. I'm full.	[another,形容词instances]
[17394]	— Would you like to have ____ apples?<\\n>— No, thanks you. I've had enough.	[another+基数词]
[17365]	— Would you like to go to the concert with me tonight?<\\n>— I'd love to, but ____ of us couple has tickets. Do you have some?	[neither,不定代词]
[17360]	— Would you like to go to the concert please?<\\n>— I'd love to, ____ I'm afraid I have no time.	[but,连词]
[17355]	— Would you like to go to the amusement park?<\\n>— If Jack does, ____.	[so,引导的倒装句]
[17340]	— Would you like to go the hospital to help the sick kids this Sunday?<\\n>— ____. I'll be free then.	[Would you like to do sth,应答句]
[17325]	— Would you like to go out to play basketball with me?<\\n>— ____, but I should finish my homework first.	[Would you like to do sth,应答句]
[17315]	— Would you like to go out for a walk with me?<\\n>— Not ____ I finish my dinner.	[not…until]
[17290]	— Would you like to go bike riding with us tomorrow?<\\n>— Sure, ____ I am busy.	[unless,引导条件状语从句]
[17275]	— Would you like to drink some juice?<\\n>— ____, but I've drunk a lot of tea.	[Would you like to do sth,应答句]
[17260]	— Would you like to come to dinner with me this evening?<\\n>— ____. but I have to babysit my younger sister.	[Would you like to do sth,应答句]
[17250]	— Would you like tea or coffee?<\\n>— ____ is OK. I really don't mind.	[either,不定代词]
[17245]	— Would you like some water or tea?<\\n>— ____. A cup of coffee, please.	[neither,不定代词]
[17241]	— Would you like some tea, please?<\\n>— Yes, I prefer tea ____ sugar.	[with,介词]
[17236]	— Would you like some tea, please?<\\n>— Yes, and l prefer tea ____ some sugar.	[with,介词]
[17231]	— Would you like some noodles?<\\n>— ____. I'm not hungry now.	[Would you like to do sth,应答句]
[17226]	— Would you like some more soup?<\\n>— ____. It is delicious, but I've had enough.	[Would you like to do sth,应答句]
[17196]	— Would you like some juice or bread?<\\n>— ____. I'm really thirsty and hungry after such a long walk.	[both,不定代词]
[17192]	— Would you like some eggs, Judy?<\\n>— ____. I don't like them at all.	[Would you like to do sth,应答句]
[17177]	— Would you like some coffee?<\\n>— No, thanks. I'm hungry. Just some ____, please.	[情境语义]
[17172]	— Would you like some coffee?<\\n>— No, thanks. I ____ drink coffee. Coffee is bad for my stomach.	[hardly,频率副词]
[17167]	— Would you like some coffee, please?<\\n>— Yes, and please get some sugar. I prefer coffee ____ sugar.	[with,介词]
[17153]	— Would you like some ____?<\\n>— Yes, just a little.	[a little+不可数名词]
[17148]	— Would you like some ____?<\\n>— Yes, a little please.	[a little+不可数名词]
[17143]	— Would you like some ____?<\\n>— Oh, yes, just a little.	[a little+不可数名词]
[17133]	— Would you like some ____?<\\n>— No, thank you. I'm not hungry at all.	[情境语义]
[17128]	— Would you like some ____.<\\n>— Oh, yes, just a little.	[a little+不可数名词]
[17123]	— Would you like me to take you to the new shopping centre?<\\n>— ____. I've been there once.	[Would you like me to do sth,应答句]
[17118]	— Would you like me to show you the way?<\\n>— ____.	[Would you like me to do sth,应答句]
[17098]	— Would you like ____?<\\n>— Thank you, but I'm not thirsty.	[情境语义]
[17093]	— Would you like ____ to drink?<\\n>— Yes, I' d like a cup of coffee.	[something+形容词]
[17089]	— Would you like ____ to drink now?<\\n>— No, thanks.	[something+形容词]
[17084]	— Would you like ____ the Wutong Mountain tomorrow?<\\n>— If my mother ____, I will go with you.	[条件状语从句,时态]
[17084]	— Would you like ____ the Wutong Mountain tomorrow?<\\n>— If my mother ____, I will go with you.	[would like to do]
[17079]	— Would you like ____ red dress as a birthday present, Mary?<\\n>— Sorry, mom. I prefer ____ orange one.	[a]
[17079]	— Would you like ____ red dress as a birthday present, Mary?<\\n>— Sorry, mom. I prefer ____ orange one.	[an+元音开头的词]
[17059]	— Would you like ____ camping with me?<\\n>— I'd like to. But I'm busy ____ my homework.	[go + v-ing]
[17059]	— Would you like ____ camping with me?<\\n>— I'd like to. But I'm busy ____ my homework.	[busy (in) doing]
[17059]	— Would you like ____ camping with me?<\\n>— I'd like to. But I'm busy ____ my homework.	[would like to do]
'''
}
