package ots

class SampleData_QuestionMapping9 {

	String content ='''[3335]	— Could you tell me how long ____?<\\n>— For two weeks.	[how long,特殊疑问句]
[3330]	— Could you tell me how long ____ the book?<\\n>— Three days.	[how long,宾语从句连接词]
[3330]	— Could you tell me how long ____ the book?<\\n>— Three days.	[how long,特殊疑问句]
[3320]	— Could you tell me ____?<\\n>— To get ready for the High School Entrance Exam.	[why,宾语从句连接词]
[3320]	— Could you tell me ____?<\\n>— To get ready for the High School Entrance Exam.	[could you…,引导的主句]
[3320]	— Could you tell me ____?<\\n>— To get ready for the High School Entrance Exam.	[stay up]
[3315]	— Could you tell me ____?<\\n>— Sure. Just go straight and turn left. You can see it on your right.	[how,宾语从句连接词]
[3310]	— Could you tell me ____?<\\n>— Sure. It started on May 31 in Korea and Japan.	[where,宾语从句连接词]
[3310]	— Could you tell me ____?<\\n>— Sure. It started on May 31 in Korea and Japan.	[when,宾语从句连接词]
[3305]	— Could you tell me ____?<\\n>— Sorry. I don' l know. I was not at the meeting.	[what,宾语从句连接词]
[3295]	— Could you tell me ____?<\\n>— Of course.	[where,宾语从句连接词]
[3290]	— Could you tell me ____?<\\n>— Of course, last night.	[when,宾语从句连接词]
[3280]	— Could you tell me ____?<\\n>— More than a year.	[how long,宾语从句连接词]
[3276]	— Could you tell me ____?<\\n>— It's near the post office.	[where,宾语从句连接词]
[3272]	— Could you tell me ____?<\\n>— It will be held in October. 2010.	[一般将来时的被动语态]
[3268]	— Could you tell me ____?<\\n>— In six days.	[how soon特殊疑问句,应答句]
[3263]	— Could you tell me ____?<\\n>— He is in the library.	[where,宾语从句连接词]
[3254]	— Could you tell me ____?<\\n>— Certainly. In half an hour.	[could you…,引导的主句]
[3254]	— Could you tell me ____?<\\n>— Certainly. In half an hour.	[when,宾语从句连接词]
[3249]	— Could you tell me ____?<\\n>— By searching the Internet.	[how,宾语从句连接词]
[3244]	— Could you tell me ____?<\\n>— At the end of July.	[when,宾语从句连接词]
[3229]	— Could you tell me ____? I'd like to take part in it.<\\n>— On July 5th.	[when,宾语从句连接词]
[3220]	— Could you tell me ____? He is wanted by the head teacher.<\\n>— Sorry, I've no idea. But he ____ here just now.	[where,宾语从句连接词]
[3220]	— Could you tell me ____? He is wanted by the head teacher.<\\n>— Sorry, I've no idea. But he ____ here just now.	[could you…,引导的主句]
[3220]	— Could you tell me ____? He is wanted by the head teacher.<\\n>— Sorry, I've no idea. But he ____ here just now.	[just now,用于一般过去时]
[3216]	— Could you tell me ____ Zhang Daqian Museum?<\\n>— The day after tomorrow, I think.	[could you…,引导的主句]
[3216]	— Could you tell me ____ Zhang Daqian Museum?<\\n>— The day after tomorrow, I think.	[when,宾语从句连接词]
[3211]	— Could you tell me ____ you'll be away?<\\n>— Only one week.	[how long特殊疑问句,应答句]
[3201]	— Could you tell me ____ yesterday?<\\n>— Because my bike was broken on my way here.	[why,宾语从句连接词]
[3191]	— Could you tell me ____ tomorrow morning?<\\n>— Well, it will start at 9:00 o'clock.	[could you…,引导的主句]
[3191]	— Could you tell me ____ tomorrow morning?<\\n>— Well, it will start at 9:00 o'clock.	[when,宾语从句连接词]
[3146]	— Could you tell me ____ last night?<\\n>— Er, I was watching TV at home.	[what,宾语从句连接词]
[3136]	— Could you tell me ____ in your hometown in winter?<\\n>— Sure.	[where,宾语从句连接词]
[3126]	— Could you tell me ____ for the meeting yesterday?<\\n>— Because the traffic was bad.	[why,宾语从句连接词]
[3122]	— Could you tell me ____ Dalian?<\\n>— Last week.	[leave for]
[3122]	— Could you tell me ____ Dalian?<\\n>— Last week.	[when,宾语从句连接词]
[3108]	— Could you tell me ___?<\\n>— Next month．	[when,宾语从句连接词]
[3093]	— Could you please tell me something about the two ____?<\\n>— ____. They are exchange students of No. 1 Middle School.	[Could you please do sth,应答句]
[3088]	— Could you please tell me ____?<\\n>— Yes, sure.	[if,宾语从句连接词]
[3083]	— Could you please tell me ____?<\\n>— Tomorrow morning.	[when to do]
[3078]	— Could you please tell me ____?<\\n>— They're over there.	[where,宾语从句连接词]
[3078]	— Could you please tell me ____?<\\n>— They're over there.	[could you…,引导的主句]
[3074]	— Could you please tell me ____?<\\n>— They are over there.	[where,宾语从句连接词]
[3074]	— Could you please tell me ____?<\\n>— They are over there.	[could you…,引导的主句]
[3069]	— Could you please tell me ____?<\\n>— I live in Yan'an.	[where,宾语从句连接词]
[3065]	— Could you please tell me ____?<\\n>— He is twenty.	[how old,宾语从句连接词]
[3055]	— Could you please tell me ____?<\\n>— Bus No. 32 will take you right there.	[which,宾语从句连接词]
[3050]	— Could you please tell me ____?<\\n>— Because it's very helpful.	[why,宾语从句连接词]
[3050]	— Could you please tell me ____?<\\n>— Because it's very helpful.	[could you…,引导的主句]
[3046]	— Could you please tell me ____ tomorrow?<\\n>— At 8 o'clock.	[what time,宾语从句连接词]
[3036]	— Could you please tell me ____ more about shoe yogurt?<\\n>— Certainly. You can look it up in this webpage.	[where,宾语从句连接词]
[3032]	— Could you please tell me ____ in today's newspaper?<\\n>— Sorry, ____.	[nothing+形容词]
[3032]	— Could you please tell me ____ in today's newspaper?<\\n>— Sorry, ____.	[something+形容词]
[3022]	— Could you please tell me ____ in America?<\\n>— On the fourth Thursday in November.	[宾语从句语序]
[3013]	— Could you please show me ____?<\\n>— Sure, no problem.	[how,宾语从句连接词]
[3013]	— Could you please show me ____?<\\n>— Sure, no problem.	[show+直接宾语+宾语从句]
[3008]	— Could you please provide us ____ some information about the students' health?<\\n>— Of course, it's my pleasure.	[provide…with]
[3004]	— Could you please pass me the eraser, Bob?<\\n>— ____.	[Could you please do sth,应答句]
[2999]	— Could you please pass me the book?<\\n>— ____.	[Could you please do sth,应答句]
[2994]	— Could you please pass me something to eat?<\\n>— What about some ____?	[情境语义]
[2990]	— Could you please help me carry the box? It's too heavy.<\\n>— ____.	[Could you please do sth,应答句]
[2986]	— Could you please help me carry the box? It's too heavy.<\\n>— ____	[Could you please do sth,应答句]
[2977]	— Could you please ____ my goldfish while I' m away?<\\n>— It's my pleasure.	[look after]
[2972]	— Could you make your bed and wash your clothes?<\\n>— ____.	[表示请求,应答句]
[2957]	— Could you help me do the dishes?<\\n>— Sorry, my sister ____ for me outside now.	[现在进行时]
[2942]	— Could you get home at five o'clock?<\\n>— ____ I'll have a meeting at that time.	[表示请求,应答句]
[2917]	— Could you come and spend the weekend with us?<\\n>— ____. I have to prepare my coming exam.	[表示请求,应答句]
[2907]	— Could we see each other at 9 o'clock tomorrow morning?<\\n>— Sorry, let's make it ____ time.	[make it+名词]
[2907]	— Could we see each other at 9 o'clock tomorrow morning?<\\n>— Sorry, let's make it ____ time.	[another,形容词instances]
[2902]	— Could we play football in your playground, Sir?<\\n>— No, ____ you have the principal's note.	[unless,引导条件状语从句]
[2897]	— Could we go and watch the football game?<\\n>— No, ____ you have the ticket.	[unless,引导条件状语从句]
[2897]	— Could we go and watch the football game?<\\n>— No, ____ you have the ticket.	[Could I…,应答句]
[2892]	— Could I use your bike for today, Sam?<\\n>— ____. I'm not using it.	[Could I…,应答句]
[2877]	— Could I borrow your dictionary?<\\n>— Of course you ____.	[Could I…,应答句]
[2868]	— Congratulations! You've got a chance to be an exchange student!<\\n>— ____.	[赞誉和表扬的应答句]
[2863]	— Congratulations! Your speech is excellent.<\\n>— ____.	[赞誉和表扬的应答句]
[2853]	— Congratulations on your success!<\\n>— ____.	[赞誉和表扬的应答句]
[2848]	— Computer is very useful.<\\n>— Yes, with the help of computers, news can ____ every corner of the world.<\\n>	[arrive, get to, reach]
[2843]	— Come on. Let's ____!<\\n>— I just want to take it easy. My feet are killing me.	[情境语义]
[2838]	— Come back quickly, Tom.<\\n>— Sure, Mum. ____.	[祈使句的应答句]
[2833]	— Come and join us. Jimmy!<\\n>— I'm sorry, but I'm really busy now. If I ____ time, I would certainly go.	[虚拟语气复合句:I would go if it were fine.]
[2828]	— Come and join us, Ben!<\\n>— I'm afraid I can't. I'm too busy now. If I ____ time, I would certainly go.	[虚拟语气复合句:I would go if it were fine.]
[2824]	— Claudia, your handwriting is much ____ than before.<\\n>— Thank you.	[much+形容词副词比较级]
[2819]	— Clark, your room is really in a mess. It needs ____.<\\n>— Sorry, mum. I'll do it at once.	[need to do]
[2819]	— Clark, your room is really in a mess. It needs ____.<\\n>— Sorry, mum. I'll do it at once.	[不定式,被动语态]
[2809]	— Chinese tennis player Li Na won a championship again!<\\n>— Yeah, I watched the game and my spirits ____ at the news.	[情境语义]
[2799]	— Chinese astronauts can also walk in space now.<\\n>— Yes, they're ____ our nation.	[be the pride of]
[2794]	— China is beginning to test the air quality with the new standard (标准) PM2.5.<\\n>— Good news! Then the old PMIO standard will be ____.	[out of]
[2789]	— China beat Australia 1:0 at the 17th Women's Football Asian Cup last night.<\\n>— Really? ____.	[陈述成就,应答句]
[2784]	— Children all like this book.<\\n>— I think it ____ very interesting.	[must,should,ought to]
[2759]	— Can you tell the differences between these two pictures?<\\n>— Differences? Oh, no. They look quite ____.	[情境语义]
[2754]	— Can you tell me why ____?<\\n>— Because I want to help the people there.	[why,宾语从句连接词]
[2745]	— Can you tell me the English meaning of the word?<\\n>— Why don't you ____ in the dictionary?	[look up]
[2741]	— Can you tell me how to use the digital camera?<\\n>— ____. Let me have a look.	[表示请求,应答句]
[2736]	— Can you tell me how many colours ____ in a rainbow?<\\n>— Seven.	[宾语从句语序]
[2731]	— Can you tell me ____?<\\n>— Yesterday.	[when,宾语从句连接词]
[2726]	— Can you tell me ____?<\\n>— Yes, 500 yuan.	[how much,宾语从句连接词]
[2722]	— Can you tell me ____?<\\n>— Sure. His home is next to the cinema.	[where,宾语从句连接词]
[2707]	— Can you tell me ____?<\\n>— He is in the library.	[where,宾语从句连接词]
[2698]	— Can you tell me ____?<\\n>— By doing more exercises and speaking.	[how,宾语从句连接词]
[2689]	— Can you tell me ____?<\\n>— About two months ago.	[when,宾语从句连接词]
[2684]	— Can you tell me ____ your parents at home?<\\n>— I often wash clothes and sweep the floor.	[how,宾语从句连接词]
[2659]	— Can you tell me ____ to travel to Dalian?<\\n>— About two hours by plane.	[cost,pay,spend,take]
[2659]	— Can you tell me ____ to travel to Dalian?<\\n>— About two hours by plane.	[how long,宾语从句连接词]
[2654]	— Can you tell me ____ to send this postcard to New York by airmail?<\\n>— Let me check. Oh, it's one dollar.	[cost,pay,spend,take]
[2654]	— Can you tell me ____ to send this postcard to New York by airmail?<\\n>— Let me check. Oh, it's one dollar.	[how much,宾语从句连接词]
[2649]	— Can you tell me ____ to live a low-carbon (低碳) life?<\\n>— OK. Use both sides of the paper. Don't use plastic bags or disposable goods (一次性用品).	[how to do]
[2639]	— Can you tell me ____ this morning?<\\n>— Sorry, I've no idea.	[why,宾语从句连接词]
[2629]	— Can you tell me ____ the prize, Tom?<\\n>— Last year.	[when,宾语从句连接词]
[2614]	— Can you tell me ____ on the Internet?<\\n>— OK, mum.	[how,宾语从句连接词]
[2564]	— Can you ride a horse?<\\n>— No, I ____.	[can,情态动词]
[2549]	— Can you play the piano?<\\n>— Yes, I ____. I often practice it on weekends.	[can,情态动词]
[2530]	— Can you pass this exam?<\\n>— ____. I'm working hard this year.	[情境语义]
[2520]	— Can you imagine ____ the Taiwan HEDP (塑化剂) event will affect our life?<\\n>— I'm not sure. Many people have begun to have water instead of drinks.	[how much,宾语从句连接词]
[2515]	— Can you help me ____ my cat while I am away?<\\n>— No problem. Just bring it to my house ____ you leave.	[before,引导时间状语从句]
[2515]	— Can you help me ____ my cat while I am away?<\\n>— No problem. Just bring it to my house ____ you leave.	[look after]
[2505]	— Can you guess ____?<\\n>— I've no idea about it.	[how much,宾语从句连接词]
[2500]	— Can you guess ____ the new schoolbag yesterday?<\\n>— Sorry, I've no idea.	[cost,pay,spend,take]
[2500]	— Can you guess ____ the new schoolbag yesterday?<\\n>— Sorry, I've no idea.	[how much,宾语从句连接词]
[2491]	— Can you give me some information about vacation trips?<\\n>— Why not ____ going to Hainan island?	[why,不定式]
[2491]	— Can you give me some information about vacation trips?<\\n>— Why not ____ going to Hainan island?	[consider doing]
[2467]	— Can you cook by ____?<\\n>— Yes, I can cook well.	[by oneself]
[2462]	— Can you come to my party on Saturday afternoon?<\\n>— ____. I'll have to help my parents.	[表示请求,应答句]
[2458]	— Can you come over to my birthday party, Susan?<\\n>— I will come if I ____ free tomorrow.	[条件状语从句,时态]
[2448]	— Can you come and give us a talk on Thursday or Friday?<\\n>— I'm afraid ____ day is possible.	[neither,形容词instances]
[2433]	— Can you answer the door, Jim? I ____ the dishes.<\\n>— I'm coming, dad.	[现在进行时]
[2428]	— Can we run across the road now?<\\n>— No, we ____. We have to wait until the light turns green.	[can't,mustn't]
[2423]	— Can Peter play games with us, Mrs. Hawking?<\\n>— Wait a minutes. He ____ a shower.	[现在进行时]
[2418]	— Can I wear the dress to school, Mum?<\\n>— No, you can't. You ____ wear the school uniform, or your teacher will be angry.	[must,情态动词]
[2408]	— Can I walk across the road now, mum?<\\n>— No, you ____. You have to wait until the light turns green.	[can't,mustn't]
[2398]	— Can I use your mobile phone?<\\n>— Of course. ____.	[情境语义]
[2393]	— Can I use your e-dictionary?<\\n>— Sorry. I don't have ____.	[one,it]
[2384]	— Can I take the magazines out?<\\n>— No, sir. They ____ out of the reading-room. It's a rule.	[can't,mustn't]
[2384]	— Can I take the magazines out?<\\n>— No, sir. They ____ out of the reading-room. It's a rule.	[must,被动语态]
[2379]	— Can I take a seat here, Sir?<\\n>— ____ My cousin will be back soon.	[情境语义]
[2355]	— Can I put ____ car here?<\\n>— Of course.	[my,形容词性物主代词]
[2345]	— Can I join you?<\\n>— Sure, we are talking about ____.	[why,宾语从句连接词]
[2340]	— Can I join Oxfam Trailwalker?<\\n>— Only if you are ____ eighteen.	[over,介词]
[2320]	— Can I help you?<\\n>— Yes, can you tell me ____?	[which,宾语从句连接词]
[2310]	— Can I help you?<\\n>— I'd like ____ for my twin daughters.	[a pair of shoes]
[2306]	— Can I help you, sir?<\\n>— I'd like to have 100 ____. I want my students to draw pictures.	[a piece of paper]
[2296]	— Can I help you, boy?<\\n>— Yes. There is ____ wrong with my bike.	[there is something wrong with]
[2281]	— Can I have some more ice cream, Mum?<\\n>— Sorry. There is ____ left in the fridge.	[nothing,none]
[2276]	— Can I have some cookies, Mom?<\\n>— ____ I'll get you some.	[Can I…,应答句]
[2272]	— Can I have some cheese pies, Mum?<\\n>— Sorry, dear. These pies ____ for the kids in the disabled children's home.	[一般现在时的被动语态]
[2262]	— Can I go to the park, Mum?<\\n>— Certainly. But you ____ be back by six o'clock.	[must,情态动词]
[2257]	— Can I go to the movie, Mum?<\\n>— Certainly. But you ____ be back by ten o'clock.	[must,情态动词]
[2247]	— Can I go bike riding with my friends, mum?<\\n>— Sure, if your homework ____.	[条件状语从句,时态]
[2247]	— Can I go bike riding with my friends, mum?<\\n>— Sure, if your homework ____.	[一般现在时的被动语态]
[2238]	— Can I come this afternoon or tomorrow morning?<\\n>— ____ is OK. I'm free today and tomorrow.	[either,不定代词]
[2233]	— Can I borrow your ruler, please?<\\n>— Yes, you ____. But you must return it to me before lunchtime.	[can,情态动词]
[2229]	— Can I borrow your dictionary?<\\n>— Yes, you ____.	[can,情态动词]
[2214]	— Can a plane fly ____ the Atlantic Ocean?<\\n>— Yes, but it needs to go ____ the clouds for hours.	[位置移动:across,through]
[2209]	— By the way, have you got ____ e-mail address?<\\n>— Oh, yes, it is swimonland@hotmail.com.	[字母,读音以元音开头]
[2205]	— By the end of this year, China's state and provincial (省的) libraries will be free to the public.<\\n>— That's ____ good news for those who often go to these places.	[news,不可数名词instances]
[2200]	— Boys, would you mind not playing basketball here?<\\n>— ____, Mr. Li.	[Would you mind…,应答句]
[2191]	— Both Li Lei and Han Meimei ____ fond of the TV program A Bite of China.<\\n>— I am also deeply moved by its stories.	[both…and,主谓一致]
[2186]	— Bob, your room is a real mess!<\\n>— ____. I'll clean it up right away.	[表达责备,应答句]
[2181]	— Bob, can you write the number seven hundred and eighty thousand and thirty-two?<\\n>— Yes, It is ____.	[基数词]
[2172]	— Bob invited us to take part in a party next Sunday.<\\n>— ____? Is it for his birthday?	[计划旅行/派对,应答句]
[2168]	— Bill, who's the little boy in the picture?<\\n>— It's me. I am much ____, aren't I?	[much+形容词副词比较级]
[2163]	— Bill, what's your sister's favorite ____?<\\n>— She likes volleyball best.	[情境语义]
[2159]	— Bill, please turn down the music, ____ Mom ____ Dad are sleeping.<\\n>— Sorry, I'll do it right away.	[both…and,主谓一致]
[2149]	— Bill had nothing for breakfast this morning, ____?<\\n>— No, he got up too late.	[nothing,反意疑问句]
[2144]	— Big animals can be a lot of trouble. Maybe you should get a small pet, like a goldfish.<\\n>— ____.	[表达建议/意见/观点,应答句]
[2139]	— Betty, do you know if Tony ____ the photo competition?<\\n>— He will, if he ____ his project on Australia.	[条件状语从句,时态]
[2134]	— Betty, ____ have you lived in China?<\\n>— For about three years.	[how long特殊疑问句,应答句]
[2129]	— Ben, would you like to play football with us?<\\n>— ____, but I have to wash the dishes first.	[Would you like to do sth,应答句]
[2124]	— Ben didn't come to school, did he?<\\n>— ____. Though he was ill.	[反意疑问句,应答句]
[2109]	— Be careful, ____ you will make mistakes in your exams.<\\n>— I know that, Mum. One can never be too careful.	[祈使句+or+陈述句]
[2104]	— Barbara, where do you work?<\\n>— I work for a company ____ sells cars.	[which,引导的定语从句]
[2099]	— Bad weather! Do you think the rain will stop soon?<\\n>— ____. I want to play baseball outside.	[情境语义]
[2094]	— Attention, please. The flight has to be ____ because of the heavy rain.	[have to,被动语态]
[2084]	— At present, one of the best ways to study is working in groups.<\\n>— More chances ____ to students to learn from each other.	[被动语态,to+间接宾语,offer]
[2080]	— As for Mr. Brown, do you know ____?<\\n>— Sure. Canada. But he has been teaching French for two years in Shanghai.	[where,宾语从句连接词]
[2075]	— Arthur is responsible ____ the newspaper, isn't he?<\\n>— ____, but Joyce is. She's the chief editor．	[be responsible for]
[2060]	— Are you sure you can do well in today's test, Lucy?<\\n>— ____. I've got everything ready.	[情境语义]
[2055]	— Are you scared of the fight?<\\n>— No, just a little ____.	[情境语义]
[2050]	— Are you satisfied with the result of the exam?<\\n>— Not at all. I can't have ____.	[bad->worse,比较级]
[2035]	— Are you in a hurry?<\\n>— No, I've got plenty of time. I ____ wait.	[can,情态动词]
[2030]	— Are you good at history, Rose?<\\n>— ____. But I will try to study it well this term.	[情境语义]
[2025]	— Are you going to Tibet for vacation?<\\n>— Yes. I want you to ____ me with some information about it.	[provide…with]
[2015]	— Are you going to the bank, Laura?<\\n>— No, I ____ to the bank already.	[have been to,have gone to,have been in]
[2010]	— Are you going to take part in the speech competition?<\\n>— ____. It's too good a chance to miss.	[情境语义]
[1990]	— Are you afraid of ____ at home, Linda?<\\n>— No, I've grown up.	[alone,lonely]
[1990]	— Are you afraid of ____ at home, Linda?<\\n>— No, I've grown up.	[afraid of]
[1985]	— Are you a soccer player in your school?<\\n>— Yes, I ____ the team two years ago. I ____ in the team for two years.	[一般过去时的时间状语]
[1985]	— Are you a soccer player in your school?<\\n>— Yes, I ____ the team two years ago. I ____ in the team for two years.	[延续性动词,用于现在完成时]
[1980]	— Are you ____ planting online vegetables?<\\n>— No. I think it's a waste of time.	[be interested in]
[1971]	— Are those stamps ____?<\\n>— No, they are not mine. They belong to ____.	[him,人称代词宾格]
[1971]	— Are those stamps ____?<\\n>— No, they are not mine. They belong to ____.	[yours,名词性物主代词]
[1956]	— Are these your books?<\\n>— No, they are not ____.	[mine,名词性物主代词]
[1946]	— Are these books ____?<\\n>— No, they're not mine. They belong to ____.	[yours,名词性物主代词]
[1946]	— Are these books ____?<\\n>— No, they're not mine. They belong to ____.	[her,人称代词宾格]
[1941]	— Are these books ____?<\\n>— No, they are not mine. They belong to ____.	[yours,名词性物主代词]
[1941]	— Are these books ____?<\\n>— No, they are not mine. They belong to ____.	[her,人称代词宾格]
[1931]	— Are Mr. and Mrs. Wang living alone in the house?<\\n>— Yes, although they have three sons, ____ of them live with their parents.	[none of+复数名词,主谓一致]
[1926]	— Are Li Yan and Wang Mei still living in Pingba?<\\n>— No, they ____ to Shanghai.	[现在完成时]
[1902]	— Ann, ____ you say this word in Chinese?<\\n>— Yes．It's easy．	[Can you…,疑问句]
[1897]	— Angela, you are going to buy a flat here, are you?<\\n>— Yes, but I can't ____ an expensive one.	[can,afford]
[1892]	— Andy, you were the only person that was late for the meeting, why?<\\n>— Sorry, sir. But I really had a ____ time finding the meeting hall.	[have a difficult time (in) doing]
[1888]	— An earthquake (地震) hit Wenchuan last month．<\\n>— ____.	[陈述遗憾的事情,应答句]
[1883]	— Amy, I hear you've got many foreign coins ____ I have a look?<\\n>— Of course, I'll fetch them for you.	[May I…,疑问句]
[1849]	— Alice, is this your dictionary?<\\n>— Let me see. Oh, no. ____ is in my school bag.	[mine,名词性物主代词]
[1844]	— After the exam, we'll have a long vacation.<\\n>— Yes, but I haven't planned ____.	[what,宾语从句连接词]
[1840]	— A subway will be built in our hometown before 2015.<\\n>— ____! Will it pass my house?	[news,不可数名词instances]
[1840]	— A subway will be built in our hometown before 2015.<\\n>— ____! Will it pass my house?	[what,引导的感叹句]
[1835]	— A single room, please.<\\n>— OK. Will you please ____ me your ID card?<\\n>— Here you are.	[情境语义]
[1830]	— A number of volunteers ____ willing to teach in China's rural areas.<\\n>— Yes, the number is getting ____.	[the number of+复数名词,主谓一致]
[1830]	— A number of volunteers ____ willing to teach in China's rural areas.<\\n>— Yes, the number is getting ____.	[a number of+复数名词,主谓一致]
[1825]	— A nice day today, isn't it?<\\n>— Yes. ____ go for a picnic and relax ourselves?	[why,不定式]
[1820]	— A new book on how to lose weight is ____ soon.<\\n>— Really? I can't wait to read it.	[come out]
[1810]	— A new 3D movie is on. Shall we go and see it this weekend?<\\n>— ____! What's it?	[Shall we…,应答句]
[1805]	— A homeless man won a lottery ticket. He became rich over night.<\\n>— ____.	[情境语义]
[1801]	— A big fire ____in Dehui, Jilin Province on June 3rd, 2013.<\\n>— That's too bad. I think we should try our best to prevent fires.	[break out]
[1796]	— 2008 Beijing Olympic Games is on the way. Do you know its slogan (口号)?<\\n>— Of course. It's ____.	[情境语义]
[1786]	— ____I use your ruler, Lingling?<\\n>— Sure. Here you are.	[May I…,疑问句]
[1781]	— ____I swim here?<\\n>— I'm sorry. Children ____ swim alone here.	[can't,mustn't]
[1777]	— ____do you speak English so well?<\\n>— Because I practice it with my partner every day.	[why,特殊疑问句]
[1772]	— ____did you visit the Science Museum?<\\n>— Three months ago.	[when,特殊疑问句]
[1757]	— ____?<\\n>— The one behind the tree.	[which,特殊疑问句]
[1752]	— ____?<\\n>— Size 8. Can I try one on?	[情境语义]
[1742]	— ____?<\\n>— Nothing serious, but a bit tired.<\\n>— Better have a rest now, dear.	[what's the matter with you]
[1728]	— ____?<\\n>— I'm looking for a pair of google glasses for my grandson.	[情境语义]
[1723]	— ____?<\\n>— I have a headache and I don't feel like eating anything.	[what's the matter with you]
[1713]	— ____?<\\n>— He is tall.	[what...look like]
[1708]	— ____?<\\n>— He is not very heavy and wears glasses.	[what...look like]
[1695]	— ____?<\\n>— A pizza, please!	[情境语义]
[1680]	— ____. Hope is always around you.<\\n>— Thank you, Dad!	[情境语义]
[1676]	— ____. Can you tell me the way to Xinhua Bookstore?<\\n>— Well, it's just around the corner.	[情境语义]
[1671]	— ____, Peter?<\\n>— I have a bad cold.	[what's the matter with you]
[1667]	— ____ your sister doing housework or playing computer games now?	[现在进行时]
[1658]	— ____ your American friend eat with chopsticks?<\\n>— Yes, but he can't use them well.	[can,be able to:辨析]
[1648]	— ____ you turn down your radio please?<\\n>— Yes, I can.	[can,情态动词]
[1618]	— ____ you sing an English song?<\\n>— Yes, I can.	[can,情态动词]
[1518]	— ____ you ever ____ Dali?<\\n>— Never. But I am going there this vacation.	[have been to,have gone to,have been in]
[1503]	— ____ you ____ your new classmate?<\\n>— Not yet. But we will.	[yet,用于现在完成时]
[1503]	— ____ you ____ your new classmate?<\\n>— Not yet. But we will.	[非延续性动词,用于现在完成时]
[1488]	— ____ you ____ the film Harry Potter 5?<\\n>— No yet. I'll see it this Sunday.	[非延续性动词,用于现在完成时]
[1484]	— ____ you ____ the film Gongfu Panda Ⅱ?<\\n>— Not yet. I'll see it this Sunday.	[非延续性动词,用于现在完成时]
[1479]	— ____ you ____ the Beatles' story?<\\n>— Yes. And their songs are popular.	[现在完成时]
[1479]	— ____ you ____ the Beatles' story?<\\n>— Yes. And their songs are popular.	[hear of]
[1475]	— ____ you ____ take a bus to school?<\\n>— Yes. But now I usually go to school on foot.	[used to陈述句->否定句,疑问句]
[1465]	— ____ you ____ drawing?<\\n>— Not yet! It will be done in a few minutes.	[yet,用于现在完成时]
[1455]	— ____ wonderful dictionary it is! Thank you for buying me such a useful present.<\\n>— I'm glad you like it.	[what,引导的感叹句]
[1440]	— ____ will your headmaster return from Beijing?<\\n>— In two weeks.	[how soon特殊疑问句,应答句]
[1431]	— ____ will you stay in Shanghai?<\\n>— For about three weeks.	[how long特殊疑问句,应答句]
[1421]	— ____ will you finish doing the work?<\\n>— In a few weeks.	[how soon特殊疑问句,应答句]
[1416]	— ____ will you come back?<\\n>— In an hour.	[how soon特殊疑问句,应答句]
[1411]	— ____ will you come back, Mum?<\\n>— In ten minutes.	[how soon特殊疑问句,应答句]
[1406]	— ____ will you be away?<\\n>— In a couple of weeks.	[how soon特殊疑问句,应答句]
[1396]	— ____ will the supper the ready? I'm very hungry.<\\n>— In a minute.	[how soon特殊疑问句,应答句]
[1386]	— ____ will the manager come back'?<\\n>— Maybe in three days.	[how soon特殊疑问句,应答句]
[1381]	— ____ will the bus come?<\\n>— It will come in ten minutes.	[how soon特殊疑问句,应答句]
[1376]	— ____ will she stay here?<\\n>— For ____.	[一半，四分之一]
[1376]	— ____ will she stay here?<\\n>— For ____.	[how long,特殊疑问句]
[1371]	— ____ will Mrs. Lin go to Germany?<\\n>— To see her daughter there.	[why,特殊疑问句]
[1366]	— ____ will it take you to get to the post office?<\\n>— About half an hour.	[how long,特殊疑问句]
[1356]	— ____ will it take us to get there by bus?<\\n>— About two hours.	[how long特殊疑问句,应答句]
[1323]	— ____ weather! It's raining!<\\n>— Bad luck! We can't go climbing today.	[weather,不可数名词instances]
[1323]	— ____ weather! It's raining!<\\n>— Bad luck! We can't go climbing today.	[what,引导的感叹句]
[1313]	— ____ TV do you watch every day?<\\n>— About two hours.	[how much,特殊疑问句]
[1308]	— ____ T-shirt do you like better, the red one or the blue one?<\\n>— I prefer the red one.	[which,特殊疑问句]
[1303]	— ____ today?<\\n>— It's June 19th.	[情境语义]
[1293]	— ____ to Japan?<\\n>— Yes. And I will be back next month.	[be going to do]
[1288]	— ____ to give the letter to Mr. Wang. It's very important.<\\n>— No, I won't.	[祈使句的应答句]
[1288]	— ____ to give the letter to Mr. Wang. It's very important.<\\n>— No, I won't.	[don't…,祈使句的否定形式]
[1284]	— ____ there any good news in today's newspaper?<\\n>— No. But there ____ some funny stories worth reading.	[news,不可数名词instances]
[1284]	— ____ there any good news in today's newspaper?<\\n>— No. But there ____ some funny stories worth reading.	[There be A and B,主谓一致]
[1274]	— ____ the small town is!<\\n>— Yes, it is more beautiful than ____ town that I visited last year.	[the]
[1274]	— ____ the small town is!<\\n>— Yes, it is more beautiful than ____ town that I visited last year.	[how引导的感叹句]
[1269]	— ____ the population of Hong Kong?<\\n>— Seven million people.	[what,特殊疑问句]
[1259]	— ____ the little girl looks!<\\n>— That's true. She can't find her Teddy Bear.	[how引导的感叹句]
[1254]	— ____ the Internet ____ in your school?<\\n>— Yes, but the computer in our office has broken down.	[be used in]
[1244]	— ____ the doctor, the most beautiful teacher Zhang Lilli is out of danger.<\\n>— We wish her to live healthy and happy life in the future.	[thanks to]
[1239]	— ____ that new bike over there?<\\n>— I think it's ____.	[whose,特殊疑问句]
[1239]	— ____ that new bike over there?<\\n>— I think it's ____.	[名词所有格]
[1224]	— ____ shall we paint the walls?<\\n>— I prefer white. It makes us feel clam and peaceful.	[what colour,特殊疑问句]
[1204]	— ____ school bag is this?<\\n>— I guess it is Lily's.	[whose,特殊疑问句]
[1199]	— ____ Rose ____ Jack watched Prince William's wedding on TV yesterday.<\\n>— What a pity! They missed the exciting moment.	[neither…nor,是并列结构连词]
[1194]	— ____ room is this?<\\n>— It' s a friend of mine.	[whose,特殊疑问句]
[1184]	— ____ people visit the 2010 Shanghai World Expo every day?<\\n>— About 300,000.	[how many,特殊疑问句]
[1179]	— ____ people are taking action to protect the environment now.<\\n>— Yes. ____ of my classmates come to school by bike now.	[分数]
[1179]	— ____ people are taking action to protect the environment now.<\\n>— Yes. ____ of my classmates come to school by bike now.	[more and more]
[1174]	— ____ of volunteers will be needed for 2014 International Horticulture in Qingdao.<\\n>— Let's go and ____ them.	[thousands of…]
[1174]	— ____ of volunteers will be needed for 2014 International Horticulture in Qingdao.<\\n>— Let's go and ____ them.	[attend,join,join in,take part in]
[1165]	— ____ nice day it is today! Let's go out to play, shall we?<\\n>— That's a good idea.	[what,引导的感叹句]
[1160]	— ____ model plane is this?<\\n>— I think it's Jim's. Look, his name is on it.	[whose,特殊疑问句]
[1151]	— ____ late for school next time<\\n>— Sorry, I won't．	[祈使句的应答句]
[1151]	— ____ late for school next time<\\n>— Sorry, I won't．	[be late for]
[1151]	— ____ late for school next time<\\n>— Sorry, I won't．	[don't…,祈使句的否定形式]
[1146]	— ____ late for school again, Tim!<\\n>— Sorry, I promise that I ____.	[祈使句的应答句]
[1146]	— ____ late for school again, Tim!<\\n>— Sorry, I promise that I ____.	[be late for]
[1146]	— ____ late for school again, Tim!<\\n>— Sorry, I promise that I ____.	[don't…,祈使句的否定形式]
[1141]	— ____ kind girl Nancy is!<\\n>— Yes, she is always ready to help others.	[what,引导的感叹句]
[1137]	— ____ keep water running when you are brushing your teeth or washing your hands, Jack.<\\n>— OK. I know we must save every drop (滴) of water.	[don't…,祈使句的否定形式]
[1127]	— ____ it is today!<\\n>— Yes. Shall we go hiking?	[weather,不可数名词instances]
[1127]	— ____ it is today!<\\n>— Yes. Shall we go hiking?	[what,引导的感叹句]
[1122]	— ____ is your opinion on the film Avatar?<\\n>— It's amazing! I was ____ moved.	[deep,deeply区别]
[1122]	— ____ is your opinion on the film Avatar?<\\n>— It's amazing! I was ____ moved.	[what is your opinion on]
[1118]	— ____ is your new T-shirt?<\\n>— It's only twenty yuan.	[how much,特殊疑问句]
[1113]	— ____ is your mother?<\\n>— She is ____ English teacher.	[what,特殊疑问句]
[1113]	— ____ is your mother?<\\n>— She is ____ English teacher.	[an+元音开头的词]
[1098]	— ____ is your father?<\\n>— He is fine. Thank you!	[how,特殊疑问句]
[1093]	— ____ is your father?<\\n>— A bank clerk. He works in a bank near my home.	[what,特殊疑问句]
[1088]	— ____ is your brother?<\\n>— He is at home.	[where,特殊疑问句]
[1083]	— ____ is your aunt?<\\n>— She is a nurse.	[what,特殊疑问句]
[1078]	— ____ is this dictionary?<\\n>— 10 yuan.	[how much,特殊疑问句]
[1073]	— ____ is the street crowded with so many people?<\\n>— Because they are waiting to watch the boat races.	[why,特殊疑问句]
[1069]	— ____ is the red shirt?<\\n>— It's 50 yuan.	[how much,特殊疑问句]
[1059]	— ____ is the nearest bus stop?<\\n>— It's 10 minutes' walk.	[how far,特殊疑问句]
[1049]	— ____ is the library from our school?<\\n>— It's quite near. Just go ____ the road.	[how far,特殊疑问句]
[1049]	— ____ is the library from our school?<\\n>— It's quite near. Just go ____ the road.	[across,介词]
[1044]	— ____ is the dictionary?<\\n>— It's $22.95.	[how much,特殊疑问句]
[1030]	— ____ is that man over there?<\\n>— He's my uncle.	[who,特殊疑问句]
[1025]	— ____ is that man over there?<\\n>— He is Dick's uncle.	[who,特殊疑问句]
[971]	— ____ is it from your home to school?<\\n>— About three miles.	[how far,特殊疑问句]
[967]	— ____ is it from Leshan to Chengdu?<\\n>— I'm not sure, but it takes about two hours to get there by bus.	[how far,特殊疑问句]
[962]	— ____ is it from here to the railway station?<\\n>— About ten kilometres.	[how far,特殊疑问句]
[947]	— ____ is it from here to No. 1 Middle School?<\\n>— About half an hour's walk. Let's go and visit it.	[how far,特殊疑问句]
[938]	— ____ is it from Haikou to Sanya?<\\n>— It's about 300 kilometres．	[how far,特殊疑问句]
[933]	— ____ is her daughter?<\\n>— The girl on the right wearing blue jeans.	[which,特殊疑问句]
[928]	— ____ is he?<\\n>— He is PSY. He sang the song Gangnam Style (江南Style).	[who,特殊疑问句]
[913]	— ____ is e-shopping getting more and more popular?<\\n>— It's cheap and convenient.	[why,特殊疑问句]
[903]	— ____ is CHINA NEWS shown on CCTV-4?<\\n>— Every day.	[how often,特殊疑问句]
[899]	— ____ interesting talk Mr. Black gave us!<\\n>— Yes. We all like it very much.	[interesting,是元音开头的词]
[899]	— ____ interesting talk Mr. Black gave us!<\\n>— Yes. We all like it very much.	[what,引导的感叹句]
[894]	— ____ I watch TV now, Mom?<\\n>— No. It's too late, and you ____ go to bed.	[must,have to:辨析]
[894]	— ____ I watch TV now, Mom?<\\n>— No. It's too late, and you ____ go to bed.	[May I…,疑问句]
[879]	— ____ I try on those shoes in the window?<\\n>— ____.They are just on show.	[Could I,疑问句]
[879]	— ____ I try on those shoes in the window?<\\n>— ____.They are just on show.	[情境语义]
[874]	— ____ I swim here?<\\n>— I'm sorry. Children ____ swim alone here.	[can't,mustn't]
[874]	— ____ I swim here?<\\n>— I'm sorry. Children ____ swim alone here.	[can,情态动词]
[839]	— ____ I have a ticket, please?<\\n>— Sorry, sir. All the tickets were sold out ten minutes ago.	[May I…,疑问句]
[830]	— ____ I go home now, Mr. Zhang?<\\n>— No. You must finish your homework first.	[May I…,疑问句]
[820]	— ____ I finish my work now, sir?<\\n>— No, you needn't. You can complete it this afternoon.	[must疑问句,应答句]
[810]	— ____ I fill in the check-in form right now, sir?<\\n>— No, you needn't. You can complete it this afternoon.	[must疑问句,应答句]
[801]	— ____ I borrow your MP4?<\\n>— Sure. Here you are.	[May I…,疑问句]
[791]	— ____ I answer this question in English?<\\n>— No, you ____. You may answer it in Chinese.	[must疑问句,应答句]
[762]	— ____ have you stayed in New York?<\\n>— For about two weeks.	[how long特殊疑问句,现在完成时]
[757]	— ____ have you lived with your grandparents?<\\n>— About three years.	[how long特殊疑问句,现在完成时]
[752]	— ____ have you lived in Binzhou?<\\n>— For about ten years.	[how long特殊疑问句,现在完成时]
[742]	— ____ have you been studying English?<\\n>— Since five years ago.	[how long特殊疑问句,现在完成时]
[737]	— ____ have you been married?<\\n>— For twenty years.	[how long特殊疑问句,现在完成时]
[728]	— ____ have you been learning English?<\\n>— I have been learning English for six years.	[how long特殊疑问句,现在完成时]
[723]	— ____ have you been in the sports club?<\\n>— Since the first month I came to the school.	[how long特殊疑问句,现在完成时]
[703]	— ____ have you been away from your hometown?<\\n>— For about 13 years.	[how long特殊疑问句,现在完成时]
[698]	— ____ have you been away from your hometown, Janet?<\\n>— Since 5 years ago.	[how long特殊疑问句,现在完成时]
[688]	— ____ has your mother worked in this factory?<\\n>— Since 1995.	[how long特殊疑问句,现在完成时]
[678]	— ____ hard work you have done!<\\n>— It's very kind of you to say so.	[work,不可数名词instances]
[678]	— ____ hard work you have done!<\\n>— It's very kind of you to say so.	[what,引导的感叹句]
[669]	— ____ good time we had at the party last night!<\\n>— Yes. It was ____ exciting party that I would never forget it.	[such+可数名词]
[669]	— ____ good time we had at the party last night!<\\n>— Yes. It was ____ exciting party that I would never forget it.	[a good time]
[669]	— ____ good time we had at the party last night!<\\n>— Yes. It was ____ exciting party that I would never forget it.	[what,引导的感叹句]
[650]	— ____ does your father play tennis after work?<\\n>— Every Tuesday and Thursday.	[how often特殊疑问句,应答句]
[641]	— ____ does your father do?<\\n>— He is a policeman．	[what do you do]
[637]	— ____ does your cousin go to the gym?<\\n>— Twice a week.	[how often特殊疑问句,应答句]
[633]	— ____ does your brother go to work?<\\n>— By bike.	[how,特殊疑问句]
[614]	— ____ does Mrs. Li wash her car?<\\n>— Once a week.	[how often特殊疑问句,应答句]
[599]	— ____ do you write a letter to your father?<\\n>— I seldom or never do that now. Instead, I call or email him almost every day.	[how often特殊疑问句,应答句]
[595]	— ____ do you water the plants, Miss Yang?<\\n>— Twice a day.	[how often特殊疑问句,应答句]
[520]	— ____ do you think of the football match?<\\n>— It's perfect. It's more exciting than ____ match that I have ever watched.	[what do you think of…]
[520]	— ____ do you think of the football match?<\\n>— It's perfect. It's more exciting than ____ match that I have ever watched.	[比较级+than any other]
[516]	— ____ do you think of the film?<\\n>— Very interesting.	[what do you think of…]
[512]	— ____ do you take exercise every week?<\\n>— Twice or three times.	[how often特殊疑问句,应答句]
[508]	— ____ do you surf the Internet, Maria?<\\n>— Twice a week.	[how often特殊疑问句,应答句]
[503]	— ____ do you study for a test?<\\n>— I study by working with a group.	[how,特殊疑问句]
[499]	— ____ do you shop?<\\n>— I shop once a month.	[how often特殊疑问句,应答句]
[494]	— ____ do you read English newspapers?<\\n>— I read China Daily every day.	[how often特殊疑问句,应答句]
[489]	— ____ do you read English newspapers?<\\n>— I read 21st Century every day.	[how often特殊疑问句,应答句]
[484]	— ____ do you play football?<\\n>— Once a week.	[how often特殊疑问句,应答句]
[471]	— ____ do you like dogs?<\\n>— Because they are very cute.	[why,特殊疑问句]
[466]	— ____ do you know so much about the UFO?<\\n>— I usually get the information by surfing the Internet.	[how,特殊疑问句]
[461]	— ____ do you improve your English?<\\n>— By listening to tapes and reading aloud.	[how,特殊疑问句]
[451]	— ____ do you have PE lessons?<\\n>— There times a week．	[how often特殊疑问句,应答句]
[437]	— ____ do you have a Music Festival at your school?<\\n>— Once a year.	[how often特殊疑问句,应答句]
[432]	— ____ do you have a class meeting?<\\n>— Once a week.	[how often特殊疑问句,应答句]
[427]	— ____ do you hang out with your friends?<\\n>— Once a week.	[how often特殊疑问句,应答句]
[417]	— ____ do you go to visit your grandma?<\\n>— Twice a month.	[how often特殊疑问句,应答句]
[412]	— ____ do you go to the library?<\\n>— Once a week.	[how often特殊疑问句,应答句]
[397]	— ____ do you go to the cinema?<\\n>— Once a month.	[how often特殊疑问句,应答句]
[393]	— ____ do you go to see your grandparents?<\\n>— Once a week.	[how often特殊疑问句,应答句]
[374]	— ____ do you get to school?<\\n>— By bus.	[how,特殊疑问句]
[369]	— ____ do you get to school every day?<\\n>— At half past seven.	[when,特殊疑问句]
[334]	— ____ do millions of online users visit the home page of the government?<\\n>— To read the news and search for the information they need.	[why,特殊疑问句]
[329]	— ____ do I save the document on the computer?<\\n>— Please click save and write a name for it.	[how,特殊疑问句]
[304]	— ____ did you sleep last night?<\\n>— Only five hours. I stayed up late to do my homework.	[how long,特殊疑问句]
[294]	— ____ did you pay for the CD?<\\n>— Only nine dollars.	[how much,特殊疑问句]
[184]	— ____ delicious beef!<\\n>— Well. You can eat more if you like it.	[beef,不可数名词instances]
[184]	— ____ delicious beef!<\\n>— Well. You can eat more if you like it.	[what,引导的感叹句]
[174]	— ____ can you tell whether a foreigner is English or American?<\\n>— Maybe by the way he speaks.	[how,特殊疑问句]
[164]	— ____ can you be ready, Andy?<\\n>— In ten minutes.	[how soon特殊疑问句,应答句]
[159]	— ____ can we get there?<\\n>— In five minutes.	[how soon特殊疑问句,应答句]
[155]	— ____ can I keep these books?<\\n>— Two weeks.	[how long,特殊疑问句]
[150]	— ____ can I get the book if I order it today?<\\n>— In a week.	[how soon特殊疑问句,应答句]
[140]	— ____ bowl of mutton soup would you like?<\\n>— A big bowl, please.	[情境语义]
[135]	— ____ book is this?<\\n>— It must be Sam's. Hemingway is his favorite author.	[whose,特殊疑问句]
[115]	— ____ bag is full, what about ____?<\\n>— It's full, too.	[her,形容词性物主代词]
[115]	— ____ bag is full, what about ____?<\\n>— It's full, too.	[his,名词性物主代词]
[110]	— ____ bad weather!<\\n>— Yes, but it's going to be fine soon, I think.	[weather,不可数名词instances]
[110]	— ____ bad weather!<\\n>— Yes, but it's going to be fine soon, I think.	[what,引导的感叹句]
[80]	— ____ are those vegetables?<\\n>— Two yuan a kilo.	[how much,特殊疑问句]
[70]	— ____ are they talking about?<\\n>— Our English teacher.	[whom,特殊疑问句]
[65]	— ____ are the apples?<\\n>— Four yuan a kilo.	[how much]
[60]	— ____ apple a day keeps the doctor away!<\\n>— What do you mean? I have never heard of ____ saying before.	[the]
[60]	— ____ apple a day keeps the doctor away!<\\n>— What do you mean? I have never heard of ____ saying before.	[apple,是元音开头的词]
[55]	— ____ an Art Festival in your school each term?<\\n>— No, but there is an English party.	[there be句型]
[46]	— ____ a nice day!<\\n>— ____.	[so+主语+助动词]
[46]	— ____ a nice day!<\\n>— ____.	[what,引导的感叹句]
[41]	— The shoes are very nice. I'll take them.<\\n>— But you must ____ first. I think the size is a bit small for you.	[try on]
[36]	— Sorry for being last again.<\\n>— ____ here on time next time, or you'll be punished.	[祈使句]
[31]	— Mum, could you buy me a dress like this?<\\n>— Certainly, we can buy ____ one than this, but ____ this.	[as...as,引导比较状语从句]
[31]	— Mum, could you buy me a dress like this?<\\n>— Certainly, we can buy ____ one than this, but ____ this.	[形容词和副词比较级]
[26]	— Listen! Helen is singing in the next room.<\\n>— It ____ be Helen. She has gone to Beijing.	[can't,mustn't]
[16]	— Food Safety has become one of the hottest topics recently.<\\n>— Yeah, it receives ____ Internet hits (点击) a day.	[thousands of…]
[10]	— ____ bookcase is this?<\\n>— It must be ____.	[whose,特殊疑问句]
[10]	— ____ bookcase is this?<\\n>— It must be ____.	[名词所有格]
'''
}
