package ots

class SampleData_QuestionMapping2 {

	String content ='''[26954]	If you see the cartoon film, you will ____ laugh.	[be made to do sth]
[26944]	If you see a sign with Business Hours: 9:00-17:00 near the door of a shop, you can buy nothing from the shop at ____.	[情境语义]
[26939]	If you really hold on in your dreams, they ____ true one day.	[条件状语从句,时态]
[26934]	If you make a mistake, just say, ____.	[情境语义]
[26929]	If you love what you are doing and work hard, you will ____ anything difficult and succeed.	[get over]
[26924]	If you like the chicken, you may have as ____ as you can.	[chicken,不可数名词instances]
[26924]	If you like the chicken, you may have as ____ as you can.	[much+不可数名词]
[26914]	If you have trouble pronouncing these words, you can repeat them over and over again ____ you are comfortable with them.	[until,引导时间状语从句]
[26909]	If you go to the theatre this evening, so ____ I.	[条件状语从句,时态]
[26909]	If you go to the theatre this evening, so ____ I.	[so,引导的倒装句]
[26904]	If you go by train, you can have quite ____ comfortable journey, but make sure you take ____ fast one.	[a]
[26899]	If you get on well ____ your classmates, you'll enjoy your school life more.	[get along with]
[26888]	If you don't work ____ enough, I don't think your dream will come ____.	[hard,hardly区别]
[26888]	If you don't work ____ enough, I don't think your dream will come ____.	[come true]
[26877]	If you don't know where the post office is, you can ask like this: Excuse me. ____?	[which,特殊疑问句]
[26872]	If you don't go to the meeting tomorrow, ____.	[条件状语从句,时态]
[26862]	If you do things ____, usually you can't do them well.	[in a hurry]
[26857]	If you can't find the place, I will show you ____.	[where,宾语从句连接词]
[26853]	If you can't decide which of the two books to borrow, why don't you take ____? I won't read them this week.	[both,不定代词]
[26848]	If you are thirsty, ____ have some tea?	[why,不定式]
[26843]	If you are in the zoo, remember not to touch or go near animals. Although some of the animals are cute, you ____ leave them alone.	[must,情态动词]
[26838]	If you ____ your name on the paper, you can get a magazine.	[write down]
[26834]	If you ____ your homework, you can go out to play football.	[条件状语从句,时态]
[26829]	If you ____ to the 2010 Shanghai Expo next month, I will go with you.	[条件状语从句,时态]
[26825]	If you ____ him, he will help you.	[条件状语从句,时态]
[26820]	If you ____ go, at least wait until the rain stops.	[must,情态动词]
[26805]	If there is ____ pollution, the air in our city will be ____ dirtier.	[much+形容词副词比较级]
[26805]	If there is ____ pollution, the air in our city will be ____ dirtier.	[much->more,比较级]
[26800]	If there ____ no buying and selling animals, there ____ no killing in nature.	[条件状语从句,时态]
[26795]	If the robot ____ wrong, you can get a new one for free or get all your money back.	[条件状语从句,时态]
[26790]	If the question ____ incorrectly, ____ question will be given to you.	[条件状语从句,时态]
[26790]	If the question ____ incorrectly, ____ question will be given to you.	[another,形容词instances]
[26785]	If the postman has a registered (挂号) letter for us, he ____ it to our flat.	[bring,carry,pass,take,fetch]
[26775]	If Ted can ____ his difficulties, he'll make great progress.	[get over]
[26760]	If price rise too high, the government has to do something ____ it.	[不定式,句子成分]
[26750]	If people ____ cutting down the forest, they will have nowhere ____.	[条件状语从句,时态]
[26750]	If people ____ cutting down the forest, they will have nowhere ____.	[where to do]
[26741]	If my father ____ back, please let me know.	[条件状语从句,时态]
[26736]	If my brother ____ well in his exams, he'll go to Tsinghua University next September.	[条件状语从句,时态]
[26723]	If it doesn't rain tomorrow, we ____ swimming.	[时间状语从句用一般现在时表示将来]
[26704]	If it ____ fine tomorrow, I will go hiking with you.	[条件状语从句,时态]
[26699]	If I were you, I would ____ electricity. It is dangerous.	[stay away from]
[26699]	If I were you, I would ____ electricity. It is dangerous.	[虚拟语气复合句:I would go if it were fine.]
[26695]	If I were a teacher, I would allow my students to ____ by themselves.	[make a decision]
[26695]	If I were a teacher, I would allow my students to ____ by themselves.	[情境语义]
[26675]	If I am wanted in the telephone, ask him to leave a ____.	[leave a message]
[26675]	If I am wanted in the telephone, ask him to leave a ____.	[情境语义]
[26655]	If by any chance Peter comes to us, please ask him to leave a ____.	[leave a message]
[26655]	If by any chance Peter comes to us, please ask him to leave a ____.	[情境语义]
[26651]	If Betty has time, she ____ climbing with her parents tomorrow.	[时间状语从句用一般现在时表示将来]
[26646]	If anyone ever asks her how old she is, she always answers, My dear, it must be terrible ____!	[grown-up]
[26646]	If anyone ever asks her how old she is, she always answers, My dear, it must be terrible ____!	[be+形容词+不定式]
[26641]	If anybody calls, tell them I'm out and ask them to ____ their names and addresses.	[情境语义]
[26631]	If all business goes paperless, at least one million tons of paper will be ____ a year.	[save money]
[26626]	If a=3 and b=4, what's the answer to the problem, a+b+1=? The answer is ____.	[情境语义]
[26621]	I'd like you ____ for a picnic with us.	[would like…to do]
[26617]	I'd like to tell you the table manners ____ you should know when you visit Korea.	[which,引导的定语从句]
[26593]	I'd like something to read. Would you please pass me the ____?	[情境语义]
[26588]	I'd like some water, and he wants ____.	[a bottle of juice]
[26583]	I'd like a ____ for dessert. Fruit, you know, is good for health.	[情境语义]
[26568]	I work very hard because I don't want to ____.	[let sb down]
[26563]	I work hard this term, but Peter works much ____.	[much+形容词副词比较级]
[26558]	I won't watch basketball matches ____ James is playing.<\\n>He pays much attention to teamwork.	[unless,引导条件状语从句]
[26553]	I won't take part in Julie's birthday party ____ I am invited.	[unless,引导条件状语从句]
[26543]	I won't go to the concert this evening. I ____ watch the NBA on TV. It's more exciting.	[would rather,不定式]
[26538]	I won't forget my teacher because she ____ so kind to me since I came to this school.	[since+一般过去时,主句用现在完成时]
[26529]	I wonder ____.	[if,宾语从句连接词]
[26524]	I wonder ____ on April 23, World Book Day. Did you find some interesting books to read?	[what,宾语从句连接词]
[26519]	I will wait ____ I hear from you.	[not…until]
[26495]	I will stay at home if it ____ tomorrow.	[条件状语从句,时态]
[26490]	I will send you an e-mail as soon as I ____ in Canada.	[as soon as,引导时间状语从句]
[26490]	I will send you an e-mail as soon as I ____ in Canada.	[时间状语从句用一般现在时表示将来]
[26476]	I will never forget the days ____ we spent together.	[that,引导的定语从句]
[26472]	I will meet my best friend ____ the morning of May 1st.	[表示时间:at,in,on]
[26427]	I will call you as soon as I ____ the ticket to the football match.	[时间状语从句用一般现在时表示将来]
[26422]	I will be ____ university student in three years.	[university,是非元音开头的词]
[26407]	I was very angry with John -- he just ____ when I spoke to him.	[主句和从句,一般时和进行时]
[26397]	I was told to meet Mr. Green at the airport. But I don't know ____ he will arrive.	[when,宾语从句连接词]
[26392]	I was so tired this morning that I couldn't ____ early as usual.	[get up]
[26368]	I was late because the bus ____ on my way to school.	[break down]
[26363]	I was feeling tired last night, so I went to bed ____ than usual.	[than,引导比较状语从句]
[26358]	I was born at eleven ____ the night of October 10, 1987.	[表示时间:at,in,on]
[26348]	I wanted to know ____ last weekend.	[what,宾语从句连接词]
[26348]	I wanted to know ____ last weekend.	[主句过去时]
[26338]	I wanted to explain, but he didn't give me any ____.	[give sb a chance]
[26333]	I want to write to Sam, but I don't know ____.	[what,宾语从句连接词]
[26328]	I want to write to John, but I don't know ____.	[what,宾语从句连接词]
[26323]	I want to know ____.	[when,宾语从句连接词]
[26318]	I want to know ____ yesterday.	[when,宾语从句连接词]
[26308]	I want to know ____ he will be the volunteer in the 2011 Universiade (世界大学生运动会) in Shenzhen.	[if,宾语从句连接词]
[26293]	I want to go to Pairs where I can learn ____ French language.	[the]
[26288]	I want my leg! I want to run! I want to jump!, a ____ girl cried in the hospital in Libya (利比亚).	[复合形容词]
[26278]	I usually sleep with the window open ____ it's very cold.	[unless,引导条件状语从句]
[26248]	I usually do some cleaning ____ Sunday morning.	[表示时间:at,in,on]
[26243]	I used to spent all my pocket money on clothes and snacks. But now, I try to ____ some money for charities.	[save money]
[26238]	I used to quarrel a lot with my parents, but now we ____ just fine together.	[get along with]
[26234]	I used to ____ the bus, but now I am used to walking.	[used to,情态动词]
[26229]	I tried to call you ____ I heard from him, but you were not in.	[as soon as,引导时间状语从句]
[26225]	I tried several skirts on, but ____ of them looked nice.	[none of+复数名词]
[26221]	I tried several skirts on, but ____ of them looked good.	[none of+复数名词]
[26201]	I told you not to be late again, John, ____ I?	[反意疑问句]
[26191]	I told her not to worry. I can look after ____.	[myself,反身代词]
[26186]	I thought the actor was famous, ____ none of my friends has ever heard of him.	[but,连词]
[26182]	I thought she was famous, but none of my friends have ever ____ her.	[hear of]
[26137]	I think The Lord of the Rings is an excellent film, ____ it is very long.	[although,引导让步状语从句]
[26132]	I think the blue shirt looks ____ better on you than the red one.	[much+形容词副词比较级]
[26127]	I think the best ____ to visit Hannan Island is in November because the weather is excellent then.	[情境语义]
[26123]	I think teenagers should ____ drive. They are not serious enough.	[should,被动语态]
[26114]	I think physics is very difficult to learn. Do you ____ me?	[agree with]
[26104]	I think people here are friendly. Do you ____ me?	[agree with]
[26089]	I think maths is ____ difficult than English.	[than,引导比较状语从句]
[26084]	I think it's really ____ hard work for me to finish the job in twenty minutes.	[work,不可数名词instances]
[26080]	I think it's not polite to laugh ____ others.	[laugh at]
[26075]	I think he's been drinking, ____ I'm not completely sure.	[though,引导让步状语从句]
[26065]	I think computers are very useful. They can help us get much ____ on the Internet.	[information,不可数名词instances]
[26065]	I think computers are very useful. They can help us get much ____ on the Internet.	[much+不可数名词]
[26061]	I think Chinese is ____ than any other subject.	[than,引导比较状语从句]
[26056]	I think Bob is the suitable person to take the job because he can do the work well with ____ money and ____ people.	[few->fewer,比较级]
[26056]	I think Bob is the suitable person to take the job because he can do the work well with ____ money and ____ people.	[little->less,比较级]
[26051]	I think Alice is the right person for the job, because she's always thinking ____ of it than of herself.	[than,引导比较状语从句]
[26037]	I think ____ should not be allowed to drive.	[复合形容词]
[26032]	I think ____ of the materials I listened to at the beginning of the exam ____ easy.	[分数作主语,主谓一致]
[26027]	I think ____ not difficult ____ English every morning.	[think it+形容词+to do]
[26002]	I still remember the park ____ we first met.	[where,引导的定语从句]
[25992]	I still remember my first teacher ____ we haven't seen each other for many years.	[though,引导让步状语从句]
[25987]	I still remember my first teacher ____ we haven't seen each other for a long time.	[though,引导让步状语从句]
[25982]	I still have ____ orange juice in the fridge.	[some+不可数名词]
[25977]	I still don't know what ____ while I was away from home.	[主语+happen]
[25977]	I still don't know what ____ while I was away from home.	[一般过去时]
[25968]	I spent a lot of time ____ English last weekend.	[spend (in) doing]
[25968]	I spent a lot of time ____ English last weekend.	[practise doing]
[25964]	I sit in front of the classroom ____ I can hear clearly.	[so that,引导目的状语从句]
[25960]	I saw some ____and ____ dancing in the street the day before yesterday.	[German,规则可数名词instances]
[25960]	I saw some ____and ____ dancing in the street the day before yesterday.	[man,名词复数]
[25955]	I saw many ____ eating grass on the hill.	[sheep,名词复数]
[25950]	I saw Li Ming ____ near the river on my way home.	[see…doing]
[25945]	I received ____ e-mail from my pen pal yesterday.	[字母,读音以元音开头]
[25935]	I really want to know ____.	[what,宾语从句连接词]
[25930]	I really want to know ____ Sun Yao is.	[how,宾语从句连接词]
[25925]	I really like ____ book you lent me yesterday.	[the]
[25915]	I really enjoyed your lecture, ____ there were some parts I didn't quite understand.	[though,引导让步状语从句]
[25911]	I really enjoyed ____ at the party last night.	[enjoy oneself]
[25897]	I prefer sports shows ____ soap operas. What about you? Me, too.	[prefer…to…]
[25873]	I paid ￥25 ____ the beef, and I only got a little.	[pay for]
[25858]	I often laugh when I see my grandma learning pop songs. But she says, One is never ____ old to learn.	[too…to do]
[25854]	I often go to school ____.	[by+交通通讯方法]
[25849]	I often ____ my homework after supper. But yesterday evening, I ____ TV.	[一般过去时的时间状语]
[25849]	I often ____ my homework after supper. But yesterday evening, I ____ TV.	[often,用于一般现在时]
[25845]	I need a ____. I want to write something．	[情境语义]
[25835]	I must return the dictionary to Allen now. I ____ it for three weeks already.	[延续性动词,用于现在完成时]
[25821]	I met Mrs. Read while I ____ in the park, but I didn't say hello to her.	[主句和从句,一般时和进行时]
[25816]	I met Mr. Green ____ I was walking across the bridge, but I didn't say hello to him.	[while,引导时间状语从句]
[25816]	I met Mr. Green ____ I was walking across the bridge, but I didn't say hello to him.	[主句和从句,一般时和进行时]
[25811]	I met Lucy in the primary school and we have been close friends ____.	[ever since,用于现在完成时]
[25801]	I love Urumqi because it is becoming ____.	[比较级 + and + 比较级]
[25796]	I love this song by Lady Gaga. Would you ____ the TV a bit, please? I can't hear it clearly.	[turn up]
[25787]	I love people ____ are polite and hard-working.	[who,引导的定语从句]
[25782]	I love people ____ are friendly to others.	[who,引导的定语从句]
[25763]	I like watching CCTV 10 ____ I can learn a lot of it.	[because,引导原因状语从句]
[25759]	I like watching CCTV 10 ____ I can learn a lot from it.	[because,引导原因状语从句]
[25749]	I like this photos and they can ____ me ____ the life of living in the countryside.	[remind sb of]
[25739]	I like the teacher ____ classes are very interesting and creative.	[whose,引导的定语从句]
[25725]	I like the MP3, ____ it's too expensive.	[but,连词]
[25720]	I like the cartoon ____ has a happy ending and makes me ____.	[which,引导的定语从句]
[25720]	I like the cartoon ____ has a happy ending and makes me ____.	[make,不定式]
[25716]	I like the car very much, but I can't afford it because the price is too ____.	[high,形容词instances]
[25707]	I like teachers who are [amusing] and can laugh with their students.	[amusing,-ing形式的形容词]
[25702]	I like swimming very much, but now I ____ swim as ____ as I used to.	[not so/as...as,引导比较状语从句]
[25697]	I like soft and gentle music. It ____ nice.	[nice,形容词instances]
[25697]	I like soft and gentle music. It ____ nice.	[sound+like+名词]
[25692]	I like seeing kids happy and, if they ____, it makes my job a lot easier.	[条件状语从句,时态]
[25692]	I like seeing kids happy and, if they ____, it makes my job a lot easier.	[省略句]
[25688]	I like playing ____ football while my sister likes playing ____ piano.	[piano,是乐器]
[25688]	I like playing ____ football while my sister likes playing ____ piano.	[play+球类棋类]
[25683]	I like places ____ it's not cold in winter.	[where,引导的定语从句]
[25678]	I like music, but I don't like ____ music of this film.	[the]
[25673]	I like going to school ____ my bike.	[on,介词]
[25658]	I like beef for dinner. My mother usually cooks ____ for me in different ways.	[it,人称代词宾格]
[25648]	I like ____ a lot, and my mother usually cooks it in different ways.	[fish,不可数名词instances]
[25643]	I left my dictionary at home. Luckily, Frank lent ____ to me.	[his,名词性物主代词]
[25639]	I know you don't like listening to ____ music very much. But how about ____ music in the film we saw yesterday?	[the]
[25639]	I know you don't like listening to ____ music very much. But how about ____ music in the film we saw yesterday?	[listen to music,listen to the music]
[25634]	I know you are shorter than your brothers, but you run ____.	[形容词和副词比较级]
[25614]	I know a little about Thailand, as I ____ there three years ago.	[一般过去时的时间状语]
[25604]	I knocked on the door but ____ answered.	[nobody,复合不定代词]
[25589]	I knew nothing about the accident ____ my friend told me yesterday.	[not…until]
[25579]	I hope Tim can come to my birthday party. Then we ____ a much happier time.	[一般将来时]
[25574]	I hope people ____ to be 200 years old ____ the future.	[in the future,用于一般将来时]
[25569]	I hope everyone can care about ____ the environment and stop ____ things.	[care about doing]
[25569]	I hope everyone can care about ____ the environment and stop ____ things.	[stop to do,stop doing]
[25564]	I hope ____ a good job in a foreign company after I graduate ____ school.	[hope to do]
[25564]	I hope ____ a good job in a foreign company after I graduate ____ school.	[from,介词]
[25554]	I hear Tom lives here, but I'm not sure ____.	[which,宾语从句连接词]
[25549]	I hear the tall girl wearing glasses is your new classmate. She's from America, ____?	[反意疑问句]
[25544]	I hear the 2006 World Cup is held in Germany ____ June 9th ____ July 9th.	[from…to…]
[25539]	I hear that Sang Lan can ____ walk ____ run till now ____ an accident, but she is doing her best to do everything she can.	[neither…nor,是并列结构连词]
[25539]	I hear that Sang Lan can ____ walk ____ run till now ____ an accident, but she is doing her best to do everything she can.	[because of]
[25529]	I hear one of the pandas ____ a baby.	[一般现在时,动词第三人称单数形式]
[25524]	I haven't checked my e-mails today, because there's ____ wrong with my computer.	[there is something wrong with]
[25494]	I have two children, and ____ of them are working in the west of China.	[both,不定代词]
[25474]	I have to well prepare for the math test tomorrow because it ____ 30% of the final exam.	[make up]
[25464]	I have to be off now. My friends ____ outside.	[现在进行时]
[25459]	I have some problems with my English writing. Can you give me some ____?	[give advice]
[25444]	I have lived in New York and London but I don't like ____ city. I like Sydney.	[either,形容词instances]
[25435]	I have great ____ in learning math and I am so worried.	[have trouble doing]
[25411]	I have been collecting stamps ____ I was nine years old.	[since+一般过去时,主句用现在完成时]
[25406]	I have a few good friends. One is in Beijing, but ____ are all in Shanghai.	[one … the others ...]
[25402]	I have ____ uncle. He is good at mending TV sets.	[an+元音开头的词]
[25392]	I have ____ notebook and two pens in my bag. ____ notebook is for you.	[a]
[25392]	I have ____ notebook and two pens in my bag. ____ notebook is for you.	[the]
[25383]	I hate travelling by air ____ you usually have to wait for hours before the plane takes off.	[because,引导原因状语从句]
[25378]	I hate those ____ don't help others when they are in trouble.	[who,引导的定语从句]
[25373]	I hate people ____ talk much but do little.	[who,引导的定语从句]
[25368]	I hardly knew anything about it ____ you told me.	[not…until]
[25363]	I had to call a taxi because the box was ____ than I'd expected.	[形容词和副词比较级]
[25344]	I guess Peter and his sister Sally enjoyed ____ at the dancing party.	[enjoy oneself]
[25304]	I got an e-mail this morning. It was ____ my foreign friend, Tony.	[from,介词]
[25299]	I got a good present on my ____ birthday.	[形容词性物主动词+序数词]
[25294]	I got a beautiful bike on ____ birthday. I like it very much.	[形容词性物主动词+序数词]
[25289]	I go to school ____ bus every morning.	[by bus]
[25284]	I go to school ____ 8 o'clock in the morning.	[at,介词]
[25274]	I found a story-book on the desk, it isn't mine, it is ____, I think.	[yours,名词性物主代词]
[25269]	I found a letter ____ on the floor when I came into the classroom.	[lie->lying,现在分词]
[25269]	I found a letter ____ on the floor when I came into the classroom.	[find … doing]
[25259]	I forget to bring a pen. Would you lend me ____?	[one,it]
[25254]	I first met Lisa three years ago when we ____ at a radio station together.	[主句和从句,一般时和进行时]
[25245]	I find ____ hard for me ____ the work in such a short time.	[find it+形容词+to do]
[25235]	I felt it hard to keep up with my classmates. But whenever I want to ____, my teacher always encourages me to work harder.	[give up]
[25225]	I feel my stomach terrible. I think I ate ____ at lunch time.	[something+形容词]
[25205]	I feared that the film would be boring ____ it turned out to be very exciting.	[but,连词]
[25200]	I enjoyed the trip to Dalian Forest Zoo so much. I didn't ____ want to go home.	[really,副词instances]
[25195]	I enjoy the popular dance hip-hop, but ____ my father ____ my mother likes it.	[neither…nor,主谓一致]
[25190]	I enjoy playing computer games, but I can't ____ too much time ____ that.	[spend (in) doing]
[25145]	I don't understand the story though there are ____ new words in it.	[little+不可数名词]
[25145]	I don't understand the story though there are ____ new words in it.	[辨析:few,a few]
[25140]	I don't understand ____ that everything's fine when it's not.	[how,宾语从句连接词]
[25130]	I don't think Mary is ____ athletic as her sister.	[not so/as...as,引导比较状语从句]
[25125]	I don't think looking after children is just ____ work.	[名词复数的所有格]
[25120]	I don't think I am different from ____ else. I am just the son of a farmer, Mo Yan said.	[anyone,复合不定代词]
[25111]	I don't think fast food is good for our health, so I ____ eat it.	[hardly,频率副词]
[25106]	I don't remember when and where I ____ this umbrella.	[where,宾语从句连接词]
[25106]	I don't remember when and where I ____ this umbrella.	[when,宾语从句连接词]
[25101]	I don't remember ____ the book yesterday.	[where,宾语从句连接词]
[25092]	I don't quite [catch] what you said at the meeting. Here catch means ____.	[情境语义]
[25087]	I don't like Xiao Shenyang's performances ____ many people like them.	[even though,引导让步状语从句]
[25063]	I don't like eating chocolate. The taste is too ____.	[情境语义]
[25058]	I don't know when my father ____ back, but I'll tell you when he ____ back.	[条件状语从句,时态]
[25058]	I don't know when my father ____ back, but I'll tell you when he ____ back.	[一般将来时]
[25048]	I don't know the man over there. Could you tell me ____?	[what,宾语从句连接词]
[25048]	I don't know the man over there. Could you tell me ____?	[could you…,引导的主句]
[25038]	I don't know the city. Where can I find ____ good restaurant?	[a]
[25033]	I don't know if Jack ____ If he ____, call me, please.	[条件状语从句,时态]
[25033]	I don't know if Jack ____ If he ____, call me, please.	[一般将来时]
[25024]	I don't know if it ____ tomorrow. If it ___, we won't go on a picnic.	[条件状语从句,时态]
[25024]	I don't know if it ____ tomorrow. If it ___, we won't go on a picnic.	[一般将来时]
[25020]	I don't know if he ____ tomorrow. If he ____, we'll climb the mountain.	[条件状语从句,时态]
[25020]	I don't know if he ____ tomorrow. If he ____, we'll climb the mountain.	[一般将来时]
[25011]	I don't know ____.	[宾语从句语序]
[25007]	I don't know ____ on the Internet, though most of people do.	[how,宾语从句连接词]
[24997]	I don't know ____ next, could you give me some ____?	[advice,不可数名词instances]
[24997]	I don't know ____ next, could you give me some ____?	[what to do]
[24992]	I don't know ____ he will come tomorrow. ____ he comes, I will tell you.	[if,引导条件状语从句]
[24992]	I don't know ____ he will come tomorrow. ____ he comes, I will tell you.	[if,宾语从句连接词]
[24987]	I don't know ____ Apple iPhones.	[why,宾语从句连接词]
[24982]	I don't have to introduce him to you ____ you know the boy.	[since,引导原因状语从句]
[24977]	I don't have enough money, so I have to go to the ____ to get some.	[情境语义]
[24967]	I don't have a present for my friend. What if ____ else brings a present?	[else,形容词instances]
[24967]	I don't have a present for my friend. What if ____ else brings a present?	[everyone,复合不定代词]
[24963]	I don't believe that this ____ boy can paint such a nice picture.	[复合形容词]
[24958]	I do want to make ____ with you.	[make friends with]
[24953]	I didn't understand ____, so I raised my hand to ask.	[what,宾语从句连接词]
[24953]	I didn't understand ____, so I raised my hand to ask.	[主句过去时]
[24943]	I didn't sleep ____ last night. I feel tired now.	[well,副词instances]
[24933]	I didn't see Laura at the party last night. Do you know ____?	[what,宾语从句连接词]
[24928]	I didn't know he came back ____ I met him in the street.	[not…until]
[24913]	I didn't hear you because I ____ the news on the radio.	[过去进行时]
[24903]	I didn't go to bed until I finished ____ my homework.	[finish doing]
[24899]	I didn't go to bed ____ my mother came back late last night．	[not…until]
[24879]	I didn't believe he could drive ____ he told me.	[not…until]
[24844]	I can't say ____ I want to go back to my hometown. It's quite a few years since I last went back.	[how much,宾语从句连接词]
[24840]	I can't remember ____ they will plant trees on Sunday or not.	[whether,宾语从句连接词]
[24835]	I can't remember ____ I put the book and I need it for my homework now.	[where,宾语从句连接词]
[24825]	I can't go with you today. There will be a test tomorrow?<\\n>— ____. Maybe next time.	[I'm sorry …,应答句]
[24805]	I can't find my watch, but it must be ____ in this room.	[somewhere,anywhere,nowhere,everywhere:辨析]
[24800]	I can't find my pen. Could you help ____ find it?	[me,人称代词宾格]
[24800]	I can't find my pen. Could you help ____ find it?	[help…to do]
[24790]	I can't connect my computer to the Internet. There must be ____ wrong with it.	[must,should,ought to]
[24790]	I can't connect my computer to the Internet. There must be ____ wrong with it.	[there is something wrong with]
[24770]	I can still remember meeting her at a party ____ it was a long time ago.	[though,引导让步状语从句]
[24765]	I can speak French, ____ not much.	[but,连词]
[24760]	I can play the guitar, but I ____ play the violin.	[can,be able to:辨析]
[24755]	I can never forget the stories ____ my grandma told me.	[that,引导的定语从句]
[24740]	I can ____ be a nurse, I'm not a very patient person.	[never,频率副词]
[24730]	I called you, but nobody answered. Where ____ you?	[be,是系动词]
[24720]	I bought some CDs for my friend and they ____ me 30 yuan.	[cost,pay,spend,take]
[24715]	I bought my son a birthday present, ____ he liked it very much.	[and,连词]
[24711]	I bought a new shirt for John, ____ he didn't like it.	[but,连词]
[24706]	I believe that those mountains ____ with trees in a few years' time.	[be covered with]
[24702]	I Believe I Can Fly is a nice song by R. Kelly. This song tells us that believing in ____ is very important.	[ourselves,反身代词]
[24702]	I Believe I Can Fly is a nice song by R. Kelly. This song tells us that believing in ____ is very important.	[believe in]
[24697]	I began watching here an hour ago, but now nothing ____ yet.	[现在完成时]
[24687]	I asked two people the way to the station, but ____ of them could help me.	[neither,不定代词]
[24678]	I asked if I could buy another toy car, but Mom [put her foot down].	[情境语义]
[24673]	I arrived at the airport ____ the plane had taken off.	[过去完成时]
[24673]	I arrived at the airport ____ the plane had taken off.	[after,引导时间状语从句]
[24668]	I argued with my best friend yesterday. She [is angry with me] now. The underlined part means____.	[be angry with]
[24668]	I argued with my best friend yesterday. She [is angry with me] now. The underlined part means____.	[mad at]
[24663]	I am waiting for my friend. ____, I will go swimming alone.	[时间状语从句用一般现在时表示将来]
[24658]	I am very thirsty. Could you please give me ____ water?	[some+不可数名词]
[24653]	I am thirsty. I want to buy ____.	[a bottle of juice]
[24648]	I am thirsty. Could you let me have ____ coke?	[some+不可数名词]
[24644]	I am thinking about ____ to spend my summer holidays.	[where to do]
[24639]	I am sure Cindy will be able to find the hotel, she has a pretty good ____ of direction.	[sense of direction]
[24634]	I am greatly interested in this painting. Something in it ____ the painter's deep love for nature.	[情境语义]
[24605]	I am a fan of Liu Qian. ____ his magic ____ his humor attracts me.	[not only…but also]
[24585]	I ____ to the cinema. Would you like to come with me?	[现在进行时]
[24575]	I ____ you already that washing hands often will help prevent the A-H1N1 Flu.	[现在完成时]
[24570]	I ____ watch this TV programme. It's very interesting.	[often,频率副词]
[24566]	I ____ TV when my parents came back.	[主句和从句,一般时和进行时]
[24551]	I ____ to the bookshop as soon as school is over this afternoon.	[一般将来时]
[24551]	I ____ to the bookshop as soon as school is over this afternoon.	[时间状语从句用一般现在时表示将来]
[24546]	I ____ to take part in the English speech contest last week.	[一般过去时的被动语态]
[24541]	I ____ to leave at once, or I'll be late for the meeting.	[一般现在时的被动语态]
[24531]	I ____ to Canada twice. It's so beautiful.	[have been to,have gone to,have been in]
[24526]	I ____ this book for two weeks. I have to return it now.	[延续性动词,用于现在完成时]
[24521]	I ____ the wrong thing. Can I use your eraser?	[一般过去时]
[24496]	I ____ tennis with my cousin every day when I was in America.	[一般过去时]
[24481]	I ____ some beautiful pictures by the old man.	[一般过去时的被动语态]
[24476]	I ____ ride a bike to school. But this morning I took a taxi because I got up late.	[usually,频率副词]
[24472]	I ____ my teacher since last year. I miss him very much.	[since+过去时间点,用于现在完成时]
[24467]	I ____ my homework, I guess I can't join you.	[现在完成时]
[24462]	I ____ my homework as soon as I get home.	[时间状语从句用一般现在时表示将来]
[24457]	I ____ my hometown for a long time. I really miss it!	[延续性动词,用于现在完成时]
[24452]	I ____ my clothes, and the phone rang.	[主句和从句,一般时和进行时]
[24437]	I ____ Mr. Smith since he moved to Shanghai.	[since+一般过去时,主句用现在完成时]
[24437]	I ____ Mr. Smith since he moved to Shanghai.	[hear from]
[24422]	I ____ like some noodles.	[would like]
[24417]	I ____ keep dogs for protection, but now I keep them as pets.	[used to,情态动词]
[24397]	I ____ him in a way. Some of his ideas are right.	[agree with]
[24383]	I ____ e-mails to my pen pal when Susan called me last night.	[主句和从句,一般时和进行时]
[24368]	I ____ along the road when I saw Peter. So we stopped and had a chat.	[主句和从句,一般时和进行时]
[24358]	I ____ a mistake. Please don't be angry with me.	[一般过去时]
[24348]	I ____ a copy of Yi Zhongtian's book yet. I might buy one tomorrow.	[非延续性动词,用于现在完成时]
[24344]	I [went to see] my grandparents last Sunday.	[情境语义]
[24339]	I [have no idea] what life would be like without water. The underlined part means ____.	[have no idea]
[24329]	Hurry up, or you ____ catch the train.	[can't,mustn't]
'''
}
