package ots

class SampleData_KnowledgePoint_Parent_Relations2 {

	String content = '''[me]	[单词]
[message]	[单词]
[milk,不可数名词instances]	[不可数名词instances]
[milk,不可数名词instances]	[milk]
[milk]	[单词]
[million,基数词]	[基数词]
[million,基数词]	[million]
[million]	[单词]
[millions of…]	[million,基数词]
[millions of…]	[of]
[millions of…]	[基数词用法]
[mind doing]	[v-ing习语]
[mind doing]	[mind]
[mind]	[单词]
[mine,名词性物主代词]	[名词性物主代词]
[mine,名词性物主代词]	[mine]
[mine]	[单词]
[moment]	[单词]
[money]	[单词]
[more and more]	[more]
[more and more]	[比较级 + and + 比较级]
[more]	[单词]
[much,副词instances]	[much]
[much,副词instances]	[副词instances]
[much]	[单词]
[much+不可数名词]	[much]
[much+不可数名词]	[不可数名词修饰语]
[much+形容词副词比较级]	[much,副词instances]
[much+形容词副词比较级]	[形容词和副词比较级修饰语]
[much->more,比较级]	[much]
[much->more,比较级]	[形容词副词比较级构成]
[much->more,比较级]	[more]
[music,不可数名词instances]	[不可数名词instances]
[music,不可数名词instances]	[music]
[music]	[单词]
[must,have to:辨析]	[have to,情态动词]
[must,have to:辨析]	[must,情态动词]
[must,should,ought to]	[should,情态动词]
[must,should,ought to]	[ought to,情态动词]
[must,should,ought to]	[must,情态动词]
[must,被动语态]	[must,情态动词]
[must,被动语态]	[情态动词的被动语态]
[must,情态动词]	[情态动词]
[must,情态动词]	[must]
[must,疑问句]	[一般疑问句]
[must,疑问句]	[must,情态动词]
[must]	[单词]
[mustn't]	[must,情态动词]
[must疑问句,应答句]	[must,疑问句]
[must疑问句,应答句]	[表示请求,应答句]
[must疑问句,应答句]	[need,情态动词]
[my,形容词性物主代词]	[形容词性物主代词]
[my,形容词性物主代词]	[my]
[my]	[单词]
[myself,反身代词]	[反身代词]
[myself,反身代词]	[myself]
[myself]	[单词]
[near,介词]	[介词]
[near,介词]	[near]
[near]	[单词]
[need to do]	[不定式习语]
[need to do]	[need,实义动词]
[need,情态动词]	[情态动词]
[need,情态动词]	[need]
[need,实义动词]	[need]
[need,实义动词]	[实义动词]
[need]	[单词]
[neither,不定代词]	[不定代词]
[neither,不定代词]	[neither]
[neither,形容词instances]	[形容词instances]
[neither,形容词instances]	[neither]
[neither,引导的倒装句]	[neither,不定代词]
[neither,引导的倒装句]	[倒装句]
[neither]	[单词]
[neither…nor,是并列结构连词]	[并列结构的连词]
[neither…nor,是并列结构连词]	[neither…nor]
[neither…nor,主谓一致]	[neither…nor]
[neither…nor,主谓一致]	[主谓一致]
[neither…nor]	[neither]
[neither…nor]	[nor]
[never,反意疑问句]	[never,否定含义]
[never,反意疑问句]	[否定含义的词+反意疑问句]
[never,否定含义]	[否定含义的词]
[never,否定含义]	[never,频率副词]
[never,频率副词]	[频率副词]
[never,频率副词]	[never]
[never]	[单词]
[news,不可数名词instances]	[不可数名词instances]
[news,不可数名词instances]	[news]
[news]	[单词]
[nice,形容词instances]	[形容词instances]
[nice,形容词instances]	[nice]
[nice]	[单词]
[no matter+wh-/how,引导让步状语从句]	[让步状语从句,连词]
[no matter+wh-/how,引导让步状语从句]	[no matter+wh-/how]
[no matter+wh-/how]	[no]
[no matter+wh-/how]	[matter]
[no one]	[one,不定代词]
[no one]	[no]
[no]	[单词]
[nobody,复合不定代词]	[nobody]
[nobody,复合不定代词]	[复合不定代词]
[nobody]	[单词]
[noise]	[单词]
[none of+复数名词,主谓一致]	[none of+复数名词]
[none of+复数名词,主谓一致]	[主谓一致]
[none of+复数名词]	[of,介词]
[none of+复数名词]	[none,不定代词]
[none,不定代词]	[不定代词]
[none,不定代词]	[none]
[none]	[单词]
[nor]	[单词]
[not only]	[only]
[not only]	[not]
[not only…but also,是并列结构连词]	[并列结构的连词]
[not only…but also,是并列结构连词]	[not only…but also]
[not only…but also,主谓一致]	[not only…but also]
[not only…but also,主谓一致]	[主谓一致]
[not only…but also]	[but also]
[not only…but also]	[not only]
[not so/as...as,引导比较状语从句]	[not so/as...as]
[not so/as...as,引导比较状语从句]	[比较状语从句,连词]
[not so/as...as]	[so]
[not so/as...as]	[as]
[not so/as...as]	[not]
[not so/as...as]	[形容词和副词的原级]
[not]	[单词]
[not…until]	[until]
[nothing much]	[much]
[nothing much]	[nothing,复合不定代词]
[nothing,none]	[none,不定代词]
[nothing,none]	[nothing,复合不定代词]
[nothing,反意疑问句]	[nothing,否定含义]
[nothing,反意疑问句]	[否定含义的词+反意疑问句]
[nothing,否定含义]	[nothing]
[nothing,否定含义]	[否定含义的词]
[nothing,复合不定代词]	[nothing]
[nothing,复合不定代词]	[复合不定代词]
[nothing]	[单词]
[nothing+形容词]	[nothing,复合不定代词]
[now]	[单词]
[nowhere]	[单词]
[number,表示数量单位的名词]	[表示数量单位的名词]
[number,表示数量单位的名词]	[number]
[number]	[单词]
[of,介词]	[of]
[of,介词]	[介词]
[of]	[单词]
[of+形容词性物主代词+own]	[of,介词]
[of+形容词性物主代词+own]	[形容词性物主代词]
[of+形容词性物主代词+own]	[own]
[off]	[单词]
[offer]	[单词]
[often,频率副词]	[频率副词]
[often,频率副词]	[often]
[often,用于一般现在时]	[often,频率副词]
[often,用于一般现在时]	[一般现在时的时间状语]
[often]	[单词]
[of引导不定式逻辑主语]	[of,介词]
[of引导不定式逻辑主语]	[it形式主语]
[of引导不定式逻辑主语]	[不定式的逻辑主语]
[old]	[单词]
[on duty]	[on,介词]
[on duty]	[duty]
[on foot]	[foot]
[on foot]	[零冠词惯用法]
[on foot]	[on]
[on the left]	[left]
[on the left]	[the惯用法]
[on the left]	[on,介词]
[on the right]	[on,介词]
[on the right]	[right]
[on,介词]	[介词]
[on,介词]	[on]
[on]	[单词]
[one … the other ...]	[the other]
[one … the other ...]	[one]
[one … the others ...]	[one]
[one of + the + 形容词和副词最高级]	[of,介词]
[one of + the + 形容词和副词最高级]	[one,不定代词]
[one of + the + 形容词和副词最高级]	[形容词和副词最高级]
[one of + 名词复数]	[of,介词]
[one of + 名词复数]	[one,不定代词]
[one,it]	[it]
[one,it]	[one]
[one,不定代词]	[不定代词]
[one,不定代词]	[one]
[one,后接that定语从句]	[that,引导的定语从句]
[one,后接that定语从句]	[one,不定代词]
[one,后接that定语从句]	[后接that定语从句的先行词]
[one]	[单词]
[oneself]	[反身代词]
[only]	[单词]
[opinion]	[单词]
[opposite,形容词instances]	[形容词instances]
[or,连词]	[or]
[or,连词]	[连词]
[or,选择疑问句]	[or]
[or,选择疑问句]	[选择疑问句]
[or]	[单词]
[order]	[单词]
[or选择疑问句,应答句]	[应答句]
[or选择疑问句,应答句]	[or,选择疑问句]
[other]	[单词]
[others]	[other]
[others]	[单词]
[ought to,情态动词]	[情态动词]
[ought to,情态动词]	[ought to]
[ought to]	[ought]
[ought to]	[to]
[ought]	[单词]
[our,形容词性物主代词]	[形容词性物主代词]
[our,形容词性物主代词]	[our]
[our]	[单词]
[ours,名词性物主代词]	[名词性物主代词]
[ours,名词性物主代词]	[ours]
[ours]	[单词]
[ourselves,反身代词]	[反身代词]
[ourselves,反身代词]	[ourselves]
[ourselves]	[单词]
[out of danger]	[danger]
[out of danger]	[out of]
[out of]	[of,介词]
[out of]	[out]
[out]	[单词]
[over,介词]	[介词]
[over,介词]	[over]
[over]	[单词]
[own]	[单词]
[pair,表示数量单位的名词]	[表示数量单位的名词]
[pair,表示数量单位的名词]	[pair]
[pair]	[单词]
[paper,不可数名词instances]	[不可数名词instances]
[paper,不可数名词instances]	[paper]
[paper]	[单词]
[part]	[单词]
[pass one's exam]	[pass]
[pass one's exam]	[exam]
[pass]	[单词]
[past]	[单词]
[pay for]	[pay]
[pay for]	[for]
[pay]	[单词]
[physics,不可数名词instances]	[不可数名词instances]
[piano,是乐器]	[乐器]
[piano,是乐器]	[piano]
[piano,是乐器]	[the+乐器]
[piano]	[单词]
[pick up]	[pick]
[pick up]	[up]
[pick]	[单词]
[piece,表示数量单位的名词]	[表示数量单位的名词]
[piece,表示数量单位的名词]	[piece]
[piece]	[单词]
[place]	[单词]
[plan on doing]	[v-ing习语]
[plan on doing]	[plan on]
[plan on]	[plan]
[plan on]	[on,介词]
[plan]	[单词]
[play,动词instances]	[play]
[play,动词instances]	[动词instances]
[play]	[单词]
[play+球类棋类]	[play,动词instances]
[play+球类棋类]	[零冠词]
[pleased]	[单词]
[politely,副词instances]	[副词instances]
[politely,副词instances]	[politely]
[politely]	[单词]
[practise doing]	[v-ing习语]
[practise doing]	[practise]
[practise]	[单词]
[prefer to do sth rather than…]	[prefer]
[prefer to do sth rather than…]	[rather than]
[prefer]	[单词]
[prefer…to…]	[prefer]
[prefer…to…]	[to,介词]
[pride]	[单词]
[promise to do]	[promise]
[promise to do]	[不定式习语]
[promise]	[单词]
[proud]	[单词]
[prove oneself]	[oneself]
[prove oneself]	[prove]
[prove]	[单词]
[provide]	[单词]
[provide…with]	[with,介词]
[provide…with]	[provide]
[put away]	[away]
[put away]	[put]
[put down]	[down]
[put down]	[put]
[put off]	[off]
[put off]	[put]
[put on]	[on]
[put on]	[put]
[put up]	[up]
[put up]	[put]
[put]	[单词]
[rather than,不定式]	[不加to的动词不定式]
[rather than,不定式]	[rather than]
[rather than]	[rather]
[rather than]	[than]
[rather]	[单词]
[reach]	[单词]
[really,副词instances]	[副词instances]
[really,副词instances]	[really]
[really]	[单词]
[receive]	[单词]
[recent]	[单词]
[record]	[单词]
[regard,及物动词]	[及物动词]
[regard,及物动词]	[regard]
[regard]	[单词]
[relaxing,-ing形式的形容词]	[-ing形式的形容词]
[relaxing,-ing形式的形容词]	[relaxing]
[relaxing]	[单词]
[remember to do,remember doing]	[v-ing习语]
[remember to do,remember doing]	[remember]
[remember to do,remember doing]	[不定式习语]
[remember]	[单词]
[remind sb of]	[of,介词]
[remind sb of]	[remind]
[remind]	[单词]
[responsible]	[单词]
[right]	[单词]
[ring]	[单词]
[room,不可数名词instances]	[不可数名词instances]
[room,不可数名词instances]	[room]
[room]	[单词]
[run off]	[off]
[run off]	[run]
[run out of]	[run]
[run out of]	[out of]
[run out]	[out]
[run out]	[run]
[run]	[单词]
[same]	[单词]
[save money]	[money]
[save money]	[save]
[save time]	[time]
[save time]	[save]
[save]	[单词]
[say,speak,talk,tell]	[tell]
[say,speak,talk,tell]	[speak]
[say,speak,talk,tell]	[say]
[say,speak,talk,tell]	[talk]
[say]	[单词]
[second]	[单词]
[secret]	[单词]
[see]	[单词]
[see…doing]	[v-ing习语]
[see…doing]	[see]
[seem,是系动词]	[系动词]
[seem,是系动词]	[seem]
[seem]	[单词]
[seem+形容词]	[系动词+形容词]
[seem+形容词]	[seem,是系动词]
[seldom,频率副词]	[seldom]
[seldom,频率副词]	[频率副词]
[seldom]	[单词]
[sell well]	[sell]
[sell well]	[well,副词instances]
[sell]	[单词]
[send for]	[send]
[send for]	[for]
[send]	[单词]
[sense of direction]	[of,介词]
[sense of direction]	[direction]
[sense of direction]	[sense]
[sense]	[单词]
[set off]	[set]
[set off]	[off]
[set out]	[set]
[set out]	[out]
[set up]	[set]
[set up]	[up]
[set]	[单词]
[Shall we…,应答句]	[表达建议/意见/观点,应答句]
[Shall we…,应答句]	[shall]
[shall]	[单词]
[sheep,名词复数]	[sheep]
[sheep,名词复数]	[不规则可数名词.复数]
[sheep]	[单词]
[shoe,规则可数名词instances]	[规则可数名词instances]
[shoe,规则可数名词instances]	[shoe]
[shoe]	[单词]
[shortly after]	[after,连词]
[shortly after]	[shortly,副词instances]
[shortly]	[单词]
[should,被动语态]	[should,情态动词]
[should,被动语态]	[情态动词的被动语态]
[should,情态动词]	[情态动词]
[should,情态动词]	[should]
[should]	[单词]
[show off]	[off]
[show off]	[show]
[show sb around]	[show]
[show sb around]	[around]
[show]	[单词]
[show+直接宾语+宾语从句]	[show]
[show+直接宾语+宾语从句]	[动词+直接宾语+宾语从句]
[side by side]	[by]
[side by side]	[side]
[side]	[单词]
[since,介词]	[since]
[since,介词]	[介词]
[since,连词]	[since]
[since,连词]	[连词]
[since,引导时间状语从句]	[时间状语从句,连词]
[since,引导时间状语从句]	[since,连词]
[since,引导原因状语从句]	[原因状语从句,连词]
[since,引导原因状语从句]	[since,连词]
[since]	[单词]
[since+过去时间点,用于现在完成时]	[延续性动词,用于现在完成时]
[since+过去时间点,用于现在完成时]	[since+过去时间点]
[since+过去时间点,用于现在完成时]	[现在完成时的时间状语]
[since+过去时间点]	[since,介词]
[since+一般过去时,主句用现在完成时]	[延续性动词,用于现在完成时]
[since+一般过去时,主句用现在完成时]	[since,引导时间状语从句]
[since+一般过去时,主句用现在完成时]	[现在完成时的时间状语]
[since+一般过去时,主句用现在完成时]	[时间状语从句,时态]
[since+一段时间+ago,用于现在完成时]	[since+一段时间+ago]
[since+一段时间+ago,用于现在完成时]	[延续性动词,用于现在完成时]
[since+一段时间+ago,用于现在完成时]	[现在完成时的时间状语]
[since+一段时间+ago]	[ago]
[since+一段时间+ago]	[since,介词]
[sky,独一无二的事物]	[sky]
[sky,独一无二的事物]	[独一无二的事物]
[sky,独一无二的事物]	[the+独一无二的事物]
[sky]	[单词]
[smell,及物动词]	[及物动词]
[smell,及物动词]	[smell]
[smell,是系动词]	[系动词]
[smell,是系动词]	[smell]
[smell]	[单词]
[smell+形容词]	[系动词+形容词]
[smell+形容词]	[smell,是系动词]
[so that,引导结果状语从句]	[结果状语从句,连词]
[so that,引导结果状语从句]	[so that]
[so that,引导目的状语从句]	[目的状语从句,连词]
[so that,引导目的状语从句]	[so that]
[so that]	[so]
[so that]	[that]
[so,副词instances]	[so]
[so,副词instances]	[副词instances]
[so,连词]	[so]
[so,连词]	[连词]
[so,引导的倒装句]	[so]
[so,引导的倒装句]	[倒装句]
[so...that,引导结果状语从句]	[so…that]
[so...that,引导结果状语从句]	[结果状语从句,连词]
[so]	[单词]
[so+形容词副词]	[形容词和副词修饰语]
[so+形容词副词]	[so,副词instances]
[so+主语+助动词]	[so]
[so…that]	[so]
[so…that]	[that]
[some time]	[time]
[some time]	[some]
[some,any]	[some]
[some,any]	[any]
[some,不定代词]	[不定代词]
[some,不定代词]	[some]
[some]	[单词]
[some+不可数名词]	[不可数名词修饰语]
[some+不可数名词]	[some]
[somebody,复合不定代词]	[somebody]
[somebody,复合不定代词]	[复合不定代词]
[somebody]	[单词]
[something,复合不定代词]	[something]
[something,复合不定代词]	[复合不定代词]
[something,后接that定语从句]	[that,引导的定语从句]
[something,后接that定语从句]	[后接that定语从句的先行词]
[something,后接that定语从句]	[something,复合不定代词]
[something]	[单词]
[something+形容词]	[something,复合不定代词]
[sometime,sometimes]	[sometime,副词instances]
[sometime,sometimes]	[sometimes,频率副词]
[sometime,sometimes]	[副词惯用法]
[sometime,副词instances]	[副词instances]
[sometime,副词instances]	[sometime]
[sometime]	[单词]
[sometimes,频率副词]	[频率副词]
[sometimes,频率副词]	[sometimes]
[sometimes]	[单词]
[somewhere,anywhere,nowhere,everywhere:辨析]	[somewhere]
[somewhere,anywhere,nowhere,everywhere:辨析]	[everywhere]
[somewhere,anywhere,nowhere,everywhere:辨析]	[anywhere]
[somewhere,anywhere,nowhere,everywhere:辨析]	[nowhere]
[somewhere]	[单词]
[soon]	[单词]
[sorry]	[单词]
[sound,是系动词]	[系动词]
[sound,是系动词]	[sound]
[sound]	[单词]
[sound+like+名词]	[like,介词]
[sound+like+名词]	[sound]
[sound+形容词]	[sound,是系动词]
[sound+形容词]	[系动词+形容词]
[speak]	[单词]
[spend (in) doing]	[v-ing习语]
[spend (in) doing]	[in,介词]
[spend (in) doing]	[spend]
[spend on]	[on,介词]
[spend on]	[spend]
[spend]	[单词]
[stay away from]	[stay]
[stay away from]	[from,介词]
[stay away from]	[away]
[stay up]	[stay]
[stay up]	[up]
[stay]	[单词]
[still,并列结构的连词]	[并列结构的连词]
[still,并列结构的连词]	[still]
[still]	[单词]
[stop to do,stop doing]	[v-ing习语]
[stop to do,stop doing]	[stop]
[stop to do,stop doing]	[不定式习语]
[stop]	[单词]
[stop…from doing]	[v-ing习语]
[stop…from doing]	[from,介词]
[stop…from doing]	[stop]
[story]	[单词]
[strict]	[单词]
[succeed]	[单词]
[succeed<->success]	[succeed]
[succeed<->success]	[动词<->名词]
[succeed<->success]	[success]
[success]	[单词]
[such...that,引导结果状语从句]	[such…that]
[such...that,引导结果状语从句]	[结果状语从句,连词]
[such]	[单词]
[such+不可数名词]	[不可数名词修饰语]
[such+不可数名词]	[such]
[such+可数名词]	[such]
[such+可数名词]	[可数名词修饰语]
[such…that]	[that]
[such…that]	[such]
[sun,独一无二的事物]	[sun]
[sun,独一无二的事物]	[独一无二的事物]
[sun,独一无二的事物]	[the+独一无二的事物]
[sun]	[单词]
[supper]	[单词]
[suppose,及物动词]	[及物动词]
[suppose,及物动词]	[suppose]
[suppose]	[单词]
[surprise]	[单词]
[swim]	[单词]
[take a walk]	[walk]
[take a walk]	[take]
[take an interest in doing]	[v-ing习语]
[take an interest in doing]	[take an interest in]
[take an interest in]	[in,介词]
[take an interest in]	[interest]
[take an interest in]	[take]
[take away]	[take]
[take away]	[away]
[take care of]	[of,介词]
[take care of]	[care]
[take care of]	[take]
[take it easy]	[easy]
[take it easy]	[take]
[take off]	[off]
[take off]	[take]
[take out]	[out]
[take out]	[take]
[take part in]	[in,介词]
[take part in]	[take]
[take part in]	[part]
[take place]	[take]
[take place]	[place]
[take up]	[up]
[take up]	[take]
[take]	[单词]
[talk]	[单词]
[taste,是系动词]	[系动词]
[taste,是系动词]	[taste]
[taste]	[单词]
[taste+形容词]	[系动词+形容词]
[taste+形容词]	[taste,是系动词]
[tea,不可数名词instances]	[不可数名词instances]
[tea,不可数名词instances]	[tea]
[tea]	[单词]
[teach sb sth]	[teach]
[teach]	[单词]
[tell a story]	[story]
[tell a story]	[tell]
[tell]	[单词]
[tell…to do]	[不定式习语]
[tell…to do]	[tell]
[than any other]	[than,引导比较状语从句]
[than any other]	[any other]
[than any…]	[any+可数名词]
[than any…]	[than,引导比较状语从句]
[than those…]	[than,引导比较状语从句]
[than those…]	[those,指示代词]
[than,连词]	[than]
[than,连词]	[连词]
[than,引导比较状语从句]	[than,连词]
[than,引导比较状语从句]	[形容词和副词比较级]
[than,引导比较状语从句]	[比较状语从句,连词]
[than]	[单词]
[Thank you…,应答句]	[表达感谢,应答句]
[Thank you…,应答句]	[thank]
[thank]	[单词]
[thanks to]	[thanks]
[thanks to]	[to]
[thanks]	[单词]
[that,宾语从句连接词]	[宾语从句语序]
[that,宾语从句连接词]	[宾语从句的连接词]
[that,宾语从句连接词]	[that,连词]
[that,连词]	[that]
[that,连词]	[连词]
[that,引导的定语从句]	[that]
[that,引导的定语从句]	[定语从句的关系词]
[that,指示代词]	[that]
[that,指示代词]	[指示代词]
[that]	[单词]
[the moment]	[moment]
[the number of+复数名词,主谓一致]	[number,表示数量单位的名词]
[the number of+复数名词,主谓一致]	[主谓一致]
[the other]	[other]
[the same as]	[as,介词]
[the same as]	[the惯用法]
[the same as]	[same]
[the]	[冠词]
[the]	[单词]
[the+比较级...the+比较级,引导比较状语从句]	[形容词和副词比较级]
[the+比较级...the+比较级,引导比较状语从句]	[比较状语从句,连词]
[the+独一无二的事物]	[the]
[the+乐器]	[the]
[the+形容词,主谓一致]	[形容词,the]
[the+形容词,主谓一致]	[主谓一致]
[the+形容词最高级+名词,后接that定语从句]	[that,引导的定语从句]
[the+形容词最高级+名词,后接that定语从句]	[the+形容词最高级+名词]
[the+形容词最高级+名词,后接that定语从句]	[后接that定语从句的先行词]
[the+形容词最高级+名词]	[形容词和副词最高级]
[the+形容词最高级+名词]	[the]
[the+姓氏,主谓一致]	[the+姓氏]
[the+姓氏,主谓一致]	[主谓一致]
[the+姓氏]	[the]
[the+序数词]	[the]
[the+序数词]	[序数词]
[the+序数词+形容词最高级]	[形容词和副词最高级]
[the+序数词+形容词最高级]	[the+序数词]
[them,人称代词宾格]	[人称代词宾格]
[them,人称代词宾格]	[them]
[them]	[单词]
[themselves,反身代词]	[themselves]
[themselves,反身代词]	[反身代词]
[themselves]	[单词]
[then]	[单词]
[There be A and B,主谓一致]	[There be,主谓一致]
[There be,主谓一致]	[there be句型]
[There be,主谓一致]	[主谓一致]
[there be]	[be]
[there be]	[there]
[there be句型,v-ing]	[v-ing习语]
[there be句型,v-ing]	[there be句型]
[there be句型]	[简单句]
[there be句型]	[there,位于句首的倒装]
[there be句型]	[there be]
[There is going to be]	[there be句型]
[There is going to be]	[be going to]
[there is something wrong with]	[wrong]
[there is something wrong with]	[something,复合不定代词]
[there is something wrong with]	[there be]
[there,位于句首的倒装]	[倒装句]
[there,位于句首的倒装]	[there]
[there]	[单词]
[the惯用法]	[the]
[think for oneself]	[oneself]
[think for oneself]	[think]
[think for oneself]	[for]
[think it+形容词+to do]	[不定式,it,宾语]
[think it+形容词+to do]	[think]
[think of]	[of,介词]
[think of]	[think]
[think]	[单词]
[think+宾语从句]	[think]
[think+宾语从句]	[动词+宾语从句]
[think…to be]	[不定式习语]
[think…to be]	[think]
[this,that]	[this,指示代词]
[this,that]	[that,指示代词]
[this,指示代词]	[this]
[this,指示代词]	[指示代词]
[this]	[单词]
[those,指示代词]	[those]
[those,指示代词]	[指示代词]
[those]	[单词]
[though,but不可一起使用]	[though,连词]
[though,but不可一起使用]	[but,连词]
[though,连词]	[though]
[though,连词]	[连词]
[though,引导让步状语从句]	[though,连词]
[though,引导让步状语从句]	[让步状语从句,连词]
[though]	[单词]
[thousand,基数词]	[基数词]
[thousand,基数词]	[thousand]
[thousand]	[单词]
[thousands of…]	[thousand,基数词]
[thousands of…]	[of]
[thousands of…]	[基数词用法]
[three years,表示时间/距离/金额]	[year]
[three years,表示时间/距离/金额]	[表示:时间/距离/金额的词]
[three years,主谓一致]	[three years,表示时间/距离/金额]
[three years,主谓一致]	[时间/距离/金额,主谓一致]
[three-year-old]	[old]
[three-year-old]	[复合形容词]
[three-year-old]	[year]
[through,介词]	[through]
[through,介词]	[介词]
[through]	[单词]
[time]	[单词]
[to be honest]	[honest]
[to one's joy]	[joy]
[to one's joy]	[to]
[to one's surprise]	[to]
[to one's surprise]	[surprise]
[to,介词]	[介词]
[to,介词]	[to]
[to]	[单词]
[tomorrow,用于一般将来时]	[tomorrow]
[tomorrow,用于一般将来时]	[一般将来时的时间状语]
[tomorrow]	[单词]
[too many]	[too+形容词副词]
[too many]	[many+可数名词]
[too many]	[many]
[too much]	[much]
[too much]	[too+形容词副词]
[too much]	[much+不可数名词]
[too,副词instances]	[副词instances]
[too,副词instances]	[too]
[too]	[单词]
[too+形容词副词]	[too,副词instances]
[too+形容词副词]	[形容词和副词修饰语]
[too…to do]	[too…to]
[too…to do]	[不定式习语]
[too…to,反意疑问句]	[too…to]
[too…to,反意疑问句]	[反意疑问句]
[too…to]	[too]
[to不可省略,be v-ed to do]	[宾语+不定式宾补,被动语态]
[to不可省略,be v-ed to do]	[不定式]
[trouble]	[单词]
[true]	[单词]
[try on]	[on]
[try on]	[try]
[try]	[单词]
[turn down]	[down]
[turn down]	[turn]
[turn off]	[off]
[turn off]	[turn]
[turn on]	[turn]
[turn on]	[on]
[turn up]	[up]
[turn up]	[turn]
[turn]	[单词]
[twice,副词instances]	[twice]
[twice,副词instances]	[副词instances]
[twice,用于现在完成时]	[用于现在完成时的副词]
[twice,用于现在完成时]	[twice,副词instances]
[twice]	[单词]
[university,是非元音开头的词]	[a+非元音开头的词]
[university,是非元音开头的词]	[非元音开头的词]
[university,是非元音开头的词]	[university]
[university]	[单词]
[unless,连词]	[unless]
[unless,连词]	[连词]
[unless,引导条件状语从句]	[条件状语从句,连词]
[unless,引导条件状语从句]	[unless,连词]
[unless]	[单词]
[until,连词]	[until]
[until,连词]	[连词]
[until,引导时间状语从句]	[时间状语从句,连词]
[until,引导时间状语从句]	[until,连词]
[until]	[单词]
[up]	[单词]
[us,人称代词宾格]	[人称代词宾格]
[us,人称代词宾格]	[us]
[us]	[单词]
[use,及物动词]	[及物动词]
[use,及物动词]	[use]
[use]	[单词]
[used to,陈述句]	[used to,情态动词]
[used to,陈述句]	[陈述句]
[used to,情态动词]	[情态动词]
[used to,情态动词]	[used to]
[used to]	[use]
[used to]	[to]
[used to陈述句->否定句,疑问句]	[used to,陈述句]
[used to陈述句->否定句,疑问句]	[陈述句->否定句,疑问句]
[useful,是非元音开头的词]	[a+非元音开头的词]
[useful,是非元音开头的词]	[useful]
[useful,是非元音开头的词]	[非元音开头的词]
[useful]	[单词]
[usually,频率副词]	[频率副词]
[usually,频率副词]	[usually]
[usually,用于一般现在时]	[usually,频率副词]
[usually,用于一般现在时]	[一般现在时的时间状语]
[usually]	[单词]
[v+ing构成]	[v-ing]
[v+ing构成]	[词形转换]
[v-ed]	[非谓语动词]
[v-ed习语]	[v-ed]
[v-ing,句子成分]	[v-ing]
[v-ing]	[非谓语动词]
[v-ing习语]	[v-ing]
[v-ing作主语,主谓一致]	[主语]
[v-ing作主语,主谓一致]	[v-ing,句子成分]
[v-ing作主语,主谓一致]	[主谓一致]
[violin,是乐器]	[乐器]
[violin,是乐器]	[the+乐器]
[violin,是乐器]	[violin]
[violin]	[单词]
[walk]	[单词]
[watch one's diet]	[watch]
[watch one's diet]	[diet]
[watch]	[单词]
[water]	[单词]
[wear]	[单词]
[weather,不可数名词instances]	[不可数名词instances]
[weather,不可数名词instances]	[weather]
[weather]	[单词]
[weekend]	[单词]
[well,表语补语形容词]	[表语补语形容词]
[well,表语补语形容词]	[well]
[well,副词instances]	[副词instances]
[well,副词instances]	[well]
[well]	[单词]
[well->better,比较级]	[形容词副词比较级构成]
[well->better,比较级]	[better]
[well->better,比较级]	[well]
[what about]	[about]
[what about]	[what]
[what about…,应答句]	[what about]
[what about…,应答句]	[表达建议/意见/观点,应答句]
[what colour,特殊疑问句]	[what colour]
[what colour,特殊疑问句]	[特殊疑问句]
[what colour]	[what]
[what colour]	[colour]
[what do you do]	[what,特殊疑问句]
[what do you do]	[do]
[what do you think of…]	[what,特殊疑问句]
[what do you think of…]	[think of]
[what is your opinion on]	[what,特殊疑问句]
[what is your opinion on]	[opinion]
[what is your opinion on]	[on,介词]
[what time,宾语从句连接词]	[宾语从句语序]
[what time,宾语从句连接词]	[what time]
[what time,宾语从句连接词]	[宾语从句的连接词]
[what time]	[time]
[what time]	[what]
[what to do]	[疑问词+不定式]
[what to do]	[what,疑问代词]
[what,宾语从句连接词]	[宾语从句语序]
[what,宾语从句连接词]	[宾语从句的连接词]
[what,宾语从句连接词]	[what,疑问代词]
[what,特殊疑问句]	[what,疑问代词]
[what,特殊疑问句]	[特殊疑问句]
[what,疑问代词]	[疑问代词]
[what,疑问代词]	[what]
[what,引导的感叹句]	[what]
[what,引导的感叹句]	[感叹句]
[what...look like]	[like,介词]
[what...look like]	[what,特殊疑问句]
[what]	[单词]
[what…like]	[like,介词]
[what…like]	[what,特殊疑问句]
[whatever,连词]	[whatever]
[whatever,连词]	[连词]
[whatever,引导让步状语从句]	[让步状语从句,连词]
[whatever,引导让步状语从句]	[whatever,连词]
[whatever]	[单词]
[what's the matter with you]	[matter]
[when to do]	[疑问词+不定式]
[when to do]	[when,疑问副词]
[when,宾语从句连接词]	[宾语从句语序]
[when,宾语从句连接词]	[宾语从句的连接词]
[when,宾语从句连接词]	[when,疑问副词]
[when,连词]	[when]
[when,连词]	[连词]
[when,特殊疑问句]	[特殊疑问句]
[when,特殊疑问句]	[when,疑问副词]
[when,疑问副词]	[when]
[when,疑问副词]	[疑问副词]
[when,引导的定语从句]	[when]
[when,引导的定语从句]	[定语从句的关系词]
[when,引导时间状语从句]	[when,连词]
[when,引导时间状语从句]	[时间状语从句,连词]
[when]	[单词]
[whenever,连词]	[whenever]
[whenever,连词]	[连词]
[whenever,引导让步状语从句]	[让步状语从句,连词]
[whenever,引导让步状语从句]	[whenever,连词]
[whenever]	[单词]
[Where have/has...been]	[Be动词,用于现在完成时]
[where to do]	[疑问词+不定式]
[where to do]	[where,疑问副词]
[where,宾语从句连接词]	[宾语从句语序]
[where,宾语从句连接词]	[where,疑问副词]
[where,宾语从句连接词]	[宾语从句的连接词]
[where,特殊疑问句]	[where,疑问副词]
[where,特殊疑问句]	[特殊疑问句]
[where,疑问副词]	[where]
[where,疑问副词]	[疑问副词]
[where,引导的定语从句]	[where]
[where,引导的定语从句]	[定语从句的关系词]
[where]	[单词]
[wherever,连词]	[wherever]
[wherever,连词]	[连词]
[wherever,引导让步状语从句]	[让步状语从句,连词]
[wherever,引导让步状语从句]	[wherever,连词]
[wherever]	[单词]
[whether,宾语从句连接词]	[whether,连词]
[whether,宾语从句连接词]	[宾语从句语序]
[whether,宾语从句连接词]	[宾语从句的连接词]
[whether,连词]	[whether]
[whether,连词]	[连词]
[whether]	[单词]
[which to do]	[疑问词+不定式]
[which to do]	[which,疑问代词]
[which,宾语从句连接词]	[宾语从句语序]
[which,宾语从句连接词]	[宾语从句的连接词]
[which,宾语从句连接词]	[which,疑问代词]
[which,特殊疑问句]	[which,疑问代词]
[which,特殊疑问句]	[特殊疑问句]
[which,疑问代词]	[which]
[which,疑问代词]	[疑问代词]
[which,引导的定语从句]	[which]
[which,引导的定语从句]	[定语从句的关系词]
[which]	[单词]
[while,连词]	[while]
[while,连词]	[连词]
[while,引导让步状语从句]	[让步状语从句,连词]
[while,引导让步状语从句]	[while,连词]
[while,引导时间状语从句]	[while,连词]
[while,引导时间状语从句]	[时间状语从句,连词]
[while]	[单词]
[while+过去进行时,主句过去进行时]	[过去进行时的时间状语]
[while+过去进行时,主句过去进行时]	[while,引导时间状语从句]
[while+过去进行时,主句过去进行时]	[时间状语从句,时态]
[who to do]	[疑问词+不定式]
[who to do]	[who,疑问代词]
[who,宾语从句连接词]	[宾语从句语序]
[who,宾语从句连接词]	[who,疑问代词]
[who,宾语从句连接词]	[宾语从句的连接词]
[who,特殊疑问句]	[who,疑问代词]
[who,特殊疑问句]	[特殊疑问句]
[who,疑问代词]	[疑问代词]
[who,疑问代词]	[who]
[who,引导的定语从句]	[who]
[who,引导的定语从句]	[定语从句的关系词]
[who]	[单词]
[whom,宾语从句连接词]	[whom,疑问代词]
[whom,宾语从句连接词]	[宾语从句语序]
[whom,宾语从句连接词]	[宾语从句的连接词]
[whom,特殊疑问句]	[whom,疑问代词]
[whom,特殊疑问句]	[特殊疑问句]
[whom,疑问代词]	[疑问代词]
[whom,疑问代词]	[whom]
[whom]	[单词]
[whose,特殊疑问句]	[特殊疑问句]
[whose,特殊疑问句]	[whose,疑问代词]
[whose,疑问代词]	[疑问代词]
[whose,疑问代词]	[whose]
[whose,引导的定语从句]	[定语从句的关系词]
[whose,引导的定语从句]	[whose]
[whose]	[单词]
[why,宾语从句连接词]	[why,疑问副词]
[why,宾语从句连接词]	[宾语从句语序]
[why,宾语从句连接词]	[宾语从句的连接词]
[why,不定式]	[疑问词+不定式]
[why,不定式]	[why,疑问副词]
[why,不定式]	[不加to的动词不定式]
[why,特殊疑问句]	[why,疑问副词]
[why,特殊疑问句]	[特殊疑问句]
[why,疑问副词]	[why]
[why,疑问副词]	[疑问副词]
[why]	[单词]
[Will you please do sth,应答句]	[Will you please,疑问句]
[Will you please do sth,应答句]	[表示请求,应答句]
[Will you please,疑问句]	[一般疑问句]
[Will you please,疑问句]	[will]
[will]	[单词]
[wish]	[单词]
[wish…to do]	[不定式习语]
[wish…to do]	[wish]
[with the help of]	[help]
[with the help of]	[with,介词]
[with,介词]	[介词]
[with,介词]	[with]
[with,主谓一致]	[with,介词]
[with,主谓一致]	[主谓一致]
[with]	[单词]
[without,介词]	[without]
[without,介词]	[介词]
[without]	[单词]
[woman teacher,复数]	[复合名词.复数]
[work out]	[out]
[work out]	[work]
[work,不可数名词instances]	[不可数名词instances]
[work,不可数名词instances]	[work]
[work]	[单词]
[worn]	[单词]
[worried]	[单词]
[worried<->anxious]	[worried]
[worried<->anxious]	[anxious]
[worried<->anxious]	[形容词->近义词]
[worse]	[单词]
[worth]	[单词]
[would like to do]	[不定式习语]
[would like to do]	[would like]
[would like]	[would]
[would like]	[like]
[would like…to do]	[不定式习语]
[would like…to do]	[would like]
[would rather,不定式]	[would rather]
[would rather,不定式]	[不加to的动词不定式]
[would rather]	[would]
[would rather]	[rather]
[Would you like me to do sth,应答句]	[表示请求,应答句]
[Would you like me to do sth,应答句]	[would like]
[Would you like to do sth,应答句]	[表示请求,应答句]
[Would you like to do sth,应答句]	[would like]
[would you mind]	[would]
[would you mind]	[mind]
[Would you mind…,应答句]	[表示请求,应答句]
[Would you mind…,应答句]	[would you mind]
[Would you please do sth,应答句]	[Would you please,疑问句]
[Would you please do sth,应答句]	[表示请求,应答句]
[Would you please,疑问句]	[would]
[Would you please,疑问句]	[一般疑问句]
[would,虚拟语气]	[would,助动词]
[would,虚拟语气]	[虚拟语气]
[would,助动词]	[would]
[would,助动词]	[助动词]
[would]	[单词]
[write down]	[down]
[write down]	[write]
[write]	[单词]
[wrong]	[单词]
[year]	[单词]
[yet,副词instances]	[副词instances]
[yet,副词instances]	[yet]
[yet,用于现在完成时]	[yet,副词instances]
[yet,用于现在完成时]	[用于现在完成时的副词]
[yet]	[单词]
[you,人称代词宾格]	[人称代词宾格]
[you,人称代词宾格]	[you]
[you,人称代词主格]	[you]
[you,人称代词主格]	[人称代词主格]
[you]	[单词]
[your,形容词性物主代词]	[形容词性物主代词]
[your,形容词性物主代词]	[your]
[your]	[单词]
[yours,名词性物主代词]	[名词性物主代词]
[yours,名词性物主代词]	[yours]
[yours]	[单词]
[yourself,反身代词]	[反身代词]
[yourself,反身代词]	[yourself]
[yourself]	[单词]
[yourselves,反身代词]	[反身代词]
[yourselves,反身代词]	[yourselves]
[yourselves]	[单词]
[被动语态,to+间接宾语,offer]	[被动语态,to+间接宾语,动词]
[被动语态,to+间接宾语,offer]	[offer]
[被动语态,to+间接宾语,动词]	[to,介词]
[被动语态,to+间接宾语,动词]	[双宾语变被动语态,主动句直接宾语->被动句主语]
[被动语态,时态]	[时态]
[被动语态,时态]	[被动语态]
[被动语态]	[*]
[比较级 + and + 比较级]	[and]
[比较级 + and + 比较级]	[形容词和副词比较级]
[比较级+than any other]	[than any other]
[比较状语从句,连词]	[比较状语从句]
[比较状语从句]	[状语从句]
[编号]	[数词其他用法]
[辨析:among,between]	[between,介词]
[辨析:among,between]	[among,介词]
[辨析:few,a few]	[a few]
[辨析:few,a few]	[few]
[表达感谢,应答句]	[应答句]
[表达建议/意见/观点,应答句]	[应答句]
[表达歉意,应答句]	[应答句]
[表达责备,应答句]	[应答句]
[表示:时间/距离/金额的词]	[其他词类]
[表示地点:at,in]	[in,介词]
[表示地点:at,in]	[at,介词]
[表示方位:in,on,to]	[in,介词]
[表示方位:in,on,to]	[to,介词]
[表示方位:in,on,to]	[on,介词]
[表示请求,应答句]	[应答句]
[表示时间:after,in]	[in,介词]
[表示时间:after,in]	[after,介词]
[表示时间:at,in,on]	[in,介词]
[表示时间:at,in,on]	[on,介词]
[表示时间:at,in,on]	[at,介词]
[表示时间:during,for]	[during,介词]
[表示时间:during,for]	[for,介词]
[表示时间:for,from,since]	[from,介词]
[表示时间:for,from,since]	[since,介词]
[表示时间:for,from,since]	[for,介词]
[表示数量单位的名词]	[名词]
[表示愿意提供帮助,应答句]	[应答句]
[表语补语形容词]	[形容词]
[宾语]	[句子成分]
[宾语+不定式宾补,被动语态]	[宾语补足语]
[宾语+不定式宾补,被动语态]	[不定式]
[宾语+不定式宾补,被动语态]	[主动句->被动句]
[宾语补足语]	[句子成分]
[宾语从句,时态]	[宾语从句]
[宾语从句,时态]	[复合句,时态]
[宾语从句]	[复合句]
[宾语从句的连接词]	[宾语从句]
[宾语从句语序]	[宾语从句]
[并列结构]	[句式]
[并列结构的连词]	[并列结构]
[并列结构的连词]	[连词]
[不定代词]	[代词]
[不定式,it,宾语]	[不定式,句子成分]
[不定式,it,宾语]	[it形式宾语]
[不定式,it,主语]	[不定式,句子成分]
[不定式,it,主语]	[it形式主语]
[不定式,被动语态]	[被动语态]
[不定式,被动语态]	[不定式]
[不定式,定语]	[不定式,句子成分]
[不定式,定语]	[定语]
[不定式,句子成分]	[不定式]
[不定式]	[非谓语动词]
[不定式的逻辑主语]	[不定式]
[不定式习语]	[不定式]
[不规则可数名词.复数]	[名词复数]
[不规则可数名词.复数]	[不规则可数名词]
[不规则可数名词]	[可数名词]
[不加to的动词不定式]	[不定式]
[不可数名词]	[名词]
[不可数名词instances]	[词义辨析]
[不可数名词instances]	[不可数名词]
[不可数名词修饰语]	[不可数名词]
[不可数名词修饰语]	[名词修饰语]
[陈述成就,应答句]	[应答句]
[陈述即将到来的挑战,应答句]	[应答句]
[陈述句]	[简单句]
[陈述句->否定句,疑问句]	[句式变换]
[陈述遗憾的事情,应答句]	[应答句]
[词类]	[*]
[词形转换]	[词类]
[词义辨析]	[词类]
[从句表示:客观真理,自然现象或习惯动作]	[主句过去时]
[代词]	[词类]
[带宾语从句的句子,被动语态]	[宾语从句]
[带宾语从句的句子,被动语态]	[主动句->被动句]
[单词]	[词类]
[倒装句]	[简单句]
[定语]	[句子成分]
[定语从句]	[复合句]
[定语从句的关系词]	[定语从句]
[定语从句的先行词]	[定语从句]
[动词]	[词类]
[动词+…+形容词]	[及物动词]
[动词+…+形容词]	[表语补语形容词]
[动词+宾语从句]	[宾语从句]
[动词+宾语从句]	[及物动词]
[动词+直接宾语+宾语从句]	[宾语从句]
[动词+直接宾语+宾语从句]	[及物动词]
[动词<->名词]	[词形转换]
[动词instances]	[词义辨析]
[动词instances]	[动词]
[独一无二的事物]	[其他词类]
[反身代词]	[代词]
[反意疑问句,应答句]	[反意疑问句]
[反意疑问句,应答句]	[应答句]
[反意疑问句]	[疑问句]
[非谓语动词]	[动词]
[非延续性动词,用于现在完成时]	[非延续性动词]
[非延续性动词,用于现在完成时]	[现在完成时]
[非延续性动词]	[动词]
[非元音开头的词]	[其他词类]
[分数]	[数词其他用法]
[分数作主语,主谓一致]	[分数]
[分数作主语,主谓一致]	[主谓一致]
[否定含义的词]	[其他词类]
[否定含义的词+反意疑问句]	[反意疑问句]
[复合不定代词]	[代词]
[复合不定代词]	[不定代词]
[复合介词]	[介词]
[复合句,时态]	[复合句]
[复合句,时态]	[时态]
[复合句]	[句式]
[复合名词.复数]	[复合名词]
[复合名词.复数]	[名词复数]
[复合名词]	[名词]
[复合形容词]	[形容词]
[副词]	[词类]
[副词instances]	[副词]
[副词instances]	[词义辨析]
[副词的构成]	[副词]
[副词惯用法]	[副词]
[感叹句]	[简单句]
[冠词]	[词类]
[规则可数名词.复数]	[名词复数]
[规则可数名词.复数]	[规则可数名词]
[规则可数名词]	[可数名词]
[规则可数名词instances]	[词义辨析]
[规则可数名词instances]	[规则可数名词]
[过去进行时]	[时态]
[过去进行时的时间状语]	[过去进行时]
[过去完成时]	[时态]
[过去完成时的时间状语]	[过去完成时]
[后接that定语从句的先行词]	[定语从句的先行词]
[基数词]	[数词]
[基数词+more]	[基数词]
[基数词+more]	[more]
[基数词的构成]	[基数词]
[基数词用法]	[基数词]
[及物动词]	[动词]
[计划旅行/派对,应答句]	[应答句]
[间接宾语]	[宾语]
[简单句]	[句式]
[交通通讯方法]	[其他词类]
[结果状语从句,连词]	[结果状语从句]
[结果状语从句]	[状语从句]
[介词]	[词类]
[近义词]	[词形转换]
[近义词]	[同义转换]
[句式]	[*]
[句式变换]	[句式]
[句子成分]	[*]
[可数名词]	[名词]
[可数名词修饰语]	[可数名词]
[可数名词修饰语]	[名词修饰语]
[乐器]	[其他词类]
[连词]	[词类]
[零冠词]	[冠词]
[零冠词+人名地名]	[零冠词]
[零冠词惯用法]	[零冠词]
[名词]	[词类]
[名词复数]	[名词]
[名词复数]	[词形转换]
[名词复数的所有格]	[名词所有格]
[名词复数的所有格]	[名词复数]
[名词所有格]	[名词]
[名词性物主代词]	[物主代词]
[名词修饰语]	[名词]
[目的状语从句,连词]	[目的状语从句]
[目的状语从句]	[状语从句]
[年龄]	[数词其他用法]
[频率副词]	[副词]
[其他词类]	[词类]
[祈使句]	[简单句]
[祈使句+and+陈述句]	[and]
[祈使句+and+陈述句]	[并列结构]
[祈使句+and+陈述句]	[祈使句]
[祈使句+or+陈述句]	[并列结构]
[祈使句+or+陈述句]	[or]
[祈使句+or+陈述句]	[祈使句]
[祈使句的反义疑问]	[反意疑问句]
[祈使句的反义疑问]	[祈使句]
[祈使句的应答句]	[应答句]
[祈使句的应答句]	[祈使句]
[情境语义]	[*]
[情态动词,时态]	[情态动词]
[情态动词,时态]	[时态]
[情态动词]	[动词]
[情态动词的被动语态]	[情态动词]
[情态动词的被动语态]	[被动语态]
[球类棋类]	[其他词类]
[让步状语从句,连词]	[让步状语从句]
[让步状语从句]	[状语从句]
[人称代词]	[代词]
[人称代词宾格]	[人称代词]
[人称代词主格]	[人称代词]
[省略句]	[简单句]
[时间/距离/金额,主谓一致]	[主谓一致]
[时间状语从句,连词]	[时间状语从句]
[时间状语从句,时态]	[时间状语从句]
[时间状语从句,时态]	[复合句,时态]
[时间状语从句]	[状语从句]
[时间状语从句用一般现在时表示将来]	[时间状语从句,时态]
[时刻]	[数词其他用法]
[时态]	[*]
[实义动词]	[动词]
[世纪年代]	[数词其他用法]
[数词]	[词类]
[数词+名词+形容词]	[数词其他用法]
[数词其他用法]	[数词]
[双宾语变被动语态,主动句直接宾语->被动句主语]	[间接宾语]
[双宾语变被动语态,主动句直接宾语->被动句主语]	[直接宾语]
[双宾语变被动语态,主动句直接宾语->被动句主语]	[主动句->被动句]
[双重所有格]	[其他词类]
[特殊疑问句,应答句]	[应答句]
[特殊疑问句]	[疑问句]
[条件状语从句,连词]	[条件状语从句]
[条件状语从句,时态]	[复合句,时态]
[条件状语从句,时态]	[条件状语从句]
[条件状语从句]	[状语从句]
[同义转换]	[句式]
[位置移动:across,through]	[across,介词]
[位置移动:across,through]	[through,介词]
[物主代词]	[代词]
[系动词]	[动词]
[系动词+形容词]	[系动词]
[系动词+形容词]	[形容词]
[现在进行时]	[时态]
[现在完成时]	[时态]
[现在完成时的被动语态]	[被动语态,时态]
[现在完成时的被动语态]	[现在完成时]
[现在完成时的时间状语]	[现在完成时]
[形容词,the]	[形容词]
[形容词,the]	[the]
[形容词]	[词类]
[形容词->近义词]	[近义词]
[形容词instances]	[形容词]
[形容词instances]	[词义辨析]
[形容词副词+enough]	[副词惯用法]
[形容词副词+enough]	[enough,副词instances]
[形容词副词比较级构成]	[形容词和副词比较级]
[形容词副词比较级构成]	[词形转换]
[形容词惯用法]	[形容词]
[形容词和副词比较级]	[副词]
[形容词和副词比较级]	[形容词]
[形容词和副词比较级修饰语]	[形容词和副词比较级]
[形容词和副词的原级]	[副词]
[形容词和副词的原级]	[as]
[形容词和副词的原级]	[形容词]
[形容词和副词修饰语]	[形容词和副词的原级]
[形容词和副词最高级]	[副词]
[形容词和副词最高级]	[形容词]
[形容词和副词最高级构成]	[形容词和副词最高级]
[形容词和副词最高级构成]	[词形转换]
[形容词和副词最高级修饰语]	[形容词和副词最高级]
[形容词性物主代词]	[物主代词]
[形容词性物主动词+序数词]	[形容词性物主代词]
[形容词性物主动词+序数词]	[序数词]
[虚拟语气]	[*]
[虚拟语气复合句:I would go if it were fine.]	[复合句,时态]
[虚拟语气复合句:I would go if it were fine.]	[would,虚拟语气]
[序数词]	[数词]
[序数词+形容词副词最高级]	[形容词和副词最高级修饰语]
[序数词+形容词副词最高级]	[序数词]
[序数词的构成]	[序数词]
[序数词用法]	[序数词]
[选择疑问句]	[疑问句]
[延续性动词,用于现在完成时]	[延续性动词]
[延续性动词,用于现在完成时]	[现在完成时]
[延续性动词]	[动词]
[一般过去时]	[时态]
[一般过去时的被动语态]	[被动语态,时态]
[一般过去时的被动语态]	[一般过去时]
[一般过去时的时间状语]	[一般过去时]
[一般将来时]	[时态]
[一般将来时的被动语态]	[被动语态,时态]
[一般将来时的被动语态]	[一般将来时]
[一般将来时的时间状语]	[一般将来时]
[一般现在时,动词第三人称单数形式]	[一般现在时]
[一般现在时,动词第三人称单数形式]	[动词]
[一般现在时,动词第三人称单数形式]	[词形转换]
[一般现在时]	[时态]
[一般现在时的被动语态]	[一般现在时]
[一般现在时的被动语态]	[被动语态,时态]
[一般现在时的时间状语]	[一般现在时]
[一般疑问句]	[疑问句]
[一半，四分之一]	[数词其他用法]
[疑问词]	[词类]
[疑问词+不定式]	[疑问词]
[疑问词+不定式]	[不定式]
[疑问代词]	[代词]
[疑问代词]	[疑问词]
[疑问副词]	[副词]
[疑问副词]	[疑问词]
[疑问句]	[简单句]
[应答句]	[简单句]
[用于现在完成时的副词]	[现在完成时]
[元音开头的词]	[其他词类]
[原因状语从句,连词]	[原因状语从句]
[原因状语从句]	[状语从句]
[赞誉和表扬的应答句]	[应答句]
[直接宾语]	[宾语]
[直接引语->间接引语]	[句式变换]
[指示代词]	[代词]
[主动句->被动句]	[句式变换]
[主动句->被动句]	[被动语态]
[主句过去时]	[直接引语->间接引语]
[主句过去时]	[宾语从句语序]
[主句过去时]	[一般过去时]
[主句过去时]	[宾语从句,时态]
[主句和从句,一般时和进行时]	[时间状语从句,时态]
[主句现在时]	[宾语从句语序]
[主句现在时]	[宾语从句,时态]
[主谓一致]	[句子成分]
[主语]	[句子成分]
[主语+happen]	[happen]
[助动词]	[动词]
[祝愿祝福,应答句]	[应答句]
[状语从句]	[复合句]
[字母,读音以元音开头]	[an+元音开头的词]
[字母,读音以元音开头]	[元音开头的词]
[shortly,副词instances]	[副词instances]
[shortly,副词instances]	[shortly]
'''
	
}
