package ots

class SampleData_QuestionMapping3 {

	String content ='''[24309]	Hurry up, ____ you will miss the plane.	[祈使句+or+陈述句]
[24289]	Hurry up, ____ you are not able to catch the last bus.	[祈使句+or+陈述句]
[24269]	Hurry up, ____ finish your homework!	[祈使句+and+陈述句]
[24265]	Hurry up! The meeting will begin ____ 3:00 pm.	[表示时间:at,in,on]
[24260]	Hurry up! The concert ____ for ten minutes.	[延续性动词,用于现在完成时]
[24255]	Hurry up! It's 5 p.m. [on the nose.]	[情境语义]
[24250]	Hurry up! If we miss ____ last bus, we'll have to get home by ____ taxi.	[the+序数词]
[24250]	Hurry up! If we miss ____ last bus, we'll have to get home by ____ taxi.	[by+交通通讯方法]
[24245]	Hurry if you want to be ____ for the beginning of the movie.	[in time]
[24240]	Huang Bo is a popular film star. He ____ brings us good films.	[always,用于一般现在时]
[24230]	However, ____ that, the city is always open to all kinds of cultures.	[because of]
[24216]	How time flies! We'll graduate. Three years ____ really a short time.	[three years,主谓一致]
[24211]	How time flies! Three years ____ really a short time.	[three years,主谓一致]
[24207]	How time flies! Several years ____ since we started our middle school life. We will keep the pleasant experience in our minds.	[since+一般过去时,主句用现在完成时]
[24202]	How smart Mary is! Of all the students in her class, she usually spends the ____ time and makes the ____ mistakes in her homework.	[little->least,最高级]
[24202]	How smart Mary is! Of all the students in her class, she usually spends the ____ time and makes the ____ mistakes in her homework.	[few->fewest,最高级]
[24192]	How much does the ticket ____ from Shanghai to Beijing?	[cost,pay,spend,take]
[24187]	How magnificent the Bund looks at night when all the lights are ____!	[turn off]
[24183]	How lovely the dog is! Can you tell me ____?	[where,宾语从句连接词]
[24178]	How long do you think he will ____?	[how long,特殊疑问句]
[24173]	How long can I ____ this magazine?	[how long,特殊疑问句]
[24163]	How is your father? Please say hello to ____ for me.	[him,人称代词宾格]
[24158]	How dangerous! She was driving the car with one hand and holding an ice cream with ____.	[one … the other ...]
[24153]	How ____ the children are playing! They even forget the time to go home!	[how引导的感叹句]
[24153]	How ____ the children are playing! They even forget the time to go home!	[副词instances]
[24148]	Hot water ____ in the students' flats from 5 p.m. to 7 pm now.	[一般现在时的被动语态]
[24143]	Hong Kong is in the ____of China.	[情境语义]
[24138]	Hong Kong ____ to be a good place for eating today.	[be known to be]
[24138]	Hong Kong ____ to be a good place for eating today.	[一般现在时的被动语态]
[24133]	Hold on to your dreams, ____ they will come true one day.	[祈使句+and+陈述句]
[24128]	His Walkman is different from ____, and it is more expensive.	[mine,名词性物主代词]
[24108]	His parents often encourage him ____ hard.	[encourage…to do]
[24103]	His parents found ____ to tell him everything that had happened.	[find it+形容词+to do]
[24093]	His name is Thomas, but he usually calls ____ Tom.	[himself,反身代词]
[24088]	His leg is seriously injured in the accident. ____ a doctor at once.	[send for]
[24078]	His grandparents live ____ in a small house, but they don't feel ____.	[alone,lonely]
[24063]	His grade in the exam put him ____ the top students in his class.	[辨析:among,between]
[24044]	Hi, mum. Have you cooked fish for dinner? I can ____ it.	[smell,及物动词]
[24039]	Hi, Kitty, I have passed ____ exams!<\\n>Oh, congratulations! I hope my sister has also passed ____.	[my,形容词性物主代词]
[24039]	Hi, Kitty, I have passed ____ exams!<\\n>Oh, congratulations! I hope my sister has also passed ____.	[hers,名词性物主代词]
[24034]	Hi, Jack. Would you please ____ the picture on the wall?	[put up]
[24029]	Hi, Betty. Do you know ____ from our school to the shopping center?	[how far,特殊疑问句]
[23995]	He's found ____ in the bag. It's empty.	[nothing,复合不定代词]
[23991]	He's flown to Hainan for a holiday, ____ he?	[反意疑问句]
[23971]	Her son ____ Coke, but now he ____ milk.	[be used to doing]
[23971]	Her son ____ Coke, but now he ____ milk.	[used to,情态动词]
[23967]	Her sister prefers to be a ____ star.	[v-ing,句子成分]
[23962]	Her mother was not at home last week. She cooked meals for ____.	[herself,反身代词]
[23957]	Her mother goes to work ____ bus every morning.	[by bus]
[23952]	Her grandpa ____ in 2000. Though he ____ for about ten years, she still misses him.	[for+一段时间]
[23952]	Her grandpa ____ in 2000. Though he ____ for about ten years, she still misses him.	[一般过去时]
[23947]	Her brother is very busy with his work now, so he has ____ time to read newspapers.	[little+不可数名词]
[23942]	Henry will give us a report as soon as he ____.	[时间状语从句用一般现在时表示将来]
[23937]	Henry speaks Chinese very well. He ____ in China since 2002.	[since+过去时间点,用于现在完成时]
[23923]	Help others whenever you can ____ you'll make the world a nicer place to live in.	[祈使句+and+陈述句]
[23919]	Hello, this is Tom speaking. ____	[情境语义]
[23914]	Hello, everybody! You are taking the important exam now. Don't be nervous. It is not as difficult as you imagine. I am sure you all will succeed. Please answer every question with great care. You know ____ you are, ____ mistakes you'll make.	[few+可数名词]
[23914]	Hello, everybody! You are taking the important exam now. Don't be nervous. It is not as difficult as you imagine. I am sure you all will succeed. Please answer every question with great care. You know ____ you are, ____ mistakes you'll make.	[the+比较级...the+比较级,引导比较状语从句]
[23909]	Hello! I'm very glad to see you. When ____ you ____ here?	[一般过去时]
[23904]	Helen was so excited at the news that she could ____ say a word.	[hardly,频率副词]
[23899]	Helen loves to talk about travel. She ____ many places.	[have been to,have gone to,have been in]
[23894]	Helen has ____ lovely pet dog. ____ dog is clever enough to bring her newspapers every evening.	[a]
[23894]	Helen has ____ lovely pet dog. ____ dog is clever enough to bring her newspapers every evening.	[the]
[23886]	He wrote his ____ novel when he was ____.	[形容词性物主动词+序数词]
[23881]	He will have to watch his ____ because of his serious stomach problem.	[watch one's diet]
[23876]	He will go to the mountains with his parents if it ____ next Sunday.	[条件状语从句,时态]
[23866]	He went into his room, ____ the light and began to work.	[turn on]
[23866]	He went into his room, ____ the light and began to work.	[一般过去时]
[23862]	He was very ill, but now he is [out of danger].	[out of danger]
[23857]	He was still working on his project while other people ____ a rest.	[while+过去进行时,主句过去进行时]
[23852]	He was so ____ when he heard the ____ news that he got the first prize in the contest.	[excited,-ed形式的形容词]
[23852]	He was so ____ when he heard the ____ news that he got the first prize in the contest.	[exciting,-ing形式的形容词]
[23842]	He was born in Italy, but he has made China his ____.	[make…one's home]
[23837]	He was asked ____ late again.	[to不可省略,be v-ed to do]
[23832]	He wants to know ____.	[when,宾语从句连接词]
[23828]	He wants to have his TV ____.	[have sth done]
[23823]	He wants to ____ friends with me.	[make friends with]
[23808]	He used to ____ in the sun, but now he is used to ____ at night.	[be used to doing]
[23808]	He used to ____ in the sun, but now he is used to ____ at night.	[used to,情态动词]
[23803]	He told us a good way ____ information.	[不定式,定语]
[23798]	He thinks himself somebody, but we think him ____.	[think…to be]
[23798]	He thinks himself somebody, but we think him ____.	[nobody,复合不定代词]
[23778]	He speaks French well, but of course not ____ a person born in France.	[not so/as...as,引导比较状语从句]
[23778]	He speaks French well, but of course not ____ a person born in France.	[副词instances]
[23763]	He speaks ____ English ____ French. Instead, he speaks German.	[neither…nor,是并列结构连词]
[23753]	He said he would come to see us ____ the next afternoon.	[sometime,sometimes]
[23753]	He said he would come to see us ____ the next afternoon.	[some time]
[23733]	He puts the flowers in the shade ____ the sun will not burn them.	[so that,引导目的状语从句]
[23723]	He often goes to the cinema on Sundays, ____?	[反意疑问句]
[23713]	He often drinks two cups of ____ water when he comes back.	[boiled water]
[23708]	He often ____ us English stories.	[tell a story]
[23703]	He offered ____ valuable advice that ____ people disagreed.	[such+不可数名词]
[23703]	He offered ____ valuable advice that ____ people disagreed.	[advice,不可数名词instances]
[23703]	He offered ____ valuable advice that ____ people disagreed.	[辨析:few,a few]
[23698]	He never ____ no matter how many difficulties he has.	[give up]
[23693]	He lost his key. It made him ____ in the cold to wait for his wife's return.	[make,不定式]
[23684]	He looks so happy. Maybe he ____ he won the first prize.	[一般现在时]
[23661]	He Jiong is a famous host at Hunan TV Station, ____ does well in making jokes.	[he,人称代词主格]
[23652]	He is too tired to move after ____ hard work.	[名词复数的所有格]
[23638]	He is one of the experienced engineers in this factory ____ hard work was repaid with the development of the factory.	[whose,引导的定语从句]
[23634]	He is getting fat, ____ he has decided to go to work on foot.	[so,连词]
[23605]	He is ____ father.	[名词所有格]
[23601]	He is ____ dogs, so he never keeps any of them at home.	[afraid of]
[23596]	He invited some classmates to come to his party, but ____ came.	[few,不定代词]
[23592]	He has written many books, but ____ of them are good.	[few,不定代词]
[23573]	He has many friends at school, ____?	[反意疑问句]
[23568]	He has been ____ honest man in his life.	[honest,是元音开头的词]
[23563]	He has a lot of money, ____ he isn't happy.	[but,连词]
[23553]	He had to retire early ____ poor health.	[because of]
[23534]	He gave my sister ____ useful book yesterday.	[useful,是非元音开头的词]
[23529]	He found ____ very difficult to drive a car.	[find it+形容词+to do]
[23524]	He failed in the math test and looks sad. Let's ____.	[cheer up]
[23520]	He dressed ____ quickly ____ he put his shoes on the wrong feet.	[so...that,引导结果状语从句]
[23515]	He doesn't play the violin so ____ as his father.	[well,副词instances]
[23515]	He doesn't play the violin so ____ as his father.	[not so/as...as,引导比较状语从句]
[23500]	He didn't tell me ____.	[主句过去时]
[23486]	He didn't help me. ____, he laughed at me.	[instead,副词instances]
[23467]	He can't decide which to choose ____ there is no difference between them.	[because,引导原因状语从句]
[23458]	He bought a pair of new slippers and it ____ him 20 yuan.	[cost,pay,spend,take]
[23454]	He believed his lucky number was ten, so he decided to live on the ____ floor.	[the+序数词]
[23449]	He began to teach ____ English last year.	[himself,反身代词]
[23449]	He began to teach ____ English last year.	[teach sb sth]
[23445]	He asked me where the 2012 Olympics ____ held.	[主句过去时]
[23435]	He asked me ____ we could go to Beijing to watch the game by plane.	[if,宾语从句连接词]
[23426]	He and his wife ____ like singing.	[both,不定代词]
[23416]	He always brakes the rules in class, and it makes his teacher [see red.]	[情境语义]
[23402]	He ____ to save his pocket money for later use, but he spent it on a toy soon.	[promise to do]
[23397]	He ____ to Dongying many times, so he knows every corner of it.	[have been to,have gone to,have been in]
[23392]	He ____ the radio every morning.	[listen to]
[23387]	He ____ plenty of money to the people in the earthquake area ____.	[help…out]
[23387]	He ____ plenty of money to the people in the earthquake area ____.	[give away]
[23383]	He ____ our school for two weeks.	[for+一段时间]
[23368]	He ____ his umbrella to me yesterday, so don't get wet.	[borrow,lend]
[23363]	He ____ his teachers before he went to work in a faraway place.	[call on]
[23358]	He ____ his classmates.	[get along with]
[23349]	He ____ go out with his parents, but now he ____ staying at home alone.	[be used to doing]
[23349]	He ____ go out with his parents, but now he ____ staying at home alone.	[used to,情态动词]
[23344]	He ____ every Sunday volunteering in an old people's home.	[spend (in) doing]
[23339]	He ____ computer games when his father ____ back home.	[主句和从句,一般时和进行时]
[23329]	He ____ all his money ____ to charity after he died.	[give away]
[23324]	He ____ a piece of waste paper, and put it into the rubbish bag.	[pick up]
[23305]	Have you read today's newspaper? Not yet. Is there ____?	[anything+形容词]
[23305]	Have you read today's newspaper? Not yet. Is there ____?	[some,any]
[23267]	Have you ever known the mobile phone has a ____ history? It is said that the world's first mobile phone was made in the 1970s.	[a long history]
[23262]	Have ____ try, you are so close to the answer, the teacher said to Eric.	[have another try]
[23257]	Harry Potter is so interesting a book that lots of teenagers like to read ____.	[one,it]
[23247]	Hangzhou is ____ to hundreds of foreign friends who are working and studying here.	[be home to]
[23232]	Han Han's books are popular. They ____ by many teenagers.	[一般现在时的被动语态]
[23223]	Hainan has its own high-speed rail line. ____ the trains run on it!	[how引导的感叹句]
[23219]	Hainan celebrated (庆祝) her twentieth birthday ____ April 26, 2008．	[表示时间:at,in,on]
[23214]	Guo Yue did quite ____ at the World Table Tennis Championship (锦标赛), but Zhang Yining did even ____.	[even+形容词副词比较级]
[23214]	Guo Yue did quite ____ at the World Table Tennis Championship (锦标赛), but Zhang Yining did even ____.	[well,副词instances]
[23205]	Guiyang is a beautiful and clean city．There are many flowers on ____ sides of the streets．	[both,形容词instances]
[23200]	Guilin is famous ____ its beautiful scenery.	[be famous for]
[23191]	Great changes have taken place since we ____ E-Times. And the computer is widely used throughout the world.	[since+一般过去时,主句用现在完成时]
[23167]	Great changes ____ in Daqing since the 1990s.	[take place]
[23167]	Great changes ____ in Daqing since the 1990s.	[since+过去时间点,用于现在完成时]
[23162]	Granny often tells us ____ water in our daily life.	[tell…to do]
[23152]	Grandma is ill. I have to ____ her at home.	[look after]
[23147]	Grace is going to give much money to charity, ____ she is not rich enough.	[though,引导让步状语从句]
[23142]	Good to see you again. It's almost three years ____ we met last time.	[it is+时间段+since]
[23137]	Good news! There ____ fewer people catching this kind of illness now.	[There be A and B,主谓一致]
[23132]	Goldilocks decided ____ for a walk in the forest.	[decide to do]
[23123]	Go on with your English study. ____ is difficult if you put your heart into it.	[nothing,复合不定代词]
[23118]	Go downstairs, ____ stand in line on the playground as soon as possible.	[祈使句+and+陈述句]
[23113]	Give the girls two bananas ____.	[each,不定代词]
[23108]	Girl students in some schools are not allowed ____ long hair.	[be allowed to do]
[23095]	Get new knowledge by reviewing the old is a famous saying by Confucius (孔子). He was a great thinker ____ words still have a great effect on millions of people around the world today.	[whose,引导的定语从句]
[23085]	George reads the newspaper every morning. That's ____ habit.	[his,形容词性物主代词]
[23080]	Ge You is ____ popular film star in China, who likes listening to music.	[a]
[23060]	From March 23rd, 2013, anyone under the age of 14 ____ go into Disney's US parks alone.	[can't,mustn't]
[23055]	Friends are those ____ make you smile, always open their hearts to you and encourage you to succeed.	[who,引导的定语从句]
[23051]	Fred plays ____ piano after ____ supper every day.	[after supper]
[23051]	Fred plays ____ piano after ____ supper every day.	[piano,是乐器]
[23047]	Frank's mother told him ____ too much sugar because it is bad for his teeth.	[tell…to do]
[23042]	Franklin told them all ____ to be in Britain again.	[how,宾语从句连接词]
[23037]	Frank lives a simple life ____ he has lots of money.	[although,引导让步状语从句]
[23027]	France is ____ European country, India is ____ Asian country.	[an+元音开头的词]
[23027]	France is ____ European country, India is ____ Asian country.	[European,是非元音开头的词]
[23017]	For everyone's safety, we ____ always remember the law against driving after drinking.	[should,情态动词]
[23012]	For breakfast, I usually have ____ and two pieces of bread.	[一半，四分之一]
[23007]	For a long time they walked without saying ____ word. John was the first to break ____ silence.	[a]
[23007]	For a long time they walked without saying ____ word. John was the first to break ____ silence.	[the]
[23003]	Football is so exciting that ____ people in the world play it.	[millions of…]
[22998]	Football is a popular ____ around the world.	[情境语义]
[22993]	Food safety is important. Rules ____ to stop people from food pollution.	[must,被动语态]
[22978]	Flowers ____ along the road last year.	[一般过去时的被动语态]
[22973]	Five-year-old children are too young to go to school, ____?	[too…to,反意疑问句]
[22968]	Fish and chips ____ the most popular takeaway food in England.	[fish and chips,主谓一致]
[22954]	Father's Day is on ____ Sunday of June.	[the+序数词]
[22939]	Father's Day is ____ June 21 this year.	[表示时间:at,in,on]
[22929]	Father often tells me ____ too much time on computer games.	[tell…to do]
[22920]	Farmers have become ____ in our hometown in recent years.	[形容词副词比较级构成]
[22920]	Farmers have become ____ in our hometown in recent years.	[比较级 + and + 比较级]
[22915]	Excuse me. Read the text louder, please. I ____ hear you.	[can,be able to:辨析]
[22900]	Excuse me, would you mind ____ your voice down, please?	[mind doing]
[22891]	Excuse me, where did you buy the toy? I made it by ____.	[by oneself]
[22886]	Excuse me, sit. You ____ open the door before the train stops.	[can't,mustn't]
[22877]	Excuse me, sir. Could you tell me ____?	[where,宾语从句连接词]
[22877]	Excuse me, sir. Could you tell me ____?	[could you…,引导的主句]
[22868]	Excuse me, how can I get to the nearest bus stop? Go down this road. It's about ____ walk.	[名词复数的所有格]
[22863]	Excuse me, could you tell me ____?	[where,宾语从句连接词]
[22863]	Excuse me, could you tell me ____?	[when,宾语从句连接词]
[22858]	Excuse me, could you please tell me which gate ____?	[could you…,引导的主句]
[22843]	Everyone was asked to bring ____ empty bottle that day.	[an+元音开头的词]
[22834]	Everyone should save every drop of water. Remember to ____ the tap after you finish washing.	[turn off]
[22825]	Everyone of you is looking forward ____ getting a good result. Better think carefully before writing down your answers. Wish you success!	[look forward to]
[22820]	Everyone likes Kevin because he talks to others ____.	[politely,副词instances]
[22810]	Everyone in the hall knew me, but I did not know ____.	[them,人称代词宾格]
[22800]	Everyone except Tom and John ____ studying for the final test now.	[except,主谓一致]
[22800]	Everyone except Tom and John ____ studying for the final test now.	[everyone,复合不定代词]
[22796]	Everyone except Bill and Jim ____ there when the meeting began.	[everyone except,主谓一致]
[22786]	Everyone ____ I come from Sichuan. Actually, I came from Shandong.	[think+宾语从句]
[22781]	Everyone ____ go through the security check (安检) when entering the World Expo Park.	[must,should,ought to]
[22772]	Everybody knows it is a nice book to ____.	[不定式,句子成分]
[22757]	Every year, more than 70,000,000 sharks ____ for their fins (鱼翅).	[一般现在时的被动语态]
[22747]	Every year, ____ farmers go to big cities to work.	[thousands of…]
[22737]	Every year I ____ the garden competition too, and I always win a little prize for the worst garden in the town!	[enter for]
[22733]	Every year driving after drinking wine ____ a lot of traffic accidents.	[cause,及物动词]
[22728]	Every year a lot of tourists travel to Hainan, because it's ____ island.	[such+可数名词]
[22718]	Every time we perform well, our teacher, will say ____, You've done a good job!	[cheerfully,副词instances]
[22713]	Every time Sam leaves the room, he remembers to ____ the lights.	[turn off]
[22693]	Every morning I take a ____ to school.	[复合形容词]
[22688]	Even Tony's granddaughter, a five-year-old girl, asked him ____ smoking.	[ask…to do]
[22683]	Even teachers can't understand some expressions ____ their students use in daily life.	[that,引导的定语从句]
[22678]	Eton College in England was ____ in 1440 by King Henry VI to give free education to poor students.	[set up]
[22678]	Eton College in England was ____ in 1440 by King Henry VI to give free education to poor students.	[一般过去时的被动语态]
[22673]	Eric's never seen a three-D movie at the cinema, ____?	[never,反意疑问句]
[22669]	Eric has ____ e-dog and his name is Hobo.	[字母,读音以元音开头]
[22665]	Enough sleep is good for health. If you ____ for your favorite TV programs, you will feel sleepy.	[stay up]
[22661]	English people can't give up hamburgers or fried chicken because they're delicious. However, the French are changing. They can't interested in ____ food like before.	[fast food]
[22651]	English is my favorite subject, and I am good ____ it.	[be good at]
[22646]	English is ____ useful language. We should learn it well.	[useful,是非元音开头的词]
[22631]	Emma, can you introduce ____ to Alice? I want to meet her.	[me,人称代词宾格]
[22631]	Emma, can you introduce ____ to Alice? I want to meet her.	[introduce sb to]
[22626]	Emma always gets good grades in different exams because she is a ____ girl.	[hard-working]
[22617]	Either Jane or Steven ____ watching TV now.	[either…or,主谓一致]
[22612]	Eighteen kids died in the school bus accident in Gansu Province. It's ____ one that I have ever heard of.	[the+形容词最高级+名词,后接that定语从句]
[22602]	Edward, you have grown up. You should learn to make your own room ____.	[make+sth+形容词]
[22587]	Eating more vegetables is good for our health. I often eat lettuce, broccoli and ____.	[规则可数名词.复数]
[22577]	Eagle Father was so ____ with his son that he kept the four-year-old son running in the snow without clothes.	[be strict with]
[22567]	Each year quite a lot of food ____ around the world. It's really time for us to do something.	[food,不可数名词instances]
[22567]	Each year quite a lot of food ____ around the world. It's really time for us to do something.	[一般现在时的被动语态]
[22562]	Each time tourists travel to Beijing, they ____ the Forbidden City.	[一般将来时的被动语态]
[22562]	Each time tourists travel to Beijing, they ____ the Forbidden City.	[show sb around]
[22558]	Each of us is looking forward ____ a good result. Let's do it more carefully.	[look forward to doing]
[22553]	Each of the foreigners holds a fork in one hand and a knife in ____.	[one … the other ...]
[22548]	Each of the club members ____ready to help those who were in trouble.	[each,主谓一致]
[22543]	During World War II, a Jewish (犹太) lady was protected by a local family in Shanghai in her ____.	[in one's fifties]
[22538]	During this year's Reading Week, I read the most books in our class. No one read ____ than I.	[many->more,比较级]
[22518]	During the Spring Festival, the heavy snow stopped many people from ____.	[stop…from doing]
[22513]	During the seven-day May Day holiday, ____ families went sightseeing.	[thousands of…]
[22508]	During the entrance (升学) exams, there are ____ parents waiting for their children outside their test center.	[thousands of…]
[22503]	Dulangkou Middle School of Shandong Province (省) is so famous that ____ people come and visit it every day.	[hundreds of…]
[22493]	Drunk driving is against the law now. It ____ be forbidden.	[must,should,ought to]
[22488]	Drugs can do great harm (危害) not only to you but also to your family. You must be ____ them.	[be away from]
[22483]	Driving after drinking wine ____ in China.	[be allowed to do]
[22473]	Drivers ____ wear seat belts while their cars are running on the road.	[must,should,ought to]
[22468]	Dr. Bethune ____ working in spite of cutting his hand during an operation.	[continue to do,continue doing]
[22463]	Dr. Smith ____ London. He will come back in a month.	[have been to,have gone to,have been in]
[22458]	Dr. Green says that these children may find ____hard to think for themselves when they are older.	[find it+形容词+to do]
[22458]	Dr. Green says that these children may find ____hard to think for themselves when they are older.	[think for oneself]
[22448]	Doris lives on the ____ floor. It's too high, so she has to take a lift every day.	[the+序数词]
[22439]	Don't you know ____ girl under the tree? She's our teacher's daughter.	[the]
[22429]	Don't worry. Your package ____ here until you come back, please enjoy shopping here.	[can,被动语态]
[22425]	Don't worry. We are thinking about ____.	[if,宾语从句连接词]
[22421]	Don't worry. Think it over and we will ____ a good idea.	[come up with]
[22406]	Don't worry. I'm sure you will ____ your classmate if you are kind and friendly to them.	[get along with]
[22396]	Don't worry about me. I'm old enough to think for ____.	[think for oneself]
[22392]	Don't wear jeans, or ____ won't be allowed to go to the concert.	[you,人称代词主格]
[22392]	Don't wear jeans, or ____ won't be allowed to go to the concert.	[be allowed to do]
[22387]	Don't watch TV too long, ____ you can't finish your homework on time.	[祈使句+or+陈述句]
[22382]	Don't wait for people to be friendly, show them ____ a friendly person you are.	[what,宾语从句连接词]
[22362]	Don't try to do everything at once. Take it a bit ____.	[at a time]
[22358]	Don't throw waste paper everywhere. It's our duty to keep our school ____.	[keep+…+形容词]
[22353]	Don't talk to Simon like that. He is just ____ eleven-year-old boy.	[an+元音开头的词]
[22343]	Don't talk to anyone about the bad news, ____ not to my mother.	[especially,副词instances]
[22339]	Don't talk loudly at the meeting. If you ____, you will have to leave.	[条件状语从句,时态]
[22334]	Don't return the video to Peter, I ____ it.	[现在完成时]
[22324]	Don't put off today's work for tomorrow. I mean, today's work ____ today.	[must,should,ought to]
[22324]	Don't put off today's work for tomorrow. I mean, today's work ____ today.	[must,被动语态]
[22314]	Don't plan ____ driving a car in Tibet, ____?	[祈使句的反义疑问]
[22314]	Don't plan ____ driving a car in Tibet, ____?	[plan on doing]
[22309]	Don't meet an Internet friend alone, ____ something dangerous may happen to you.	[祈使句+or+陈述句]
[22300]	Don't make so much noise. The children ____ an English lesson.	[现在进行时]
[22275]	Don't just wait for other's help. God help those who help ____.	[help oneself]
[22266]	Don't just believe the advertisement. That medicine is ____ it says.	[not so/as...as,引导比较状语从句]
[22261]	Don't just believe the advertisement. That kind of camera is ____ as it says.	[not so/as...as,引导比较状语从句]
[22256]	Don't jump to a conclusion! Let's ____ the problem first.	[let,不定式]
[22241]	Don't forget to wash your hands ____ you have meals.	[before,引导时间状语从句]
[22236]	Don't forget to take your bag when you ____ the bus.	[get off]
[22236]	Don't forget to take your bag when you ____ the bus.	[时间状语从句用一般现在时表示将来]
[22232]	Don't forget to ____ the lights when you leave the classroom.	[turn off]
[22223]	Don't forget ____ the light before you leave the room.	[forget to do,forget doing]
[22223]	Don't forget ____ the light before you leave the room.	[turn off]
[22218]	Don't forget ____ an umbrella ____ you. It's going to rain.	[forget to do,forget doing]
[22218]	Don't forget ____ an umbrella ____ you. It's going to rain.	[with,介词]
[22213]	Don't eat the meat. It smells ____.	[smell+形容词]
[22208]	Don't drive so fast! We must slow down when we drive ____ the tunnel.	[位置移动:across,through]
[22203]	Don't drink the soup. It smells ____.	[smell+形容词]
[22183]	Don't ask him to study too late into the night. ____, he is only a small child.	[after all]
[22183]	Don't ask him to study too late into the night. ____, he is only a small child.	[情境语义]
[22174]	Don't ____ up English. It's very important.	[give up]
[22164]	Don't ____ today's work for tomorrow. Today's work must be done today.	[put off]
[22159]	Don't ____ to strangers on your way to and from school, mother often ____ to me.	[say,speak,talk,tell]
[22149]	Don't ____ the bus until it stops.	[get off]
[22144]	Don't ____ so often. It's bad for your health.	[stay up]
[22134]	Doing exercise ____ good for your health.	[v-ing作主语,主谓一致]
[22125]	Does the man need ____ operation at once, doctor Li?	[an+元音开头的词]
[22120]	Does anybody know if ____b____ to Shenzhen in the morning next Saturday?	[there be句型]
[22120]	Does anybody know if ____b____ to Shenzhen in the morning next Saturday?	[宾语从句语序]
[22115]	Do you want to be healthy? ____. Smiling can help you stay healthy.	[祈使句]
[22111]	Do you think which language is ____, Japanese or English?	[形容词和副词比较级]
[22107]	Do you think there ____ robots in People's homes in the future?	[there be句型]
[22107]	Do you think there ____ robots in People's homes in the future?	[宾语从句语序]
[22103]	Do you think English is ____ interesting subject?	[interesting,是元音开头的词]
[22093]	Do you say Yes or No to the discipline (纪律) that students are not allowed ____ at school?	[be allowed to do]
[22083]	Do you notice the strange noise of the computer? Maybe ____ is wrong with it.	[there is something wrong with]
[22073]	Do you like music ____ makes you relaxed?	[that,引导的定语从句]
[22068]	Do you know the man ____ is sitting behind Nancy?	[who,引导的定语从句]
[22064]	Do you know the girl ____ is singing in the classroom?	[who,引导的定语从句]
[22044]	Do you know a spaceship flies at about nineteen kilometers ____ second?	[a]
[22035]	Do you know ____ Lin Tao's father will come to school tomorrow?	[if,宾语从句连接词]
[22031]	Do you know ____ Guangzhou tomorrow?	[现在进行时]
[22031]	Do you know ____ Guangzhou tomorrow?	[whether,宾语从句连接词]
[22026]	Do you know ____ girl in green? She is our monitor.	[the]
[22011]	Do you hope to go ____?	[somewhere,anywhere,nowhere,everywhere:辨析]
[21993]	Do some exercise every day. I hope you are ____ good health.	[in…health]
[21988]	Do not use so much water. It's ____.	[情境语义]
[21968]	Did you know that the Earth is home to ____ animals?	[millions of…]
[21964]	Did you Know ____ at the bus stop? Maybe their teacher.	[whom,宾语从句连接词]
[21959]	Did you find ____ very interesting to play Yo-Yo?	[find it+形容词+to do]
[21955]	Did you find ____ very interesting to play volleyball?	[find it+形容词+to do]
[21945]	Did you borrow the comic book from the library?<\\n>Yes, I ____ it for three days. I'll return it this afternoon.	[for+一段时间]
[21940]	Did you borrow the bike ____ Jim?	[from,介词]
[21935]	Did Mary visit that old town by ____ last week?	[by oneself]
[21925]	Dick, it is the ____ time in ____ days that you're made the same mistake.	[基数词]
[21925]	Dick, it is the ____ time in ____ days that you're made the same mistake.	[the+序数词]
[21921]	Diaoyu Islands ____ China's inherent territory (固有领土) since ancient times.	[since+一般过去时,主句用现在完成时]
[21911]	Debbie is growing fast. She is even ____ than her mother.	[even+形容词副词比较级]
[21902]	Dear students, please read every sentence carefully. The more ____ you are, the ____ mistakes you'll make.	[the+比较级...the+比较级,引导比较状语从句]
[21897]	Dear students, please read every sentence carefully. ____ you are, ____ mistakes you'll make.	[the+比较级...the+比较级,引导比较状语从句]
[21893]	Dear friends, please read every sentence carefully. Details decide ____ or not. If you take it seriously, you'll achieve your goal.	[succeed<->success]
[21888]	David, get up early, ____ you'll catch the early bus.	[祈使句+and+陈述句]
[21883]	David wrote a story about teenage life, and it ____ as a book in 2003.	[come out]
[21878]	David was so excited at the good news that he could ____ say a word.	[hardly,频率副词]
'''
}
