package ots

class SampleData_QuestionMapping1 {

	String content ='''[Question ID]	题目	[知识点名称]
[43254]	Zhang Lili hardly had time to think of herself before she saved her students, ____?<\\n>No, she didn't. Her actions moved all of us. So she is regarded as The Prettiest Woman Teacher.	[hardly,反意疑问句]
[43194]	Your son has kept ____ for two hours. You'd better ask him to have a rest.	[keep doing]
[43117]	You'll do much better ____ you' re more careful with your spelling.	[if,引导条件状语从句]
[42248]	Work hard, ____ you won't catch up with the other students.	[祈使句+or+陈述句]
[42151]	Why not ____ your teacher for help when you can't finish ____ the story by yourself.	[finish doing]
[42151]	Why not ____ your teacher for help when you can't finish ____ the story by yourself.	[why,不定式]
[40975]	We have been good friends ____ we joined the same ping-pong team.	[since+一般过去时,主句用现在完成时]
[40728]	We are glad to see that Beijing is developing ____ these years than ever before.	[形容词副词比较级构成]
[40459]	Uncle Wang bought two ____ for me yesterday.	[bread,不可数名词instances]
[40459]	Uncle Wang bought two ____ for me yesterday.	[milk,不可数名词instances]
[40441]	Two places of interest in Beijing are well-known to people from home and abroad. One is the Great Wall, ____ is the summer palace.	[one … the other ...]
[40160]	Tom will make more progress if he ____ harder.	[条件状语从句,时态]
[39944]	Today computers ____ in both cities and towns.	[be used in]
[39944]	Today computers ____ in both cities and towns.	[一般现在时的被动语态]
[39911]	To make your own study plan is a good way to become a top student. After your plan ____, you should correct it from time to time, and then it will be more helpful.	[come out]
[39907]	To make our dreams come true, we are supposed to set goals ____ then try our best to achieve them.	[and then]
[39883]	To help others is more valuable than anything else. ____ we show our love and care to others, the world will be full of happiness and pleasure.	[as long as,引导条件状语从句]
[39799]	Threes and flowers ____ every year to make our country more beautiful.	[一般现在时的被动语态]
[39618]	This pen is Tom's. Give it to ____, please.	[him,人称代词宾格]
[38982]	There's a lot to do. We can't ____ to waste any time.	[can,afford]
[38778]	There is ____ old bridge near my house.	[an]
[38353]	The World Without Thieves is a very moving film. I ____ it twice already.	[already,用于现在完成时]
[38353]	The World Without Thieves is a very moving film. I ____ it twice already.	[twice,用于现在完成时]
[38061]	The theme park is about ____ ride from the museum. You should start out right now.	[名词复数的所有格]
[37131]	The number of the cars in our neighborhood is about eight ____, and ____ of them are new cars.	[hundred,基数词]
[37131]	The number of the cars in our neighborhood is about eight ____, and ____ of them are new cars.	[分数]
[36769]	The home-made ice-cream in this restaurant tastes ____. Would you like some?	[taste+形容词]
[36769]	The home-made ice-cream in this restaurant tastes ____. Would you like some?	[形容词instances]
[36750]	The heavy snow made the mountain climbers ____ on their way.	[make,不定式]
[36456]	The FIFA World Cup is ____ fantastic that a lot of people in the world are crazy (疯狂的) about it.	[so...that,引导结果状语从句]
[36088]	The British celebrate ____, which is one of their traditional festivals. Kids are excited about the presents hidden in the stockings (长筒袜).	[情境语义]
[35791]	The accident happened ____ a cold winter morning.	[表示时间:at,in,on]
[35603]	The ____ instructions (说明) on medicine are necessary for the sick. They explain ____ whether the medicine is out of date.	[副词的构成]
[35492]	Thank you for ____ my grandpa when I was away.	[look after]
[35492]	Thank you for ____ my grandpa when I was away.	[for,介词]
[35335]	Susan isn't here now. She ____ to England. She will come back next month.	[have gone to]
[35224]	Steve, could you tell me ____?	[could you…,引导的主句]
[35224]	Steve, could you tell me ____?	[when,宾语从句连接词]
[34618]	She didn't tell us ____ the day before.	[主句过去时]
[33895]	Please ____ the TV before you go to bed.	[turn off]
[33181]	Oh, you've got a new book. Is there ____ interesting?	[anything+形容词]
[33181]	Oh, you've got a new book. Is there ____ interesting?	[some,any]
[32789]	Nanjing isn't so large ____ Shanghai, however, it's the second ____ city in East China.	[not so/as...as,引导比较状语从句]
[32789]	Nanjing isn't so large ____ Shanghai, however, it's the second ____ city in East China.	[the+序数词+形容词最高级]
[32592]	My sister asked me ____ our bedroom yesterday.	[ask…to do]
[31791]	Mum, Love Me Once Again is a very moving film. I ____ it twice already.	[already,用于现在完成时]
[31791]	Mum, Love Me Once Again is a very moving film. I ____ it twice already.	[twice,用于现在完成时]
[31574]	Mr. Wang didn't tell us ____ ten years ago.	[主句过去时]
[31281]	Most students like the teachers ____ can understand them well.	[who,引导的定语从句]
[31222]	More buildings ____ in this city in 2010.	[一般将来时的被动语态]
[30234]	Look! There are many foreigners____ the Great Wall.	[there be句型,v-ing]
[29655]	Li Na had won the championship in France Tennis. All the Asians ____ her challenging spirits and excellent English.	[be proud of]
[29544]	Let's get some ____ about tourism on the Internet.	[information,不可数名词instances]
[29475]	Learning a foreign language needs a certain ____, no matter how easy it is.	[情境语义]
[29451]	Last winter it was very cold and ____ was a lot of snow in the north.	[there be句型]
[29447]	Last weekend, the Greens had great fun ____ at Water World.	[have fun doing]
[29442]	Last Thursday when I got to the station, I ____ I had left my ticket at home.	[情境语义]
[29437]	Last Sunday my aunt ____ at home with me. We were watching TV all day.	[一般过去时的时间状语]
[29432]	Last summer vacation, we ____ many photos when we had a trip to Dalian.	[一般过去时的时间状语]
[29423]	Last night, I ____ computer games when my mother came into my bedroom. You can't imagine how embarrassed I was then!	[主句和从句,一般时和进行时]
[29414]	Last night l didn't go to bed ____ the football game was over.	[not…until]
[29405]	Last night Dad and Mum didn't come back home ____ I finished my homework.	[not…until]
[29400]	Last month a new law ____ in China to stop people from smoking in public places.	[一般过去时的被动语态]
[29391]	Larry is ____ Jimmy. He is not the tallest boy in our class.	[not so/as...as,引导比较状语从句]
[29386]	Laptops are smaller and lighter so that they can be carried very ____.	[情境语义]
[29376]	Lao She is the ____ of Tea House (茶馆).	[情境语义]
[29371]	Lanzhou is the only capital city that the Yellow River, the second ____ river in China, passes through.	[序数词+形容词副词最高级]
[29366]	Landing on the moon sounds ____. I hope I can go there one day.	[sound+形容词]
[29353]	l don't know if Jack ____. If he ____, call me, please.	[一般将来时]
[29353]	l don't know if Jack ____. If he ____, call me, please.	[时间状语从句用一般现在时表示将来]
[29348]	Kunming is ____ city that thousands of people visit it every day.	[such...that,引导结果状语从句]
[29344]	Kids ____ not to play computer games too long.	[tell…to do]
[29344]	Kids ____ not to play computer games too long.	[宾语+不定式宾补,被动语态]
[29280]	Kate, could you tell me ____?	[when,宾语从句连接词]
[29072]	Jimmy's parents are teachers. ____ of them teaches Chinese. They both teach French.	[neither,不定代词]
[29058]	Jimmy can't buy any new books because he has ____ his money.	[run out of]
[29014]	Jim dislikes people ____ talk much but never do anything.	[who,引导的定语从句]
[29009]	Jim asked Li Ping ____his best wishes to everybody.	[ask…to do]
[28958]	Jenny! Do you know that one-third of the boys in our class ____ the singer Zhang Shaohan?	[分数作主语,主谓一致]
[28929]	Jenny is a quiet girl, and she likes playing ____ violin.	[violin,是乐器]
[28915]	Jenny goes to school on foot. It takes her about half ____ hour to get there.	[hour,是元音开头的词]
[28910]	Jenny goes to school ____ than any other student in her class.	[比较级+than any other]
[28895]	Jenny ____ with a Chinese family for two years. Now she's used to the life in China.	[for+一段时间,用于现在完成时]
[28890]	Jenny ____ in the chicken when you called her at 5 o'clock this afternoon?	[主句和从句,一般时和进行时]
[28885]	Jennifer takes a lot of exercise every day and she is always full of ____.	[be full of energy]
[28870]	Jean used to be crazy ____ computer games, but now she is interested ____ pop music and modern dance.	[crazy about]
[28870]	Jean used to be crazy ____ computer games, but now she is interested ____ pop music and modern dance.	[be interested in]
[28860]	Jason likes the ____ of the cake. It is a heart.	[情境语义]
[28855]	Jason is ____ than most of kids in my class. He is very active.	[than,引导比较状语从句]
[28840]	Jane, please turn off the lights ____ you leave the classroom.	[before,引导时间状语从句]
[28835]	Jane is one of the students in the class ____ have ever been to China.	[who,引导的定语从句]
[28830]	Jane is good at singing, and she ____ to sing in her room very often.	[be heard to do sth]
[28820]	Jane is getting fatter, so her father advises her ____ more exercise.	[advise…to do]
[28810]	Jane can speak English ____. She wants to work for the Special Olympic Games.	[well,副词instances]
[28785]	James, I'm too tired. Let's stop ____ a rest.	[stop to do,stop doing]
[28780]	James with the Greens ____ the White Tower Park if it ____ tomorrow.	[条件状语从句,时态]
[28780]	James with the Greens ____ the White Tower Park if it ____ tomorrow.	[with,主谓一致]
[28765]	Jackson ____ school two years ago and he ____ for two years.	[一般过去时的时间状语]
[28765]	Jackson ____ school two years ago and he ____ for two years.	[延续性动词,用于现在完成时]
[28761]	Jack's teacher asked him ____ off the lights after class.	[ask…to do]
[28751]	Jack, ____, or you will get heavier.	[祈使句+or+陈述句]
[28746]	Jack usually takes ____ walk for half an hour after work.	[take a walk]
[28736]	Jack took an interest in ____ ping-pong soon after he came to China.	[take an interest in doing]
[28732]	Jack likes reading a newspaper ____ he is having breakfast.	[while,引导时间状语从句]
[28722]	Jack is a little ____ than Peter.	[a little+形容词副词比较级]
[28717]	Jack is a famous writer. ____ new book is very popular.	[his,形容词性物主代词]
[28712]	Jack has ____.	[a piece of bread]
[28692]	I've read ____ sports news about the F1 race today.	[a piece of news]
[28688]	I've made some coffee. Would you like ____?That would be fine.	[coffee,不可数名词instances]
[28688]	I've made some coffee. Would you like ____?That would be fine.	[some+不可数名词]
[28683]	I've got two tickets for tonight's concert. One is for me, ____ is for you.	[one … the other ...]
[28678]	I've got several novels written by MoYan. You can borrow ____ if you like.	[one,不定代词]
[28673]	I've got quite a few dictionaries. Among them, this English dictionary is ____.	[形容词和副词最高级]
[28663]	I've already told him but he is still not clear ____ to do next.	[what to do]
[28653]	It's your ____ as a teacher to protect your students.	[It is our duty to do]
[28633]	It's very warm here in the room. You'd better ____ your coat.	[take off]
[28623]	It's very nice ____ you ____ my parents your best wishes.	[of引导不定式逻辑主语]
[28613]	It's very kind ____ you. Thank you for your help.	[of引导不定式逻辑主语]
[28608]	It's very important for us to learn how to learn by ____.	[by oneself]
[28603]	It's very hot here. Why not ____ your coat?	[dress,put on,wear]
[28593]	It's very friendly ____ him to help me when I'm in trouble.	[of引导不定式逻辑主语]
[28588]	It's very convenient ____ us to buy train tickets now because we can buy them either from the station or on the internet.	[for引导不定式逻辑主语]
[28578]	It's twelve o'clock at night, but he is ____ working.	[still,并列结构的连词]
[28563]	It's too late to invite any more people. ____, you know how Tim hates parties.	[besides,副词instances]
[28553]	It's too bright and sunny. Why not ____ your sun glasses?	[dress,put on,wear]
[28548]	It's time to say goodbye to my school. I'll always remember the people ____ have helped me.	[who,引导的定语从句]
[28538]	It's time for sports. Let's ____ bowling, shall we?	[let,不定式]
[28533]	It's time for sports! ____ your sports shoes, please!	[dress,put on,wear]
[28523]	It's time for CCTV news. Let's ____ the TV and watch it.	[turn on]
[28509]	It's sunny. Let's go sighting ____ watching TV in our hotel room.	[instead of]
[28500]	It's so brave ____ the soldier to save the boy's life.	[of引导不定式逻辑主语]
[28490]	It's six o'clock now. My parents ____ me outside the school.	[现在进行时]
[28485]	It's said that smoking won't be ____ in indoor public places or workplaces in China.	[be allowed to do]
[28480]	It's said that more than 100 ____ will attend this meeting in Shanghai.	[woman teacher,复数]
[28466]	It's said that ____ apple ____ day keeps the doctor away.	[apple,是元音开头的词]
[28461]	It's said in the newspaper that 215 more new schools ____ in Zhengzhou by 2020.	[一般将来时的被动语态]
[28451]	It's reported that President Xi Jinping arrived ____ Moscow ____ March 22nd, paying a three-day visit to Russia.	[arrive in]
[28451]	It's reported that President Xi Jinping arrived ____ Moscow ____ March 22nd, paying a three-day visit to Russia.	[表示时间:at,in,on]
[28432]	It's raining outside. Take your umbrella, ____ you'll get wet.	[祈使句+or+陈述句]
[28427]	It's raining heavily outside. Why don't you ____ your raincoat?	[dress,put on,wear]
[28418]	It's quite exciting ____ me ____ the Internet.	[for引导不定式逻辑主语]
[28408]	It's quite common in Britain to say Thank you to the drivers ____ people get off the bus.	[when,引导时间状语从句]
[28388]	It's not polite to speak loudly ____ you are having a meal.	[while,引导时间状语从句]
[28378]	It's not good to be late ____ school.	[be late for]
[28373]	It's not always necessary to look up the words ____ the dictionary while reading. Sometimes we need to guess.	[in,介词]
[28354]	It's nice of you ____ me with my maths.	[of引导不定式逻辑主语]
[28350]	It's nice ____ you to ____ so much time showing me around your school.	[cost,pay,spend,take]
[28350]	It's nice ____ you to ____ so much time showing me around your school.	[of引导不定式逻辑主语]
[28345]	It's much ____ to have a small lovely room than a big cold one.	[much+形容词副词比较级]
[28316]	It's hot. Let's have some ____.	[情境语义]
[28311]	It's hard to keep the house ____ with three kids.	[keep+…+形容词]
[28306]	It's half past four in the afternoon. The students are playing ____ basketball now.	[basketball,是球类棋类]
[28302]	It's going to rain. Don't forget ____ an umbrella.	[forget to do,forget doing]
[28302]	It's going to rain. Don't forget ____ an umbrella.	[bring,carry,pass,take,fetch]
[28297]	It's getting warmer and warmer ____ spring, and plants start growing.	[表示时间:at,in,on]
[28293]	It's getting dark. I ____ go home now.	[must,have to:辨析]
[28288]	It's Father's Day. I'll get ____ tie for my father.	[a]
[28278]	It's common knowledge that black tea ____ in China more than 600 years ago.	[一般过去时的被动语态]
[28270]	It's cold outside. Why ____ stay at home?	[why,不定式]
[28261]	It's bad for health to hurry to move into a house ____ has new furniture in it.	[that,引导的定语从句]
[28251]	It's a nice house ____ it hasn't got a garden.	[but,连词]
[28236]	It's a good habit ____ breakfast every day.	[不定式,it,主语]
[28231]	It's a good ____ to have breakfast every morning.	[情境语义]
[28226]	It's a custom in China to have some tea or other drinks before the meal ____.	[一般现在时的被动语态]
[28222]	It's ____ to travel from Taiyuan to Taiwan now because the planes can get there directly. You can visit the island if you like.	[情境语义]
[28218]	It's ____ to teach a man to fish than to give him fish.	[情境语义]
[28213]	It's ____ to read the map before you travel to a new place.	[情境语义]
[28208]	It's ____ to listen to light music when you feel tired.	[relaxing,-ing形式的形容词]
[28203]	It's ____ rather cold. I shall put my jacket on.	[get+形容词]
[28198]	It's ____ pleasure to see ____ sun rising in ____ east.	[a]
[28198]	It's ____ pleasure to see ____ sun rising in ____ east.	[in the east]
[28198]	It's ____ pleasure to see ____ sun rising in ____ east.	[sun,独一无二的事物]
[28173]	It will be hard for us to get up in the morning if we ____ to bed too late.	[时间状语从句用一般现在时表示将来]
[28168]	It will be a long time ____ Peter ____ his work.	[before,引导时间状语从句]
[28168]	It will be a long time ____ Peter ____ his work.	[时间状语从句用一般现在时表示将来]
[28159]	It will be ____ if you buy a return ticket on the train when you travel in England.	[much+形容词副词比较级]
[28155]	It will ____ them several years to learn English well.	[cost,pay,spend,take]
[28151]	It will ____ much time if we drive instead of walking.	[cost,pay,spend,take]
[28151]	It will ____ much time if we drive instead of walking.	[save time]
[28146]	It was very hard for me to make a ____, but I decided to leave my job.	[make a decision]
[28137]	It was such a funny show that people couldn't help ____ again and again.	[cannot help doing]
[28132]	It was so noisy outside last night that I could ____ fall asleep.	[hardly,频率副词]
[28122]	It was reported that nine Chinese people ____ in a balloon crash (坠毁) in Egypt on February 26, 2013.	[一般过去时的被动语态]
[28112]	It was a difficult time for the quake-hit victims in Ya'an, but they didn't ____ hope.	[give up]
[28107]	It was a different time, but we never ____ hope.	[give up]
[28102]	It was ____ that he had to ask for help.	[work,不可数名词instances]
[28102]	It was ____ that he had to ask for help.	[such...that,引导结果状语从句]
[28092]	It was ____ lovely weather ____ we decided to spend the day on the beach.	[weather,不可数名词instances]
[28092]	It was ____ lovely weather ____ we decided to spend the day on the beach.	[such...that,引导结果状语从句]
[28087]	It usually ____ Mum about half an hour to cook supper.	[cost,pay,spend,take]
[28082]	It took us twelve people three weeks to build the house.<\\n>They said they could finish it with ____ people and in ____ time.	[little->less,比较级]
[28077]	It took me two weeks ____ reading the novels written by Guo Jingming.	[不定式,it,主语]
[28077]	It took me two weeks ____ reading the novels written by Guo Jingming.	[finish doing]
[28067]	It takes us about ____ hour to get to the Yangzhou-Taizhou Airport from Yangzhou by ____ bus.	[by bus]
[28062]	It seems that the aged people ____ the H7N9 more easily from the recent cases.	[pick up]
[28057]	It seems that it is going to rain. You'd better ____ the windows open when you leave the house.	[had better,不定式]
[28052]	It' s a good habit ____ breakfast every day.	[不定式,it,主语]
[28052]	It' s a good habit ____ breakfast every day.	[have breakfast]
[28048]	It rained heavily, so we ____ stay at home watching TV or surfing the Internet all day.	[must,have to:辨析]
[28044]	It rained heavily this morning, but ____ of my classmate were late for school.	[none of+复数名词,主谓一致]
[28039]	It isn't warm today, ____ the sun is shining.	[although,引导让步状语从句]
[28029]	It is very important ____ people to have food and water every day.	[for引导不定式逻辑主语]
[28024]	It is true that knowledge ____ rather than being taught.	[一般现在时的被动语态]
[28009]	It is the largest ____ in our city. You can borrow all kinds of books there.	[情境语义]
[28001]	It is terrible. It's raining so ____ that we can ____ go out.	[hard,hardly区别]
[27996]	It is said that the football match may be ____ because of the bad weather.	[put off]
[27991]	It is said that many animals are in danger. So we need to ____ them better.	[情境语义]
[27966]	It is reported that people throw ____ plastic bags along this street every day.	[hundreds of…]
[27962]	It is reported that it would take a person 21 days ____ a good habit.	[get into]
[27957]	It is reported that Daimiao Culture Square ____ in Taian next year.	[一般将来时的被动语态]
[27947]	It is reported that a small plane from South Africa crashed (坠毁) northwest of Changsha ____ May 28, 2004.	[表示时间:at,in,on]
[27942]	It is reported that a lot of adults take lessons online ____ further education.	[for,介词]
[27937]	It is really cool to realize your dream ____ great effort.	[through,介词]
[27928]	It is polite ____ a gift when you visit somebody for the first time.	[不定式,it,主语]
[27923]	It is over ____ from Shijiazhuang to Beijing.	[名词复数的所有格]
[27918]	It is our hope that we can live in a ____ world and say goodbye to the wars for ever.	[情境语义]
[27914]	It is our duty ____ our hometown clean and beautiful. We must do something for it.	[It is our duty to do]
[27890]	It is impolite to leave ____ the meeting finishes.	[before,引导时间状语从句]
[27880]	It is good for the fish to have ____ water plants in the tank (鱼缸) to keep the water pure.	[辨析:few,a few]
[27870]	It is easy to find a good hotel in our city ____ we have many of them here.	[because,引导原因状语从句]
[27850]	It is a good habit to go to ____ bed early and get up early.	[go to bed]
[27845]	It is a good habit to ____ all your things in correct places.	[put away]
[27840]	It is a good habit that we should never ____ today's work till tomorrow.	[put off]
[27835]	It is a good habit of ____ to read a few lines before going to bed.	[a/an+可数名词+of+名词性物主代词]
[27830]	It is a good habit for us that we should never ____ today's work till tomorrow.	[put off]
[27821]	It is ____ to teach a kid the way to solve a problem than tell him or her the solution directly.	[than,引导比较状语从句]
[27812]	It is ____ that Mr. Gao sailed across the world by himself ____ within about 130 days.	[情境语义]
[27807]	It doesn't look like rain, so you ____ bring your umbrella with you.	[need,情态动词]
[27797]	It ____ Yang Liwei about 21 hours ____ the earth 14 times in his spaceship.	[不定式,it,主语]
[27797]	It ____ Yang Liwei about 21 hours ____ the earth 14 times in his spaceship.	[cost,pay,spend,take]
[27792]	It ____ usually ____ at this time of year, but today it is raining heavily.	[usually,用于一般现在时]
[27787]	It ____ to drive after drinking wine.	[be allowed to do]
[27783]	It ____ them several years to build the Qinghai-Tibet Railway.	[cost,pay,spend,take]
[27778]	It ____ ten years since we last ____ in Beijing.	[it is+时间段+since]
[27773]	It ____ several years to build Qinghai-Tibet Railway, the highest railway in the world.	[cost,pay,spend,take]
[27768]	It ____ Mr. Green an hour to fix up his bicycle yesterday.	[cost,pay,spend,take]
[27764]	It ____ Mike twenty minutes to walk to school every day.	[cost,pay,spend,take]
[27749]	It ____ heavily when I left the cinema.	[主句和从句,一般时和进行时]
[27745]	It ____ hard outside. You have to stay at home.	[现在进行时]
[27740]	It ____ be Nosy. She ____ to the doctor's.	[can't,mustn't]
[27740]	It ____ be Nosy. She ____ to the doctor's.	[have been to,have gone to,have been in]
[27735]	Is today's football match worth ____?	[be worth doing]
[27725]	Is this research center ____ the foreign guests visited last week?	[one,后接that定语从句]
[27720]	Is this kind of pet ____ a pet dog these days?	[as...as,引导比较状语从句]
[27720]	Is this kind of pet ____ a pet dog these days?	[friendly,-ly结尾的形容词]
[27715]	Is this a photo of your daughter? She looks ____ in the pink dress!	[lovely,-ly结尾的形容词]
[27710]	Is there any difference between your idea and ____?	[his,名词性物主代词]
[27705]	Is there ____ with your bike?	[there is something wrong with]
[27695]	Internet bars mustn't let people under 18 in or let anybody ____ bad things.	[let,不定式]
[27685]	In Britain, you ____ be 18 if you want to drive a car.	[must,情态动词]
[27676]	In western countries ____ is the most important festival, just like Spring Festival in China.	[情境语义]
[27671]	In this exam, you're asked to write a composition of about ____.	[复合形容词]
[27666]	In the West, people like to finish a meal with ____, for instance, dessert.	[something+形容词]
[27661]	In the United States, 27% of people ____ the ages of 18~34 live with their parents.	[between,介词]
[27651]	In the talent show, I performed well and Ann did even ____.	[even+形容词副词比较级]
[27646]	In the piano contest, my brother didn't play well and I did ____.	[even+形容词副词比较级]
[27641]	In the past few years, thousand of films ____ all over the world.	[in the past few years,用于现在完成时]
[27641]	In the past few years, thousand of films ____ all over the world.	[现在完成时的被动语态]
[27636]	In the past few years there ____ great changes in my hometown.	[in the past few years,用于现在完成时]
[27631]	In the old days, they ____ in the factory from morning to evening.	[be made to do sth]
[27626]	In the future, there isn't going to ____ enough space to ____ on the earth.	[There is going to be]
[27626]	In the future, there isn't going to ____ enough space to ____ on the earth.	[不定式,定语]
[27602]	In summer, food goes bad easily ____ it is put in the refrigerator.	[unless,引导条件状语从句]
[27597]	In some western countries shops are closed ____ weekends.	[at weekends]
[27592]	In some places there are watchtowers on the beaches to ____ people about sharks in the water.	[情境语义]
[27587]	In recent years, the economy of our country ____ rapidly.	[in recent years,用于现在完成时]
[27577]	In our school library there ____ a number of books on science, and in these years the number of them ____ growing larger and larger.	[the number of+复数名词,主谓一致]
[27577]	In our school library there ____ a number of books on science, and in these years the number of them ____ growing larger and larger.	[There be A and B,主谓一致]
[27572]	In our hospital, the number of women doctors ____ larger and larger.	[the number of+复数名词,主谓一致]
[27567]	In our city, ____ middle school students want to work as a teacher in the future.	[thousands of…]
[27558]	In order to speak English better, we ____ be afraid of losing face. Because the most important thing is to practice. Remember, practice makes perfect.	[should,情态动词]
[27553]	In order to protect the environment, people in Japan have to ____ for their trash.	[cost,pay,spend,take]
[27548]	In order to keep healthy, you should eat ____ fast food, ____ fresh vegetables and take enough exercise.	[little->less,比较级]
[27548]	In order to keep healthy, you should eat ____ fast food, ____ fresh vegetables and take enough exercise.	[many->more,比较级]
[27539]	In order to finish the project, we'll have to work ____ hours a day.	[基数词+more]
[27534]	In order to find ____ better job, she planned to learn ____ second foreign language.	[a+序数词]
[27529]	In order to eat safely, I think we ____ make some food by ourselves instead of buying some.	[had better,不定式]
[27525]	In order to balance the study and entertainments, every student is supposed to plan the time ____.	[情境语义]
[27506]	In many places in China, the old over 90 ____ not only by their family but also by the government.	[the+形容词,主谓一致]
[27502]	In many countries, teenagers under 18 should not ____ to Internet bars.	[should,被动语态]
[27493]	In July, 2012, the 30th Olympic Games ____ in London.	[一般将来时的被动语态]
[27478]	In fact, China is one of the thirstiest countries ____ it has the world's third largest water supply (可用量).	[though,引导让步状语从句]
[27469]	In England you must drive on the ____ side of the road.	[opposite,形容词instances]
[27465]	In competition, as in life, you ____ not always win.	[may,情态动词]
[27456]	In China students ____ greet the teachers when classes began.	[be supposed to do]
[27452]	In Changsha, it's hot in July, but it's even ____ in August.	[even+形容词副词比较级]
[27448]	In April, the weather in some places in Shanxi was really changeable. People still remember they have ____ four seasons in a week.	[情境语义]
[27444]	In American, most people always ____ after meal in a restaurant while some of us don't care about others' service much.	[情境语义]
[27439]	I'm waiting for my friend. ____, I'll go shopping alone.	[条件状语从句,时态]
[27424]	I'm very glad I have my own room in my house. I ____ do what I want in it.	[can,情态动词]
[27409]	I'm taller than Bill, but I sit ____ him.	[in front of,复合介词]
[27404]	I'm talking to you, Jack. Please listen to ____ carefully.	[me,人称代词宾格]
[27394]	I'm sure you know the difference ____ look for and find.	[between A and B]
[27374]	I'm sure that stricter rules to control cigarette smoking ____ very soon.	[一般将来时的被动语态]
[27355]	I'm sorry. You speak so ____ and I can't catch what you said.	[情境语义]
[27350]	I'm sorry, I didn't ____ you clearly. Would you say it again?	[情境语义]
[27346]	I'm sorry to have kept you ____ for almost two hours.	[keep…doing]
[27341]	I'm sorry I'm late. I should get here 10 minutes ____.	[形容词和副词比较级]
[27341]	I'm sorry I'm late. I should get here 10 minutes ____.	[数词+名词+形容词]
[27336]	I'm sorry I left the book at home. I ____ it here tomorrow, I promise.	[tomorrow,用于一般将来时]
[27331]	I'm sorry ____ you that you didn't pass the maths exam.	[be+形容词+不定式]
[27316]	I'm really [anxious], because my backpack is lost.	[worried<->anxious]
[27311]	I'm reading now. Please tell him ____ the TV a bit.	[tell…to do]
[27311]	I'm reading now. Please tell him ____ the TV a bit.	[turn down]
[27306]	I'm not sure when the plane will ____ and when it will land.	[take off]
[27301]	I'm not sure if he ____ or not. If he ____, I'll telephone you.	[条件状语从句,时态]
[27297]	I'm not sure about the meaning of the word. You'd better look it up in a(n) ____.	[情境语义]
[27292]	I'm not sure about the meaning of the word. You'd better look it up in a ____.	[情境语义]
[27288]	I'm not sure ____ next week.	[whether,宾语从句连接词]
[27278]	I'm not hungry because I ____ lunch already.	[already,用于现在完成时]
[27273]	I'm not good at English. I think it's not easy ____ foreign language well.	[不定式,it,主语]
[27253]	I'm just going to ____ market, mum. Do you want ____?	[the]
[27253]	I'm just going to ____ market, mum. Do you want ____?	[something,复合不定代词]
[27228]	I'm going to the supermarket to buy some ____ this afternoon.	[milk,不可数名词instances]
[27209]	I'm going to start a club to help students ____ are not interested in schoolwork.	[who,引导的定语从句]
[27194]	I'm going to be late for work. There're ____ buses on this route (线路).	[too many]
[27184]	I'm glad to find that many trees ____ in our city last year.	[一般过去时的被动语态]
[27174]	I'm feeling much better now so you ____ call the doctor.	[need,情态动词]
[27169]	I'm expecting a pet dog for long, but mom has no time to buy ____ for me.	[one,it]
[27164]	I'm expecting a digital camera for long, but dad has no time to buy ____ for me.	[one,it]
[27149]	I'm afraid that no one knows ____.	[who,宾语从句连接词]
[27134]	I'm ____ building a new zoo because I think zoos are terrible places for animals to live in.	[be against doing]
[27115]	I'll take ____ of the cameras, one is for my brother, the other is for Jim.	[all,both]
[27110]	I'll park the car at Pacific Place, ____ the car park there is full.	[unless,引导条件状语从句]
[27105]	I'll never forget the lesson ____ last year.	[that,引导的定语从句]
[27100]	I'll never forget the day ____ the great scientist came to our school and gave us a speech.	[when,引导的定语从句]
[27096]	I'll move the table away. It takes up ____.	[room,不可数名词instances]
[27096]	I'll move the table away. It takes up ____.	[too much]
[27091]	I'll go to visit my aunt in England ____ the summer holidays start..	[as soon as,引导时间状语从句]
[27086]	I'll go to the zoo if it ____ tomorrow.	[条件状语从句,时态]
[27071]	I'll go out for a walk after supper if it ____ rain.	[条件状语从句,时态]
[27066]	I'll give it to Jim as soon as I ____ him tomorrow.	[时间状语从句用一般现在时表示将来]
[27056]	I'll do it better if the teacher ____ me another chance.	[条件状语从句,时态]
[27022]	If you work hard, you'll get ____ A in the exam.	[字母,读音以元音开头]
[27017]	If you watch carefully, you can see ____ the man does the trick with the cards.	[how,宾语从句连接词]
[27013]	If you want to take care of your health, you should ____ junk food．	[stay away from]
[26998]	If you want to get more information about English learning, please visit our ____: www.yyxx.com.	[情境语义]
[26993]	If you want to change the world, you have to ____ yourself first.	[情境语义]
[26988]	If you want to buy this dress, you'd better ____ first to make sure it fits you.	[情境语义]
[26978]	If you want to be thinner and healthier, you should eat ____ food and take ____ exercise.	[little->less,比较级]
[26978]	If you want to be thinner and healthier, you should eat ____ food and take ____ exercise.	[much->more,比较级]
[26973]	If you want people to treat you nicely, then you have to treat ____ nicely, too.	[them,人称代词宾格]
[26968]	If you try to sit on two chairs, you will fall ____ them. For life, you must choose one chair.	[between,介词]
[26964]	If you still have any other questions, please ____ your hands.	[put up]
[26959]	If you sit in a chair ____ a long time, your back may begin to hurt.	[for+一段时间]
'''
}
