package ots

class SampleData_QuestionMapping7 {

	String content ='''[14264]	— What do you think your life will be like ____ twenty years?<\\n>— Yeah. I have thought about it ____ three years.	[表示时间:during,for]
[14260]	— What do you think of Zhou Libo?<\\n>— I think he does well ____ talk shows. Many people like him.	[do well in…]
[14256]	— What do you think of your new neighbor?<\\n>— I don't think he is so ____ as the old one.	[not so/as...as,引导比较状语从句]
[14256]	— What do you think of your new neighbor?<\\n>— I don't think he is so ____ as the old one.	[friendly,-ly结尾的形容词]
[14251]	— What do you think of your last trip?<\\n>— I had a very scary ____ in the mountains. I won't go there again.	[情境语义]
[14241]	— What do you think of Tom's speaking?<\\n>— No one does ____ in our class.	[形容词和副词比较级]
[14237]	— What do you think of this skirt?<\\n>— It's beautiful and it fits me well, ____ I like it very much.	[so,连词]
[14232]	— What do you think of these two books?<\\n>— ____ of them are interesting. And I've read them several times.	[both,不定代词]
[14222]	— What do you think of the zongzi?<\\n>— They ____ delicious. Are they made by your mother?	[taste+形容词]
[14212]	— What do you think of the traffic in our city?<\\n>— lt's ____ than it used to be, but there's still a long way to go.	[情境语义]
[14207]	— What do you think of the sweater?<\\n>— It's too ____, and I don't have enough money to buy it.	[情境语义]
[14202]	— What do you think of the price of gold in the world?<\\n>— Nowadays it is getting much ____ than before.	[much+形容词副词比较级]
[14187]	— What do you think of the movie by Zhao Wei?<\\n>— Terrific. I like ____ very much.	[one,it]
[14178]	— What do you think of the house?<\\n>— It is much more beautiful than ____.	[ours,名词性物主代词]
[14169]	— What do you think of the film?<\\n>— It's so ____ that I want to see it again.	[情境语义]
[14164]	— What do you think of the film you saw yesterday?<\\n>— Oh! It's one of ____ films I've ever seen.	[the+形容词最高级+名词]
[14159]	— What do you think of the film Rush Hour?<\\n>— ____, but someone thinks it's ____.	[boring,-ing形式的形容词]
[14159]	— What do you think of the film Rush Hour?<\\n>— ____, but someone thinks it's ____.	[形容词副词+enough]
[14154]	— What do you think of the film Avatar?<\\n>— It's fantastic. The only pity is that I ____ the beginning of it.	[一般过去时]
[14150]	— What do you think of the entertainment show you saw last night?<\\n>— It's so ____ that I want to see it again.	[exciting,-ing形式的形容词]
[14145]	— What do you think of the dress?<\\n>— Wonderful. I don't think I can find a ____ one.	[形容词和副词比较级]
[14140]	— What do you think of the documentary A Bite of China?<\\n>— ____. It has attracted lots of TV audiences.	[情境语义]
[14130]	— What do you think of the 3D film the Titanic last night?<\\n>— It was ____. I enjoyed it a lot.	[情境语义]
[14126]	— What do you think of Sanya?<\\n>— Oh, it's a beautiful city, I ____ there for several times.	[have been to]
[14122]	— What do you think of Mike?<\\n>— He is ____ honest boy.	[honest,是元音开头的词]
[14117]	— What do you think of math, Lily?<\\n>— I think it's ____ than English.	[形容词和副词比较级]
[14109]	— What do you think of his speech?<\\n>— Oh, no one does ____.	[形容词和副词比较级]
[14105]	— What do you think of her spoken English?<\\n>— Oh, no one speaks ____.	[形容词和副词比较级]
[14095]	— What do you think of Eat-up Campaign (光盘行动)?<\\n>— I think it's really necessary. It is reported that the food that Chinese people every year ____ is enough to feed 200 million people for a year.	[情境语义]
[14085]	— What do you often do after class?<\\n>— I often play basketball ____ my friends.	[with,介词]
[14081]	— What do you often do ____ classes to relax?<\\n>— Listen to music or walk around the school.	[between,介词]
[14076]	— What do you often do ____ classes to relax yourself?<\\n>— Take walks with my friends.	[between,介词]
[14066]	— What do you know about Walt Disney?<\\n>— He ____ cartoons for newspapers.	[情境语义]
[14057]	— What do you call your father's sister?<\\n>— ____.	[情境语义]
[14052]	— What did your teacher say this morning?<\\n>— She told us ____.	[that,宾语从句连接词]
[14047]	— What did your parents think about your decision?<\\n>— They always let me do ____ I think I should.	[what,宾语从句连接词]
[14028]	— What did your dad tell you, my baby?<\\n>— He said the sun ____ in the east.	[从句表示:客观真理,自然现象或习惯动作]
[14018]	— What did you have ____ breakfast this morning?<\\n>— I had some bread and a glass ____ milk.	[for,介词]
[14018]	— What did you have ____ breakfast this morning?<\\n>— I had some bread and a glass ____ milk.	[a glass of]
[14014]	— What did you get ____ your mother ____ Mother's Day?<\\n>— A beautiful card and a scarf.	[表示时间:at,in,on]
[14014]	— What did you get ____ your mother ____ Mother's Day?<\\n>— A beautiful card and a scarf.	[for,介词]
[14009]	— What did you get ____ your birthday, Tony?<\\n>— An ipad3 from my aunt.	[for,介词]
[13999]	— What did you do yesterday evening, Gina?<\\n>— I ____ Titanic 3D in the City Cinema.	[一般过去时]
[13969]	— What did the teacher say just now?<\\n>— Sorry. I didn't catch it. I ____ something else.	[现在进行时]
[13914]	— What did Jack ask you just now?<\\n>— He wanted to know how long ____ when I reached the cinema.	[过去完成时]
[13909]	— What did her father ask?<\\n>— He asked ____ yesterday.	[if,宾语从句连接词]
[13900]	— What did Allen say just now?<\\n>— Sorry, I don't know. I ____ a phone.	[过去进行时]
[13895]	— What day is it today?<\\n>— It's Monday, and it's my ____ birthday.	[形容词性物主动词+序数词]
[13885]	— What can we do for the people in Yushu, Qinghai Province?<\\n>— Why not ____ some clothes?	[why,不定式]
[13885]	— What can we do for the people in Yushu, Qinghai Province?<\\n>— Why not ____ some clothes?	[give away]
[13880]	— What can I do for you?<\\n>— I'm looking at that dress. It looks nice. May I ____?	[try on]
[13871]	— What can I do for you, madam?<\\n>— ____ pair of shoes, please.	[a pair of shoes]
[13866]	— What beautiful shoes you're wearing! They must be expensive.<\\n>— No. They only ____10 yuan.	[cost,pay,spend,take]
[13861]	— What bad weather!<\\n>— Yes. The radio says it will be even ____ later on.	[even+形容词副词比较级]
[13856]	— What are you looking for?<\\n>— I'm looking for the ring ____ my husband bought me last year.	[that,引导的定语从句]
[13851]	— What are you looking for?<\\n>— I'm looking for the pen ____ my father gave me last week.	[which,引导的定语从句]
[13847]	— What are you looking for?<\\n>— I'm looking for the pen ____ I bought yesterday.	[which,引导的定语从句]
[13843]	— What are you looking for?<\\n>— I'm looking for the jacket ____ I bought yesterday.	[which,引导的定语从句]
[13833]	— What are you going to do when you grow up?<\\n>— A singer, but my parents wish me ____ a teacher.	[wish…to do]
[13829]	— What are you going to do this weekend?<\\n>— I'd like ____ my parents.	[would like to do]
[13820]	— What are you going to do this afternoon?<\\n>— We are going to have a football match if it ____.	[时间状语从句用一般现在时表示将来]
[13815]	— What are you going to do for the School Day?<\\n>— We'll ____ a new play.	[put on]
[13810]	— What are you going to be when you grow up, Sam?<\\n>— ____ teacher like you.	[a]
[13806]	— What are you doing?<\\n>— I'm ____ TV.	[现在进行时]
[13802]	— What are you doing?<\\n>— I'm ____ my English book.	[look for]
[13797]	— What are you doing, Simon?<\\n>— I have finished my homework, and now I ____ the computer games.	[现在进行时]
[13758]	— What are the ____ doing there?<\\n>— They are busy ____ their science experiment.	[busy (in) doing]
[13758]	— What are the ____ doing there?<\\n>— They are busy ____ their science experiment.	[复合名词.复数]
[13753]	— What are on show in the museum?<\\n>— Some photos ____ by the children of Yushu, Qinghai.	[v-ed]
[13743]	— What are Johnson's family like?<\\n>— ____?	[what…like]
[13738]	— What about this black coat, sir?<\\n>— It ____ nice. I'll take it.	[look+形容词]
[13734]	— What about having a drink?<\\n>— ____.	[what about…,应答句]
[13729]	— What about going to the South Lake for a picnic next weekend?<\\n>— OK. But I'm not sure ____ it will rain.	[whether,宾语从句连接词]
[13725]	— What about going to JiuLi Lake this summer vacation?<\\n>— ____.	[what about…,应答句]
[13720]	— What about ____ speech?<\\n>— It was too tiring, you know, ____ speech for me?	[a]
[13720]	— What about ____ speech?<\\n>— It was too tiring, you know, ____ speech for me?	[the]
[13710]	— What a strong sandstorm (沙尘暴)! ____?<\\n>— I'm afraid so. We're getting into the sandstorm season now.	[情境语义]
[13700]	— What a nice T-shirt! Can I have it, Mom?<\\n>— Well, It really look nice, ____ I think it's too expensive.	[but,连词]
[13690]	— What a nice MP5! Whose is it?<\\n>— It's ____. My father bought it for me.	[mine,名词性物主代词]
[13650]	— What a hot day!<\\n>— Yes. Let's ____.	[go swimming]
[13646]	— What a hot day!<\\n>— The weather report says it will be much ____ tomorrow.	[much+形容词副词比较级]
[13636]	— What a hot day! I am a bit thirsty.<\\n>— Would you like some ____?	[情境语义]
[13632]	— What a heavy snow outside!<\\n>— We should stay here ____ it stops.	[before,引导时间状语从句]
[13627]	— What a heavy rain!<\\n>— So it is. I prefer ____ rather than ____ on such a rainy day.	[prefer to do sth rather than…]
[13617]	— What a hard life my parents live!<\\n>— So do my parents. When I grow up, I ____ to make them live more happily.	[时间状语从句用一般现在时表示将来]
[13613]	— What a fine day! Shall we go hiking, Bob?<\\n>— I'd love to. But it's not the right ____, I am busy now.	[the moment]
[13603]	— What a clean and bright classroom, isn't it?<\\n>— Yes, it's always clean and bright because it ____ every day.	[一般现在时的被动语态]
[13598]	— What a big box! Can I help you?<\\n>— No, thanks. There's ____ in it. It's empty.	[nothing,复合不定代词]
[13589]	— What a beautiful dress you are wearing today!<\\n>— ____. It's nice of you to say so.	[赞誉和表扬的应答句]
[13579]	— What ____ you usually have for breakfast?<\\n>— ____ and a cup of coffee.	[a piece of bread]
[13574]	— What ____ useful book it is!<\\n>— Yeah, it tells you how to play ____ guitar.	[guitar,是乐器]
[13569]	— What ____ the noise, Bill?<\\n>— Sorry, I broke my glass.	[一般过去时]
[13559]	— What ____ do you like?<\\n>— I run every morning, and often play tennis at weekends.	[情境语义]
[13554]	— What ____ do you like better?<\\n>— Basketball.	[情境语义]
[13549]	— What ____ cold weather!<\\n>— Yes. But it's ____ unusual experience for us, we normally live in a hot place.	[weather,不可数名词instances]
[13549]	— What ____ cold weather!<\\n>— Yes. But it's ____ unusual experience for us, we normally live in a hot place.	[an+元音开头的词]
[13544]	— What ____ can you give me on learning English?<\\n>— I think you could join an English club.	[advice,不可数名词instances]
[13540]	— What ____ are those sweaters?<\\n>— They are yellow.	[情境语义]
[13530]	— Were you at school at 8:00 this morning?<\\n>— Yes. I ____ with my teacher at that time.	[过去进行时]
[13520]	— Were you at home at 9:00 last night? I called you but nobody answered.<\\n>— Sorry, I ____ at that time.	[过去进行时]
[13510]	— We're playing really well this season. We believe we will win!<\\n>— ____.	[believe…,应答句]
[13505]	— We're organizing a party next Saturday, and I'd like you to come.<\\n>— ____! I have a meeting to attend that day. Thank you all the same.	[表示请求,应答句]
[13496]	— Well, you look so happy!<\\n>— Because I got a good ____.	[规则可数名词instances]
[13491]	— Well, my sons take great interest in most of the food on the menu.<\\n>— Thanks. ____?<\\n>— Yes, fried fish, beef, chips and cola, please.	[情境语义]
[13482]	— We'll visit the Summer Palace ____ there is a heavy rain tomorrow.<\\n>— OK! Boating on the lake must be great fun.	[unless,引导条件状语从句]
[13478]	— We'll take part in the speech competition.<\\n>— ____!	[陈述即将到来的挑战,应答句]
[13473]	— We'll study in different schools next term．Enjoy your time in the new school!<\\n>— ____	[祝愿祝福,应答句]
[13468]	— We'll have an English exam tomorrow.<\\n>— ____.	[陈述即将到来的挑战,应答句]
[13464]	— We'll have a hiking trip, but when shall we meet?<\\n>— Let's make it ____ half past eight ____ the morning of June 21.	[表示时间:at,in,on]
[13464]	— We'll have a hiking trip, but when shall we meet?<\\n>— Let's make it ____ half past eight ____ the morning of June 21.	[make it+名词]
[13454]	— We'll go to Qing Yuan Mountain tomorrow. Why ____ join us?<\\n>— That's a good idea.	[why,不定式]
[13450]	— We'll go for a picnic if it ____ this Sunday.<\\n>— Wish you a lovely weekend.	[时间状语从句用一般现在时表示将来]
[13440]	— Welcome to our house!<\\n>— Oh, how nice! It's bigger than ____.	[ours,名词性物主代词]
[13421]	— We'd better not read ____ the sun.<\\n>— I agree. It's bad for our eyes.	[in,介词]
[13417]	— We will have a new foreign teacher this term. Do you know ____ when he was in his hometown?<\\n>— A policeman.	[what,宾语从句连接词]
[13413]	— We shouldn't speed too much time on computer games, it's bad for our eyes.<\\n>— ____!	[表达建议/意见/观点,应答句]
[13408]	— We plan to go out for a picnic next weekend. Would you like to come along?<\\n>— ____. It's my favourite.	[Would you like to do sth,应答句]
[13403]	— We never know ____ the old man is.<\\n>— They say he is a teacher.	[what,宾语从句连接词]
[13398]	— We need a new leader for our Helping Hands Club, but I don't know ____.<\\n>— Why not Mary? She is always willing to help others.	[who to do]
[13393]	— We must act now because time is ____.<\\n>— Yes. Let's start.	[run out]
[13389]	— We made a good job of our English groupwork.<\\n>— ____! Your topic on Advertisement English is fascinating.	[陈述成就,应答句]
[13384]	— We have worked for a long time, so we ____ a rest.<\\n>— Sounds good!	[stop to do,stop doing]
[13374]	— We have finished watering all the trees, Miss Li.<\\n>— ____! Boys and girls, let's have a drink.	[陈述成就,应答句]
[13364]	— We couldn't find you anywhere around 8:00 yesterday evening.<\\n>— I'm sorry for it. My mother and I ____ in the square.	[过去进行时]
[13350]	— We can't be successful ____ we keep working hard.<\\n>— I agree with you.	[unless,引导条件状语从句]
[13346]	— We can use this special pen to record or take pictures.<\\n>— Really? Will you please show me ____ it?	[how to do]
[13331]	— We can use QQ to communicate with each other online.<\\n>— Good. Will you please show me ____.	[how to do]
[13326]	— We can use QQ to chat with each other on the Internet.<\\n>— Really? Will you please show me ____ it?	[how to do]
[13316]	— We are going to play in tomorrow's football match. I feel very nervous, Dad.<\\n>— ____. I'm sure you can win the match.	[take it easy]
[13312]	— We are going to play a football game ____ Class 3 this Sunday.<\\n>— I will cheer you on. I hope our class will win.	[against,介词]
[13307]	— We are going on a school trip tomorrow.<\\n>— ____.	[计划旅行/派对,应答句]
[13292]	— Was Kate at the party last night?<\\n>— Yes, she ____ a really nice dress.	[过去进行时]
[13287]	— Waiter, $20 for dinner, right?<\\n>— I'm afraid $25, sir, for drinks are ____.	[情境语义]
[13282]	— Up to now the Chinese Communist Party (中国共产党) has nearly ____ history.<\\n>— Yes, it was founded ____ July 23rd, 1921.	[复合形容词]
[13282]	— Up to now the Chinese Communist Party (中国共产党) has nearly ____ history.<\\n>— Yes, it was founded ____ July 23rd, 1921.	[表示时间:at,in,on]
[13272]	— Two ____ died in the accident．<\\n>— ____ terrible it is!	[man,名词复数]
[13272]	— Two ____ died in the accident．<\\n>— ____ terrible it is!	[how引导的感叹句]
[13253]	— Tony, I'm too nervous to give a speech in the graduation ceremony.<\\n>— ____! I believe you can do it!	[take it easy]
[13243]	— Tony, I have trouble ____ the text.<\\n>— Remember ____ it three times at least.	[have trouble doing]
[13243]	— Tony, I have trouble ____ the text.<\\n>— Remember ____ it three times at least.	[remember to do,remember doing]
[13233]	— Tony, could you give me a hand?<\\n>— Wait a minute. I ____.	[现在进行时]
[13228]	— Tony, ____ you ____ smoking?<\\n>— Yes. Drinking tea is my favorite now.	[现在完成时]
[13228]	— Tony, ____ you ____ smoking?<\\n>— Yes. Drinking tea is my favorite now.	[stop to do,stop doing]
[13214]	— Tomorrow will be sunny. How about having a picnic in the park?<\\n>— ____ But I have to prepare for tomorrow's exam.	[How about...,应答句]
[13199]	— Tomorrow is David's tenth birthday.<\\n>— Yes. Let's give ____ a CD. He likes music	[him,人称代词宾格]
[13194]	— Tommy, you can never let others know what I have told you today.<\\n>— Don't worry. I will keep the ____.	[keep a secret]
[13184]	— Tommy, do you know if Frank ____ to the theatre with us this Sunday if it ____?<\\n>— Sorry, I have no idea.	[时间状语从句用一般现在时表示将来]
[13179]	— Tom, your hair is too long, and you should have it ____ this weekend.<\\n>— OK, I will do it this Sunday.	[have sth done]
[13174]	— Tom, your books should be in right order.<\\n>— OK. I'll ____ right now.	[put away]
[13169]	— Tom, who taught ____ English last term?<\\n>— Mr. Smith did.	[you,人称代词宾格]
[13159]	— Tom, supper is ready.<\\n>— I don't want to eat ____, Mum. I'm not feeling well.	[anything,复合不定代词]
[13154]	— Tom, please tell me ____.<\\n>— In Sunshine Secondary School.	[where,宾语从句连接词]
[13149]	— Tom, it's cold outside, ____ your coat when you go out.<\\n>— OK, Mom.	[put on]
[13144]	— Tom, I'm watching a football match. What about you?<\\n>— ____	[so,引导的倒装句]
[13139]	— Tom, do you know if Sam ____ to my party next week?<\\n>— I think she will come if she ____ free.	[时间状语从句用一般现在时表示将来]
[13124]	— Tom, can I borrow your book Chicken Soapy.<\\n>— Sorry, I ____ it to Mary.	[现在完成时]
[13124]	— Tom, can I borrow your book Chicken Soapy.<\\n>— Sorry, I ____ it to Mary.	[borrow,lend]
[13119]	— Tom, be careful not to drive too fast, ____.<\\n>— Thank you for your advice.	[情境语义]
[13111]	— Tom! Look at the man in black over there. Can you tell me ____?<\\n>— Oh! He is my friend, Jim.	[who,宾语从句连接词]
[13106]	— Tom wants to know if you will have a picnic tomorrow.<\\n>— Yes. But if it ____, we'll play chess instead.	[时间状语从句用一般现在时表示将来]
[13091]	— Tom is the ____ one I want to work with. He is always complaining.<\\n>— Be more patient. He is still a good boy.	[情境语义]
[13081]	— Tom is good at drawing. How about Mike?<\\n>— Mike is ____, I think. He has got more prizes than Tom.	[形容词和副词比较级]
[13076]	— Tom is from America.<\\n>— Great! He can help me ____ my English.	[help sb with sth]
[13061]	— Tom didn't go to school this morning, did he?<\\n>— ____. Though he had a bad cold.	[反意疑问句,应答句]
[13056]	— Today is the ____ day in my life, because I won the first prize in the competition.<\\n>— Congratulation!	[the+形容词最高级+名词]
[13051]	— To keep healthy, you'd better eat more vegetables and fruits every day.<\\n>— Thanks for your advice. I'll have more ____.	[情境语义]
[13046]	— Tina, is this ____ schoolbag?<\\n>— Yes, it's mine.	[your,形容词性物主代词]
[13041]	— Tina, are you going to play ____ chess on School Day?<\\n>— Yes, and I'll also play ____ violin that afternoon.	[chess,是球类棋类]
[13041]	— Tina, are you going to play ____ chess on School Day?<\\n>— Yes, and I'll also play ____ violin that afternoon.	[violin,是乐器]
[13036]	— Tim and I will visit the exhibition this weekend. Would you like to join us?<\\n>— ____.	[Would you like to do sth,应答句]
[13017]	— This yard is so clean today and everything looks fine.<\\n>— I didn't notice that. It's clear someone ____ it.	[现在完成时]
[13002]	— This problem are too hard to ____. Will you give me some advice?<\\n>— There are many ways. The most important is to have a plan.	[work out]
[12998]	— This math problem is so difficult that only she can work it out.<\\n>— ____ clever the girl is!	[how引导的感叹句]
[12988]	— This is ____ fascinating town I have ever visited.<\\n>— Yes, I've never seen a ____ one.	[形容词和副词最高级构成]
[12988]	— This is ____ fascinating town I have ever visited.<\\n>— Yes, I've never seen a ____ one.	[形容词和副词比较级]
[12983]	— This dress was last year's style.<\\n>— I think it still looks perfect ____ it has gone out this year.	[even though,引导让步状语从句]
[12978]	— This dress looks beautiful on you. How much is it?<\\n>— It ____ me more than a thousand yuan.	[cost,pay,spend,take]
[12973]	— This desk is too heavy. I ____ move it. Could you help me?<\\n>— No problem.	[can,情态动词]
[12958]	— They say there's a new restaurant nearby.<\\n>— Yes, and it ____ for no more than a week.	[延续性动词,用于现在完成时]
[12953]	— They say there are many monkeys in this mountain. But I saw none of them last time I was here.<\\n>— Hope we can see ____ today.	[some,不定代词]
[12948]	— They said sorry to me, but I wouldn't listen.<\\n>— It is foolish of you ____ others for the mistakes.	[of引导不定式逻辑主语]
[12943]	— They have never been to Australia before.<\\n>— ____.	[neither,引导的倒装句]
[12928]	— There's too much salt in the Chinese diet.<\\n>— So there is. The WHO says only 1.5 grams of salt ____ for each man every day.	[一般现在时的被动语态]
[12919]	— There's ____ important in today's newspaper, isn't there?<\\n>— Sorry, I don't know. I haven't got the paper yet.	[something+形容词]
[12914]	— There's ____ ball on the ground. Would you please pass ____ ball to me?<\\n>— With pleasure.	[the]
[12909]	— There was thick haze (雾霾) in our city this spring. What do you think of it?<\\n>— I think ____ cars we drive, ____ pollution our city will have.	[the+比较级...the+比较级,引导比较状语从句]
[12904]	— There was a telephone call for you.<\\n>— ____.	[情境语义]
[12899]	— There used to be lots of fish in the lake.<\\n>— Yes, but there are very ____ now.	[few+可数名词]
[12899]	— There used to be lots of fish in the lake.<\\n>— Yes, but there are very ____ now.	[fish,名词复数]
[12879]	— There is something wrong with your bike, ____?<\\n>— Yes. I'll have it ____ tomorrow.	[have sth done]
[12879]	— There is something wrong with your bike, ____?<\\n>— Yes. I'll have it ____ tomorrow.	[反意疑问句]
[12869]	— There is going to be a new movie on tonight. Will you be free then?<\\n>— ____ Let's go together.	[nothing much]
[12864]	— There is a smile on Miss Gao's face. She must be ____ with Sam's work.<\\n>— I think so. No one did as ____ as him in our class.	[be pleased with]
[12859]	— There is a girl in front of our classroom. Do you know ____?<\\n>— She is my neighbor, Sue	[who,宾语从句连接词]
[12855]	— There is ____ with my leg.<\\n>— Don't worry. Let me help you	[something+形容词]
[12845]	— There are so many problems. I'm so afraid.<\\n>— You should try to ____ your shyness first. You're not a child any more.	[get over]
[12836]	— There are always many volunteers in great events, ____?<\\n>— Yes, many hands make light work!	[反意疑问句]
[12827]	— There ____ some pork in the basket. Who bought it?<\\n>— My father did.	[there be]
[12827]	— There ____ some pork in the basket. Who bought it?<\\n>— My father did.	[不可数名词instances]
[12822]	— There ____ so many foreigners in the streets these days.<\\n>— They might be runners in the Yellow River Estuary (入海口,河口) International Marathon.	[there be]
[12802]	— The weather report says there is going to ____ a typhoon tonight.<\\n>— So we had better ____ out.	[be going to do]
[12802]	— The weather report says there is going to ____ a typhoon tonight.<\\n>— So we had better ____ out.	[there be]
[12792]	— The weather is very good. Let's go to the seaside.<\\n>— ____. Why not?	[表达建议/意见/观点,应答句]
[12787]	— The weather changes often nowadays.<\\n>— ____. The high temperature was 32℃ yesterday, but it is 19℃ today.	[so+主语+助动词]
[12782]	— The volunteers are doing a great job in Yushu.<\\n>— Yes. They are helping the people ____ are suffering from the earthquake.	[who,引导的定语从句]
[12778]	— The village ____ I visited last year has changed a lot.<\\n>— Really? I hope to go there one day.	[that,引导的定语从句]
[12773]	— The TV show Home with Kids is so wonderful. You shouldn't miss it.<\\n>— If I have time, I ____ it.	[时间状语从句用一般现在时表示将来]
[12763]	— The transportation in our country is much more ____ than it used to be.<\\n>— But travelling becomes much easier!	[情境语义]
[12758]	— The teachers in that school speak either English or French,　or even ____.<\\n>— That's so cool!	[both,不定代词]
[12753]	— The sweater is not the right ____ for me.<\\n>— Well, shall I get you a bigger one or a smaller one?	[情境语义]
[12749]	— The sun is shining brightly. ____ your sunglasses, Amy.<\\n>— OK, Mom.	[dress,put on,wear]
[12744]	— The Summer Palace is wonderful. Have you ever visited any other interesting places?<\\n>— Yes. Also, we ____ to the Great Wall.	[have been to,have gone to,have been in]
[12740]	— The summer holiday is on the way. We'll have more freedom.<\\n>— ____. But we should learn to manage ourselves.	[表达建议/意见/观点,应答句]
[12730]	— The skirt looks different from others and it is nice.<\\n>— Thanks. It ____ by my mother last month.	[一般过去时的被动语态]
[12725]	— The radio says it will rain next Sunday.<\\n>— ____. We're going for a picnic that day.	[应答句]
[12720]	— The radio ____ that there will be another heavy rain in Guangdong.<\\n>— Too bad. It has rained for the whole week.	[say,speak,talk,tell]
[12705]	— The party is a great success. We've had a good time.<\\n>— ____.	[Thank you…,应答句]
[12695]	— The number of the students in our class ____ fifty-six.<\\n>— How many of ____ are girls?	[the number of+复数名词,主谓一致]
[12681]	— The model ship is wonderful.<\\n>— It ____ me two days to make it.	[cost,pay,spend,take]
[12676]	— The meat is ____ delicious.<\\n>— Yes, but don't eat ____.	[much,副词instances]
[12676]	— The meat is ____ delicious.<\\n>— Yes, but don't eat ____.	[too+形容词副词]
[12671]	— The math exam is coming. I'm very nervous.<\\n>— Just ____ I'm sure you'll do well in it.	[take it easy]
[12661]	— The local living conditions (条件) have improved a lot ____ China set up the city of Sansha.<\\n>— And more and more people would like to go there for business.	[since+一般过去时,主句用现在完成时]
[12656]	— The little girl ____ her seat to an old man on the bus.<\\n>— What a kind girl!	[offer]
[12646]	— The light in his office is still on. Do you know ____?<\\n>— In order to prepare for tomorrow's meeting.	[why,宾语从句连接词]
[12641]	— The land in the southwest of China is in great need of ____.<\\n>— Yes, it hasn't rained for a long time there.	[情境语义]
[12637]	— The jeans look so special. May I try them on?<\\n>— OK, ____. Here is a room for you.	[情境语义]
[12632]	— The house price has been rising in the past two years.<\\n>— Yes, I cannot ____ to buy a small apartment even with my parents' help.	[can,afford]
[12627]	— The heavy rain [cheered] the farmers up.<\\n>— Yes, it hasn't rained for a long time.	[cheer up]
[12622]	— The girls are talking about the art festival ____.<\\n>— Yes. They have so many fun things to share.	[副词instances]
[12617]	— The girl ____ all her savings to the people in the Southwest for the serious drought (旱灾).<\\n>— What a donation and what a nice girl!	[give out]
[12612]	— The food looked bad, but it ____ OK.<\\n>— So we can't judge a man by his appearance.	[taste+形容词]
[12572]	— The doctor told me ____ too much but I find it difficult.<\\n>— The doctor is right. The less you drink, ____ you will be.	[tell…to do]
[12572]	— The doctor told me ____ too much but I find it difficult.<\\n>— The doctor is right. The less you drink, ____ you will be.	[the+比较级...the+比较级,引导比较状语从句]
[12568]	— The dish is delicious!<\\n>— Well, at least it's as ____ as the one I cooked yesterday.	[as...as,引导比较状语从句]
[12558]	— The coffee is good. ____?<\\n>— Certainly. I am very glad you love it.	[表示请求,应答句]
[12553]	— The coffee is good, Kathy.<\\n>— Sure, Simon. It'll taste much ____ if you drink it with some milk.	[much+形容词副词比较级]
[12544]	— The CCTV reported that Premier Wen Jiabao played basketball with some students on Children's Day.<\\n>— ____! And Premier Wen always encourages us to study hard and do more sports.	[what,引导的感叹句]
[12535]	— The cake looks ____.<\\n>— Yes, and it tastes even ____.	[形容词和副词比较级]
[12531]	— The cake is too expensive. Would you like to show me a ____ one?<\\n>— Sure. Here you are.	[形容词和副词比较级]
[12526]	— The bread is delicious.<\\n>— It must taste ____ with some jam in it.	[形容词和副词比较级]
[12522]	— The boy can speak both English and Japanese ____ he is only ten.<\\n>— Wow, what a clever boy!	[though,引导让步状语从句]
[12518]	— The box is too heavy to carry. What's in it?<\\n>— Oh, it ____ books.	[be filled with]
[12508]	— The advantages of the Chongqi Bridge have already been seen.<\\n>— ____ good news to us!	[what,引导的感叹句]
[12498]	— That's a nice mobile phone.<\\n>— It is. My aunt ____ it for my last birthday.	[一般过去时]
[12493]	— That's a heavy box. Can I give you a hand?<\\n>— ____. I'm strong enough to carry it.	[Would you like me to do sth,应答句]
[12488]	— That mountain in Guilin ____ an elephant.<\\n>— So it does, it's amazing!	[look+like+名词]
[12483]	— That actor often joins in different activities in Beijing. Do you know ____?<\\n>— For 5 years.	[how long,宾语从句连接词]
[12478]	— Thanks for your wonderful dinner. I have to go now.<\\n>— It's raining hard. Don't ____ until it stops.	[not…until]
[12473]	— Thanks for your help.<\\n>— ____.	[Thank you…,应答句]
[12463]	— Thanks for the delicious food.<\\n>— ____.	[Thank you…,应答句]
[12458]	— Thanks for taking my friends and me out tonight.<\\n>— ____.	[Thank you…,应答句]
[12448]	— Thank you for taking me around your school, Daming.<\\n>— ____	[Thank you…,应答句]
[12434]	— Thank you for your help.<\\n>— ____.	[Thank you…,应答句]
[12429]	— Thank you for the presents. They are so great!<\\n>— ____.	[Thank you…,应答句]
[12424]	— Thank you for the present you sent me. It's so nice.<\\n>— ____.	[Thank you…,应答句]
[12414]	— Thank you for helping me so much!<\\n>— ____.	[Thank you…,应答句]
[12399]	— Tell me ____.<\\n>— Well, it's like…	[what,宾语从句连接词]
[12394]	— Tell me ____ about Brother Sharp, please.<\\n>— He was a beggar (乞丐). He became a blue-eyed boy (红人) on the Internet because of his cool appearance and dressing style.	[something,复合不定代词]
[12389]	— Tell him about the news when he ____, John.<\\n>— Yes, I will.	[时间状语从句用一般现在时表示将来]
[12374]	— Ted, could you please ____ the trash?<\\n>— Of course, Mom.	[take out]
[12364]	— Taiwan is our Treasure Island, it is an important part of China.<\\n>— Yeah, It lies ____ the southeast of China and ____ the east of Fujian.	[表示方位:in,on,to]
[12360]	— Susan, you know what? We can have a dog!<\\n>— Great! But I prefer to have a cat. It is much ____ to look after.	[much+形容词副词比较级]
[12356]	— Susan, why are you still here? They are all ready to start.<\\n>— I'm sorry, but I ____ when to leave.	[一般过去时的被动语态]
[12351]	— Susan, what are the advantages of MP5 players?<\\n>— Mom, they are smaller and lighter ____ they can be carried very easily.	[so that,引导结果状语从句]
[12347]	— Suihua is so beautiful. It's like a big garden.<\\n>— Yes. Many tree and flowers ____ in our city every year.	[一般现在时的被动语态]
[12343]	— Study hard, ____ you won't pass the exam.<\\n>— I see, Mum.	[祈使句+or+陈述句]
[12333]	— Steven, could you help me ____ when the plane will take off on the Internet?<\\n>— I'm sorry, my computer doesn't work.	[find out]
[12329]	— Steve, did you see the lantern show when you were in Fuzhou?<\\n>— Of course! ____ beautiful lanterns!	[what,引导的感叹句]
[12324]	— Steve, ____ do you play basketball after school?<\\n>— Twice a week. It can keep me healthy.	[how often,特殊疑问句]
[12319]	— Ssh, be quiet! The baby ____ in the next room.<\\n>— Oh, sorry.	[现在进行时]
[12314]	— Sorry. I ____ your letter.<\\n>— Never mind. I will do it myself after school.	[I'm sorry …,应答句]
[12309]	— Sorry, Tommy. I've lost your book.<\\n>— ____ I've got another copy.	[I'm sorry …,应答句]
[12304]	— Sorry, sir. I made a mistake again.<\\n>— ____. Practice more and you will do better.	[I'm sorry …,应答句]
[12299]	— Sorry, Mr. Green. I have ____ my homework at home.<\\n>— Never mind. But don't forget next time.	[forget,leave:辨析]
[12295]	— Sorry, I'm late.<\\n>— It doesn't matter. The meeting ____ just for several minutes.	[延续性动词,用于现在完成时]
[12291]	— Sorry, I made a mistake again.<\\n>— ____. Practice more and you will succeed.	[I'm sorry …,应答句]
[12286]	— Sorry, I can't go shopping with you tonight.<\\n>— ____	[I'm sorry …,应答句]
[12281]	— Sorry, Frank. I'm busy today. I can't go swimming with you.<\\n>— ____.	[I'm sorry …,应答句]
[12276]	— Sorry, but I couldn't find your tape.<\\n>— ____. I've got another one.	[I'm sorry …,应答句]
[12266]	— Something ____ terrible. What goes bad in the kitchen?<\\n>— The meat.	[smell+形容词]
[12262]	— Some parts of China are very thirsty now. I think water ____ to those places.<\\n>— I think so.	[must,被动语态]
[12257]	— Some boys think maths is ____ English.<\\n>— So do I.	[形容词和副词比较级]
[12252]	— So you were in the supermarket ____ you heard a strange sound, right?<\\n>— That's true. I ran out as quickly as possible.	[when,引导时间状语从句]
[12242]	— So many problems! I'm tired.<\\n>— You should try to ____ them by yourself. You are not a child any longer.	[get over]
[12237]	— So many people! Could I stand here?<\\n>— ____. Don't you see the sign Line up, please?	[表示请求,应答句]
[12232]	— So kind of you to give me a ride to the station!<\\n>— ____.	[Thank you…,应答句]
[12208]	— Sir, could you please put out your cigarette? This is a smoke-free (无烟的) school.<\\n>— ____.	[表示请求,应答句]
[12198]	— Simon, I wonder ____.<\\n>— Last Saturday.	[when,宾语从句连接词]
[12194]	— Show me the map, please. I wonder ____.<\\n>— Look, it's here, in the east of China, near Taiwan Province.	[where,宾语从句连接词]
[12180]	— She's never spoken to a foreigner, ____?<\\n>— Yes. She's active and can speak English freely.	[never,反意疑问句]
[12175]	— She has gone abroad, ____?<\\n>— No. She is still teaching us English at our school now.	[反意疑问句]
[12160]	— Sharon, remember to lock the door before leaving the house.<\\n>— ____.	[祈使句的应答句]
[12150]	— Shall we stop and have ____ tea now?<\\n>— All right.	[some+不可数名词]
[12146]	— Shall we see the movie today or tomorrow?<\\n>— ____ It's all the same to me.	[or选择疑问句,应答句]
[12141]	— Shall we pay ____ visit to Expo 2010, Shanghai?<\\n>— No, I'd rather stay at home and play ____ football.	[play+球类棋类]
[12131]	— Shall we join in the Green World Summer Camp?<\\n>— ____.	[Shall we…,应答句]
[12126]	— Shall we have a cup of office?<\\n>— ____.	[Shall we…,应答句]
[12122]	— Shall we go to the concert this evening?<\\n>— ____. Let's buy the tickets first.	[Shall we…,应答句]
[12098]	— Shall we go skateboarding after school?<\\n>— Sorry, my parents said that I ____ be at home early.	[must,情态动词]
[12083]	— Shall we go out to play basketball?<\\n>— ____. Because we are having an important test this afternoon.	[Shall we…,应答句]
[12078]	— Shall we go out for a walk?<\\n>— Sorry, I can't. I ____ my homework.	[现在进行时]
[12068]	— Shall we go out for a trip to relax ourselves after the final exam?<\\n>— ____.	[Shall we…,应答句]
[12063]	— Shall we go hiking tomorrow?<\\n>— ____. The radio says it will rain.	[Shall we…,应答句]
[12058]	— Shall we go for a picnic in the park this Saturday?<\\n>— Oh, that ____ good.	[Shall we…,应答句]
[12053]	— Shall we get off the bus here?<\\n>— Yes. But we won't get off ____ it stops.	[not…until]
[12048]	— Shall we call for a taxi?<\\n>— OK. Let me ____ the phone number in Yellow Pages.	[look up]
[12043]	— Shall I tell Sally about it?<\\n>— No, you ____. I've told her already.	[need,情态动词]
[12038]	— Shall I tell Jim the good news?<\\n>— No, you ____. I've told him already.	[Shall we…,应答句]
[12033]	— Shall I take you to the shopping mall after work?<\\n>— No, thanks. My father said he would ____ on his way home.	[pick up]
[12023]	— Shall I take this chair to your room?<\\n>— ____. I'll do it myself.	[Would you like me to do sth,应答句]
[12018]	— Shall I take my swimming suit?<\\n>— No, you ____. We will just go hiking in the mountain.	[need,情态动词]
[11998]	— Sam, what will the weather be like tomorrow?<\\n>— Sorry, Mum. I didn't watch the weather forecast just now, I ____ a football match.	[过去进行时]
[11993]	— Sam, what can I do to get up early?<\\n>— Set the alarm at 6:00 am, ____ you'll make it.	[祈使句+and+陈述句]
[11988]	— Sam, my iPhone is in my bedroom. Could you ____ it for me?<\\n>— No problem.	[bring,carry,pass,take,fetch]
[11983]	— Sam, let's go and play basketball.<\\n>— Not now. I ____ Dick with his English.	[现在进行时]
[11973]	— Sam, come downstairs, please. I need your help.<\\n>— Sorry, mum, I ____ on the phone.	[现在进行时]
[11964]	— Sally, would you like some more cakes?<\\n>— ____. I'm full.	[Would you like to do sth,应答句]
[11950]	— Sally, I went to the concert last night. How big the symphony hall is!<\\n>— So it is. It is ____ to hold more than one thousand people.	[形容词副词+enough]
[11945]	— Sally, I am going to Shanghai tomorrow.<\\n>— ____.	[计划旅行/派对,应答句]
[11940]	— Sally, could you go and help your father wash the car?<\\n>— Why ____? I'm busy now. Amy is lying on the grass doing nothing.	[me,人称代词宾格]
[11935]	— Sally and Linda are good at running. Who runs ____?<\\n>— Linda does.	[形容词和副词比较级]
[11930]	— Ruth, I want to have some milk.<\\n>— There's ____ left. What about orange juice?	[none,不定代词]
[11925]	— Rose, we will start at six tomorrow morning. Don't be late, ____?<\\n>— ____. I'll be there on time.	[祈使句的应答句]
[11925]	— Rose, we will start at six tomorrow morning. Don't be late, ____?<\\n>— ____. I'll be there on time.	[祈使句的反义疑问]
[11920]	— Rita, your Chinese is very good. ____ have you been in China?<\\n>— Since I was five.	[how long特殊疑问句,现在完成时]
[11915]	— Ring me up ____ you come to my house, will you?<\\n>— Sure, I will.	[before,引导时间状语从句]
[11910]	— Remember, boys and girls. ____ you work, ____ result you will get.<\\n>— We know, Miss Gao.	[the+比较级...the+比较级,引导比较状语从句]
[11886]	— Putian Railway Station has come into use recently.<\\n>— ____ exciting news! We can go to Fuzhou or Xiamen more quickly than before.	[news,不可数名词instances]
[11886]	— Putian Railway Station has come into use recently.<\\n>— ____ exciting news! We can go to Fuzhou or Xiamen more quickly than before.	[what,引导的感叹句]
[11881]	— Please write down the telephone number.<\\n>— Sorry, but I have no ____ to write on.	[情境语义]
[11876]	— Please turn off the TV. The baby ____.<\\n>— OK. I'll go out for a walk.	[现在进行时]
[11852]	— Please tell me ____ the scarf?<\\n>— She bought it online, I guess.	[where,宾语从句连接词]
[11847]	— Please take my seat here. Granny.<\\n>— ____	[表示愿意提供帮助,应答句]
[11838]	— Please remember ____ the lights when you leave the room.<\\n>— OK, I will.	[remember to do,remember doing]
[11833]	— Please give me a ____ when you arrive.<\\n>— OK. I'll tell you everything as soon as I get there.	[give sb a ring]
[11828]	— Please give Alice the story book ____ you see her.<\\n>— All right.	[if,引导条件状语从句]
[11818]	— Please don't throw paper on the ground.<\\n>— ____, I won't.	[祈使句的应答句]
[11803]	— Please ____ the tigers. It's dangerous to take photos with them.<\\n>— Oh, I see. Thank you.	[keep off]
[11799]	— Physics ____ more difficult than Chinese, do you think so?<\\n>— Yes, I think so.	[physics,不可数名词instances]
[11794]	— Philip has gone to New Zealand.<\\n>— Oh, can you tell me ____?	[when,宾语从句连接词]
[11784]	— Peter, what if your parents go out?<\\n>— They ask me to ____ myself.	[look after]
[11779]	— Peter, what have done with the poor dog? He is wet through!<\\n>— Not ____, mum! I never do the same thing a second time.	[me,人称代词宾格]
[11755]	— Peter, how old is your father this year?<\\n>— ____. And we just had party for his ____ birthday last weekend.	[序数词的构成]
[11745]	— Peter, don't play that kind of joke any more!<\\n>— Sorry! I ____ do it again.	[祈使句的应答句]
[11737]	— Peter, can you tell me the differences ____ the four words?<\\n>— Sorry, I don't know.	[辨析:among,between]
'''
}
