package ots

class SampleData_QuestionMapping8 {

	String content ='''[11732]	— Peter, ____ do you visit your grandparents?<\\n>— Twice a month.	[how often特殊疑问句,应答句]
[11727]	— Peter shut his mouth at the meeting all the time. How about Tom?<\\n>— ____.	[so,引导的倒装句]
[11722]	— Peter looks sporty.<\\n>— Yes. He is the ____ runner in my class.	[the+形容词最高级+名词]
[11717]	— Peter has made great progress in math recently.<\\n>— ____, and so have you.	[so+主语+助动词]
[11712]	— Peter has hurt his leg.<\\n>— Oh, ____!	[陈述遗憾的事情,应答句]
[11702]	— Peter has changed a lot, hasn't he?<\\n>— Yes. He used to ____ the guitar, but now he is more ____ in playing soccer.	[be interested in]
[11702]	— Peter has changed a lot, hasn't he?<\\n>— Yes. He used to ____ the guitar, but now he is more ____ in playing soccer.	[used to,情态动词]
[11697]	— Peter doesn't mind lending you his camera.<\\n>— He ____. I've already borrowed one.	[need,情态动词]
[11692]	— Peter doesn't know many people here.<\\n>— ____.	[neither,引导的倒装句]
[11687]	— Pauline has lost her phone.<\\n>— No. It's in her bag. I ____ hear it.	[can,情态动词]
[11673]	— Pardon? I didn't catch ____.<\\n>— I said the book sold very well in our school.	[what,宾语从句连接词]
[11668]	— Paper ____ wood. We should not waste paper.<\\n>— I agree. I always use ____ sides of paper.	[be made from]
[11668]	— Paper ____ wood. We should not waste paper.<\\n>— I agree. I always use ____ sides of paper.	[both,不定代词]
[11653]	— Our shirts look the same.<\\n>— Yes, but ____ looks newer.	[yours,名词性物主代词]
[11648]	— Our school is going to hold the ____ Culture Festival.<\\n>— I see. And we can take part in ____ activities.	[序数词的构成]
[11633]	— Our foreign teacher Mr. Green ____ us English since three years ago.	[since+过去时间点,用于现在完成时]
[11629]	— Our classroom ____ every day.<\\n>— So it is. It's our duty to keep it clean and tidy.	[一般现在时的被动语态]
[11624]	— Our class won the English speaking contest.<\\n>— Congratulations! You ____ be very proud of it.	[must,情态动词]
[11614]	— Our city looks more beautiful!<\\n>— Yes. Lots of trees and grass ____ since last year.	[现在完成时的被动语态]
[11614]	— Our city looks more beautiful!<\\n>— Yes. Lots of trees and grass ____ since last year.	[since+过去时间点,用于现在完成时]
[11609]	— Our Chinese football team has ____ the match.<\\n>— Congratulations.	[现在完成时]
[11604]	— Open the window please, Mike?<\\n>— ____? I didn't hear what you said.	[表示请求,应答句]
[11600]	— Oh, your skirt looks beautiful!<\\n>— ____	[赞誉和表扬的应答句]
[11596]	— Oh, you 're reading a newspaper. Is there ____ in it?<\\n>— I don 't know. I read it just now.	[something+形容词]
[11591]	— Oh, you are here. I'm looking for you all the morning. ____?<\\n>— To the library.	[have been to]
[11586]	— Oh, we've missed the 6 o'clock film.<\\n>— ____. It'll be on again in two hours.	[陈述遗憾的事情,应答句]
[11582]	— Oh, there's someone in the room.<\\n>— ____ must be my brother.	[it,人称代词主格]
[11577]	— Oh, the traffic is too heavy.<\\n>— Let's change ____ route to the airport.	[another,不定代词]
[11572]	— Oh, no. Where is my purse?<\\n>— Don't worry. I saw ____ black one in the drawer. Is it yours?	[a]
[11567]	— Oh, no! There isn't any sugar left.<\\n>— ____. I'll buy some when I go into town.	[陈述遗憾的事情,应答句]
[11562]	— Oh, Nancy! Do you live here?<\\n>— No. This house is ____. I'm here to see his baby.	[名词所有格]
[11547]	— Oh, Jack, your MP4 looks nice. Is it new?<\\n>— No. I ____ it since two years ago.	[延续性动词,用于现在完成时]
[11547]	— Oh, Jack, your MP4 looks nice. Is it new?<\\n>— No. I ____ it since two years ago.	[since+一段时间+ago,用于现在完成时]
[11542]	— Oh, I've missed the bus!<\\n>— ____. There's another one in five minutes.	[陈述遗憾的事情,应答句]
[11532]	— Oh, it's too difficult for me ____ the task in such a short time.<\\n>— Cheer up! I am sure you can.	[不定式,it,主语]
[11532]	— Oh, it's too difficult for me ____ the task in such a short time.<\\n>— Cheer up! I am sure you can.	[for引导不定式逻辑主语]
[11522]	— Oh, I had a terrible toothache.<\\n>— You'd better ____ see a dentist and have you had teeth pulled out.	[had better,不定式]
[11503]	— Now more people are paying attention to the school bus safety.<\\n>— So we believe ____ there will be fewer accidents in future.	[副词instances]
[11493]	— Not only the young but the old are getting interested ____ WeChat (微信).<\\n>— They can communicate more freely.	[be interested in]
[11489]	— Nobody will become a hero without the help of others.<\\n>— That's true. ____	[情境语义]
[11484]	— Nobody likes ____, so we should be kind to everyone.<\\n>— I agree with you.	[like to do]
[11484]	— Nobody likes ____, so we should be kind to everyone.<\\n>— I agree with you.	[不定式,被动语态]
[11479]	— Nobody knows ____ he was after he graduated from Beijing University.<\\n>— But I was once told he was a doctor working in a far-away village.	[what,宾语从句连接词]
[11475]	— Nick, would you mind ____ out of the bathroom?<\\n>— Sorry. It won't be long.	[mind doing]
[11465]	— Nancy, don't always ____ that old jacket. It looks terrible.<\\n>— But I think it's cool, Mom.	[dress,put on,wear]
[11465]	— Nancy, don't always ____ that old jacket. It looks terrible.<\\n>— But I think it's cool, Mom.	[take off]
[11445]	— My shoes are worn out.<\\n>— ____	[情境语义]
[11440]	— My pen is lost and I can't find it anywhere.<\\n>— So you will have to buy ____.	[one,it]
[11426]	— My old friend White is going to visit me.<\\n>— We haven't seen each other ____ five years.	[for+一段时间,用于现在完成时]
[11421]	— My new iphone was stolen when I took a bus yesterday.<\\n>— ____.	[陈述遗憾的事情,应答句]
[11406]	— My mother likes reading.<\\n>— ____.	[so,引导的倒装句]
[11396]	— My mother is asleep. Tell Tom ____ too much noise.<\\n>— OK.	[tell…to do]
[11391]	— My mother and I will go to Shanghai this summer.<\\n>— ____. Shall we go together?	[so,引导的倒装句]
[11387]	— My grandparents are sleeping in the bedroom. Would you mind my ____ TV?<\\n>— Certainly not. We can go out for a walk.	[mind doing]
[11387]	— My grandparents are sleeping in the bedroom. Would you mind my ____ TV?<\\n>— Certainly not. We can go out for a walk.	[turn off]
[11383]	— My grandfather was ill in hospital last week.<\\n>— ____.	[陈述遗憾的事情,应答句]
[11378]	— My grandfather is ill in hospital this week.<\\n>— ____.	[陈述遗憾的事情,应答句]
[11368]	— My favourite TV ____ is A Bite of China (舌尖上的中国)<\\n>— We like it, too. My mother often cooks delicious food after watching it.	[情境语义]
[11363]	— My English teacher visited Australia last summer.<\\n>— Which city did he visit?<\\n>— ____.	[情境语义]
[11353]	— My daughter ate a lot of ice cream in school.<\\n>— Yes, ____.	[so+主语+助动词]
[11348]	— My dad bought me a new MP4, but I don't know ____.<\\n>— Let's read the instructions.	[how to do]
[11338]	— My car ____. Could you please give me a ride tomorrow?<\\n>— I'm sorry I can't. I'm ____ London tomorrow morning.	[break down]
[11338]	— My car ____. Could you please give me a ride tomorrow?<\\n>— I'm sorry I can't. I'm ____ London tomorrow morning.	[leave for]
[11333]	— My brother won the first prize in speech competition.<\\n>— Congratulations! You ____ be excited about that!	[must,should,ought to]
[11319]	— My aunt goes to climb mountains every Sunday.<\\n>— Oh? But she ____ hate climbing mountains.	[used to,情态动词]
[11314]	— Must we leave now?<\\n>— No, we ____. We still have two more hours.	[must疑问句,应答句]
[11300]	— Must we finish the work before six?<\\n>— No, you ____. You may do it tomorrow.	[must疑问句,应答句]
[11296]	— Must we finish our homework now?<\\n>— No, you ____.	[must疑问句,应答句]
[11291]	— Must we clean the classroom now?<\\n>— No, you needn't. It ____ after school.	[can,被动语态]
[11277]	— Must I water the flowers right now?<\\n>— No, you ____. You may do it after supper.	[must疑问句,应答句]
[11267]	— Must I wait for you here?<\\n>— No, you ____.	[must疑问句,应答句]
[11262]	— Must I wait for you here now?<\\n>— No, you ____. You may be back in half an hour.	[must疑问句,应答句]
[11257]	— Must I turn down the radio now?<\\n>— No, you ____.	[must疑问句,应答句]
[11253]	— Must I stay at home the whole afternoon?<\\n>— No, you ____.	[must疑问句,应答句]
[11234]	— Must I return the book tomorrow morning?<\\n>— No, you ____. You ____ keep it for three days.	[can,情态动词]
[11234]	— Must I return the book tomorrow morning?<\\n>— No, you ____. You ____ keep it for three days.	[must疑问句,应答句]
[11219]	— Must I return the book this week?<\\n>— No, you ____. You can ____ it for 20 days.	[must疑问句,应答句]
[11219]	— Must I return the book this week?<\\n>— No, you ____. You can ____ it for 20 days.	[for+一段时间]
[11214]	— Must I mop up the floor now?<\\n>— No, you ____.	[must疑问句,应答句]
[11209]	— Must I leave the room now?<\\n>— No, you ____.	[must疑问句,应答句]
[11199]	— Must I learn all these words by heart?<\\n>— No, you ____. It'll be fine if you copy them in your exercise books.	[must疑问句,应答句]
[11174]	— Must I go to medical school and be a doctor like you, Dad?<\\n>— No, you ____, son. You're free to make your own decision.	[must疑问句,应答句]
[11169]	— Must I go and do it now?<\\n>— No, you ____. We still have two more days.	[must疑问句,应答句]
[11165]	— Must I get up early tomorrow morning?<\\n>— No, you ____.	[must疑问句,应答句]
[11151]	— Must I finish the work today?<\\n>— No, you ____. You ____ finish it tomorrow.	[must疑问句,应答句]
[11146]	— Must I finish the work today?<\\n>— No, you ____.	[must疑问句,应答句]
[11141]	— Must I finish the work today, Mom?<\\n>— No, you ____. You can finish it tomorrow.	[must疑问句,应答句]
[11132]	— Must I finish my homework today, Ms Liu?<\\n>— No, ____.	[must疑问句,应答句]
[11127]	— Must I finish my homework right now?<\\n>— No, you ____.	[must疑问句,应答句]
[11123]	— Must I finish my homework now?<\\n>— No, you ____. You can do it this evening.	[must疑问句,应答句]
[11113]	— Must I finish my homework at school?<\\n>— No, you____. You can do it at home.	[must疑问句,应答句]
[11109]	— Must I finish my homework at school?<\\n>— ____. You can do it at home and hand it in next week.	[must疑问句,应答句]
[11095]	— Must I clean the room now?<\\n>— No, you ____. You can do it tomorrow.	[must疑问句,应答句]
[11086]	— Must I be home before eight o'clock, Mum?<\\n>— No, you ____. But you have to come back before ten o'clock.	[must疑问句,应答句]
[11076]	— Mum,<\\n>— Hurry up! Your father ____ for us.	[现在进行时]
[11067]	— Mum, where are my socks?<\\n>— Under your bed. You should ____ your things.	[put away]
[11063]	— Mum, where are my shoes?<\\n>— They're in ____ black box under the bed.	[the]
[11058]	— Mum, when can I watch TV?<\\n>— As soon as your homework ____.	[as soon as,引导时间状语从句]
[11058]	— Mum, when can I watch TV?<\\n>— As soon as your homework ____.	[时间状语从句用一般现在时表示将来]
[11053]	— Mum, we have to buy some more salt.<\\n>— ____ There is enough salt in our country.	[陈述遗憾的事情,应答句]
[11044]	— Mum, there's something wrong with my ____. Would you wake me up tomorrow morning?<\\n>— No problem, dear.	[情境语义]
[11039]	— Mum, must I wash the dishes right now?<\\n>— No, you ____.	[must疑问句,应答句]
[11035]	— Mum, must I stay there the whole day?<\\n>— No, you ____.You ____ come back after lunch, if you like.	[can,情态动词]
[11035]	— Mum, must I stay there the whole day?<\\n>— No, you ____.You ____ come back after lunch, if you like.	[must疑问句,应答句]
[11021]	— Mum, it's late. Why are you still here?<\\n>— Dad hasn't come back yet. I ____ for him.	[现在进行时]
[11016]	— Mum, I'm too thirsty.<\\n>— How about having some ____?	[情境语义]
[11011]	— Mum, I'm tired of doing too much homework every day.<\\n>— Oh, dear, without hard work, you can't ____ your dream.	[achieve one's dream]
[11006]	— Mum, I'm really ____ about the result of the exam.<\\n>— Cheer up. I believe you can be successful.	[be happy with]
[11002]	— Mum, I'm not feeling well.<\\n>— Oh, dear! ____	[陈述遗憾的事情,应答句]
[10978]	— Mum, I think I'm ____ to go back to school.<\\n>— Not really, my dear. You'd better stay at home for another day or two.	[well,表语补语形容词]
[10978]	— Mum, I think I'm ____ to go back to school.<\\n>— Not really, my dear. You'd better stay at home for another day or two.	[形容词副词+enough]
[10965]	— Mum, I don't feel like eating.<\\n>— Oh dear! ____	[陈述遗憾的事情,应答句]
[10956]	— Mum, doing homework all the time makes me a dull. What about going for a picnic?<\\n>— ____.	[what about…,应答句]
[10951]	— Mum, could you buy me a dress like this?<\\n>— Certainly, we can buy ____ one than this, but ____this.	[as...as,引导比较状语从句]
[10951]	— Mum, could you buy me a dress like this?<\\n>— Certainly, we can buy ____ one than this, but ____this.	[形容词和副词比较级]
[10946]	— Mum, could I have an MP3 like this?<\\n>— Certainly, we can buy ____ one, but as good as this.	[形容词和副词比较级]
[10926]	— Mum, ____ is my football?<\\n>— It's under your bed.	[where,特殊疑问句]
[10922]	— Mum, ____ is my camera?<\\n>— Look, it's on your desk.	[where,特殊疑问句]
[10917]	— Mum, ____ I go out to play?<\\n>— Yes, you can. But you must finish your homework first.	[may疑问句,应答句]
[10907]	— Ms Lin is very popular among the students.<\\n>— Yes. Her classes are ____ lively and interesting.	[always,频率副词]
[10893]	— Mr. Wang, can you tell me ____?<\\n>— [www.hledu.net] will help you.	[where,宾语从句连接词]
[10888]	— Mr. Wang, can I finish my homework tomorrow?<\\n>— Sorry, you ____.	[can,情态动词]
[10883]	— Mr. Wang ____ be on the playground, I think.<\\n>— He ____ be on the playground. I saw him in the office just now.	[can't,mustn't]
[10883]	— Mr. Wang ____ be on the playground, I think.<\\n>— He ____ be on the playground. I saw him in the office just now.	[may,情态动词]
[10868]	— Mr. Smith, would you please speak a little more ____?<\\n>— Sorry! I thought you could follow me.	[副词]
[10853]	— Mr. Smith must have been to your home this morning.<\\n>— No, he ____, because he didn't know my address.	[情态动词,时态]
[10848]	— Mr. Smith always has ____ to tell us.<\\n>— So he does.	[a piece of news]
[10838]	— Mr. Li, I can't understand everything in class.<\\n>— Don't worry! I'll ____ the main points at the end.	[情境语义]
[10833]	— Mr. Li was sent to teach Chinese in an American high school last year.<\\n>— Yes, I know. He told me he would never forget his pleasant ____ while working there.	[情境语义]
[10828]	— Mr. Li is ill in hospital. His daughter is looking after him.<\\n>— ____.	[陈述遗憾的事情,应答句]
[10823]	— Mr. Li ____ to Mary carefully when I entered the classroom this morning.<\\n>— He is very patient ____ he is young.	[though,引导让步状语从句]
[10823]	— Mr. Li ____ to Mary carefully when I entered the classroom this morning.<\\n>— He is very patient ____ he is young.	[主句和从句,一般时和进行时]
[10818]	— Mr. Lee ____ to a student when I entered the classroom this morning.<\\n>— He is very patient ____ he is young.	[though,引导让步状语从句]
[10818]	— Mr. Lee ____ to a student when I entered the classroom this morning.<\\n>— He is very patient ____ he is young.	[主句和从句,一般时和进行时]
[10813]	— Mr. Hu, can you tell us how to learn math well?<\\n>— Sure. But remember nothing can be learned ____ hard work.	[without,介词]
[10798]	— Morning, class. Is ____ here?<\\n>— No, sir. Tom is absent.	[everybody,复合不定代词]
[10793]	— Morning, boys and girls! Please try your best in today's exam! Good luck to all of you!<\\n>— ____	[祝愿祝福,应答句]
[10779]	— Mommy, can I ride your new motor bike to school?<\\n>— Sorry, dear! You are too ____ to do that.	[too…to]
[10774]	— Mom, shall we have supper now?<\\n>— Oh, we won't have supper ____ your dad comes back.	[until,引导时间状语从句]
[10769]	— Mom, must I clean my room now?<\\n>— No, you ____. You can do it tomorrow.	[must疑问句,应答句]
[10764]	— Mom, may I go out to play now?<\\n>— Yes, you can. But your homework ____ first, I think.	[must,被动语态]
[10760]	— Mom, I won first place in the 1,000-meter race.<\\n>— ____ I am proud of you.	[陈述成就,应答句]
[10755]	— Mom, I was the first to reach the top of the mountain.<\\n>— Good job, Jack! I'm ____ of you.	[be proud of]
[10745]	— Mom, I want to ask grandpa a question.<\\n>— Oh. ____ is reading a newspaper upstairs.	[he,人称代词主格]
[10735]	— Mom, I got ____ place in the English Speech Competition.<\\n>— ____! That's really good news, dear!	[陈述成就,应答句]
[10735]	— Mom, I got ____ place in the English Speech Competition.<\\n>— ____! That's really good news, dear!	[the+序数词]
[10725]	— Mom, I am thirsty. Where is ____ cup?<\\n>— Is this ____?<\\n>— Yes, thank you.	[my,形容词性物主代词]
[10725]	— Mom, I am thirsty. Where is ____ cup?<\\n>— Is this ____?<\\n>— Yes, thank you.	[yours,名词性物主代词]
[10720]	— Mom, I am afraid that I can't get through the hard time we're having now.<\\n>— My boy, be brave and tell yourself ____.	[tell…to do]
[10715]	— Mom, can I leave my homework for tomorrow?<\\n>— I'm afraid not. Don't ____ what you can do today till tomorrow.	[put off]
[10710]	— Mom, Bill is coming to dinner this evening.<\\n>— OK. Let's give him ____ to eat.	[something+形容词]
[10705]	— Miss Li, must we hand in our homework right now?<\\n>— No, you ____. You can hand it in tomorrow.	[must疑问句,应答句]
[10700]	— Miss Lee, I didn't catch what you said. Could you tell me ____ again?<\\n>— OK.	[how,宾语从句连接词]
[10695]	— Miss Gao, I am feeling bored. Would you mind my ____ here?<\\n>— You had better not, for smoking is forbidden in public now.	[mind doing]
[10685]	— Mind your steps as you go, or you'll fall down on to the wet ground.<\\n>— ____.	[祈使句的应答句]
[10675]	— Mike, you look so excited.<\\n>— Yeah! There ____ a tennis game played by Li Na this evening.	[there be句型]
[10675]	— Mike, you look so excited.<\\n>— Yeah! There ____ a tennis game played by Li Na this evening.	[be going to do]
[10670]	— Mike, why do you still stay here? They have gone home.<\\n>— I'm sorry, but I ____ when to leave.	[一般过去时的被动语态]
[10665]	— Mike, why are you watching TV again?<\\n>— I ____ my homework.	[现在完成时]
[10660]	— Mike, is that new bike ____?<\\n>— Yes. My mother bought it for me yesterday.	[yours,名词性物主代词]
[10655]	— Mike, could you tell me if Mary ____ to my party tomorrow?<\\n>— I think she will if she ____ time.	[时间状语从句用一般现在时表示将来]
[10655]	— Mike, could you tell me if Mary ____ to my party tomorrow?<\\n>— I think she will if she ____ time.	[if,宾语从句连接词]
[10650]	— Mike, could you come and give me ____ hand?<\\n>— OK, Mum. I'm coming now.	[give sb a hand]
[10641]	— Mike hurt his arm the day before yesterday. Now he's in hospital.<\\n>— ____.	[陈述遗憾的事情,应答句]
[10631]	— Merry Christmas!<\\n>— ____.	[祝愿祝福,应答句]
[10626]	— Merry Christmas and Happy New Year!<\\n>— ____.	[祝愿祝福,应答句]
[10621]	— Meng Fei had his arm broken while recording If You Are the One in Beijing.<\\n>— Really? Then perhaps he ____ host TV programs for some time.	[can,情态动词]
[10611]	— Meat isn't really dangerous, is it?<\\n>— Oh! ____! It's not at all good for our health.	[反意疑问句,应答句]
[10607]	— May we leave the classroom now?<\\n>— No, you ____. You shouldn't leave until the bell rings.	[may疑问句,应答句]
[10602]	— May we leave the classroom now?<\\n>— No, you ____. You ____ to leave until the bell rings.	[be supposed to do]
[10602]	— May we leave the classroom now?<\\n>— No, you ____. You ____ to leave until the bell rings.	[not…until]
[10588]	— May I use your pen?<\\n>— Sure. Here are two and you can use ____ of them.	[either,不定代词]
[10583]	— May I use your calculator?<\\n>— Sorry, I left ____ at home.	[one,it]
[10568]	— May I speak to the headmaster?<\\n>— He ____ a meeting now. Can I take a message?	[现在进行时]
[10549]	— May I speak to Mary?<\\n>— ____. I'll call her at once.	[hold on]
[10544]	— May I speak to John?<\\n>— Sorry, he ____ Japan. But he ____ in two days.	[表示时间:after,in]
[10544]	— May I speak to John?<\\n>— Sorry, he ____ Japan. But he ____ in two days.	[have been to,have gone to,have been in]
[10529]	— May I smoke here?<\\n>— No, you ____. This is a no-smoking room.	[can't,mustn't]
[10499]	— May I play computer games now, mom?<\\n>— No. You ____ finish your homework first.	[must,have to:辨析]
[10494]	— May I play computer games for a while, mum?<\\n>— No, you ____. You have already played for two hours.	[may疑问句,应答句]
[10484]	— May I have a look at ____ book tonight?<\\n>— Of course, you can. I have ____ old one at home.	[an]
[10484]	— May I have a look at ____ book tonight?<\\n>— Of course, you can. I have ____ old one at home.	[the]
[10474]	— May I go swimming in the lake, Mum?<\\n>— No, you ____. It's too dangerous.	[may疑问句,应答句]
[10454]	— May I come in? I'm sorry I am late.<\\n>— Come in, please. But could you please tell me ____?	[why,宾语从句连接词]
[10449]	— May I borrow your dictionary?<\\n>— Sure, but please ____ it soon.	[情境语义]
[10444]	— May I borrow these two books, please?<\\n>— Yes, you can ____ them for two weeks.	[for+一段时间]
[10439]	— May I borrow these books?<\\n>— Certainly. You can borrow ____ of the two books, but you can't borrow ____.	[either,不定代词]
[10439]	— May I borrow these books?<\\n>— Certainly. You can borrow ____ of the two books, but you can't borrow ____.	[both,不定代词]
[10434]	— May I ____ your dictionary?<\\n>— Sorry. Li Lei ____ it for five days.	[表示时间:for,from,since]
[10434]	— May I ____ your dictionary?<\\n>— Sorry. Li Lei ____ it for five days.	[borrow,lend]
[10419]	— Maths is as interesting as English, I think.<\\n>— ____. English is more interesting than maths.	[表达建议/意见/观点,应答句]
[10415]	— Math is too difficult, I nearly give it up.<\\n>— Please don't, nothing is ____ if you put your heart into it.	[情境语义]
[10410]	— Mary, would you like to ____ this game?<\\n>— I'd love to, but I have to finish ____ the composition first.	[attend,join,join in,take part in]
[10410]	— Mary, would you like to ____ this game?<\\n>— I'd love to, but I have to finish ____ the composition first.	[finish doing]
[10380]	— Mark, please don't play basketball on the road. It's very dangerous.<\\n>— ____. I am going home at once.	[祈使句的应答句]
[10375]	— Maris, don't forget to put sugar in my coffee.<\\n>— I ____ some already.	[already,用于现在完成时]
[10367]	— Maria, ____ the dog, will you?<\\n>— Why ask me? Tom is playing there.	[祈使句的反义疑问]
[10362]	— Many teenagers show interesting the books that are written ____ Guo Jingming.<\\n>— That's true. My son says he can get what he thinks and wants in his books.	[by,被动语态]
[10347]	— Maggie, I really love your handwriting.<\\n>— ____.	[赞誉和表扬的应答句]
[10332]	— Lucy, do you like ____?<\\n>— Yes. Most of my clothes are ____.	[情境语义]
[10327]	— Lucy, ____?<\\n>— It's Friday. The weekend is coming.	[情境语义]
[10322]	— Lots of trees and flowers ____ on both sides of Huanshan Road last year.<\\n>— Oh, that's beautiful.	[一般过去时的被动语态]
[10317]	— Look. What a nice garden!<\\n>— Yes. It ____ every day.	[一般现在时的被动语态]
[10307]	— Look, what's in the tree?<\\n>— ____ bird, I think.	[a]
[10282]	— Look, the tall building looks very modern.<\\n>— Yes, and there is a garden on its ____. A garden in the air!	[情境语义]
[10273]	— Look, Sue is over there.<\\n>— That ____ be her. She is in Canada now.	[can't,mustn't]
[10268]	— Look, a blind man is in the middle of the street. It's too dangerous.<\\n>— Let's go and help him ____ the road.	[位置移动:across,through]
[10263]	— Look! What's that moving high up in ____ sky?<\\n>— It must be ____ plane.	[a]
[10263]	— Look! What's that moving high up in ____ sky?<\\n>— It must be ____ plane.	[sky,独一无二的事物]
[10259]	— Look! What's ____ in the sky?<\\n>— It looks like a kite.	[this,that]
[10249]	— Look! This answer is beautiful.<\\n>— ____?	[try on]
[10249]	— Look! This answer is beautiful.<\\n>— ____?	[why,不定式]
[10239]	— Look! There is a horse racing program on TV now.<\\n>— Hmm .... It ____ exciting.	[seem+形容词]
[10229]	— Look! The man at the gate ____ be our headmaster. He is always standing there every morning.<\\n>— No, it ____ be him. He is holding a meeting in the office now.	[can't,mustn't]
[10224]	— Look! The lights in the teachers' office are still on. Is Mr. Li working?<\\n>— No. It ____ be Mr. Li. I saw him leave just now.	[can't,mustn't]
[10214]	— Look! The light is still on in Mr. Zhang's office.<\\n>— I'm afraid he ____ his work yet.	[yet,用于现在完成时]
[10209]	— Look! That teacher is explaining something to her students again and again!<\\n>— ____ teacher she is!	[what,引导的感叹句]
[10204]	— Look! That is the women ____ I met yesterday.<\\n>— Oh? She's my aunt.	[who,引导的定语从句]
[10185]	— Look! Mr. Wang is standing under the tree.<\\n>— It ____ be Mr. Wang. He has gone to Shanghai.	[can't,mustn't]
[10181]	— Look! Mr. Wang is fishing over there.<\\n>— No, it ____ be him. He has already gone to Beijing on business.	[can't,mustn't]
[10176]	— Look! It's raining heavily. ____ take a raincoat with you?<\\n>— Well, I'll take one right now.	[why,不定式]
[10166]	— Look! How ____ the boy are!<\\n>— Yes. They won the game this afternoon.	[excited,-ed形式的形容词]
[10151]	— Look! Here comes our school bus.<\\n>— No hurry. Don't get on it ____ it has stopped.	[not…until]
[10146]	— Look! Everything ____ with snow.<\\n>— It's very beautiful! Let's make a snowman together.	[be covered with]
[10141]	— Look! A blind man is in the middle of the street. It's too dangerous!<\\n>— Let's help him go ____ the street.	[位置移动:across,through]
[10127]	— Look at the young lady in red. Is it Mrs. King?<\\n>— No, It ____ be her. She is wearing a white dress today.	[can't,mustn't]
[10122]	— Look at the sign on the right.<\\n>— Oh, parking ____ here.	[be allowed to do]
[10117]	— Look at the people in the lake. They are playing happily. Let's ____, too.<\\n>— Good idea.	[情境语义]
[10112]	— Look at the noisy kids!<\\n>— Haven't you heard the saying When the cat is away, the mice ____?	[时间状语从句用一般现在时表示将来]
[10107]	— Look at the noisy kids!<\\n>— Haven't you heard the saying When the cat is away, the mice ___.?	[时间状语从句用一般现在时表示将来]
[10102]	— Look at the glasses on the desk. Are they David's?<\\n>— They ____ belong to him. I saw him go out with glasses just now.	[can't,mustn't]
[10097]	— Look at the dark clouds, it's going to rain soon.<\\n>— ____. It's been so dry for months. Many trees have died.	[表达建议/意见/观点,应答句]
[10092]	— Look at the boy playing basketball on the ground. Is it George?<\\n>— It ____ be him. He told me he would play basketball after class, but he's not sure.	[may,情态动词]
[10087]	— Look at that pretty girl! Do you know ____?<\\n>— She is a dancer.	[what,宾语从句连接词]
[10082]	— Look at that photo, what a happy family!<\\n>— Yes, it's a photo ____ my family.	[of,介词]
[10077]	— Look at that girl! Is it Susan?<\\n>— No, it ____ be her. She has gone back to her hometown.	[can't,mustn't]
[10063]	— Long time no see. How is everything going now?<\\n>— ____.	[情境语义]
[10053]	— Long time no see!<\\n>— I've just returned. I ____ to Zhengzhou for a meeting last month.	[一般过去时的被动语态]
[10048]	— Long time no see! I think you ____ a lot.<\\n>— Yes. I used to be quiet, but now I'm outgoing.	[现在完成时]
[10044]	— Liu Xiang had to give up the race because of his foot.<\\n>— ____	[陈述遗憾的事情,应答句]
[10039]	— Liu Xiang and Yao Ming are famous sports stars.<\\n>— Yes. ____ of them have set a good example to us.	[both,不定代词]
[10035]	— Listen, the music ____ sweet.<\\n>It's Yesterday Once More, my favorite.	[sound+形容词]
[10010]	— Listen! Someone is playing the piano.<\\n>— Wow! ____ beautiful music! I like it very much.	[music,不可数名词instances]
[10010]	— Listen! Someone is playing the piano.<\\n>— Wow! ____ beautiful music! I like it very much.	[what,引导的感叹句]
[10005]	— Listen! Someone is playing ____ piano.<\\n>— Wow! ____beautiful music! I like it very much.	[music,不可数名词instances]
[10005]	— Listen! Someone is playing ____ piano.<\\n>— Wow! ____beautiful music! I like it very much.	[piano,是乐器]
[9995]	— Listen! Helen is singing in the next room.<\\n>— It ____ be Helen, She has gone to Beijing.	[can't,mustn't]
[9980]	— Lingling! Do you know ____ woman in white?<\\n>— Yes. She is ____ nurse in Liaocheng People's Hospital.	[a]
[9980]	— Lingling! Do you know ____ woman in white?<\\n>— Yes. She is ____ nurse in Liaocheng People's Hospital.	[the]
[9966]	— Linda, pass my glasses to me, please. I can ____ read the words in the newspaper.<\\n>— With pleasure.	[hardly,频率副词]
[9961]	— Linda, I called you this morning, but nobody answered the phone.<\\n>— I'm sorry. I ____ football with my friends then.	[过去进行时]
[9956]	— Linda, I am very thirsty.<\\n>— Let's go to the nearest supermarket ____ some drink, OK?	[v-ing,句子成分]
[9951]	— Linda, help ____ to some fruit.<\\n>— Thank you.	[help oneself to…]
[9946]	— Linda, could you tell me ____?<\\n>— He is an actor.	[what,宾语从句连接词]
[9941]	— Linda, can you tell me something about Mo Yan?<\\n>— Sure. He is the writer ____ won the Nobel (诺贝尔) Literature Prize.	[who,引导的定语从句]
[9937]	— Lin Tao, why are you so ____?<\\n>— Because Wang Meng got three gold medals at the Winter Olympics.	[excited,-ed形式的形容词]
[9932]	— Lily, there is ____ schoolbag near the window. Is it yours?<\\n>— Yes, it is. Thank you!	[a]
[9922]	— Lily, open ____ door, please.<\\n>— I'm coming.	[the]
[9913]	— Lily, don't forget to ____ the lights and lock the door before you leave the classroom.<\\n>— OK.	[turn off]
[9898]	— Lily has never milked a cow before, ____?<\\n>— Yes, she has.	[never,反意疑问句]
[9894]	— Lily has a silk ____. Listen, she is singing in the next room!<\\n>— How nice!	[情境语义]
[9889]	— Li Na is ____ first Asian who won championship in French Tennis Open.<\\n>— We're proud of her!	[the+序数词]
[9884]	— Li Lei, summer vacation is coming. Where will you go?<\\n>— I decide ____ to Mount Emei	[decide to do]
[9879]	— Li Lei, hurry up! The bus is coming!<\\n>— Oh, no. We ____ cross the street until the traffic lights turn green.	[can't,mustn't]
[9870]	— Let's play ____ soccer.<\\n>— I don't have ____ soccer ball.	[a]
[9870]	— Let's play ____ soccer.<\\n>— I don't have ____ soccer ball.	[play+球类棋类]
[9860]	— Let's park our car here.<\\n>— No, we ____. Look at the sign No parking.	[can't,mustn't]
[9856]	— Let's have a birthday party for you this Sunday evening.<\\n>— Thanks, but I don't think it's ____ to have it for me.	[形容词副词+enough]
[9851]	— Let's go to the zoo by taxi, ____?<\\n>— Maybe we can go there ____. It's not far.	[let's+反义疑问词]
[9851]	— Let's go to the zoo by taxi, ____?<\\n>— Maybe we can go there ____. It's not far.	[on foot]
[9847]	— Let's go to the Holiday Beach.<\\n>— ____!	[表达建议/意见/观点,应答句]
[9838]	— Let's go to see the stamp collection show.<\\n>— ____	[表达建议/意见/观点,应答句]
[9833]	— Let's go to play soccer after class, OK?<\\n>— ____	[表达建议/意见/观点,应答句]
[9828]	— Let's go shopping at the new mall.<\\n>— Why not shop onlines? It's ____.	[情境语义]
[9823]	— Let's go out for a picnic on Sunday.<\\n>— ____.	[表达建议/意见/观点,应答句]
[9818]	— Let's go hiking. Look, what a beautiful day!<\\n>— ____.	[表达建议/意见/观点,应答句]
[9813]	— Let's go hiking ____ staying at home, shall we?<\\n>— A good idea.	[instead of]
[9809]	— Let's go fishing after the exam, ____?<\\n>— Sounds great!	[let's+反义疑问词]
[9800]	— Let's get the key ____ the question.<\\n>— OK. Let's start.	[key to]
[9795]	— Let's do something for Ya'an children.<\\n>— Why not write letters to cheer ____ up?	[cheer up]
[9795]	— Let's do something for Ya'an children.<\\n>— Why not write letters to cheer ____ up?	[them,人称代词宾格]
[9781]	— Let's buy some cards for our teachers on Teachers' Day.<\\n>— Why not make some by hand? It's much ____.	[much+形容词副词比较级]
[9776]	— Let's buy a new car.<\\n>— Oh, no! We have almost ____ the money.	[run out of]
[9771]	— Let's ____ some dumplings right now.<\\n>— OK. I will cut up the meat first.	[情境语义]
[9763]	— Leo, could you tell me ____?<\\n>— I heard they were very mad at you.	[why,宾语从句连接词]
[9759]	— Leo, ____ no milk or eggs in the fridge.<\\n>— Oh, I'll go and buy some right away.	[There be A and B,主谓一致]
[9759]	— Leo, ____ no milk or eggs in the fridge.<\\n>— Oh, I'll go and buy some right away.	[milk,不可数名词instances]
[9750]	— latest Yangzhou Daily, please!<\\n>— Only one copy left. Would you like to have ____, sir?	[one,it]
[9746]	— Kelly, how long ____ you ____ in this school?<\\n>— For three years. I'll graduate in July.	[how long特殊疑问句,现在完成时]
[9736]	— Keep quiet, please. They ____ a meeting.<\\n>— Sorry.	[现在进行时]
[9727]	— Kate, which subject do you like better, Chinese or English?<\\n>— ____. I like them very much.	[both,不定代词]
[9723]	— Kate, I'm going on business. Please look after ____ well.<\\n>— Don't worry, Mom. I will.	[look after]
[9723]	— Kate, I'm going on business. Please look after ____ well.<\\n>— Don't worry, Mom. I will.	[yourself,反身代词]
[9708]	— Kate has won the first prize in the singing competition.<\\n>— ____ pleasant surprise this gave her classmates.	[what,引导的感叹句]
[9698]	— Julia, will you please go and move that desk?<\\n>— ____?	[Will you please do sth,应答句]
[9693]	— Juile, what ____ in your hand?<\\n>— Look! It's a new iPad for my daughter.	[现在进行时]
[9683]	— John, you ____ go out to play until your homework ____.<\\n>— OK, Mum.	[时间状语从句用一般现在时表示将来]
[9683]	— John, you ____ go out to play until your homework ____.<\\n>— OK, Mum.	[一般现在时的被动语态]
[9683]	— John, you ____ go out to play until your homework ____.<\\n>— OK, Mum.	[can,be able to:辨析]
[9683]	— John, you ____ go out to play until your homework ____.<\\n>— OK, Mum.	[not…until]
[9668]	— John, ____ do you visit your grandparents?<\\n>— Once a week.	[how often,特殊疑问句]
[9654]	— Jimmy isn't here. Where is he?<\\n>— He hurt his arm on the playground just now. He ____ to the school doctor's.	[have been to,have gone to,have been in]
[9649]	— Jim, who taught ____ Chinese before you came to school?<\\n>— Nobody. I learned it by ____.	[you,人称代词宾格]
[9649]	— Jim, who taught ____ Chinese before you came to school?<\\n>— Nobody. I learned it by ____.	[by oneself]
[9640]	— Jim, Tom is looking for his English book. Is this ____?<\\n>— No, that is ____. I don't know where his is.	[his,名词性物主代词]
[9640]	— Jim, Tom is looking for his English book. Is this ____?<\\n>— No, that is ____. I don't know where his is.	[mine,名词性物主代词]
[9635]	— Jim, please help ____ to some bread.<\\n>— Thank you.	[help oneself to…]
[9630]	— Jim, I'm very thirsty.<\\n>— Let's go to the nearest supermarket ____ drink, OK?	[不定式,句子成分]
[9625]	— Jim, I'm afraid I can't go to your party tonight. My grandma is ill.<\\n>— ____.	[陈述遗憾的事情,应答句]
[9600]	— Jim, can you repair the computer for me now?<\\n>— ____. I have to take care of my little sister.	[表示请求,应答句]
[9585]	— Jim, ____ read books while you are walking in the street. It's very dangerous.<\\n>— OK, thank you.	[don't…,祈使句的否定形式]
[9581]	— Jim never goes to school late.<\\n>— ____.	[neither,引导的倒装句]
[9576]	— Jim isn't in the classroom. Where is he?<\\n>— He ____ to the teacher's office.	[have gone to]
[9572]	— Jim is reading a book under that tree.<\\n>— It ____ be Jim. He has gone to Hainan.	[can't,mustn't]
[9567]	— Jim does well in Chinese in our class.<\\n>— ____. No one does better than him.	[so+主语+助动词]
[9562]	— Jerry, do you mind my pointing out your mistakes?<\\n>— ____. Your advice is of great value to me.	[Would you mind…,应答句]
[9552]	— Jenny, would you please ____ my dog when I am away?<\\n>— No problem.	[look after]
[9547]	— Jenny, what's your favorite ____?<\\n>— I like bananas best.	[情境语义]
[9543]	— Jenny, is this ____ bike?<\\n>— Oh, no, it's not ____.	[your,形容词性物主代词]
[9543]	— Jenny, is this ____ bike?<\\n>— Oh, no, it's not ____.	[mine,名词性物主代词]
[9534]	— Jeff seems unhappy. What's the matter?<\\n>— He got his bike lost this afternoon. Let's go to ____ him ____.	[cheer up]
[9529]	— Jason is too stubborn sometimes.<\\n>— I quite ____. But he's always friendly to others.	[表达建议/意见/观点,应答句]
[9525]	— Jane, is this your dictionary?<\\n>— Yes, it's ____. Thank you.	[mine,名词性物主代词]
[9520]	— Jane, is this ____ umbrella?<\\n>— No, it's not mine. It is ____.	[your,形容词性物主代词]
[9520]	— Jane, is this ____ umbrella?<\\n>— No, it's not mine. It is ____.	[hers,名词性物主代词]
[9516]	— Jane， if you have any trouble, be sure to call me.<\\n>— ____.	[祈使句的应答句]
[9508]	— Jane has never been to the Great Wall, ____?<\\n>— Yes, she has. She knows it very well.	[never,反意疑问句]
[9503]	— Jane got an A in the Maths test.<\\n>— ____. She works the hardest in our class.	[情境语义]
[9499]	— Jane got an A' in the Chinese test.<\\n>— So she did. [She works the hardest in our class].	[情境语义]
[9490]	— Jackie Chan has donated ____ dollars to charity.<\\n>— He is an example to us all.	[thousands of…]
[9485]	— Jack? Jack? Can you come?<\\n>— I ____ my homework.	[现在进行时]
[9480]	— Jack, you seem to be ____.<\\n>— Yes. It's 8:20 now and my train leaves in ten minutes.	[in a hurry]
[8922]	— Is this your key, Kathy?<\\n>— No. ____ is on the desk.	[mine,名词性物主代词]
[8176]	— I'm afraid a car is too expensive for me.<\\n>— But more and more Chinese can ____ to buy one.	[can,afford]
[8157]	— I'll take part in the boys' 200-meter race this afternoon!<\\n>— ____	[陈述即将到来的挑战,应答句]
[8152]	— I'll have a tennis game tomorrow. I'm a little bit nervous.<\\n>— Believe in ____. You're the best in our club.	[yourself,反身代词]
[8152]	— I'll have a tennis game tomorrow. I'm a little bit nervous.<\\n>— Believe in ____. You're the best in our club.	[believe in]
[8147]	— I'll go to the USA next month.<\\n>— ____ for?	[计划旅行/派对,应答句]
[8143]	— I'll go to South Africa in June.<\\n>— ____ exciting news! The World Cup will be held there.	[news,不可数名词instances]
[8143]	— I'll go to South Africa in June.<\\n>— ____ exciting news! The World Cup will be held there.	[what,引导的感叹句]
[8133]	— I'll go to Beijing for the coming summer holiday.<\\n>— ____.	[计划旅行/派对,应答句]
[8123]	— I'll go on a picnic with my classmates tomorrow.<\\n>— ____.	[计划旅行/派对,应答句]
[8118]	— I'll fly to Qingdao for my holiday this weekend.<\\n>— Wonderful! ____	[计划旅行/派对,应答句]
[8113]	— If you like the new house, you'd better buy it.<\\n>— But it's really expensive. I can't ____ it.	[can,afford]
[8103]	— If you have any problems, be sure to call me.<\\n>— ____.	[表示愿意提供帮助,应答句]
[8093]	— If there are ____ people driving, there will be ____ air pollution.<\\n>— Yes, the air will be fresher and cleaner.	[little+不可数名词]
[8093]	— If there are ____ people driving, there will be ____ air pollution.<\\n>— Yes, the air will be fresher and cleaner.	[few+可数名词]
[8093]	— If there are ____ people driving, there will be ____ air pollution.<\\n>— Yes, the air will be fresher and cleaner.	[little->less,比较级]
[8088]	— If our government ____ attention to controlling food safety now, our health ____ in danger.	[条件状语从句,时态]
[8083]	— If I work hard at my lessons from now on, can I do well in them?<\\n>— Sure. ____.	[情境语义]
[8079]	— If I have time, I will take you to the beach. It's so nice!<\\n>— Really? We can go there by ____.	[by oneself]
[8074]	— If a=4, b=5, what's the answer to the questiona+2ab+1=?<\\n>— ____.	[基数词的构成]
[8069]	— I'd like you to tell me something about Shen Nongjia.<\\n>— I'm sorry, but neither Jack nor I ____ there.	[neither…nor,主谓一致]
[8064]	— I'd like to introduce my best friend to you, peter.<\\n>— Thank you, Lucy. But we ____ already.	[already,用于现在完成时]
[8059]	— I'd like a cup of black coffee. What about you, Maggie?<\\n>— I prefer coffee ____ sugar.	[with,介词]
[8049]	— I would like you to talk about the Great Wall.<\\n>— I'm sorry, but ____ Jack ____ I have been there.	[neither…nor,是并列结构连词]
[8044]	— I would like some coffee with milk.<\\n>— ____.	[情境语义]
[8039]	— I wore sports shoes to the ball yesterday evening by mistake!<\\n>— Oh, dear, you must be very ____ at the ball!	[情境语义]
[8034]	— I won't have time to go shopping with you this afternoon.<\\n>— But you ____ me yesterday.	[promise to do]
[8034]	— I won't have time to go shopping with you this afternoon.<\\n>— But you ____ me yesterday.	[情境语义]
[8019]	— I wonder if your wife will go to the party.<\\n>— If your wife ____. so ____.	[条件状语从句,时态]
[8014]	— I wonder if the psychologist will come to our school this weekend.<\\n>— If he ____, we will be very excited.	[条件状语从句,时态]
[8004]	— I wonder ____.<\\n>— Shandong Province.	[where,宾语从句连接词]
[7999]	— I wonder ____.<\\n>— I'm afraid we'll be late.	[if,宾语从句连接词]
[7994]	— I wonder ____ you'll water this kind of tree.<\\n>— Once a week.	[how often,宾语从句连接词]
[7989]	— I wonder ____ pet fish.<\\n>— They are a pleasure to watch.	[why,宾语从句连接词]
[7984]	— I wonder ____ like to be an astronaut (宇航员).<\\n>— I don't know, but I imagine it's exciting.	[不定式,it,主语]
[7984]	— I wonder ____ like to be an astronaut (宇航员).<\\n>— I don't know, but I imagine it's exciting.	[what…like]
[7979]	— I won the 100-meter race on our sports day.<\\n>— ____ We are proud of you!	[陈述成就,应答句]
[7941]	— I watched the NBA game last night.<\\n>— ____ amazing game it was!	[what,引导的感叹句]
[7369]	— I don't like documentaries.<\\n>— ____.	[neither,引导的倒装句]
[7263]	— I can't find my seat. Could you show me, sir?<\\n>— ____. May I see your ticket, please?	[表示请求,应答句]
[6000]	— Here is a ____ of my family.<\\n>— Oh, it's very nice. Is this your father?	[情境语义]
[4574]	— Do you play ____ piano in your free time?<\\n>— No, I like sports. I often play ____ soccer with my friends.	[piano,是乐器]
[4574]	— Do you play ____ piano in your free time?<\\n>— No, I like sports. I often play ____ soccer with my friends.	[play+球类棋类]
[4380]	— Do you know who cleaned the blackboard, Tina?<\\n>— Yes. John ____.	[省略句]
[3849]	— Do you have to attend the meeting, Sam?<\\n>— Yes, I do. And not only I but also she ____ to attend the meeting.	[not only…but also,主谓一致]
[3392]	— Dad, do you like my picture?<\\n>— ____! It's the nicest one I've ever seen!	[how引导的感叹句]
[3388]	— Dad, did you tell mother about the gift for Mother's Day?<\\n>— No. Don't [let the cat out of the bag]. We'll give her a surprise.	[情境语义]
[3384]	— Dad, ____ is my Mp4?<\\n>— It's in your desk.	[where,特殊疑问句]
[3380]	— Dad is sleeping. Would you mind not ____ here?<\\n>— I'm sorry about that.	[mind doing]
[3370]	— Could you tell us how long ____?<\\n>— About three days.	[how long,宾语从句连接词]
[3370]	— Could you tell us how long ____?<\\n>— About three days.	[how long,特殊疑问句]
[3355]	— Could you tell me the way to the Science Museum, please?<\\n>— Yes, walk along this street. You'll see it ____ your left.	[on the left]
[3335]	— Could you tell me how long ____?<\\n>— For two weeks.	[how long,宾语从句连接词]
'''
}
